### ISSUE TITLE
Mouse cursor position is freezed at last detected position when quickly moving mouse cursor out of mpv window

### ISSUE THREAD

**Issue by Tsuchimikado** [tomasklaen/uosc#1000]
How to reproduce:
- add `video-sync=display-resample` to mpv.conf
- play video (not triggered when video paused)
- quickly move mouse cursor out of mpv window

Mouse cursor position is fixed to monitor coordinates and not to mpv window. It can be checked by resizing mpv window which results to UI elements fading in/out, buttons highlighted, thumbfast showing thumbs etc.

<details>
<summary>screenshots</summary>

![](https://i.imgur.com/AAuHZ82.png)
![](https://i.imgur.com/vlFNNwq.png)
</details>

uosc [5.6.0](https://github.com/tomasklaen/uosc/releases/tag/5.6.0)
mpv [0.39.0](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.39.0-x86_64.7z/download)
os Windows 10

**Comment by tomasklaen** [comment]
I can't reproduce. Maybe I don't 100% get what you're describing. Video of it happening would help.

But either way, I'd guess this is an mpv issue? We just respond to cursor position events mpv sends us.

**Comment by Tsuchimikado** [comment]
Sorry, tried it on fresh portable and found that `hwdec=d3d11va` is also needed.

<details><summary>mpv.conf</summary>

```
osc=no
osd-bar=no
border=no
video-sync=display-resample
hwdec=d3d11va
volume=23
```
</details>

> I'd guess this is an mpv issue?

Cannot reproduce this in default UI and [ModernX](https://github.com/cyl0/ModernX).

> Video of it happening would help.


https://github.com/user-attachments/assets/e5274b9d-ec14-4c4b-9e04-5197b6df1e96

**Comment by Tsuchimikado** [comment]
Tested uosc 5.6.0 with mpv from 0.38.0 down to 0.33.0 and result is same.
Then tested mpv 0.33.0 with other versions of uosc and found that latest unaffected version is 4.5.0.
Latest mpv working with uosc 4.5.0 is mpv 0.37.0.

Probably culprit is somewhere here https://github.com/tomasklaen/uosc/compare/4.5.0...4.6.0.
I personally strongly suspect this function https://github.com/tomasklaen/uosc/blob/5a02c6d205fb0993adf07aacb894b4d444ff34b1/scripts/uosc.lua#L548-L556 from https://github.com/tomasklaen/uosc/pull/412
As for current 5.6.0 version removing `cursor.hover_raw and` from https://github.com/tomasklaen/uosc/blob/08201fc3705dccda80e78ec133a54eeed9e53588/src/uosc/lib/cursor.lua#L404 is fixing this issue but I do not know how it will affect uosc in total.

config used
<details><summary>mpv.conf</summary>

```
osc=no
osd-bar=no
border=no
video-sync=display-resample
hwdec=d3d11va
volume=0
geometry=853x480+0+0
no-keepaspect-window
```
</details>

**Comment by FichteFoll** [comment]
Something like this would explain why I sometimes still have uosc elements visible despite having moved my pointer outside of the mpv window. It's not consistently reproduced, but it does occur frequently enough to be noticable.

**Comment by tomasklaen** [comment]
> removing cursor.hover_raw and from is fixing this issue but I do not know how it will affect uosc in total.

Me neither :) That code was submitted by @christoph-heinrich to add touch support, and I'm not 100% sure what happens to touch interfaces when we remove it. I do have a touch laptop with linux on it, but it just emulates cursor, so I don't have anything to test it on.

But that seems to be the culprit. From looking at it, it triggers leave only when `mouse.hover` was `true` in previous event, and `false` in current one. So in other words, it detects cursor leave. It seems fine, but from your reports I'd guess mpv triggers one more event with `mouse.hover == false` which would trigger enter here.

Maybe we need to do the detection from leave to enter as well. Try changing the `else` to:

```lua
elseif not cursor.hidden or not cursor.hover_raw and mouse.hover then
```

if that helps.

**Comment by Tsuchimikado** [comment]
> ```lua
> elseif not cursor.hidden or not cursor.hover_raw and mouse.hover then
> ```

I am probably doing something wrong but changing it makes UI not reacting to mouse cursor at all.

<details><summary>By the way I am using modified cursor.lua for almost a month and did not encounter any problems.</summary>

```lua
-- Movement
function handle_mouse_pos(_, mouse)
	if not mouse then return end
--	if cursor.hover_raw and not mouse.hover then
	if not mouse.hover then
		cursor:leave()
	else
		cursor:move(mouse.x, mouse.y)
	end
	cursor.hover_raw = mouse.hover
end
mp.observe_property('mouse-pos', 'native', handle_mouse_pos)
```
</details>

**Comment by tomasklaen** [comment]
This would be the whole function:

```lua
function handle_mouse_pos(_, mouse)
	if not mouse then return end
	if cursor.hover_raw and not mouse.hover then
		cursor:leave()
	elseif not cursor.hidden or not cursor.hover_raw and mouse.hover then
		cursor:move(mouse.x, mouse.y)
	end
	cursor.hover_raw = mouse.hover
end
```

**Comment by Tsuchimikado** [comment]
Thank you. It is working. Tested it a little and looks like issue is fixed now.

**Comment by christoph-heinrich** [comment]
I've had that a few times myself, but was never able to reproduce it. Thanks for looking into it.
