### ISSUE TITLE
Change a UI language without changing `slang`

### ISSUE THREAD

**Issue by asakura42** [tomasklaen/uosc#1006]
I don't want to change `slang` (it set to the language I learn right now), but i want to uosc UI to be in English. What to do?

**Comment by tomasklaen** [comment]
Config file:

```conf
# Localization language priority from highest to lowest.
# `slang` is a keyword to inherit values from `--slang` mpv config.
# Supports paths to custom json files: `languages=~~/custom.json,slang,en`
languages=slang,en
```

**Comment by alexandrecleite** [comment]
Hello! I created a pt-br.json file based on the files in the ~/.config/mpv/scripts/uosc/intl/ folder.

I edited uosc.conf and added this: languages=pt-br.json,slang,en
But nothing changed in my UI. How can I make it work and/or share this translation with you?
Thank you in advance, Alex
