### ISSUE TITLE
Changing audio tracks and subtitles with the mouse wheel as in the original player.

### ISSUE THREAD

**Issue by EvilToasterDBU** [tomasklaen/uosc#1007]
It is not enough to change the audio tracks and subtitles with the mouse wheel, as in the original player, so that by hovering over the icon for selecting the audio track or subtitles, you can quickly change them by scrolling the mouse wheel.

**Comment by Solarunit** [comment]
I personally don't like this approach in UI in general (not only in uosc) because is some cases you can accidentally trigger something with mouse wheel and this is annoying.  If there was such option in uosc I would disable it.

**Comment by EvilToasterDBU** [comment]
I think it would be good to have such a feature optional, and not to clean it up for good

**Comment by tomasklaen** [comment]
This should be configurable if #588 gets implemented, so I'll close this in favor of that.
