### ISSUE TITLE
Change the color of an element(s)?

### ISSUE THREAD

**Issue by AziRizvi** [tomasklaen/uosc#1008]
Since changing the colour of individual elements is not supported, I would like to ask is there any way the script file can be edited directly to achieve this effect?

I just want to make the timeline look like this, thank you.

![k1](https://github.com/user-attachments/assets/0b604ac6-aa7f-49dd-b4ae-c4cc43b60c5c)

**Comment by tomasklaen** [comment]
Here:

https://github.com/tomasklaen/uosc/blob/8220bad02a01f935e45b42bf6637b2ca9f665669/src/uosc/elements/Timeline.lua#L254-L255

You need to add color param to rect method with color in BBGGRR HEX format (so RGB HEX backwards).

```lua
ass:rect(fax, fay, fbx, fby, {color = 'eaa300', opacity = config.opacity.position})
```
