### ISSUE TITLE
Subtitle search just won't work.

### ISSUE THREAD

**Issue by AziRizvi** [tomasklaen/uosc#1009]
UOSC Version: 5.6.0.
MPV Version: v0.39.0-149-g7e834ce8
Platform: Windows 10 22H2 (Version 10.0.19045 Build 19045)

The subtitle search for me just does not work at all no matter what file I try it with, it always says no results to me, if I try finding the subtitles for the same file using SMPlayer which also uses OpenSubtitles, it works just fine.

Here's a short video in case it helps maybe? I don't know. (You can see that with Ziggy it didn't work but with SMPlayer, it did.)

https://github.com/user-attachments/assets/bf59dd21-eb87-4797-8393-8eeb3e31aef7

Out of curiosity, I checked the network connection history of Ziggy to see if it was _even_ connecting to the internet or not and I do see that it indeed is.

![image](https://github.com/user-attachments/assets/71317e5e-e9fc-4fe4-bd64-64ca6eba8885)

**Comment by tomasklaen** [comment]
Works fine for me:

![image](https://github.com/user-attachments/assets/c1c49f53-38bf-40ac-900e-91bdd5537390)

No idea what might be wrong on your side. You can try adding:

```lua
print('data:', utils.to_string(data))
```

somewhere in here: https://github.com/tomasklaen/uosc/blob/8220bad02a01f935e45b42bf6637b2ca9f665669/src/uosc/lib/menus.lua#L1014

to see what the raw response is.

**Comment by AziRizvi** [comment]
I just tried purging my mpv.conf to see if it would help and it worked.
My slang was set to eng `slang = eng` I just changed it to `slang = en, eng`
And now ziggy is working.
