### ISSUE TITLE
Chapter-markers not displaying thumbnails.

### ISSUE THREAD

**Issue by AziRizvi** [tomasklaen/uosc#1010]
Chapter-markers are not displaying thumbnails, one of them usually does but the rest just show a black thumbnail/box.
Not sure if this is intentional or not and I'm also not sure if this is a UOSC issue or a thumbfast one.

MPV Version: v0.39.0-176-gca7006a6
UOSC Version: 5.6.0
Thumbfast Version: Git Master
Platform: Windows 10 22H2

![QJ75K2kebE](https://github.com/user-attachments/assets/9d88cfda-392e-4471-a58a-426eed040fbd)

![ci9QVG71NG](https://github.com/user-attachments/assets/f515c569-018d-4b04-b79b-d4a16c3a5a0b)

**Comment by po5** [comment]
There's a black frame at that timestamp.
