### ISSUE TITLE
Allow icons and actions for (item) submenus

### ISSUE THREAD

**Issue by itsmeipg** [tomasklaen/uosc#1011]
I can't change the icon/add actions for items containing items, even though I can make them active.

**Comment by tomasklaen** [comment]
Actions don't show up for submenu buttons. They don't have values so the API wouldn't work, and action buttons would clash with submenu preview.

We _could_ add values to submenus to support this, but I don't know what to do with the preview then, and overall I feel like this shouldn't be a thing.

**Comment by itsmeipg** [comment]
Oh okay that makes sense. Btw another small issue I have is action buttons not showing if selectable is false. Idk if I should open another issue (I made so many).

**Comment by tomasklaen** [comment]
Should they show up when selectable is false? Setting it to false implies the item is inactive, shouldn't be interacted with. It's used to make titles/separators. I wouldn't expect actions to show on those.

**Comment by itsmeipg** [comment]
![image](https://github.com/user-attachments/assets/6b547cea-f148-44f2-9c28-d18018e88475)
I have a color menu that displays color properties with actions on the side to increase/decrease the values. Clicking the item does nothing so I think it should be unselectable. I think if an item is set to be unselectable, then it should be up to the menu creator to remove any existing actions (if they want).
