### ISSUE TITLE
Please support disabling the playback speed indicator separately.

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#1013]
Please support disabling the playback speed indicator separately, as it is used very rarely and blocks the video.
![image](https://github.com/user-attachments/assets/5591b6d6-fc67-47f6-8d70-a2542aab054f)

Thank you very much for bringing an excellent client experience tool to mpv. 👍👍👍😜

**Comment by po5** [comment]
Remove it from the list yourself. That's what the config is for.
https://github.com/tomasklaen/uosc/blob/main/src/uosc.conf#L83

**Comment by zhouxinghong** [comment]
`Remove it from the list yourself. That's what the config is for.`
What is the name of this control? Please provide. Thanks a lot! 🙏

**Comment by zhouxinghong** [comment]
Thank you very much for your help🙏! 👍🍦😜👏
