### ISSUE TITLE
Let us bind UOSC Menu keys?

### ISSUE THREAD

**Issue by KoshulaDora** [tomasklaen/uosc#1015]
I updated from a pretty old uosc version to current version. I am missing the arrows and mouse buttons for navigating to parent and child directories, and there doesn't seem to be any way to bind them beside editing the source code?

**Comment by mrfragger** [comment]
https://github.com/tomasklaen/uosc/issues/977#issuecomment-2336452200

**Comment by KoshulaDora** [comment]
> I just don't want arrows to activate items, but directory navigation menus could implement horizontal arrow navigation for directories. I'll look at it later.
> 
> But what do you mean by "mouse buttons for navigating to parent and child directories"? I don't recall there being buttons for this.

Some mouses have forward and backward buttons on side, and in source code of most recent version, in file `/uosc/elements/Menu.lua` Around line 1134 there is a `elseif key == mbtn_back` that seems to be dedicated to backward button of mouse. 

I think around the first version of uosc that implemented directory search, the `mbtn_back` and, presumably, `mbtn_forward`, did the current job of `Backspace` and `right` button, meaning going to parent directory and going into directory. It made it _very_ convenient to navigate in mpv without touching keyboard. 

Currently pressing the backward and forward buttons in mouse just makes the mpv go back to playing the former or later file in folder.

**Comment by KoshulaDora** [comment]
No mouse forward button implementation I guess

**Comment by mrfragger** [comment]
Thanks so much for making the left/arrow buttons for navigation.  I have no issue pressing ENTER to load subs/video/audio,  etc.  It's great now.
