### ISSUE TITLE
Add whole folder to playlist

### ISSUE THREAD

**Issue by musjj** [tomasklaen/uosc#1021]
It'd be nice if you can add a whole folder in `open-file` into the playlist. It looks like that the "Add to playlist" button does nothing to folders right now.

**Comment by hooke007** [comment]
![image](https://github.com/user-attachments/assets/3c694944-2465-498e-8378-cef037013941)

**Comment by tomasklaen** [comment]
The buttons are working again.

**Comment by musjj** [comment]
Thanks for the fix, both the button and shortcut now works!
