### ISSUE TITLE
Please support hiding the progress bar at the bottom.

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#1022]
![image](https://github.com/user-attachments/assets/fc885484-8dbf-43bb-acad-ac74bea9eef4)
Please support hiding the progress bar at the bottom.

**Comment by po5** [comment]
Please read uosc.conf

**Comment by zhouxinghong** [comment]
I didn't find this setting?
Please let me know! Thank you very much! 😜

**Comment by zhouxinghong** [comment]
Because of this progress bar, it is impossible to completely enter the borderless playback state.

**Comment by tomasklaen** [comment]
https://github.com/tomasklaen/uosc/blob/3df0af21cee3dbdca645ea425a0209bdac6076de/src/uosc.conf#L18-L22

**Comment by zhouxinghong** [comment]
Thanks so much for your help! 🏆👍😜
