### ISSUE TITLE
[uosc] script-opts/uosc.conf:138 unknown key 'autoload_types', ignoring

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#1023]
[uosc] script-opts/uosc.conf:138 unknown key 'autoload_types', ignoring
https://github.com/tomasklaen/uosc/archive/refs/heads/main.zip

**Comment by tomasklaen** [comment]
[`autoload_types` renamed to `load_types` which now supports a new same flag](https://github.com/tomasklaen/uosc/commit/2e4fd5c15344f61cafe770c676bacd458fb75f81)

**Comment by zhouxinghong** [comment]
Thank you very much for your help! 👍🏆😜
