### ISSUE TITLE
MPV/UOSC stops registering keys after downloading subtitles

### ISSUE THREAD

**Issue by dborsukov** [tomasklaen/uosc#1025]
https://github.com/user-attachments/assets/0ae37d0f-0cd7-492b-938b-272d40a380b5

```
UOSC 5.6.2
System:
  Kernel: 6.8.0-49-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0
  Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.41 wm: xfwm4 dm: LightDM
    Distro: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
```

**Comment by tomasklaen** [comment]
I don't see this happening on windows, or any issues in code that could cause this, so it has to be an mpv issue.

We use a custom binary to talk to APIs. This is spawned as a subprocess. Could it be that doing it cases your mpv window to lose focus?

**Comment by dborsukov** [comment]
Keys start working again after I open and close any UOSC ui element.
I think this narrows it down to either MPV or UOSC issue.

https://github.com/user-attachments/assets/2b19db3e-3394-4145-9668-4dbf0e41f242

**Comment by dborsukov** [comment]
Tested on latest version of MPV (0.39) and different window manager (GNOME) in a fresh Manjaro VM. Same behavior.

**Comment by tomasklaen** [comment]
Try applying this patch to `elements/Menu.lua` and see what it reports:

```diff
diff --git a/src/uosc/elements/Menu.lua b/src/uosc/elements/Menu.lua
index 55308f8..66a3382 100644
--- a/src/uosc/elements/Menu.lua
+++ b/src/uosc/elements/Menu.lua
@@ -1029,6 +1029,7 @@ function Menu:add_key_binding(key, name, fn, flags)
 end
 
 function Menu:enable_key_bindings()
+	print('enabling menu keybindings')
 	-- `+` at the end enables `repeatable` flag
 	local standalone_keys = {
 		'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', '/', 'mbtn_back',
@@ -1147,6 +1148,7 @@ function Menu:handle_shortcut(shortcut, info)
 end
 
 function Menu:disable_key_bindings()
+	print('disabling menu keybindings')
 	self:search_disable_key_bindings()
 	for _, name in ipairs(self.key_bindings) do mp.remove_key_binding(name) end
 	self.key_bindings = {}
```

Or here's the changed file: [Menu.lua.zip](https://github.com/user-attachments/files/17946841/Menu.zip)

The last message before the issue starts happening should be "disabling menu keybindings". If it says "enabling..." when the menu is closed, then there's something weird with uosc.

BTW: I think that downloading same subtitles doesn't add to your your daily limit.

**Comment by dborsukov** [comment]
> Try applying this patch to elements/Menu.lua and see what it reports

It does say "disabling menu keybindings" after I close uosc menu, so no issues there. 

After tinkering a bit with code I discovered that spawning an async ziggy task seems to be the root cause.
Skipping this call "fixes" the issue:

```diff
--- lib/menus.lua.old	2024-11-28 14:57:12.486442732 +0200
+++ lib/menus.lua	2024-11-28 14:58:08.340666311 +0200
@@ -962,35 +962,14 @@
 			'--destination', destination_directory,
 		})
 
-		call_ziggy_async(args, function(error, data)
-			if not menu:is_alive() then return end
-			if should_abort(error, data, function(data) return type(data.file) == 'string' end) then return end
-
-			load_track('sub', data.file)
-
-			menu:update_items({
-				{
-					title = t('Subtitles loaded & enabled'),
-					bold = true,
-					icon = 'check',
-					selectable = false,
-				},
-				{
-					title = t('Remaining downloads today: %s', data.remaining .. '/' .. data.total),
-					italic = true,
-					muted = true,
-					icon = 'file_download',
-					selectable = false,
-				},
-				{
-					title = t('Resets in: %s', data.reset_time),
-					italic = true,
-					muted = true,
-					icon = 'schedule',
-					selectable = false,
-				},
-			})
-		end)
+		menu:update_items({
+			{
+				title = t('Skipped async task'),
+				bold = true,
+				icon = 'check',
+				selectable = false,
+			},
+		})
 	end
 
 	---@param query string
```

I'm assuming something about calling `subprocess` on linux through `command_native` api causes this, unless there is a deeper issue with ziggy itself, which seems unlikely in this case.

**Comment by tomasklaen** [comment]
So it's what I was suggesting in my first post :) Spawning the subprocess makes the window loose focus until you click it again. Or maybe it just becomes unresponsive to shortcuts?

Either way, I don't see anything we could do about this on our side.

**Comment by dborsukov** [comment]
You were definitely right about subprocess causing this issue. However, I'm still skeptical about window losing focus at the window manager level because: mouse works immediately(without needing to refocus the window), the issue persists after manually changing focus back and forth, and certain keys remain registered (Enter, Backspace, Escape, and directional keys all work as usual).

Anyway, I understand that this is very niche and low priority, so I won't bother you about it anymore. I consider this issue resolved, close it at your discretion.

**Comment by tomasklaen** [comment]
So this seems to happen on all newer mpv builds. I can replicate myself on windows with 0.39.

Please report it there if it isn't already. I'll keep this open until it's fixed so people can find out what's going on.

**Comment by tomasklaen** [comment]
So this was a well hidden uosc bug after all 😳.
