### ISSUE TITLE
Hello everyone! Can I customize the height of the progress bar?

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#1029]
Hello everyone! Can I customize the height of the progress bar?
![image](https://github.com/user-attachments/assets/9073ff79-ccb8-494a-ab54-6694cf1e72ca)
Windows 10

**Comment by tomasklaen** [comment]
It's in the config. timeline_size and progress_size.

**Comment by zhouxinghong** [comment]
Ok, thank you very much for your help!👍🤞🏆🍦😜
