### ISSUE TITLE
[Feature Request] Cycle Timeline Visibility.

### ISSUE THREAD

**Issue by AziRizvi** [tomasklaen/uosc#1031]
I really like UOSC but one thing I miss about the native osc.lua is how it had a keybind where you could cycle the osc/timeline visibility at will, sometimes I need to look at the timeline or just want it to be visible despite what the timeline_persistency is set to and scrolling down to the timeline area also activates the control buttons which is annoying. 

Would you consider implementing this for UOSC please?
If not then, I guess feel free to close this.
Thanks.

**Comment by itsmeipg** [comment]
In input.conf, `[key] script-message-to uosc toggle-elements timeline`
