### ISSUE TITLE
Get item actions from callback

### ISSUE THREAD

**Issue by itsmeipg** [tomasklaen/uosc#1032]
Would it be possible to access a selected item's actions in callback? Just by hovering over the main item, instead of selecting/hovering over the item's action(s).

**Comment by tomasklaen** [comment]
There are no hover events currently. Not sure if it's a good idea adding them. That would be a lot of noise. What is the use case?

**Comment by itsmeipg** [comment]
![image](https://github.com/user-attachments/assets/bcab4962-c609-4669-a361-beaab5bd5747)
I have multiple items in multiple submenus that control number properties (colors, deband, etc) and in my callback function, I want to listen to event.type == "key" (ctrl+left/right) to decrease/increase rapidly, instead of having to hover over an action and hold enter. selected_item only gives info about the item value, which none of these items have, so the only way to get info about the selected item is by using the item value in a way its not supposed to be used, or by doing some complicated calculations with menu_id and selected_item.index. It would be great if I could just link the key combo to the item's actions directly.

**Comment by tomasklaen** [comment]
> so the only way to get info about the selected item is by using the item value in a way its not supposed to be used

In non-callback menus, value is used as an mpv command. In callback menus, it's just passed to you, so it can be whatever you need it to be.

If I understand correctly, you want ctrl+left/right to increase/decrease some variable. So use `item.value` as the name/identifier of that variable, and edit it during a `key` event based on waht key was pressed.

**Comment by itsmeipg** [comment]
I should have thought this out more before making this issue... I'll paste my actions into the value. Thanks for the help!
