### ISSUE TITLE
Add support for GUI for adding import youtube cookies features easily to skip youtube throttle 

### ISSUE THREAD

**Issue by trimechee** [tomasklaen/uosc#1033]
Hi, thanks so much for the amazing awesome vital UOSC ! 💯 🥇

users complain that youtube throttles bitrates when using external media player and yt-dlp has to import youtube cookies in some cases to fix this problem, we hope for an easy graphical interface to easily import youtube cookies and then, mpv playback youtube videos without throttle,  thanks !

https://mpv.io/manual/stable/#options-ytdl-raw-options

--ytdl-raw-options=username=user,password=pass

authentification options
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#authentication-options

cookies yt-dlp commands command line arguments
--cookies-from-browser firefox ( firefox does not lock the export of cookies to yt dlp unlike chrome, some users aid we should disconnect from our youtube account if this  doesn't work and try again )

chrome --disable-features=LockProfileCookieDatabase --disable-features=NetworkServiceSandbox

yt-dlp cookies imports
https://github.com/coletdjnz/yt-dlp-youtube-oauth2
https://github.com/coletdjnz/yt-dlp-get-pot
https://github.com/seproDev/yt-dlp-ChromeCookieUnlock

https://github.com/54ac/stream-detector (can export cookies to exteranl tool)

https://github.com/zaidka/cliget (can export cookies to exteranl tool)

https://github.com/ytdl-patched/ytdl-patched
https://github.com/pratikpatel8982/yt-dlp-mp4decrypt
https://github.com/pratikpatel8982/yt-dlp-hianime

https://github.com/rotemdan/ExportCookies

**Comment by tomasklaen** [comment]
The UI API we are working with (ass tags) is too limited to even start thinking about adding configuration UIs. Configuration will have to stay in config files.

Configuration is also something you do once, and than just use the player. Putting in a lot of effort to make a UI for it is not worth it imo.
