### ISSUE TITLE
Hello friend! Can the foreground color of 150 be modified?

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#1035]
Hello friend! Can the foreground color of 150 be modified?
![image](https://github.com/user-attachments/assets/f5cbc76c-8eff-4e86-8ab0-d2867ca54ba5)
Hello friend! Can the foreground color of 150 be modified?

Thank you very much for writing a great UI extension for mpv. 👍😜

**Comment by tomasklaen** [comment]
Please start reading the config file and not make an issue for every option you want to change.

```
# A comma delimited list of color overrides in RGB HEX format. Defaults:
# foreground=ffffff,foreground_text=000000,background=000000,background_text=ffffff,curtain=111111,success=a5e075,error=ff616e
color=
```

**Comment by zhouxinghong** [comment]
> Please start reading the config file and not make an issue for every option you want to change.
> 
> ```
> # A comma delimited list of color overrides in RGB HEX format. Defaults:
> # foreground=ffffff,foreground_text=000000,background=000000,background_text=ffffff,curtain=111111,success=a5e075,error=ff616e
> color=
> ```
OK! Thank you very much for your help! 👍👍👍👍👍🤞👏🍦😜

**Comment by mrfragger** [comment]
```
#blue (change to default theme color....no space between start of line)
#color=foreground=6aabcf,foreground_text=000000,background=1d2f38,background_text=ffffff

# green
#color=foreground=8ccf6a,foreground_text=000000,background=20381d,background_text=ffffff

# purple
#color=foreground=a26acf,foreground_text=000000,background=2e1d38,background_text=ffffff

# red
color=foreground=CF6A6F,foreground_text=000000,background=662323,background_text=ffffff

# orange
#color=foreground=1C1B1F,foreground_text=000000,background=412f21,background_text=FFFBFE

# brown 
#color=foreground=e1c5ad,foreground_text=000000,background=3b2f24,background_text=FFFBFE

# black
#color=foreground=FFFBFE,foreground_text=1C1B1F,background=1C1B1F,background_text=FFFBFE
```

**Comment by zhouxinghong** [comment]
OK! Thank you very much for your help! 👍👍👍👍👍🤞👏🍦😜
