### ISSUE TITLE
Don't show title on hover for an "end of range" chapter

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#125]
The kind of range is only/mostly relevant while the range itself is active, not afterwards. If you use the sponsorblock plugin while watching videos from YouTube, you will occasionally see a sponsor or a self-plug range or similar where the "end" chapter will be shown on hover for almost the entire video.

It would be more useful if instead uosc showed "intro segment (info)" after the first marker and nothing after the second marker of a range. I don't think it makes sense to apply a change here to the sponsorblock plugin because technically it does use the correct way of implementing this and when navigating the chapter menu for example, being able to select the "… end" marker is a use case. It's just that with the new UI that it doesn't work too well.

Example video: https://www.youtube.com/watch?v=oSSCRUmaquo

![2022-08-23_11-29-43](https://user-images.githubusercontent.com/931051/186124036-b92acd8c-46a8-47c3-aff0-18b709a969d6.png)

cc @po5

**Comment by tomasklaen** [comment]
This is hard. A lot of ranges, such as anime openings, have only starting chapters, and their end is decided by start of any subsequent one.

In this case, chapters sequence would be something like: OP,Episode title,...

So if I told chapter title tooltip to ignore range ending chapters, it'd never display the "Episode title", which is wrong.

Right now, chapter ranges code is completely agnostic to everything, and ranges are determined by user supplied configuration, and I don't want to change that.

Ideally, sponsor block should only declare starting chapters, and rename their ending ending ones to something like title of the video, or "Content", or something like that.

In case that sponsorblock behavior can't be changed, the simplest solution to this I can think of would be another option with list of regular expressions that would tell uosc what chapters should be marked as ending and not displayed as tooltips.

**Comment by po5** [comment]
I agree that in this case where ranges are built from explicit start and end chapters you wouldn't want that behavior, but uosc ranges also do things like highlighting openings and endings.  
You would want to display a "Part A" chapter on hover, even if it's what closed the "OP" range.

Maybe your proposed behavior + special handling of `.*` end patterns would work, but we may not want to trust such heuristics.

**Comment by FichteFoll** [comment]
> This is hard. A lot of ranges, such as anime openings, have only starting chapters, and their end is decided by start of any subsequent one.
> 
> In this case, chapters sequence would be something like: OP,Episode title,...

Indeed, it does not apply to chapters in anime, but with sponserblock the situation is kind of different and one that comes up frequently enough for me to notice.

How about a regex that hides chapter names on hover if it matches or that transforms chapters via regex replacement? That way it can stay generic but also be configured to match the sponsorblock case.

**Comment by christoph-heinrich** [comment]
Can you please test if #153 works for you?
