### ISSUE TITLE
Allow other scripts to detect uosc

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#138]
Probably through setting a `uosc` key on `shared-script-properties` with `utils.shared_script_property_set()`.

My use case is disabling an osd message for current speed, when uosc's flash-speed can be called instead. https://github.com/po5/evafast

**Comment by tomasklaen** [comment]
I've looked into `shared_script_property_set`, and after reading all the warnings in the docs to not use it, I instead added a `get-version` message handler:

```lua
-- Register response handler
mp.register_script_message('uosc-version', function(version)
	print('uosc version', version)
end)

-- Ask for version
mp.commandv('script-message-to', 'uosc', 'get-version', mp.get_script_name())
```
