### ISSUE TITLE
Remaining time scaled by speed

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#141]
Before 7f2803046ac4891ccc85f7df9f966a6a48b659ca the remaining playback time was scaled by speed. Was that an intentional change?

If that was a side effect of getting millisecond resolution, you can instead append the properties with `/full` like is used in [osc.lua](https://github.com/mpv-player/mpv/blob/211ce69f74214f8f9d2225df5b683718bab2f60d/player/lua/osc.lua#L2071-L2084).

If that was intentional, it would be great if there was an option to show the scaled remaining time, as that is more useful imo.
Btw unscaled remaining time is also available in [`time-remaining`](https://mpv.io/manual/stable/#command-interface-time-remaining).

**Comment by tomasklaen** [comment]
No it wasn't intentional, so I've tried to put it back in 8a6632c, but it had bugs, which I've finally fixed now in 7ecf258c0afa1e17a8e071ee13c309d6db2bec96 🤐.
