### ISSUE TITLE
Ability to set all options for script-defined menus

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#143]
Currently, only `items` and `title` get passed.  
`selected_index` and possibly other options would be nice to have.

**Comment by tomasklaen** [comment]
You can now pass `type`, `active_index`, and `selected_index`, though `selected_index` defaults to `active_index` or `1`, so it's redundant in most cases.

`type` is useful to give the menu toggling ability (showing menu with same type will close it).
