### ISSUE TITLE
Show parent menus when calling show-submenu

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#144]
As an option? May not be desired all the time.

**Comment by tomasklaen** [comment]
Uh, I think this one's going to be a wontfix unless someone gives me a reasonable use case.

When you open a menu, you want to active an item in it. Menus disappear when you activate an item. So why would I open something like **Aspect ratio** menu, and than want to navigate up?

**Comment by tomasklaen** [comment]
The push-back here is coming from the current menu implementation being a bit messy, and implementing pre-opened sub-menus might not be super simple. So I don't want to spend time implementing something that won't provide much value.

Also I'd personally prefer opening clean menus with only the stuff I want to use without the noise of irrelevant parents on the side.

**Comment by christoph-heinrich** [comment]
One thing I can think of is accidentally opening the wrong menu.
When the wrong menu folder gets opened, one can simply click on the parent menu to get back and choose the correct one, but when e.g. the track menu gets opened on accident, one has to reopen the menu.

**Comment by po5** [comment]
My use case is script menus, where you can directly open a sub-option but it's helpful to expose all options from the parent as well.

**Comment by christoph-heinrich** [comment]
Oh, I misunderstood. So basically you want it to be the same when opening a submenu via script as it is when navigating there via the menu.

**Comment by tomasklaen** [comment]
All right, I'll look into it.
