### ISSUE TITLE
Wrong icons

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#147]
Since 804faf9e01424a000926c4321129f85bb762b193 it renders the wrong icons.
![wrong_icons](https://user-images.githubusercontent.com/8932183/187519716-5500573c-bfe2-4a9b-9231-c25c3ec3730e.png)

Edit: the submenu arrow isn't shown at all.

**Comment by christoph-heinrich** [comment]
Using the UTF-8 dec code from [here](https://unicode-table.com/en/1F5D5/) and replacing the existing character string produces the correct icon for me. Tried it with minimize and maximize.
E.g. `'\240\159\151\149'` would be minimize.
The icons are too small though.

**Comment by hooke007** [comment]
off topic: I have a question here, why we don't use the icon in the osd-font, but render the another volume icon?

https://github.com/mpv-player/mpv/blob/0f30b0757fb969455119d83d3f29dec3d66f6c9c/player/lua/osc.lua#L2119-L2122

**Comment by christoph-heinrich** [comment]
Using the icon font from mpv is a good idea, then its always consistent, independent of what other fonts users have installed

**Comment by tomasklaen** [comment]
@christoph-heinrich What!? I have no idea why it's displaying different icons for you 😢. Did you put the font from the `fonts` directory into your `mpv/fonts/`? All I'm doing is using codepoints for characters in here: https://zavoloklom.github.io/material-design-iconic-font/icons.html

@hooke007 I didn't consider using the mpv built in one as I don't see any docs with a list of icons inside it, and I doubt it has all that might be needed. I'm in the middle of creating user configurable buttons bar that'll allow adding buttons that can execute commands, or toggle/cycle properties. So I want to support a variety of icons and also be able to give people a URL where they can just copy & paste the characters for them.

**Comment by tomasklaen** [comment]
@christoph-heinrich can you try adding these lines to `render_timeline()` (right after the `ass` is created):

```lua
ass:icon(100, 100, 48, '')
ass:icon(200, 100, 48, '\239\132\160')
```

they should both display a bug icon:

![image](https://user-images.githubusercontent.com/47283320/187541796-c29701ab-c7b0-4c7c-ab20-304786592f9d.png)

**Comment by hooke007** [comment]
> I doubt it has all that might be needed

Unfortunately it only contains the icons original osc used.
<img width="550" alt="snip2022-08-30 22 03 20" src="https://user-images.githubusercontent.com/41094733/187543570-b4fb3089-fafb-495d-bdd0-1443384d8f79.png">

**Comment by tomasklaen** [comment]
Or scrap it, I'll swap to google's material icon font that is based on ligatures. That should be foolproof.

@hooke007 yeah that's not enough, and they are ugly 🤐.

**Comment by christoph-heinrich** [comment]
![icons](https://user-images.githubusercontent.com/8932183/187544646-90a3d02d-de9e-4283-8573-342b6cc73da0.png)

**Comment by po5** [comment]
I get intended icons after placing the font file in my `fonts` directory. Have you done that @christoph-heinrich?

**Comment by tomasklaen** [comment]
There, this ^ is a way better solution. Now we get a super comfy icon names for free 😄:

```lua
ass:icon(300, 100, 48, 'pause')
```

Hope this works for everyone.

**Comment by po5** [comment]
Works here. Unless of course I remove the font, displays text instead of icons. I think this was a user issue.

**Comment by christoph-heinrich** [comment]
Fwiw the '\239\132\160'` from before is in a [private use area](https://unicode-table.com/en/search/?q=%EF%84%A0), which means there is no officially defined symbol and there will never be one for that code.

**Comment by tomasklaen** [comment]
@po5 Yeah that's cool too. Works like `<img alt="text">` prop in html. When the font is missing users will see a fallback text.

**Comment by tomasklaen** [comment]
The only potential issue I see here (if @christoph-heinrich reports that he made it work that is) is if there is some mpv/libass configuration that doesn't support ligatures.

**Comment by christoph-heinrich** [comment]
now it looks like
![icons](https://user-images.githubusercontent.com/8932183/187546432-7360aac9-ca5d-4f9a-8e4c-56778ec96b22.png)

**Comment by tomasklaen** [comment]
This makes me very sad. Are you installing the font where it's supposed to be? Other than that I have no idea...

What's your system/mpv build/version? Does anyone else with similar setup share this issue?

**Comment by christoph-heinrich** [comment]
No, I missed installing the font. Arch has a `nodejs-material-design-icons` package, but that doesn't seem to work, so I'll have to figure out how to manually install a font.

**Comment by tomasklaen** [comment]
You don't need to install it system wide, just place the font from this repo's `fonts/` into your `mpv/fonts/` directory.

**Comment by hooke007** [comment]
ref https://mpv.io/manual/master/#files-~/-config/mpv/fonts/

**Comment by christoph-heinrich** [comment]
No idea why I can't get this to work for me.
```
.config/mpv/fonts
❯ ls
Material-Design-Iconic-Font.ttf  MaterialIconsSharp-Regular.otf
```
That should be right, no?

**Comment by hooke007** [comment]
Eh, probably you met with an issue from upstream?
If loaded successfully it would be list in the mpv log.

![snip 2022-08-30 225815](https://user-images.githubusercontent.com/41094733/187551283-81644264-b223-4971-ac1b-b0a629d99ad1.jpg)

**Comment by christoph-heinrich** [comment]
```
[osd/libass] Setting up fonts...
[osd/libass] Loading font file '/home/christoph/.config/mpv/fonts/MaterialIconsSharp-Regular.otf'
[osd/libass] Error opening memory font 'MaterialIconsSharp-Regular.otf'
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/Twitter Color Emoji/TwitterColorEmoji-SVGinOT.ttf, 0, TwitterColorEmojiSVGinOT
[osd/libass] fontselect: Using default font family: (MaterialIconsSharp-Regular, 400, 0) -> /usr/share/fonts/Twitter Color Emoji/TwitterColorEmoji-SVGinOT.ttf, 0, TwitterColorEmojiSVGinOT
[osd/libass] fontselect: (MaterialIconsSharp-Regular, 400, 0) -> /usr/share/fonts/Twitter Color Emoji/TwitterColorEmoji-SVGinOT.ttf, 0, TwitterColorEmojiSVGinOT
[osd/libass] Glyph 0x63 not found, selecting one more font for (MaterialIconsSharp-Regular, 400, 0)
[osd/libass] fontselect: Using default font family: (MaterialIconsSharp-Regular, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
[osd/libass] fontselect: (MaterialIconsSharp-Regular, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
```
huh

**Comment by christoph-heinrich** [comment]
It works!

I've removed the downloaded version and simply made a symlink to the one in the repo.
No idea why the downloaded version didn't work, but whatever.

**Comment by christoph-heinrich** [comment]
We should probably mention the font in the installation instructions. (at least after the next release)

**Comment by tomasklaen** [comment]
Yes that's the plan. I'm leaving readme as is as it still applies to last stable.
