### ISSUE TITLE
Speed widget disappears on timeline hover

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#148]
Even when flashed with a command. Volume widget doesn't behave like this, and can display even if we're hovering on the timeline.  
I understand why it's hidden, to not interfere with the hovered time (and now chapter title), but it should still appear when explicitly flashed.

**Comment by tomasklaen** [comment]
You are asking to make me intentionally implement element clashing? Having speed and timestamp+chapter title overlap would look super bad and confusing, as it's all just text and lines.

If you're hovering timeline, it's definitely easier to move the mouse a bit up than to press a shortcut for flashing.

This really doesn't make sense to me, sorry.

**Comment by FichteFoll** [comment]
I understand the request for only applying when the timeline is flashed with a key and explicitly not when hovered with a mouse, i.e. the speed widget should probably be hidden once the mouse hovers the timeline.
