### ISSUE TITLE
How to make volume silder always available

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#154]
Some videos may not contains Aids. Unless skipping to another video or append the external audio track, it's not conveninent for users to change the vol via uosc.
Another case I often meet with —— in idle mode change volume first and then load the video I want.

I quickily viewed the source code but found that deleting this line doesn't work for main branch (But worked for 
 the latest release). I may missed sth else. https://github.com/tomasklaen/uosc/blob/272a8efb4743a1559c89b56b0b08a9d45c4b584f/scripts/uosc.lua#L1862

**Comment by hooke007** [comment]
> you want the volume UI even when currently opened video doesn't have audio?

True. I mean audio tracks https://mpv.io/manual/master/#options-aid

> The hiding volume UI when no audio was https://github.com/tomasklaen/uosc/pull/109 PR I've merged

That's the question here, I noticed this pr and reverted the commit in my fork but still doesn't work.
Just as I mentioned before ''found that deleting this line doesn't work for main branch (But worked for
the latest release)''

> Maybe a 👍 👎 poll?

No, i would only make this change in my fork.

**Comment by tomasklaen** [comment]
> BTW, I never saw any other players or third-party osc would hide vol button when "opening video doesn't have audio"...

Yes I thought about it and I'll revert it back, but I'm working on some visualization of audio not being available.

To answer your question, the line you posted only stopped rendering the element, but it was still interactive, which was a bug, so I've implemented `element.enabled` flag which stops all rendering and interactivity. For all 3 volume elements it's set by:

```lua
on_prop_has_audio = function(this, has_audio) this.enabled = has_audio end,
```

**Comment by Natural-Harmonia-Gropius** [comment]
In my opinion, this can be solved by `watch-later-options=volume`. that you can't know the loudness of audio track before played.

If you know the sound is quiet, then it is safe to turn it up.
Or it's loud, first I'd say it's rare, and second I'd suggest just taking the headphones off

**Comment by Natural-Harmonia-Gropius** [comment]
Alternativly change the conditions to `if this.width == 0 or opacity == 0 or state.is_image then return end` could be work.

**Comment by hooke007** [comment]
> this can be solved by watch-later-options=volume

That's not the point. From my view, stop rendering the buttons/elements in OSC/UI when the corresponding things (this could be duration, subtitles or else) is unavalible in current files, which is an odd behavior. So does vol slider.

**Comment by tomasklaen** [comment]
Ok so I'm done with the disabled indicator UI, but before I commit it, as asked above, shouldn't we hide the volume at least for images? Do you expect a volume slider even when viewing images?

**Comment by hooke007** [comment]
I hope the slider could always be available because it always reflact program's vol rather tnan the track's vol.
And Here is an example edge case that 'expect a volume slider even when viewing images'.
https://www.reddit.com/r/mpv/comments/wgs1g2/how_do_i_playback_a_bunch_of_png_images_in_mpv/

**Comment by tomasklaen** [comment]
But that reddit example would be recognized as video no? He's essentially creating a video stream of pngs. So I'd expect `is_video == true` and  `is_image == false` when that's playing. Also he's probably the only person in the world doing that :)

**Comment by hooke007** [comment]
Anyway, comit whatever you prefer, I could make the diff in my fork :)

**Comment by tomasklaen** [comment]
After a bit of thinking, this is a media player after all, it makes sense to be able to control it's volume even when currently played file has no audio. We might implement image viewing mode in the future, but for now, this stays enabled.
