### ISSUE TITLE
Show playlist index and size indicator

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#16]
I would like to see the playlist index and the size of the playlist in front of the video title in the top bar, but only if there are 2 or more items in the playlist.

**Comment by darsain** [comment]
Again, too much clutter for title, but it might be more fitting as its own indicator somewhere around timeline, that way you can also look at it with peek-timeline command instead of having to drag the cursor to the top bar.

**Comment by FichteFoll** [comment]
Just to be clear, I mean to show it as follows:

```
6/10 - Playlist item 5 (0-indexed)
```

I suppose adding that indicator to a different location could work, too, but I wouldn't know where. I'm certainly used to this information being next to the current title, but I'm open for experiments.

**Comment by FichteFoll** [comment]
Also, I think adding the chapter count and playlist size to their menu headers would be a simple but useful change. Not so much for the track selection menus, though.

**Comment by tomasklaen** [comment]
This was actually implemented recently. Forgot about this issue.

**Comment by FichteFoll** [comment]
Me too, I forgot I even reported it but was glad when I saw it got added.
