### ISSUE TITLE
Hard to read title

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#168]
Sometimes the title becomes very hard to read because of the content of the video.

![title](https://user-images.githubusercontent.com/8932183/188276093-59f91cc5-b150-4f9b-a991-48f62aa1376b.png)

Should we add a background to the top bar, like osc.lua does, or do you have any other suggestions?

**Comment by tomasklaen** [comment]
I'll do something about it once I'm done with controls bar.
