### ISSUE TITLE
Add `load-subtitles` into `subtitles` menu

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [tomasklaen/uosc#169]
As windows media player does.
![188289782-dbe36d2c-c22b-4616-bc64-39ee983d03f9](https://user-images.githubusercontent.com/50797982/188289990-24a25ef6-70a6-4241-9d47-433db6ec0d28.png)

**Comment by tomasklaen** [comment]
Yes I was thinking about it as well. Will do.
