### ISSUE TITLE
Show disabled more prominently in `subtitles`

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [tomasklaen/uosc#170]
Add a Disabled label as English in left, to improve visibility.
![188289864-bb4e4e5f-542f-4c7a-af2a-6f56914ba3cb](https://user-images.githubusercontent.com/50797982/188289998-e67be3d3-cc1e-44b6-be52-b1d563162d30.png)
![image](https://user-images.githubusercontent.com/50797982/188289864-bb4e4e5f-542f-4c7a-af2a-6f56914ba3cb.png)

**Comment by tomasklaen** [comment]
Will do.

**Comment by FichteFoll** [comment]
Or should it perhaps read "None" as in "no subtitles"?

**Comment by tomasklaen** [comment]
![image](https://user-images.githubusercontent.com/47283320/188850312-f5d45d51-3198-48cb-a089-8a03f4bb02d5.png)
