### ISSUE TITLE
Option to keep menu active upon selecting an item

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#171]
This would be half of an easier solution for #144, consider this script menu:

![image](https://user-images.githubusercontent.com/42466980/188295056-618e6da3-a356-4f38-ba24-bc31471d22f4.png)

Any menu like this that lets you set options would benefit from not closing on every item selection.
```
Command {
    title: string | nil;
    hint: string | nil;
    close: bool;
    value: string | string[];
}
```
This definition, with close defaulting to true, would remove some of the frustration.

The second half is that script menus can't update themselves, so the "current value" hint (WebM/yes) on previous menus would be wrong after changing an option.

Ignoring this and having scripts fall back to a self-drawn menu for setting options defeats the point of integrating with uosc's menu system.

**Comment by tomasklaen** [comment]
Well, you are trying to use a context menu as a form :) I'm not against supporting something like this, but will have to think about the best solution. I want to rewrite how menus are implemented after I'm done with controls bar, so I'll look into it then.

**Comment by po5** [comment]
An idea would be a modifier prefix much like `no-osd`, so that menus defined in input.conf can also use it. Would probably have to be in the comment though.
`<           script-binding uosc/prev               #! keep-open # Navigation > Prev`

**Comment by tomasklaen** [comment]
You can now both keep the menu open, and update it. See the example in the readme:

https://github.com/tomasklaen/uosc#update-menu-menu_json
