### ISSUE TITLE
First and last item in menus and submenus are not aligned properly

### ISSUE THREAD

**Issue by maaldheefee** [tomasklaen/uosc#176]
Version: commit: [87e7e9e](https://github.com/tomasklaen/uosc/commit/87e7e9ec09e3a602978082077ef5ea69ee46b0c9)

As seen in this screenshot.

![image](https://user-images.githubusercontent.com/16198035/189310514-67e59b44-2edf-4da5-a615-c760c90c3322.png)

**Comment by tomasklaen** [comment]
I'm currently refactoring menus, so none waste time submitting a PR for this, I'll fix it there.
