### ISSUE TITLE
Allow customization top_bar_title 

### ISSUE THREAD

**Issue by maaldheefee** [tomasklaen/uosc#177]

**Comment by tomasklaen** [comment]
How? There's nothing to customize. I won't be adding a different color option just for title, and lowering opacity of the background will make the text unreadable when on top of other text, see #168.

**Comment by maaldheefee** [comment]
I meant allow changing of the text using property expansion.

**Comment by tomasklaen** [comment]
You mean this #24?

**Comment by maaldheefee** [comment]
Yes

**Comment by dyphire** [comment]
@tomasklaen I think it is necessary to set the `--title` to be customizable, because in some cases the media title is not useful information. 
For example:
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/09/14/20220914202347.png)
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/09/14/20220914202357.png)
As you can see, the title does not show useful content. This should be displayed as the `{filename}`

**Comment by dyphire** [comment]
> @tomasklaen I think it is necessary to set the `--title` to be customizable, because in some cases the `media-title` is not useful information. 

At the same time, the streaming file should always use the `media-title`, because the `filename` is also not a valid information for it.
If the user is not allowed to customize the `--title`, I think it is more correct to always display the `filename` first, and only force the `media-title` to be used for streaming files.

**Comment by dyphire** [comment]
> But let's say I give you an option to customize title template. What will you do exactly? Switch it to filename? Then when you open a stream or file downloaded from a service that changed its name to some hash, it will display its URL or that hash as a title

As long as we provide customizable title options, we can do more control. Whether in the input.conf or mpv.conf file.
For example, you can use automatic condition configuration in mpv.conf to switch the title for the stream file.
```
[media-title]
 profile-cond=path:match('://')~=nil or path:match('^magnet:')~=nil  or ...
 profile-restore=copy
 script-opts-append=uosc-title=${media-title}

```
Similarly, we can choose to use the media title as the default value, and switch file names for specific files through automatic condition configuration:
```
[fliename]
 profile-cond=filename:match("cXcY@FRDS")~=nil or ...
 profile-restore=copy
 script-opts-append=uosc-title=${fliename}

```
This is the advantage of the `--title` option provided by mpv's official osc.lua script. 
I don't understand why to restrict user behavior, which denies more possibilities for this script.

**Comment by tomasklaen** [comment]
```
profile-cond=filename:match("cXcY@FRDS")~=nil or ...
```

Srsly? Ugh, whatever.

But those conditionals won't apply unless you reopen mpv btw.

**Comment by christoph-heinrich** [comment]
Doesn't the `force-media-title` option of mpv already fulfill your needs?

**Comment by tomasklaen** [comment]
If `force-media-title` accepts templates than it sure would. Let me know, as I'd like to revert the changes above because I hate as we currently have to strip `" - mpv"` from the end of the native `title` template.

**Comment by tomasklaen** [comment]
It doesn't 😢.

**Comment by christoph-heinrich** [comment]
How about we only expand it, if it actually contains `${...}` ? Because I remember seeing some comment about expanding taking an unreasonable 150ms. I think something like `title:match('${[%w-]+}') should do it.

**Comment by dyphire** [comment]
> It doesn't 😢. In retrospect it actually can't, as it'd cause infinite recursion.

In fact, I don't understand how to use from this commit:joy:: https://github.com/tomasklaen/uosc/commit/85b49002a81c0cc010e59fe1ac6ee095cfe2d458

**Comment by christoph-heinrich** [comment]
I think we should continue to display `media-title` (just like the original osc does) and `force-media-title` not expanding properties is really a problem of mpv itself, and not of uosc. Open an issue over there about it (unless there is already one, didn't look).

**Comment by christoph-heinrich** [comment]
It seems to behave nicely, so I'm fine with it.
One thing I noticed is that when opening mpv without a file, the window title becomes 'No file', but that was not reflected in the top bar. Also the current implementation would not react to changes in the title property.
What do you think about that?
``` diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index a52650e..d4f9033 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -3034,7 +3034,7 @@ function TopBar:render()
 	local visibility = self:get_visibility()
 	if visibility <= 0 then return end
 	local ass = assdraw.ass_new()
-
+	
 	-- Window title
 	if options.top_bar_title and (state.title or state.has_playlist) then
 		local max_bx = self.title_bx - self.spacing
@@ -4064,14 +4064,16 @@ if options.pause_on_click_shorter_than > 0 then
 end
 mp.set_key_bindings(mouse_keybinds, 'mouse_movement', 'force')
 mp.enable_key_bindings('mouse_movement', 'allow-vo-dragging+allow-hide-cursor')
-
-mp.register_event('file-loaded', function()
-	parse_chapters()
-	local title_template = mp.get_property_native('title')
+local function update_title(title_template)
 	if title_template:sub(-6) == ' - mpv' then title_template = title_template:sub(1, -7) end
 	set_state('title', mp.command_native({"expand-text", title_template}))
+end
+mp.register_event('file-loaded', function()
+	parse_chapters()
+	update_title(mp.get_property_native('title'))
 end)
 mp.register_event('end-file ', function() set_state('title', nil) end)
+mp.observe_property('title', 'string', function(_, title) update_title(title) end)
 mp.observe_property('playback-time', 'number', create_state_setter('time', update_human_times))
 mp.observe_property('duration', 'number', create_state_setter('duration', update_human_times))
 mp.observe_property('speed', 'number', create_state_setter('speed', update_human_times))
```
The downside to this is that now, when opening mpv with a file, it at first shows 'No title' until the file is loaded.
