### ISSUE TITLE
!help : hwo to use sponser-block-yt & chapter-range for noob

### ISSUE THREAD

**Issue by omaru-ok** [tomasklaen/uosc#178]
![image](https://user-images.githubusercontent.com/108952834/189438943-ce57f35f-6606-4c2a-bac0-2759ade306b1.png)
i got this error and sponser-block segmets not workign ?

**Comment by christoph-heinrich** [comment]
Is there a space in front of the `chapter_ranges` in your uosc.conf?

**Comment by omaru-ok** [comment]
yeah it does work

![image](https://user-images.githubusercontent.com/108952834/189478477-235995ff-7061-4043-a8d3-8a71bf630984.png)


but im thinkign fo something like  colored-output at timeline by sponserblock ? is that possible

**Comment by christoph-heinrich** [comment]
Yes that's possible. I thought that already worked with the default conf, but apparently not? (I don't use sponsorblock)
What are the segments called that you want to highlight?

**Comment by omaru-ok** [comment]
> Yes that's possible. I thought that already worked with the default conf, but apparently not? (I don't use sponsorblock) What are the segments called that you want to highlight?

i want to highllight as much as it can . such as intraction-reminder, and self-sponser  etc.

**Comment by christoph-heinrich** [comment]
I've now tried out [mpv_sponsorblock](https://github.com/po5/mpv_sponsorblock) and that works without a problem. No configuration required, simply copy the `sponsorblock.lua` file and the `sponsorblock_shared` folder into the scripts directory.

Have you changed the `chapter_ranges` configuration? Because the default one should just work.

**Comment by omaru-ok** [comment]
> I've now tried out [mpv_sponsorblock](https://github.com/po5/mpv_sponsorblock) and that works. No configuration required, simply copy the `sponsorblock.lua` file and the `sponsorblock_shared` folder into the scripts directory.
> 
> Have you changed the `chapter_ranges` configuration? Because the default one should just work.

thx it does work :O 

but 
![image](https://user-images.githubusercontent.com/108952834/189499121-b6245ce1-fb2f-4ed7-98b9-af92266dc753.png)
is that normal warning?

**Comment by christoph-heinrich** [comment]
There is an issue on their repo about it https://github.com/po5/mpv_sponsorblock/issues/54

**Comment by omaru-ok** [comment]
> `local_database=no`

thx
