### ISSUE TITLE
Clipped menu hints

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#191]
Happens on the default `font_height_to_letter_width_ratio`.  
I need to make it absurdly high e.g. 0.75 to not get clipping, but that impacts other parts of the UI.
![XC  Tokyo Gambo - 01 RAW (WEB 844p) mkv_000029 000](https://user-images.githubusercontent.com/42466980/189879336-b53ffea8-d714-4caa-bdb6-ea658f8d675c.png)

**Comment by tomasklaen** [comment]
Can you tell me what the title+hint combinations are? So I can replicate.

**Comment by tomasklaen** [comment]
Oh right that's playlist indexes. nvm 😳.

**Comment by tomasklaen** [comment]
Should be fine now.

**Comment by po5** [comment]
It is fixed.
