### ISSUE TITLE
Cannot seek using the timeline when mouse pointer is at the bottom edge of screen when fullscreen

### ISSUE THREAD

**Issue by maaldheefee** [tomasklaen/uosc#192]
I believe the bottom most pixels should trigger the timeline. Instead triggers my MBTN_LEFT action.

1 pixel from the bottom edge
![image](https://user-images.githubusercontent.com/16198035/189912843-7dd240f1-f700-4559-a619-f180ebdb9589.png)

at the bottom edge
![image](https://user-images.githubusercontent.com/16198035/189913148-2b801200-819f-45a0-9d7c-486ebd73cc2f.png)

**Comment by maaldheefee** [comment]
Likewise at the top edge. You can't click the close button by moving the mouse pointer to the top right corner.

**Comment by tomasklaen** [comment]
Hm... I thought that maybe window border is not being removed/disabled when in fullscreen, but it is. Works fine for me with or without the uosc border enabled. So, I can't replicate.

Are you using the latest uosc?

**Comment by maaldheefee** [comment]
Strange. I cannot reproduce it on my PC either. But PC and laptop has the exact same configs, same build of mpv, and Windows 11.

Only on my laptop, bottom and right edge don't work. Right end of the timeline also triggers normal MBTN_LEFT action.

I'm on the latest commit on master.

**Comment by hooke007** [comment]
Can reproduce here.

**Comment by christoph-heinrich** [comment]
Can't reproduce, otherwise I would have looked into it :disappointed:

**Comment by tomasklaen** [comment]
What are your OS/mpv combinations that have this issue?

I've tried this on win, and my laptop running majaro, and all works fine. But honestly, the fact that this is not an issue on most setups suggests the uosc is working correctly, and it's probably mpv in some environments reserving 1 edge pixel for window resizing or something, and forgetting to disable it in fullscreen.

I don't think we can do anything about it here.

**Comment by christoph-heinrich** [comment]
I do wonder if that's a desktop environment dependent thing. Maybe some desktop environments allow the cursor to move one pixel outside of the screen, which would then be considered outside of the element.

Can you please apply the following patch and then report the coordinates that get reported at the edge of your screen in fullscreen?

``` diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index 90eb8d0..bc4a024 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -3604,6 +3604,7 @@ end
 
 function update_cursor_position()
 	cursor.x, cursor.y = mp.get_mouse_pos()
+	print(cursor.x, cursor.y)
 
 	-- mpv reports initial mouse position on linux as (0, 0), which always
 	-- displays the top bar, so we hardcode cursor position as infinity until
```
On a 1920x1080 screen we would expect x values from 0 to 1919 and y values from 0 to 1079.

If you get values from 0 to 1920 for x and 0 to 1080 for y, the fix would be to simply cap the values to the window dimensions.
But if you get values from 1 to 1920 for x and 1 to 1080 for y, we would need some way of finding out which range of values your DE to properly deal with it, and I don't think that's possible.
A kind of terrible solution would be to find out which desktop environment is currently running and then have a list of DEs with their mouse input behavior.

**Comment by hooke007** [comment]
> What are your OS/mpv combinations that have this issue?

Windows 10
Mac OS Monterey

**Comment by Natural-Harmonia-Gropius** [comment]
> Only on my laptop

How about when 100% dpi scaling?

**Comment by maaldheefee** [comment]
> What are your OS/mpv combinations that have this issue?

Windows 11 build 22621.457 / mpv-git / with 125% scaling

> How about when 100% dpi scaling?

Yes. 100% scaling works.

I tried compatibility options on Windows, with 125% scaling, but none of it seems to work.

> On a 1920x1080 screen we would expect x values from 0 to 1919 and y values from 0 to 1079.

Yes. That's what I get. Scaling has no effect on these values.

**Comment by hooke007** [comment]
Temporary solution `hidpi-window-scale=no`

**Comment by christoph-heinrich** [comment]
Must be a fractional scaling thing. I'm on KDE plasma and it always reports either a `display-hidpi-scale` of 1 or 2. both of which work.

**Comment by christoph-heinrich** [comment]
In my limited testing this seems to work exactly as it should:
``` diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index 409a0dd..f937e8a 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -599,8 +599,8 @@ end
 ---@param point {x: number; y: number}
 ---@param rect {ax: number; ay: number; bx: number; by: number}
 function get_point_to_rectangle_proximity(point, rect)
-	local dx = math.max(rect.ax - point.x, 0, point.x - rect.bx + 1)
-	local dy = math.max(rect.ay - point.y, 0, point.y - rect.by + 1)
+	local dx = math.max(rect.ax - point.x, 0, point.x - rect.bx)
+	local dy = math.max(rect.ay - point.y, 0, point.y - rect.by)
 	return math.sqrt(dx * dx + dy * dy);
 end
 
@@ -2638,8 +2638,7 @@ function Timeline:get_time_at_x(x)
 end
 
 function Timeline:set_from_cursor()
-	-- add 0.5 to be in the middle of the pixel
-	mp.commandv('seek', self:get_time_at_x(cursor.x + 0.5), 'absolute+exact')
+	mp.commandv('seek', self:get_time_at_x(cursor.x), 'absolute+exact')
 end
 
 function Timeline:on_mbtn_left_down()
@@ -2868,8 +2867,7 @@ function Timeline:render()
 
 	-- Hovered time and chapter
 	if (self.proximity_raw == 0 or self.pressed) and not (Elements.speed and Elements.speed.dragging) then
-		-- add 0.5 to be in the middle of the pixel
-		local hovered_seconds = self:get_time_at_x(cursor.x + 0.5)
+		local hovered_seconds = self:get_time_at_x(cursor.x)
 		local chapter_title, chapter_title_width = nil, nil
 
 		if (options.timeline_chapters ~= 'never' and state.chapters) then
@@ -3620,8 +3618,9 @@ function update_cursor_position()
 	local dpi_scale = mp.get_property_native('display-hidpi-scale', 1.0)
 	dpi_scale = dpi_scale * options.ui_scale
 
-	cursor.x = cursor.x / dpi_scale
-	cursor.y = cursor.y / dpi_scale
+	-- add 0.5 to be in the middle of the pixel
+	cursor.x = (cursor.x + 0.5) / dpi_scale
+	cursor.y = (cursor.y + 0.5) / dpi_scale
 
 	Elements:update_proximities()
 	request_render()
```

**Comment by christoph-heinrich** [comment]
After thinking about it, it would probably be best if we were to not scale display resolution and mouse input, and store the scaling factor as a state property and then let the elements scale their size based on that. Rendering with scaled pixels will inevitably lead to suboptimal results. Sure it would be possible to convert to real pixels, then do any rounding etc, and then convert back to scaled pixels, but at that point we might as well always use real pixels.

The downside of that is, that it's more invasive to the rest of the code then the current solution. But I think in most cases we would only have to touch the `update_dimensions()` function. The timeline would need some extra work in the rendering function (cursor line, chapter lines, cache ranges). Any fonts would also have to be scaled by that global scaling factor.
