### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#193]
This crash doesn't always happen, seems to be a race condition.
![Screenshot_20220913_190904](https://user-images.githubusercontent.com/8932183/189964240-afa64f91-74fc-4af4-8eea-8af341a4034d.png)

From a quick look at the code, it seems the values get initialized in `update_dimensions()`, but that doesn't reliably happen before the first render. So the solution would be to ensure that things are initialized before trying to render them. Either initialize with default values at the very beginning, or have a nil check for one of the values in the render function.

---

Btw the first impression of the way things are organized now is pretty good :+1:

**Comment by tomasklaen** [comment]
Weird, this never happened to me 🤷‍♂️. Should be fixed.

> Btw the first impression of the way things are organized now is pretty good 👍

I still hate a lot about the codebase, but I don't think I want to spend time creating an actual UI framework for a single project and a very unique environment, so we are stuck with this for the time being.

**Comment by tomasklaen** [comment]
At least we have some types and go-to-definition now :)

**Comment by christoph-heinrich** [comment]
Considering that this is all subtitle rendering, it's pretty darn good already.

But I do wonder what things would be like if mpv actually provided a proper UI framework out of the box.
Rendering certainly would be more efficient (currently it calls libass on every frame for each osd overlay, even if the text hasn't changed at all...). Something like [Dear ImGui](https://github.com/ocornut/imgui) with Lua bindings for scripts would seem like a good fit, but also a bit overkill tbh.
