### ISSUE TITLE
Add menu for editions

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#20]
Editions are a seldomly used feature in Matroska files, since they require ordered chapters – an almost unknown magic –, but they exist.

Definitely not a priority for me, as I can easily cycle editions with a native mpv binding (which happens *very* rarely), but for the sake of completeness I thought I should mention this.

**Comment by darsain** [comment]
First time seeing these editions. Looking at mpv docs and still don't really understand what they are.

Is it like sets of different chapters for same video file that you can switch between?

**Comment by FichteFoll** [comment]
That's a good summary. An edition is a list of chapters, or more precisely: ordered chapters, which means a second edition could for example provide a different order for the same chapters without needing a separate video file. They an even reference chapters from other files (in the same folder) through ordered chapters.

https://mod16.org/hurfdurf/?p=8 provides the best overview on this that I know of.

**Comment by darsain** [comment]
K. I'll look into this when more people request it, since it looks like none is using it atm, or when I'll have absolutely nothing else to do.

Todo when adding support for this:
- stop ensuring chapters are ordered chronologically by sorting them, and sort them only for purpose of generating chapter ranges

**Comment by FichteFoll** [comment]
I don't how how mpv provides ordered chapters internally. It may already translate the ordered chapters into a virtual chapter stream for scripts to use.
