### ISSUE TITLE
Menu items support escaping > characters

### ISSUE THREAD

**Issue by Hill-98** [tomasklaen/uosc#205]
`>` character can sometimes be useful, can we get something like `#! Video > Scale Conversion > 21:9 -\> 16:9` Something like that?

**Comment by tomasklaen** [comment]
Or you can use `→` :)

**Comment by Hill-98** [comment]
Yeah, it is indeed a good substitute.

**Comment by omaru-ok** [comment]
> Or you can use `→` :)

hwo did u typed that?

**Comment by tomasklaen** [comment]
Currently we are splitting titles with a simple `split(' *> *')` pattern.

Lua doesn't support negative lookbehind unfortunately, and I don't want to create a string parsing loop for a silly thing like this, so using `→` as an alternative (and imo more appropriate) character is the least painful compromise here.
