### ISSUE TITLE
Improving cached ranges visualization

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#206]
I was supposed to be refactoring chapter ranges today, but I got sidetracked by trying to improve how we render cached ranges. I've tried it by rendering stripes over un-cached areas, and it looks pretty good imo:

![image](https://user-images.githubusercontent.com/47283320/190379052-7447331c-8b89-455a-b15a-c80a0291baa2.png)

But it raised my CPU usage from 13% to 30% 😳, which is a no go. It also doesn't look that good on top of a progress styled as a bar, because I've tried making it a bit more performant by rendering dark background as a single rectangle, and then stripes on top, unfortunately the order in which ass composes these drawings when alpha is present makes whites grey 😠. To fix this, I'd have to render black stripes separately, which would be even bigger performance hit.

The code responsible for rendering it along with a static example to try it out is here:

https://github.com/tomasklaen/uosc/blob/stripes/scripts/uosc.lua#L1082

It's used as:

```lua
ass:stripes(bax, fay, bbx, fby, {ignore_ranges = {{0.3, 0.6}}})
```

If anyone has any idea how to make it more performant, I'm all ears.

Afaik there's no way to use textures in this environment, right? All I see is `overlay-add`, but that doesn't allow cropping.

**Comment by omaru-ok** [comment]
> I was supposed to be refactoring chapter ranges today, but I got sidetracked by trying to improve how we render cached ranges. I've tried it by rendering stripes over un-cached areas, and it looks pretty good imo:
> 
> ![image](https://user-images.githubusercontent.com/47283320/190379052-7447331c-8b89-455a-b15a-c80a0291baa2.png)
> 
> But it raised my CPU usage from 13% to 30% 😳, which is a no go. It also doesn't look that good on top of a progress styled as a bar, because I've tried making it a bit more performant by rendering dark background as a single rectangle, and then stripes on top, unfortunately the order in which ass composes these drawings makes whites grey 😠. To fix this, I'd have to render black stripes separately, which would be even bigger performance hit.
> 
> The code responsible for rendering it along with a static example to try it out is here:
> 
> https://github.com/tomasklaen/uosc/blob/stripes/scripts/uosc.lua#L1082
> 
> It's used as:
> 
> ```lua
> ass:stripes(bax, fay, bbx, fby, {ignore_ranges = {{0.3, 0.6}}})
> ```
> 
> If anyone has any idea how to make it more performant, I'm all ears.
> 
> Afaik there's no way to use textures in this environment, right? All I see is `overlay-add`, but that doesn't allow cropping.

this looks so good :O

**Comment by Natural-Harmonia-Gropius** [comment]
Does ass or something supports to draw a gradient similar to following css?
```css
background: linear-gradient(
  120deg,
  rgba(0, 0, 0, 1) 0%,
  rgba(0, 0, 0, 1) 25%,
  rgba(102, 102, 102, 1) 25%,
  rgba(102, 102, 102, 1) 50%,
  rgba(0, 0, 0, 1) 50%,
  rgba(0, 0, 0, 1) 75%,
  rgba(102, 102, 102, 1) 75%
);
```

**Comment by tomasklaen** [comment]
@Natural-Harmonia-Gropius no. Here's what's supported: https://aegi.vmoe.info/docs/3.0/ASS_Tags/

**Comment by po5** [comment]
It does not. To achieve gradients in ass, you either need hardcoded stripes of "pixels", or a big unicolor drawing with a high blur and a \\clip.  
The most common way to achieve textures in ass is through specially crafted fonts, e.g. the popular grain.ttf which turns each character into a different style of grain-like texture.  
You can do cropping before feeding an image to ovaylay-add, through discarding specific portions of the bgra data. I wouldn't recommend it, however.

**Comment by tomasklaen** [comment]
Yeah I was just playing with using ░ character to draw this:

![image](https://user-images.githubusercontent.com/47283320/190403705-f80d1ac7-d6a4-4722-bab2-709ac78aaf75.png)

Doesn't look as good, I can't get rid of the visible bands, and I don't know how consistent this would be on various systems with different fonts.

@po5 you're saying there are fonts designed to draw stuff like this? Can you give me some pointers/links/names?

**Comment by Natural-Harmonia-Gropius** [comment]
https://www.dafont.com/code-128.font
what about `0034` with `\i`

**Comment by christoph-heinrich** [comment]
I don't see a problem with how things look currently (screenshots are with `timeline_cached_ranges=ffffff:0.50`)
![cached_playing](https://user-images.githubusercontent.com/8932183/190413673-d73143f4-dedb-47c7-9cbb-1ccf92bcf8d1.png)
![cache_paused](https://user-images.githubusercontent.com/8932183/190413682-3dc5b3a3-bf79-4f45-92a9-6237f4fd781f.png)

**Comment by christoph-heinrich** [comment]
If you're willing to compile mpv yourself, I'd recommend to use something like
``` diff
diff --git a/sub/osd_libass.c b/sub/osd_libass.c
index c916c530c2..82eb94ae3c 100644
--- a/sub/osd_libass.c
+++ b/sub/osd_libass.c
@@ -16,6 +16,7 @@
  */
 
 #include <math.h>
+#include <stdint.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
@@ -29,6 +30,7 @@
 #include "common/msg.h"
 #include "osd.h"
 #include "osd_state.h"
+#include "osdep/timer.h"
 
 static const char osd_font_pfb[] =
 #include "generated/sub/osd_font.otf.inc"
@@ -635,6 +637,8 @@ void osd_set_external_remove_owner(struct osd_state *osd, void *owner)
     pthread_mutex_unlock(&osd->lock);
 }
 
+double time_filtered = 300.0;
+
 static void append_ass(struct ass_state *ass, struct mp_osd_res *res,
                        ASS_Image **img_list, bool *changed)
 {
@@ -648,8 +652,14 @@ static void append_ass(struct ass_state *ass, struct mp_osd_res *res,
     ass_set_frame_size(ass->render, res->w, res->h);
     ass_set_pixel_aspect(ass->render, res->display_par);
 
+    int64_t time = mp_time_us();
     int ass_changed;
     *img_list = ass_render_frame(ass->render, ass->track, 0, &ass_changed);
+    time = mp_time_us() - time;
+    if(time > 2) {
+        time_filtered = time_filtered * 0.99  + time * 0.01;
+        printf("%f\n", time_filtered);
+    }
 
     ass->changed |= ass_changed;

``` 
This measures time spent in libass in microseconds, with a simple lowpass filter because it's rather noisy otherwise.
By default after opening mpv there a re two overlays. One for uosc and one for console. The if is there to filter out the console overlay (time is very short when console isn't open).

**Comment by tomasklaen** [comment]
The problem is bars on top of bars on top of bars each with its own opacity. Your inversion proposal will add another bar. It's not pretty or clear.

Stripes would add a new indicator paradigm, a texture, and it'd be the only texture there, so no confusion.

I'll research creating my own font and implementing it that way. If that doesn't work out, I'll draw cached ranges with full opacity, separated from foreground by 1 px (clicking them will still click timeline).

**Comment by christoph-heinrich** [comment]
I do agree that the stripes from the first screenshot are better then what we currently have visually, but I'm worried about the performance impact of where this is going. Maybe providing the stripes as a bitmap and then tiling that would be faster? But I don't know if that's really an option here. [visualizer.lua](https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua) embeds an image, but gives that to ffmpeg instead of drawing as a subtitle.

**Comment by tomasklaen** [comment]
Success!

![image](https://user-images.githubusercontent.com/47283320/190654096-62af81e6-426b-452d-987d-1a4e5b364507.png)

Texture is a 100px square glyph, so we only need to render a couple dozen chars to cover the screen. And I can't detect any CPU slowdown.

But check the stripes branch for static example (don't forget to use the fonts from there, that's where the textures are), and refer if you see any issues with rendering or CPU cost.

**Comment by christoph-heinrich** [comment]
For me rendering time went from ~210us to ~390us in the minimized state.

**Comment by christoph-heinrich** [comment]
Visibility of chapters:
![Screenshot_20220916_171514](https://user-images.githubusercontent.com/8932183/190674225-95b61e4c-2430-4309-b40e-00103491c118.png)
![Screenshot_20220916_171755](https://user-images.githubusercontent.com/8932183/190674231-cd433b1e-0d81-4a3a-bcbc-b41fe2077500.png)

**Comment by tomasklaen** [comment]
@christoph-heinrich awesome! those are all insignificant numbers, so I'm gonna polish it up a bit and merge to main.

Chapters: I've already tweaked dots to be more visible, and I'll do a pass for lines as well.

> Btw I'm surprised that it's absolutely seamless using glyphs 👍

I was too :) but if you think about it, monospace fonts were used to draw seamless boxes in terminals for decades now, so it should be expected from any font rendering engine to tile them properly.

**Comment by tomasklaen** [comment]
So I did improve the chapter rendering, in c909409, but still didn't like it. There were still visibility issues and all of the indicators on top of each other were still getting crowded even after changing the cached ranges to stripes.

So I decided to scrap the current chapters rendering and redesign it with diamonds on top of the timeline:

![image](https://user-images.githubusercontent.com/47283320/190902522-a1e8968c-9f39-4384-8ee4-7e58e400a820.png)

And minified:

![image](https://user-images.githubusercontent.com/47283320/190902533-724f4131-456b-4842-ae1c-eda2365c6720.png)

I think it looks great, don't see any visibility issues, the code is much simpler, config file is slimmed down. Only positives :)

**Comment by Natural-Harmonia-Gropius** [comment]
I want to keep the `lines` with `width = 1` here, I prefer the low-profile style.

**Comment by tomasklaen** [comment]
I'm sorry but I'm not going back to lines. When you had chapter range edge, progress edge, chapter line, and maybe cursor indicators all near each other it was incredibly crowded and hard to judge what's going on. It was objectively terrible.

But I've changed the `timeline_chapters` boolean option to `timeline_chapters_opacity` so you can control how noticeable they are to hopefully satisfy your low-profile requirement.
