### ISSUE TITLE
Showing cache remaining time in the timeline bar.

### ISSUE THREAD

**Issue by RexAckermann** [tomasklaen/uosc#208]
It's something that is available on the default osc ,I think it might be a good idea to add the option to view it.Thanks in advance,

**Comment by omaru-ok** [comment]
> It's something that is available on the default osc ,I think it might be a good idea to add the option to view it.Thanks in advance,

hmm  owner . can make it like a option to bind to certain moment for cache seek?

**Comment by po5** [comment]
I don't know where you'd display this and why, knowing the total cache time isn't very useful, unless it happens to all be ahead of the current position.

mpv's info pane exposes this information if you only want to check it occasionally, which seems like the only use case to me.

Displaying *upcoming* cache remaining time may be useful however, to know how much useful video you have buffered.

**Comment by RexAckermann** [comment]
> I don't know where you'd display this and why, knowing the total cache time isn't very useful, unless it happens to all be ahead of the current position.
> 
> mpv's info pane exposes this information if you only want to check it occasionally, which seems like the only use case to me.
> 
> Displaying _upcoming_ cache remaining time may be useful however, to know how much useful video you have buffered.
Yes , this is what I meant ,"Displaying upcoming cache remaining time" 
Thanks ,for making it clear.

**Comment by tomasklaen** [comment]
With commit above, buffered time is displayed when lower than 60 seconds. Here's how it looks like at:

![image](https://user-images.githubusercontent.com/47283320/190990482-c2c28e84-e7fc-4f81-ad17-fb1ff0abc2dc.png)

![image](https://user-images.githubusercontent.com/47283320/190990735-91da1f95-7fe6-4bc7-bf20-110603d4d9c9.png)

![image](https://user-images.githubusercontent.com/47283320/190990782-1a33cc53-9281-4a62-b1cd-76d9cc732258.png)

**Comment by omaru-ok** [comment]
> With commit above, buffered time is displayed when lower than 60 seconds. Here's how it looks like at:
> 
> ![image](https://user-images.githubusercontent.com/47283320/190990482-c2c28e84-e7fc-4f81-ad17-fb1ff0abc2dc.png)
> 
> ![image](https://user-images.githubusercontent.com/47283320/190990735-91da1f95-7fe6-4bc7-bf20-110603d4d9c9.png)
> 
> ![image](https://user-images.githubusercontent.com/47283320/190990782-1a33cc53-9281-4a62-b1cd-76d9cc732258.png)

when is goin to happend new realease?

**Comment by tomasklaen** [comment]
Today or tomorrow hopefully.
