### ISSUE TITLE
Clicking the end of the timeline loads next item, but moving the mouse anywhere on the screen causes seeking

### ISSUE THREAD

**Issue by maaldheefee** [tomasklaen/uosc#211]
**Steps:** Click the end of the timeline (to skip to next item)

**Expected behavior:** Current item ends and next item starts playing normally

**Current behavior:** Next item loads, but the click is not "released", so moving the mouse anywhere on the screen causes seeking, as if I'm clicking and dragging on the timeline. I have to click somewhere on the timeline again to stop this behavior.

It doesn't happen 100% of the time.

**Comment by tomasklaen** [comment]
This should fix it.
