### ISSUE TITLE
First uncached range looks different to the rest

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#215]
It seemed like the first uncached range looked slightly different to the rest, so I started investigating.
Setting the `texture_opts.opacity` to 1 made it very clear that for some reason the first uncached area is rendered differently to the rest. No idea what's going on here.
![timeline_texture](https://user-images.githubusercontent.com/8932183/190933738-7ba98fcd-b765-416f-8417-63985df653d6.png)
It doesn't matter if the first range starts at 0 or above, it always looks different.

---
On a related note, why switch between `a` and `b` texture? The switch is slightly jarring, and simply sticking with `a` looks fine imo.

**Comment by tomasklaen** [comment]
I wasn't resetting texture shift.

I'm switching to a more dense texture to improve visibility when minimized. I've changed the swap point to the last pixel of sliding so it's less perceptible now.
