### ISSUE TITLE
weird texture on some menus' background

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#229]
![Snipaste_2022-09-20_11-03-05](https://user-images.githubusercontent.com/41094733/191230009-30eeed18-b204-44a9-85eb-6e64f8a667ca.jpg)

Is it designed? I'm not sure.

**Comment by tomasklaen** [comment]
It should look like this:

![image](https://user-images.githubusercontent.com/47283320/191233527-68e31f9e-fa67-4d68-8c97-8f9b8319bd29.png)

Are you using current uosc and fonts from main?

**Comment by hooke007** [comment]
Ah, I didn't notice the default font was changed.

**Comment by omaru-ok** [comment]
> It should look like this:
> 
> ![image](https://user-images.githubusercontent.com/47283320/191233527-68e31f9e-fa67-4d68-8c97-8f9b8319bd29.png)
> 
> Are you using current uosc and fonts from main?

how can we combine JETbrain mono with that   i mean 


like oscfont+ jetbrain  mono 

```--osd-font=Jetbrain mono``` ?

**Comment by tomasklaen** [comment]
uosc inherits font from mpv.conf. It's [in the docs](https://github.com/tomasklaen/uosc#options).
