### ISSUE TITLE
`speed_opacity` does not appear to work

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#231]
It appears as if the `speed_opacity` setting does not work at the moment. I found the dark background to be too distracting and wanted to tone it down a bit by reducing the opacity of the entire bar (since the background isn't configurable by itself – not sure if it should be), but specifyng `speed_opacity=0.3` in my config file doesn't seem to have an effect.

**Comment by tomasklaen** [comment]
Yeah after recent reworks to controls bar this setting is mostly ignored now.

What would you expect it to control? Opacity of the background, or the whole thing including notches and text?

**Comment by christoph-heinrich** [comment]
With all text being completely opaque now, I think it should control background only.

**Comment by FichteFoll** [comment]
I'm very much fine with background only as I fear the foreground might become too hard to read once I've toned down the background enough to not distract me.
