### ISSUE TITLE
Update video in readme 

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#234]
With all the recent features (thumbnails) that have been added, updating the video to showcase these changes would be great. Especially for people discovering uosc for the first time.

**Comment by hooke007** [comment]
But it matches the current release version.

**Comment by tomasklaen** [comment]
As @hooke007 said, the readme is for current stable release.

**Comment by Zabooby** [comment]
I see, once the new release comes out will you update the video too?

**Comment by tomasklaen** [comment]
I always treated the "minimalist" as describing a design philosophy and not a feature set, but I see how it mean the latter to people, so I don't mind changing the tagline. If anyone has a good idea I'm all ears.

**Comment by christoph-heinrich** [comment]
```
Minimalist and feature-rich proximity based UI replacement.
```
It's a small change, but it removes the ambiguity.

**Comment by FichteFoll** [comment]
*proximity-based
