### ISSUE TITLE
Minimise button doesn't align with maximise and restore buttons

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#236]
How it used to be:

![image](https://user-images.githubusercontent.com/78969986/191567028-6a80e1db-dc07-49c3-8389-326b84fd503e.png)

How it is now:

![image](https://user-images.githubusercontent.com/78969986/191567173-5be30420-a626-422f-8796-048455542a5e.png)

**Comment by tomasklaen** [comment]
It's just the way the minimize button is designed in the icon set we are using. It's supposed to be the bottom part of the square, which is imo semantically more accurate to its purpose.

Either way, it's fine.
