### ISSUE TITLE
Questions about text backgrounds and menu textures.

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#237]
I recently updated uosc and have come across 2 changes that I don't know how to revert back to its state in older versions:

I can't figure out how to remove the background behind text as well as the playlist/chapter number:

![image](https://user-images.githubusercontent.com/78969986/191582366-8e37088e-a486-4aa6-94cb-fd6a0df2e88d.png)

Like this: 

![image](https://user-images.githubusercontent.com/78969986/191582592-b422a15a-5fdd-4cac-a0ca-f6bab8bdecb0.png)

Also this weird texture that appears only in the open file menu:

![image](https://user-images.githubusercontent.com/78969986/191582941-b6727d18-8986-4c6f-b2da-69bbe1e7aff5.png)

How it used to be:

![image](https://user-images.githubusercontent.com/78969986/191583306-9657c4df-399f-483a-81dc-544744a5c6d7.png)

**Comment by tomasklaen** [comment]
Top bar having a background is necessary because of #168.

Menu title has a texture so it's visually distinctive from both normal items and active items.

I'll not be making this customizable.

**Comment by Zabooby** [comment]
Have you thought about bringing the title to the bottom like in mpv's built in osc?
I think it could look cleaner with everything at the bottom.

![image](https://user-images.githubusercontent.com/78969986/191589005-1cdb5c54-4eb4-451e-9eaa-c288dc006faa.png)

**Comment by Zabooby** [comment]
> Have you thought about bringing the title to the bottom like in mpv's built in osc? I think it could look cleaner with everything at the bottom.
> 
> ![image](https://user-images.githubusercontent.com/78969986/191589005-1cdb5c54-4eb4-451e-9eaa-c288dc006faa.png)

Also this way you get all the information you need about the file being played by one mouse hover rather than having to hover both the top and bottom.

**Comment by Zabooby** [comment]
Would you mind if I opened a new issue for this to get peoples thoughts?

**Comment by tomasklaen** [comment]
I'm not putting title into timeline. This is not my design direction:

![image](https://user-images.githubusercontent.com/47283320/191594053-dd8399ee-c618-44d4-b048-d05635240474.png)

You should use mouse when you want to control something with it. If you want to check some ui state, bind `toggle-ui` to a key like <kbd>tab</kbd>.

And no, the answer to your issue getting closed is not to create a new issue.

If you want every pixel of a UI to cater to your tastes, you'll have to create your own.

**Comment by FichteFoll** [comment]
How about adding opacity settings for the top bar? It's about the only control widget that doesn't have one (aside from controls).

**Comment by tomasklaen** [comment]
My dudes, I swear if you started using uosc at 4.0, and I changed it to how 3.0 looks, you'd be creating issues in the opposite direction.

But here's the option.

**Comment by FichteFoll** [comment]
Thanks, I love unreadable titles. :upside_down_face: 

(To be honest, I just think the contrast is a bit to high and tone everything down a bit, except for the timeline which is fine.)
