### ISSUE TITLE
mpv's core options `--osd-*` would mess up the rendering of uosc

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#241]
To fast reproduce and check, set `osd-back-color=1` in mpv.conf.

Here is the preview:

UOSC ——
![Snipaste_2022-09-22_17-21-52](https://user-images.githubusercontent.com/41094733/191801272-521b26f1-715a-4435-bc16-f80fb49c6d4d.jpg)

But Original OSC would not be affected by those options.

![Snipaste_2022-09-22_17-20-29](https://user-images.githubusercontent.com/41094733/191801617-33301c80-4010-4bc6-9f42-29c6327be4d4.jpg)

**Comment by tomasklaen** [comment]
😨 I have no idea what `osd-back-color` is doing. It's setting background to texts it seems, but I don't know how. The ass tags documentation I'm using: https://aegi.vmoe.info/docs/3.0/ASS_Tags/#index21h3
doesn't mention anything about text backgrounds or how to cancel it. I've tried some reset tag `\r` but it made no difference.

**Comment by tomasklaen** [comment]
Also didn't notice anything in the https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua file that would be trying to prevent this.

**Comment by hooke007** [comment]
It's funny I saw a user want OSC to respect those options. https://github.com/mpv-player/mpv/issues/5809

**Comment by pjeanjean** [comment]
I think this is set in the style, specifically through BorderStyle, right there : https://github.com/mpv-player/mpv/blob/eca78ee9259bd477e6a8073165e3ebe22bc4423e/sub/ass_mp.c#L66

It looks like setting the style to Default by adding `\\rDefault` to the tags in `ass_mt:txt` fixes a bunch of these, but I can't tell if there are side effects to that.

**Comment by hooke007** [comment]
@tomasklaen

> It looks like setting the style to Default by adding \\rDefault to the tags in ass_mt:txt fixes a bunch of these, but I can't tell if there are side effects to that.

Yeah `\\rDefault` works, had tested some options and no issue found so far.
