### ISSUE TITLE
OSD disappeared

### ISSUE THREAD

**Issue by vmv** [tomasklaen/uosc#247]
Using this lines in mpv.conf, and uosc stops working:
1: this will make uosc to look weird:
`cache = yes
  demuxer-max-bytes = 500M`
 2: this makes uosc completely not working:
  ` script-opts-add=uosc-chapter_ranges="^op |^op$| op$|opening$<ffcf81:0.5>.*, ^ed |^ed$| ed$|ending$<ffcf81:0.5>.*|{eof}, ^intro$<ffcf81:0.5>.*, ^outro$<ffcf81:0.  5>.*|{eof}, sponsor start<64e2ff:.5>sponsor end, segment start<64e2ff:0.5>segment end, ^sponsors?<64e2ff:.5>.*"`

**Comment by tomasklaen** [comment]
What version are you on?

**Comment by vmv** [comment]
I know they are commented man.. :)
Dev version, for helping out.

**Comment by tomasklaen** [comment]
`chapter_ranges` changed, your config is now invalid. Read the `uosc.conf` for new config docs.

But this is a problem. I can make it not break, but even then all people with old configs will now have broken chapter ranges :/

I guess I'll have to detect old default and swap it for the new one, because I don't want to rename the option.

**Comment by vmv** [comment]
New is always better.. just tell me what to do.. thanks.
I'm fine for now, no rush.

**Comment by tomasklaen** [comment]
Read the new `script-opts/uosc.conf` file, it's all documentded there.

**Comment by tomasklaen** [comment]
This is not resolved yet. I need make it not break and use new defaults on old configs still.

**Comment by vmv** [comment]
Ok, thanks.. you know better.

**Comment by omaru-ok** [comment]
ayo please make new release :(

**Comment by tomasklaen** [comment]
@omaru-ok please stop posting into this issue tracker. Every one of your posts is a full quote of the previous one and a line like "whoa", or asking for a new release. This is no longer just off-topic, this is borderline spam.

**Comment by dyphire** [comment]
To be honest, I prefer the old option. Some animations have Japanese chapters: opening→オープニング; ending→エンディング.
The old option can well include it. After reconstruction, I can only modify the script to achieve this.

Opening a PR to add these names is trivial, but I'm afraid it will lead to potential multilingual chapter requirements.
Is it possible to add a new option to mimic the old chapter title customization?

**Comment by tomasklaen** [comment]
^ should solve this.

**Comment by vmv** [comment]
still, using option 1, cache= .. wreaks the bottom bar

**Comment by vmv** [comment]
https://imgur.com/nYnx2PU
![Screenshot_2](https://user-images.githubusercontent.com/17906882/192002534-45f62bdf-690f-443a-94cf-b8aa513cc0c5.png)

**Comment by tomasklaen** [comment]
Yeah when there's cache present, the UI displays what parts of the timeline are not cached. That is correct behavior.

**Comment by vmv** [comment]
ok
