### ISSUE TITLE
Submenus appear briefly when they shouldn't

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#248]
When clicking the menu button or using a hotkey to open the menu the top submenu briefly shows until the cursor moves.

https://user-images.githubusercontent.com/78969986/191933941-0dafe0f1-e24f-4657-951e-99e0505b13db.mp4

**Comment by Zabooby** [comment]
The menu button issue is fixed now but the issue is still occurring when using a hotkey to open the menu. 

Can you replicate this, I'm using my right click mouse button if that matters?

**Comment by tomasklaen** [comment]
Just inspect the commit above. It implemented `menu-blurred` command. Use that in your hotkey if you want to open a menu that doesn't pre-select an item.

**Comment by Zabooby** [comment]
My bad, its working fine now.
