### ISSUE TITLE
Playlist getting extended when using Shuffle button

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#250]
Refer to https://github.com/tomasklaen/uosc/issues/235#issuecomment-1256074159

Making this issue just in case if it was missed out.

**Comment by tomasklaen** [comment]
It wasn't I was just working on other things.

Yeah I have no idea what's going on there. All I'm doing is:

```lua
mp.commandv('playlist-play-index', new_random_index)
```

when at the end of the file. This is the whole function:

```lua
function navigate_playlist(delta)
	local playlist, pos = mp.get_property_native('playlist'), mp.get_property_native('playlist-pos-1')
	if playlist and #playlist > 1 and pos then
		local index = decide_navigation_in_list(playlist, pos, delta)
		if index then mp.commandv('playlist-play-index', index - 1) return true end
	end
	return false
end
```

**Comment by hooke007** [comment]
It must some other scripts like autoload did it.

**Comment by tomasklaen** [comment]
@hooke007 thank you! I was bracing for hours of frustrating debugging :)

**Comment by NaiveInvestigator** [comment]
yep it works now as intended after removing autoload.lua . Could we add this as like a warning on the README on the next release?

**Comment by tomasklaen** [comment]
As I understand it this is a bug in autoload that manifests even without uosc, right? I don't think I should inform people about bugs from other scripts.

**Comment by hooke007** [comment]
Off topic:
Now I found it a known bug. https://github.com/mpv-player/mpv/issues/8575
Another worse bug: https://github.com/mpv-player/mpv/issues/8969
