### ISSUE TITLE
config confusion ! 

### ISSUE THREAD

**Issue by omaru-ok** [tomasklaen/uosc#259]
![image](https://user-images.githubusercontent.com/108952834/192095289-f157b6cf-544f-48c5-9dcb-dcd0e3f0d29a.png)
i want to change that <diamand > llike chapter indicator . and that //////  pattern of saying for cache ranges i want to change them ? 
is there any option available?

**Comment by hooke007** [comment]
No

**Comment by omaru-ok** [comment]
> 

sad mooment

**Comment by hooke007** [comment]
I had never seen that any osc-like script would allow user to replace the UI elements.

The ones who share the similar demands —— they chose to write their own OSC script.

**Comment by FichteFoll** [comment]
I liked the line chapters a lot as well, but I also realize that with the striping they would be hard to make out …

**Comment by Zabooby** [comment]
I installed [fontforge]( https://github.com/fontforge/fontforge) to try and customise textures and I was able to change the open file menu texture. @omaru-ok this might be what you're looking for?

Which letters are textures actually used by uosc, I noticed a bunch of extra textures that don't seemed to be used anywhere. I already know n is used for the menu texture?

**Comment by omaru-ok** [comment]
> I installed [fontforge](https://github.com/fontforge/fontforge) to try and customise textures and I was able to change the open file menu texture. @omaru-ok this might be what you're looking for?
> 
> Which letters are textures actually used by uosc, I noticed a bunch of extra textures that don't seemed to be used anywhere. I already know n is used for the menu texture?

woah . 
idk bro just make em  little like older uosc used to be . like   :)

**Comment by Zabooby** [comment]
> I had never seen that any osc-like script would allow user to replace the UI-elements' texture.
> 
> The ones who share the similar demands —— they chose to write their own OSC script.

I found [fontforge](https://github.com/fontforge/fontforge) which lets me edit the textures file and was able to customise the open file menu texture. 

Which letters are textures actually used by uosc, I noticed a bunch of extra textures that don't seemed to be used anywhere. I already know n is used for the menu texture?

**Comment by hooke007** [comment]
> I found [fontforge](https://github.com/fontforge/fontforge) which lets me edit the textures file and was able to customise the open file menu texture.

Of course, re-encoding the font is a hacky but feasible solution.

> Which letters are textures actually used by uosc

https://github.com/tomasklaen/uosc/commit/c909409254321e437dcb392ed235a60cdf4aa160#diff-c50787032c5c7cbca7c979ffc03182fb4222da761006e97e7363ef3c849e27d5

So far seems only a/b/n

**Comment by hooke007** [comment]
These Qs ought to be answer by @tomasklaen :-)

**Comment by Natural-Harmonia-Gropius** [comment]
If you want `chapter_style=lines`, Try this out.
https://github.com/Natural-Harmonia-Gropius/uosc/commit/e0c993d79a8bfbd225b7797696ba700d2d126a12

**Comment by omaru-ok** [comment]
> If you want `chapter_style=lines`, Try this out. [Natural-Harmonia-Gropius@e0c993d](https://github.com/Natural-Harmonia-Gropius/uosc/commit/e0c993d79a8bfbd225b7797696ba700d2d126a12)
> 
> About textures, 😓. ![image](https://user-images.githubusercontent.com/50797982/192102194-9ffa575a-e7cf-4268-a218-4609e89ff6bb.png)

yes yes . instaed of giving me this texture gime nothign 🤣  
yep i do not like texture in uosc menu

**Comment by tomasklaen** [comment]
> What's the reason for having extra textures?

I was making a textures file, and wanted to include some I might use in the future.

> Could my solution break things in the future?

Just obvious issues: your uosc will not look like it was intended to.

> Do you plan on adding more textures to the ui?

I don't see that far into the future.

> I found [fontforge](https://github.com/fontforge/fontforge) which lets me edit the textures file and was able to...

Or you know, you can try to just be content with defaults, and not waste so much time ricing every pixel on your screen :)

---

@omaru-ok 90% of your messages are spamming, demanding new version release, or being rude. I'm 1 post away from blocking you.
