### ISSUE TITLE
Menu is a black bar

### ISSUE THREAD

**Issue by burnergit1** [tomasklaen/uosc#268]
Windows 10
mpv installed with scoop

![mpv_xwj0vRqeRe](https://user-images.githubusercontent.com/114365129/192166507-9f59d76c-9125-4cb5-9d1f-76f03ddd8384.png)

**Comment by Zabooby** [comment]
You have to add things to the menu, pretty sure it is empty by default.
Read the readme for more details.

**Comment by omaru-ok** [comment]
> Windows 10 mpv installed with scoop
 please provide more info as uosc.conf

**Comment by hooke007** [comment]
> pretty sure it is empty by default

Nope. You could delete your input.conf to get the default menu.

**Comment by christoph-heinrich** [comment]
I think if there isn't a menu defined in the input.conf, it should still show the default config instead of an empty one. I'll have a look later.

**Comment by burnergit1** [comment]
> > Windows 10 mpv installed with scoop
> 
> please provide more info as uosc.conf

default


> > pretty sure it is empty by default
> 
> Nope. You could delete your input.conf to get the default menu.

no such file

**Comment by christoph-heinrich** [comment]
#269 should solve your problem
