### ISSUE TITLE
Incompatibility with Syncplay's chat feature

### ISSUE THREAD

**Issue by Tsukreya** [tomasklaen/uosc#27]
[Syncplay](https://github.com/Syncplay/syncplay/) is a media playback synchronization program, you can use mpv with it. They have a chat feature, allowing you to type and display messages directly in mpv's window, but it seems to break uosc rendering.

I use newest uosc, mpv build 0.32.0, syncplay 1.6.4a on Windows.

Steps to reproduce this bug:
1. Install Syncplay, choose mpv as a player, enable chat input and/or output in settings.
2. Open a video in a room, and display the UI by interacting with the player.
3. The playback bar seems to be higher than it should be, and the volume bar parts from its frame.

Screenshot of the issue: 
https://ptpimg.me/hvjnv1.png

The problem doesn't arise if chat output is turned off, and chat input is set to 'bottom' or 'middle' in Syncplay. 
I don't know if this is an issue with how syncplay handles things, and if this is even fixable, but I cannot seem to find a workaround (the chat function is quite crucial to me), and I really like the uosc UI.

**Comment by darsain** [comment]
I'll look into it, but can't say when. Quite a lot of other things on my plate atm.

**Comment by Tsukreya** [comment]
That is alright, cheers!

**Comment by tomasklaen** [comment]
@pjeanjean thx for clarifying :) I guess I can close this now. And I think I'll make a wiki page for it. Don't want to fill readme with interoperability notes for every script out there.
