### ISSUE TITLE
vim-key to navigate in menu : request

### ISSUE THREAD

**Issue by omaru-ok** [tomasklaen/uosc#275]
![image](https://user-images.githubusercontent.com/108952834/192890582-9834cc64-f550-4985-8af4-0e84afbb5782.png)
im trying to get  **j,k,h,l**  as up,down,left,rigt  etc  at the menu ,   same as `vim-navigation` 

i do remember  uosc had this in old version ? maybe  
can i have it now? 🙏  sorry if i make mistake . please forgive me

**Comment by hooke007** [comment]
It was removed
https://github.com/tomasklaen/uosc/commit/f27e17e7dcbe89aa6d3655c8cf2c741c60c1da10

**Comment by tomasklaen** [comment]
I removed it because supporting 3 different shortcut groups was a bit over the top, and also as a preparation to potentially implementing #198 in the future.

**Comment by christoph-heinrich** [comment]
You could make a branch where you add it back in and when you want to update, pull upstream main and then rebase your branch onto that.
