### ISSUE TITLE
Cursor autohide not restored

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#28]
Minimizing the bar with `peek-timeline` when hovering on it doesn't re-enable cursor autohide.

**Comment by darsain** [comment]
Could you elaborate? With steps to reproduce and expected behavior? Because everything I try is working fine.

**Comment by po5** [comment]
Make sure cursor autohide is enabled, hover the fullsize progress bar, press a key bound to `uosc/peek-timeline`.
Expected behavior: the cursor autohides as the bar is no longer visible

**Comment by darsain** [comment]
>  Expected behavior: the cursor autohides as the bar is no longer visible

The cursor autohides when mpv autohides it, and that is exactly what is happening for me, so can't replicate.

Note: uosc doesn't autohide the cursor, it just tries to sync hiding of uosc elements to when mpv autohides the cursor. The cursor autohiding is done by mpv.

**Comment by po5** [comment]
Some UI elements like the volume bar, progress bar and menu prevent cursor autohide on hover, I assume that's what going on here.

**Comment by darsain** [comment]
Still can't replicate. They don't prevent autohide for me. And I don't remember implementing any autohide prevention, so... no idea.

**Comment by tomasklaen** [comment]
No matter what I try I can't reproduce this, so until someone provides steps to actually reproduce, I'll keep this closed.
