### ISSUE TITLE
Handle small window sizes

### ISSUE THREAD

**Issue by maaldheefee** [tomasklaen/uosc#280]
Please add some ways to handle small window sizes. Either by hiding some elements if there's not enough space, or scaling after a certain threshold.

![image](https://user-images.githubusercontent.com/16198035/193245779-083a03f2-59f6-4a7e-94ee-0dd7bff7382f.png)

In the mean time, is there a command to turn off or hide the whole UI?

**Comment by tomasklaen** [comment]
Every app solves this issue by requiring a min window size. uosc can't do this on its own, so you should set this in your `mpv.conf`:

```conf
autofit-smaller=400x400
```

Or do you actually want uosc to support windows that small? Because that's definitely a wontfix.

**Comment by maaldheefee** [comment]
Is there a way to toggle the whole UI?

**Comment by maaldheefee** [comment]
I want to be able to keep the window on top and use it similar to picture-in-picture mode. Even at 400x400 the UI is takes up too much space and the elements are very close together, so being able to hide the whole UI would be useful.

**Comment by hooke007** [comment]
I guess what you want is sth like `visibility` ?
https://github.com/mpv-player/mpv/blob/98e6fb26a3e03ae58d7026d4a28df3074a7459dc/player/lua/osc.lua#L47

**Comment by maaldheefee** [comment]
Yes. https://mpv.io/manual/master/#on-screen-controller-visibility

**Comment by tomasklaen** [comment]
Elements now disable themselves one by one based on available space to prevent collisions.

The order is: volume > controls > timeline. Top bar, when enabled, has the highest priority.
