### ISSUE TITLE
Self updating menus loose selection on active prop change

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#282]
Started happening with 0ad72e5f85002406e962042a07f4120b981b2701.

This used to be particularly noticeable with the chapter menu, because it's active prop was `playback-time` and so this constantly happened during playback. That has improved a lot with the recent commit 5b70a762e0f51591fa1279d0ea513ca4a160296e, but it does still happen when the current chapter changes.

I still had an mpv instance open from before that commit, which is where I noticed it. Here is a recording from that instance.

https://user-images.githubusercontent.com/8932183/193411758-f249b61a-4393-483b-b829-c2b5dd9c634f.mp4

To solve this we could either bring back a separate serializer for the active prop, or always open a new menu where we select the same item as before instead of updating it, but loosing the selection does make sense when the list itself actually changes.

**Comment by tomasklaen** [comment]
Can't replicate:

[2022-10-01-17-46-26.webm](https://user-images.githubusercontent.com/47283320/193426149-9f9e5159-2a9b-4d6a-ba11-9979f0485b6f.webm)

And it also shouldn't happen. The only time the selected index gets niled is when menu gets updated in a sequence of "items > no items > items".

**Comment by christoph-heinrich** [comment]
So I've now tried it again and it automatically selects the first item if nothing is selected due to mouse movement. Selecting things with keyboard works perfectly fine. So in the video above it got unselected due to mouse movement, and immediately after selected again because the active prop `playback-time` changed.

**Comment by christoph-heinrich** [comment]
From a quick test, simply setting the selected_index to `-1` instead of `nil` in `on_global_mouse_move()` works, but it breaks a few things. What do you think of wrapping around in menus? So when you're at the first item and press up, the last item gets selected.
Then `next()` and `prev()` could treat out of range values just like nil.

**Comment by dyphire** [comment]
> I've now tried it again and it automatically selects the first item if nothing is selected due to mouse movement. 

Can't replicate, but it automatically selects the first item when the current chapter changes in my tests. The pr https://github.com/tomasklaen/uosc/pull/284 can fix it.

**Comment by tomasklaen** [comment]
I still can't replicate the issue described here. And since @dyphire can't either, do you maybe have your own uosc fork with some outdated code?

I did see what @dyphire complained above (automatically selects the first item when the current chapter changes), and that is fixed in the commit above that refactors the navigation reset and item pre-selection. Dunno if it also affects this issue, because again, can't replicate, and don't see any issue in the code even after careful examination during refactoring.

The only time this can happen is if something briefly flushes all of the items in the menu (so navigation reset sets the selected_index to nil), and then re-applies them.

**Comment by christoph-heinrich** [comment]
I was using 40c675dd1f1ff4352ddf43fe6f2cb17e8660c5b7, so no outdated code or custom patches here.

I must have done a shit job describing the issue, because @dyphire said he can't replecate, but then described that he experienced the exact problem I'm talking about here, so he actually could replicate...

The commit above fixes the issue.
