### ISSUE TITLE
possible to have HDR passthrough

### ISSUE THREAD

**Issue by Nioh8** [tomasklaen/uosc#287]
thanks for the frontend its great, just wondering if you could implement HDR passthrough for use on windows as
referenced here: https://github.com/mpv-player/mpv/issues/10158

no worries if not but thanks anyway.

**Comment by po5** [comment]
uosc draws its UI with ass subtitles. Any HDR stuff regarding subs would most likely be the player's job, not uosc's.

**Comment by hooke007** [comment]
uosc is not a frontend at all. Nothing we could do here.
