### ISSUE TITLE
[FR] Adjust chapters timestamps based on playback speed

### ISSUE THREAD

**Issue by xfzv** [tomasklaen/uosc#288]
[oltodosel/show_chapters.lua](https://github.com/oltodosel/mpv-scripts/blob/master/show_chapters.lua) does this (bottom left corner):

https://user-images.githubusercontent.com/78810647/193477164-ac2c4474-605e-4303-ab7e-bfd31e6a7f37.mp4

It would be nice to get the same behavior with uosc.

**Comment by po5** [comment]
It makes sense for remaining time to scale with speed, but here you'd want to also change the current and hovered timestamps.  
It would break my workflow, would need a setting for it.

**Comment by hooke007** [comment]
> It makes sense for remaining time to scale with speed

+1.
But I cannot understand why the current time should be scaled with speed. And never seen a media player share the same behavior.

**Comment by tomasklaen** [comment]
I don't know. This seems more confusing than useful. As mentioned, it'd require scaling every timestamp with speed, which makes it impossible to judge where you actually are in the timeline without setting speed to 1 briefly.

So right now you're 1 against 3.
