### ISSUE TITLE
alass support

### ISSUE THREAD

**Issue by RexAckermann** [tomasklaen/uosc#290]
https://github.com/kaegi/alass

This looked like a good tool.Someone utilized it with mpv with this https://github.com/joaquintorres/autosubsync-mpv
But it breaks the uosc.Something goes wrong with theirs menu.lua.
Is it possible to intigrate that somehow ?

**Comment by tomasklaen** [comment]
I don't see why or how would their menu conflict with uosc, but I've tried testing it anyway and yeah, works fine. No issues.

**Comment by tomasklaen** [comment]
Maybe you're not following their installation instructions properly. You need to put all of their files into its own `scripts/autosubsync` directory, not just scatter them in `scripts`.

**Comment by RexAckermann** [comment]
> Maybe you're not following their installation instructions properly. You need to put all of their files into its own `scripts/autosubsync` directory, not just scatter them in `scripts`.

Okay ,thanks for the help.
The actual problem was ,I had an old menu script in the scipts dirrectory.I think having two menu.lua was causing the problem.
