### ISSUE TITLE
[Feature Request]: Allow all elements have their own individual colors

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#294]
![image](https://user-images.githubusercontent.com/72654596/193747583-5d6ef09f-05aa-411f-9508-191b82b16422.png)

I changed the hex value of `foreground` in my `uosc.conf` to red and thought it would change only the timeline's color but instead it changes almost the whole UI's color. I feel if we make all the elements have their own color would bring be neat! Might also help people to differentiate who also have similar icons for control buttons too. 

And also for some reason I tried to change the `foreground` color using auto conditional profiles but it didn't work. I think I might have missed something out. Here is my snippet.

```
[Youtube]
	profile-cond=get("path", ""):find("^https://www.youtube.com/") ~= nil or get("path", ""):find("^https://youtu.be/") ~= nil
	profile-restore=copy-equal
	ytdl-raw-options=sub-lang="en,en-GB",write-sub=,write-auto-sub=,ignore-config=
	sub-scale=0.5
	sub-back-color=0.0/0.75
	script-opts=uosc-foreground=e82511
```

**Comment by tomasklaen** [comment]
I'm trying to minimize configuration fatigue by not having options for every pixel on the screen., so I'm not going to implement and maintain a dozen and more options so that people can color their UI into a rainbow.

In fact, I'm going to remove 2 color options right now :)

**Comment by NaiveInvestigator** [comment]
Could we atleast just change only the color of the timeline? That would work really. ;-;

**Comment by tomasklaen** [comment]
You'll have to maintain your own fork.

**Comment by tomasklaen** [comment]
I've changed my mind, `*_text` color options are back. I've seen a screenshot with a valid use case for them.

But I'm still not adding a color option for every box and text on the screen. That's too much.

**Comment by NaiveInvestigator** [comment]
> You'll have to maintain your own fork.

I am still a novice at programming and have also pored over the code for hours but couldn't still figure out how to change the timeline color. Could we just add this as like an experimental feature for just only the timeline, if it breaks anything no need to maintain it. 

But if you still feel like not adding it if you could give me a hint on how to change the timeline color would be awesome! 

Sorry for bothering you again ;-;. I will try not to mention this topic later on in the future.

**Comment by christoph-heinrich** [comment]
``` diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index d189371..f4e17e1 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -2905,7 +2905,7 @@ function Timeline:render()
 	ass:draw_stop()
 
 	-- Progress
-	ass:rect(fax, fay, fbx, fby, {opacity = options.timeline_opacity})
+	ass:rect(fax, fay, fbx, fby, {opacity = options.timeline_opacity, color = '0000ff'})
 
 	-- Uncached ranges
 	local buffered_time = nil
```

**Comment by NaiveInvestigator** [comment]
TYSM!!! It seems i missed out the quotes since at the time i thought HEX values are numbers too so they don't need them but anyways tysm again!!
