### ISSUE TITLE
Mouse drag not propagated to other scripts

### ISSUE THREAD

**Issue by dumblob** [tomasklaen/uosc#295]
I did not study the code much but it seems mouse drag is being swallowed even if no action is bound to it in the given context/situation.

E.g. I would like `uosc` to work with `MBTN_LEFT  script-binding drag-to-pan
` in `input.conf` (drag-to-pan comes from https://github.com/occivink/mpv-image-viewer/blob/master/scripts/image-positioning.lua script). But the binding works only if I do not put `uosc` into `scripts/` folder.

Any hints how to propagate the binding instead of swallowing it?

**Comment by tomasklaen** [comment]
uosc doesn't intercept `MBTN_LEFT` unless the cursor is on top of an interactive element. So if you just click the background, you should get whatever you configured in your `input.conf`. I've just tried it with `MBTN_LEFT cycle pause` and everything works fine.

In other words, all mouse button bindings are completely disabled when cursor is not hovering any uosc element.

No idea what might be your issue, or what more I could do to make it not conflict with other stuff.

**Comment by hooke007** [comment]
I can reproduce this issue in my mpv config for images(using the similar script as image-positioning.lua)

**Comment by hooke007** [comment]
More finding here:

If using original osc instead --
I forced set `border=no` & `script-message osc-visibility always` . And then I could not make `script-binding drag-to-pan` work neither. I guess it should be 'mouse detecting area' which blocks `script-binding drag-to-pan` .

**Comment by tomasklaen** [comment]
We are intercepting mouse move. I guess that's the issue here. And there's no way around it. We need it to know where the mouse is to implement everything else in the UI. Can't just disable it.

**Comment by tomasklaen** [comment]
But the script should overwrite ours if it'd enable its bindings only when needed.

**Comment by dumblob** [comment]
> We are intercepting mouse move. I guess that's the issue here.

Yep, that exactly was also my guess when I skimmed the code quickly. Therefore my question whether the mouse drag could then be again re-emitted?

**Comment by tomasklaen** [comment]
Someone correct me if I'm wrong, but as far as I know, once you register `mouse_move` listener, that's it. The only way someone else gets those events is if they register their listener after us. I don't think there's an API that'd allow sharing.

Doesn't help that `mp.set_key_bindings()` is undocumented. I think I've just copy & pasted it from `osc.lua`.

**Comment by christoph-heinrich** [comment]
I didn't test it, but the [mouse-pos](https://mpv.io/manual/master/#command-interface-mouse-pos) property sounds suitable.

**Comment by christoph-heinrich** [comment]
Please test #301

**Comment by dumblob** [comment]
Thanks a lot! It works for me now.

Btw. I am surprised by this fast development - really could not even find the time to react and do more about this. Keep at it!
