### ISSUE TITLE
mpv window is still "active" after minimizing with uosc's minimize button

### ISSUE THREAD

**Issue by maaldheefee** [tomasklaen/uosc#296]
If I minimize with top bar minimize button, input keys are still active until I click another window. If I set `border=yes` and  `top_bar=always` and minimize with the with the real minimize button the window gets deactivated properly.

uosc version: f9981ce
OS: Windows 11 22H2

**Comment by tomasklaen** [comment]
To minimize we are simply calling the `cycle window-minimized` mpv command, who's implementation is completely outside of our hands. You'll have to search for or create an mpv issue if that still bothers you.
