### ISSUE TITLE
Suggestion: option to set title size

### ISSUE THREAD

**Issue by pintassilgo** [tomasklaen/uosc#297]
I just found this amazing script and am still learning about it. As I understand it, the most suitable way to set title size is with `top_bar_size`, but this also makes window buttons (minimize, maximize, exit) bigger which is undesired for me.

Default title size is small for me, but I don't want to change anything else.

Thanks.

**Comment by tomasklaen** [comment]
I want to prevent configuration fatigue by not bloating the config wile with a configuration option for every single pixel on the screen. The UI is already one of the most customizable and configurable ones out there.

If you truly need to control the size of every box and/or text of the UI independently, you'll have to maintain your own fork, or draw your own UI.
