### ISSUE TITLE
Play a local file, When drag timeline the buffering indicator repeatedly appear.

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [tomasklaen/uosc#304]
I think 1 second delay needs to be added to show the buffering indicator, sometimes a short appearance when playing online video, but the video is still playing.

https://user-images.githubusercontent.com/50797982/194522654-83de55b0-16e8-4243-9672-d81e9cf2a1bd.mp4

**Comment by christoph-heinrich** [comment]
Doesn't happen with #298.
