### ISSUE TITLE
UI dissappears if cursor is dragged at the very end of the timeline

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#305]
https://user-images.githubusercontent.com/72654596/194689560-c03bff09-aaa7-48f2-a15b-41efc946544c.mp4

Sorry for the choppy vid, I hope it makes sense tho.

Edit: On the second song I also dragged to the end but ig OBS didn't capture it properly. On the third song, the UI disappears.

**Comment by christoph-heinrich** [comment]
Please open the [console](https://mpv.io/manual/master/#console) when that happens. If it's a crash we can see where and why it crashed.

**Comment by NaiveInvestigator** [comment]
I get this after the UI dissappears
![image](https://user-images.githubusercontent.com/72654596/194690578-69f8c705-625a-459f-812f-a30c7c312fab.png)

Here is my audio profile if you need it too just in case:
```
[Audio]
	profile-cond=string.match(p.filename, "%.mp3$")~=nil or string.match(p.filename, "%.ogg$")~=nil or string.match(p.filename, "%.wav$")~=nil or string.match(p.filename, "%.flac$")~=nil or string.match(p.filename, "%.aac$")~=nil or string.match(p.filename, "%.wma$")~=nil or string.match(p.filename, "%.m4a$")~=nil or string.match(p.filename, "%.opus$")~=nil or string.match(p.filename, "%.vorbis$")~=nil or string.match(p.filename, "%.alac$")~=nil#  ("%.flac$" and "%.mp3$" are lua string patterns that match strings only if they ends in ".flac" or ".mp3" respectively).
	profile-restore=copy-equal
	fs=no
	geometry=20%+100%+0% # the syntax here is: <size of the window>+<x value of the position>+<y value of the position>
```

**Comment by Natural-Harmonia-Gropius** [comment]
The border has become transparent in recent versions or me, and this issue may be related to this.

**Comment by dyphire** [comment]
> The border has become transparent in recent versions for me, and the issue may be related to this.

The `*_opacity` options behavior changes after this commit https://github.com/tomasklaen/uosc/commit/f084a3ac4bdb69b6edf8128a24d50f4ff7cab8fc.

`timeline_opacity=0.9`, before:
![image](https://user-images.githubusercontent.com/61936050/194694851-ec907b8b-2653-4cbf-86af-3bdc8612f523.png)
`timeline_opacity=0.9`, after:
![image](https://user-images.githubusercontent.com/61936050/194694878-a93a55eb-8efc-4a4e-afd8-35d443513d0f.png)

But I'm not sure it's related to this issue.

**Comment by tomasklaen** [comment]
Should be fixed now.

**Comment by dyphire** [comment]
> Should be fixed now.

Will the `*_opacity` options behavior be fixed?

**Comment by tomasklaen** [comment]
What do you mean by "fix"? It works correctly now. 0.9 opacity is 90% visible. You want 0.9 to be fully opaque? Why?

**Comment by dyphire** [comment]
> What do you mean by "fix"? It works correctly now. 0.9 opacity is 90% visible. You want 0.9 to be fully opaque? Why?

> >  
> >  The `*_opacity` options behavior changes after this commit [f084a3a](https://github.com/tomasklaen/uosc/commit/f084a3ac4bdb69b6edf8128a24d50f4ff7cab8fc).  
> >  `timeline_opacity=0.9`, before: 
> > ![image](https://user-images.githubusercontent.com/61936050/194694851-ec907b8b-2653-4cbf-86af-3bdc8612f523.png) 
> > `timeline_opacity=0.9`, after: 
> > ![image](https://user-images.githubusercontent.com/61936050/194694878-a93a55eb-8efc-4a4e-afd8-35d443513d0f.png)
> > 

From the above screenshot comparison, it can be clearly seen that since [f084a3a](https://github.com/tomasklaen/uosc/commit/f084a3ac4bdb69b6edf8128a24d50f4ff7cab8fc) 0.9 opacity is not 90% visible. The behavior has been broken.

**Comment by tomasklaen** [comment]
You need to clarify what exactly you mean here, because your screenshots are telling the opposite story than you. And no matter what I try (normal or with `osd-back-color=1`), opacity just works fine.

**Comment by dyphire** [comment]
> You need to clarify what exactly you mean here, because your screenshots are telling the opposite story than you. And no matter what I try (normal or with `osd-back-color=1`), opacity just works fine.

Maybe my description caused a misunderstanding.
Before this commit [f084a3a](https://github.com/tomasklaen/uosc/commit/f084a3ac4bdb69b6edf8128a24d50f4ff7cab8fc), `timeline_opacity=0.7`:
![image](https://user-images.githubusercontent.com/61936050/194698928-9fc4f7ef-000f-49d6-be7b-16cff0a8853b.png)
After this commit  [f084a3a](https://github.com/tomasklaen/uosc/commit/f084a3ac4bdb69b6edf8128a24d50f4ff7cab8fc), `timeline_opacity=0.9`: 
![image](https://user-images.githubusercontent.com/61936050/194694878-a93a55eb-8efc-4a4e-afd8-35d443513d0f.png)

The `*_opacity` options behavior changed. If this is an expected change, then I agree that it is normal.

**Comment by tomasklaen** [comment]
> If this is an expected change, then I agree that it is normal.

Yes. 90% opacity shouldn't be rendered as 100% opacity. Current behavior is correct.
