### ISSUE TITLE
Shuffle button should follow `shuffle` option state

### ISSUE THREAD

**Issue by pintassilgo** [tomasklaen/uosc#310]
For uses like me who have `shuffle` enabled in `uosc.conf`, shuffle control button should be highlighted at startup, providing the correct visual feedback that current playlist is running in shuffled order.

---

Still regarding shuffling:

>  @tomasklaen [commented](https://github.com/tomasklaen/uosc/issues/235#issuecomment-1253651143):
> And the `playlist-(un)shuffle` commands seem to be destructive. I don't want people to press the button, open the playlist to find something there, and see it all randomly ordered.

I guess this the main reason for `uosc` to implements its own shuffling instead of using native commands. But `uosc`'s shuffle has multiple flaws:

- Even with `shuffle=yes`, when I open a playlist (`.m3u` file with one filename/path per line) the first item to play is always the original first instead of a random one.

- It's bad for small playlists because it does nothing to prevent repeated playback as it only checks if next item is different from current. Example: if you have a playlist of just 5 items, it starts playing file1, next is file4, next may be file1 again, then next may also be file4 again...

- Not a deal breaker, but `previous` is useless with `uosc`'s shuffle implementation, it acts the same as `next` i.e. choose randomly.

None of this happens with native `playlist-(un)shuffle`.

For what you called "*destructive*", if `uosc` changes to use `playlist-(un)shuffle` user should be able to view original playlist order by just clicking "shuffle" button to disable it. Or if you prefer: `uosc` can do it automatically under the hood by running `playlist-unshuffle` right before showing playlist, then when menu closes it runs `playlist-shuffle` again.

Before someone says that cumulative `playlist-shuffle` prevents the ability to restore original order, just run `playlist-unshuffle; playlist-shuffle` instead, that way you ensure `playlist-unshuffle` always restores original order.

**Comment by hooke007** [comment]
User can activate `playlist-shuffle` by other methods (i.e. input/ another script /console). Once it was execute twice, the playlist would never be recovered.

**Comment by pintassilgo** [comment]
In current uosc, original playlist order is also subject to be lost if `playlist-shuffle` executes twice. If user don't want that to happen, they should educate themselves to avoid doing that.

As I understand it, tomasklaen don't want to lose original playlist order in menu. This is inevitable when `state.has_playlist == true` and the user somehow runs `playlist-shuffle` twice in a row. My proposal doesn't change that, it would be the same as current form.

What I'm proposing is to:
- execute `playlist-unshuffle; playlist-shuffle` when clicking to shuffle instead of trying to shuffle by its own. 
- if `shuffle` is enabled, execute `playlist-unshuffle` right before displaying playlist menu, given that tomasklaen wants the playlist to be displayed in original order.
- if `shuffle` is enabled, execute `playlist-shuffle` right after closing playlist menu to restore shuffled order.
- sync shuffle control button to `shuffle` state at startup for the correct visual feedback i.e. if mpv opens with `shuffle=yes`, shuffle button must inform the user that shuffle is enabled.

I see no drawbacks and this would fix the issues of uosc's shuffle implementation.

uosc's shuffle implementation may remain in source only for shuffling directory entries, because they aren't part of an actual playlist so aren't affected by `playlist-(un)shuffle`.

**Comment by hooke007** [comment]
Probably the current “shuffle” could be renamed to “random play” to avoid be misunderstanding.

**Comment by tomasklaen** [comment]
Commit above fixes the initial state mismatching `uosc.conf`.

Regarding all the proposals here: I'm in a hurry so don't want to spent 30 minutes writing an essay of all the issues with it, as I've already went through this implementing the current shuffling, so just _no_.

The only actual issue I see in current implementation is potential confusion for people used to mpv's shuffle, hopefully the 2nd commit above clarifying the option/control descriptions remedies it.

If you want mpv's shuffle, just use mpv's shuffle. Remove mpv's `shuffle` toggle control from `controls`, and replace it with buttons that shuffle and unshuffle your playlist.

> it only checks if next item is different from current

This can be improved. I'll add it to my low priority to-dos.

**Comment by pintassilgo** [comment]
Thanks. The initial issue is fixed. I'm learning about `controls=`, it's impressively customizable yet it isn't capable enough to fulfill what I intend to achieve.

My button would use `command:`, but:
1. How to toggle a `command:` button between active/inactive when clicked? It looks impossible with current uosc. Styling button as active is currently restricted to `cycle:`, but then I can't run a command which is a must.
2. It's needed something like `script-message-to uosc set shuffled yes` to sync button status, but `set` is currently restricted to button badge, it can't handle button status.

Actual example:

`shuffle.lua`:
```lua
local shuffled = 'yes'

function toggle(shf)
  if shf == nil then
    if shuffled == 'yes' then
      shf = 'no'
    else
      shf = 'yes'
    end
  end

  if shf == 'yes' then
    mp.command('playlist-unshuffle; playlist-shuffle')
    shuffled = 'yes'
  else
    mp.command('playlist-unshuffle')
    shuffled = 'no'
  end
  mp.osd_message(shf)
end

mp.register_script_message('toggle', toggle)
```

`input.conf`:
```
s script-message-to shuffle toggle yes
S script-message-to shuffle toggle no
```

My button in `uosc.conf`:
```
<has_playlist>command:shuffle:script-message-to shuffle toggle?Shuffle
```

It works, but button is static. Ideally it should sync with `shuffled` value, being active when `true`.

**Comment by tomasklaen** [comment]
The commit above adds support for properties managed by external scripts. You can implement it in your script like so:

```lua
-- Send initial value so that the button has a correct active state
mp.commandv('script-message-to', 'uosc', 'set', 'foo', 'yes')
-- Listen for changes coming from `toggle` or `cycle` button
mp.register_script_message('set', function(prop, value)
    -- ... do something with `value`
    -- Update uosc external prop
    mp.commandv('script-message-to', 'uosc', 'set', 'foo', value)
end)
```

And make a button for it with:

```
toggle:icon_name:foo@script_name
```

Value has to be a string or a number, booleans are not allowed, so you have to convert them to `yes/no` strings.

**Comment by NaiveInvestigator** [comment]
@pintassilgo If you don't mind could you send your shuffle script and your button too, sadly I couldn't figure out how to make it work.

**Comment by pintassilgo** [comment]
@NaiveInvestigator

- `shuffle.lua`:
```lua
local shuffled = 'yes'
mp.commandv('script-message-to', 'uosc', 'set', 'shuffled', 'yes')

function toggle(shf)
  -- shuffle directory items
  if mp.get_property_number('playlist-count') < 2 then
    mp.command('script-binding uosc/shuffle')
    return
  end

  -- handle button click (toggle state)
  if shf == nil then
    if shuffled == 'yes' then
      shf = 'no'
    else
      shf = 'yes'
    end
  end

  -- shuffle actual playlist
  if shf == 'yes' then
    mp.command('playlist-unshuffle; playlist-shuffle')
    shuffled = 'yes'
  else
    mp.command('playlist-unshuffle')
    shuffled = 'no'
  end
  mp.commandv('script-message-to', 'uosc', 'set', 'shuffled', shuffled)
end

mp.register_script_message('toggle', toggle)

-- listen for click in shuffle button
mp.register_script_message('set', function(prop, value)
  toggle(value)
end)
```

- `uosc.conf`:
In `controls=` line, replace `shuffle` by

      <!has_playlist>shuffle,<has_playlist>toggle:shuffle:shuffled@shuffle?Shuffle

- `input.conf`:

      Alt+s script-message-to shuffle toggle yes # shuffle current playlist
      Alt+S script-message-to shuffle toggle no # unshuffle current playlist

If you have any questions, feel free to ask and I'll try to answer.
