### ISSUE TITLE
Any reason why the UI is overlapping?

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#313]
![mpv-shot0141](https://user-images.githubusercontent.com/100978782/194770593-2ab6bb33-f9e9-4fe6-a1f3-4a8394caa05b.jpg)

On mpv I have
osc = no
osd-bar=no
border = no

I am on Windows

**Comment by christoph-heinrich** [comment]
You need the [fonts](https://github.com/tomasklaen/uosc/tree/main/fonts).

**Comment by Cananbolt** [comment]
Thank you, I put the fonts on the same directory as my mpv.conf file and it resolved the issue.
