### ISSUE TITLE
Flashing Play or Paused Sign

### ISSUE THREAD

**Issue by RexAckermann** [tomasklaen/uosc#316]
It kind of feels inverted for me how they flashes on play and pause.
Don't you think they show they opposite signs ?
Pardon me if I'm wrong and thanks in advance.

**Comment by tomasklaen** [comment]
It flashes the current state. Why would you want it to flash the previous one?

**Comment by hooke007** [comment]
> Don't you think they show they opposite signs ?

Nope, you could check youtube or any other websites that show the play and pause icons.
