### ISSUE TITLE
`toggle-ui` works unstable when called frequently

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [tomasklaen/uosc#317]
At the end of the video the behavior has been reversed. But console output indicates that I emitted the event correctly.

This is quite a fussy issue, because it's very difficult to reproduce under normal use, feel free to close this.

https://github.com/Natural-Harmonia-Gropius/InputEvent/blob/master/inputevent.lua
with input.conf
```
MBTN_LEFT           cycle pause                                         #@click
MBTN_LEFT           cycle fullscreen                                    #@double_click
MBTN_LEFT           script-binding uosc/toggle-ui                       #@press
MBTN_LEFT           script-binding uosc/toggle-ui                       #@release
```

https://user-images.githubusercontent.com/50797982/195094205-88c3d319-6535-4770-a5d4-a9f4b0d40e6d.mp4

![image](https://user-images.githubusercontent.com/50797982/195095998-b1deeb0b-bf38-48a9-a3ec-e728a755f7c9.png)

**Comment by tomasklaen** [comment]
With commit above, you can set element's min visibility explicitly with:

```
script-message-to uosc set-min-visibility 0.5
```

to set min visibility for all elements, or

```
script-message-to uosc set-min-visibility 0.5 timeline,speed
```

to set it only for some.

This is the same value modified by `toggle-ui` and `toggle-elements` APIs, so if any of them are triggered on the same element(s), they'll overwrite what you've set with `set-min-visibility`.
