### ISSUE TITLE
Equalizer support

### ISSUE THREAD

**Issue by RexAckermann** [tomasklaen/uosc#329]
Is it possible to add equalizer support on the menu with either sliders or buttons like this one,

https://gist.github.com/avih/41acff712abd32e1f436235388c8b523#file-equalizer-lua

**Comment by tomasklaen** [comment]
I don't think I'll be adding an equilizer to uosc. This is primarily a video player, and I don't want to bloat the code base with stuff that only 0.01% of people would use.

And why can't you just use the script by avih?

**Comment by hooke007** [comment]
There would be more issues here.
- `equalizer` is not mpv’ native filter, and it is not the only one choice of audio eq filter from ffmpeg. (i.e. [superequalizer](https://ffmpeg.org/ffmpeg-filters.html#toc-superequalizer))
- These filters have many parameters and flags.

Which means we may have to add lots of codes to implement the feature.

**Comment by RexAckermann** [comment]
Yes ,I know but eventually you may add support for sliders in menu.If that's their anyone could maybe make a secondary script that utilizes uosc ui.
Thanks though.
