### ISSUE TITLE
Problems with italic text

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#330]
As noted in https://github.com/tomasklaen/uosc/pull/322#issuecomment-1279829167 and https://github.com/tomasklaen/uosc/pull/322#issuecomment-1279830925 there is some problem with text rendering, but even after searching for hours I have no idea what the problem is. I did manage to make a minimal patch to reproduce it though.
![image](https://user-images.githubusercontent.com/8932183/196009492-9563eff5-0756-4bda-958d-271a0168c61f.png)
```diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index a474273..8b39cc1 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -3257,6 +3257,7 @@ function TopBar:render()
 			ass:txt(title_ax + padding, self.ay + (self.size / 2), 4, text, {
 				size = self.font_size, wrap = 2, color = bgt, border = 1, border_color = bg, opacity = visibility,
 				clip = string.format('\\clip(%d, %d, %d, %d)', self.ax, self.ay, max_bx, self.by),
+				italic = true
 			})
 			title_ay = by + 1
 		end
```
Changing the `italic = true` to `italic = false` makes it look the way it's supposed to again.
![image](https://user-images.githubusercontent.com/8932183/196009537-9197be4b-10be-41a6-b8b0-253f59b30ee2.png)

Removing the italic from the chapter title also makes the text smaller
![image](https://user-images.githubusercontent.com/8932183/196009832-442ad239-a061-40e7-a63b-75eb33648f7b.png)
```diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index a474273..0bae986 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -3271,7 +3271,7 @@ function TopBar:render()
 			ass:rect(title_ax, title_ay, bx, by, {
 				color = bg, opacity = visibility * options.top_bar_title_opacity, radius = 2,
 			})
-			ass:txt(title_ax + padding, title_ay + height / 2, 4, '{\\i1}' .. text .. '{\\i0}', {
+			ass:txt(title_ax + padding, title_ay + height / 2, 4, text, {
 				size = font_size, wrap = 2, color = bgt, border = 1, border_color = bg, opacity = visibility * 0.8,
 				clip = string.format('\\clip(%d, %d, %d, %d)', title_ax, title_ay, bx, by),
 			})
```

I even tried the latest libass commit https://github.com/libass/libass/commit/75a3dbac9bd41842a4d00b0d42c9513e2c8aec67 instead of the latest release, but no difference.

**Comment by tomasklaen** [comment]
Well, this has to be some new weirdness with ass tags I didn't encounter yet. Like wrapping the text in `{\\i1}` might reset something. Looking at it, the second `{\\i0}` is actually not needed there and might be doing something bad, try removing it. Or maybe the box drawing 1st character is messing with something? Try removing that too to see if it has any effect.

I might look into it tomorrow if you won't figure it out. But no obvious culprit comes to mind atm.

**Comment by christoph-heinrich** [comment]
I already tried all of that and in my PR the italic tags are replaced by `italic=true` in opts because it's needed for width estimation but it still happens.

**Comment by tomasklaen** [comment]
I actually can't replicate this:

![image](https://user-images.githubusercontent.com/47283320/197749319-a864a3d7-4913-430d-be17-38b0965faf9b.png)

And looking at your screenshots closer, it seems like libass in your environment is sometimes using a different font to render italic text, which has different character sizing/dimensions, making it look like the size has changed. Just look at lowercase `e` and `g` in the italic examples, they are a different font.

**Comment by christoph-heinrich** [comment]
Using `text_width_estimation=yes` never leads to any parts being cut off for you?
![image](https://user-images.githubusercontent.com/8932183/197823374-10a5688f-97e3-4b95-b206-2dcd14fbdaf1.png)
Because for me it's always too short because of that issue. Doesn't happen with `text_width_estimation=no` though.
