### ISSUE TITLE
Buffering indicator/spinner is pretty fast

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#339]
I like the new buffer indicator, but it's a bit too fast and in-your-face for my taste. I don't know any other spinner that moves this fast.

Would it be desirable to reduce the speed to 50% (or 75%) of the current value or alternatively add an option to control it or instead (ideally not)?

**Comment by tomasklaen** [comment]
I also thought that the indicator was a bit too much in your face. I've made it smaller, a bit transparent, and made the animation tiny bit slower. Not much though, as I don't mind the speed, and don't want it to be slow. The indicator most of the time pops up only for a couple hundred milliseconds, if it'd be too slow it'd look like a static icon.
