### ISSUE TITLE
Controls sometime appear on top of the timeline

### ISSUE THREAD

**Issue by odrling** [tomasklaen/uosc#340]
I seem to only reproduce it on streams, occasionally.
Occurs on both c00e296953ffa85fbb6db02cc3c53e0ceb0e1a59 (latest commit on master at time of writing) and 4.3.0.

https://0x0.st/o3-F.mkv

**Comment by tomasklaen** [comment]
This _should_ fix it, but I've never encountered this issue and can't reproduce, so I was fixing it blind.

**Comment by odrling** [comment]
Thanks, that did fix the issue.
