### ISSUE TITLE
Unbuffered segments are updated late for streams

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#343]
While watching a stream (and especially during the first ~10 minutes but even after 23), you can periodically observe the unbuffered segment jumping around. Not sure if there is something that uosc can do about this.

https://user-images.githubusercontent.com/931051/197855367-fe8c71ac-8f76-4b15-baa9-85c7c9f5d696.mp4

Edit: I just realized I wasn't using the latest version because the script was modularized and my update script consisting of a `wget` call doesn't know how to handle that.

**Comment by hooke007** [comment]
The original osc should share the same behavior.
