### ISSUE TITLE
Playlist/File control button gets activated automatically when window size is smaller than 40% of the screen

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#350]
![GIF 27-10-2022 8-51-24 pm](https://user-images.githubusercontent.com/72654596/198323401-396aa6fa-a36e-485f-a491-fdb676eca8e3.gif)

Here the window size is 20%. I think this has something to do with the menu overlapping a bit to where the button is present, cause at bigger window sizes they are not intersecting so it doesn't activate. Tho I am not too sure it is the actual cause but this is what I've observed. This wasn't present in the previous versions of uosc. And also I have only pressed the button ONCE not twice to clear things out. I even pressed the moved the mouse away from the window on the second song but sadly I couldn't figure out how to make the cursor be recorded too.

Edit: Fixed some spellings and stuff

**Comment by tomasklaen** [comment]
If I understand it correctly, the item inside playlist menu gets activated as soon as you press the playlist button? #348 fixes your problem right?

**Comment by NaiveInvestigator** [comment]
Oh sorry I haven't seen that PR, will try that and confirm!

**Comment by NaiveInvestigator** [comment]
> If I understand it correctly, the item inside playlist menu gets activated as soon as you press the playlist button? #348 fixes your problem right?

Yes I tried that and I fixes it! But I did notice that it takes a lil bit longer to open the menu than before tho. Not sure if I imagined it or it was my pc lagging or something.

Sorry for bothering you, will close this issue. Thank you for the help!
