### ISSUE TITLE
Hanging thumbnail

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#357]
`thumbfast clear` is not called when:
- Minimum timeline size is zero
- User hovers on the timeline (displaying a thumbnail)
- User keeps left click held as he drags far enough up for the timeline to reach 0 in size

The thumbnail border gets cleared, but the thumbnail overlay doesn't.  
It stays stuck at its last position, until left click is released, where it properly clears.

**Comment by tomasklaen** [comment]
I think all of these have been fixed for some time now? Feel free to correct me.
