### ISSUE TITLE
Support for old mpv versions

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#359]
You mentioned [here](https://github.com/tomasklaen/uosc/commit/d4697134a1347eb82d68def837a28c1031f58307#commitcomment-88041927) that you want to support versions before 0.33.0.

A fundamental part of the UI, mouse handling, broke support for pre-0.33.0 in 9dd78e85eb1723cf7c2f9faac49296cc59991ff2.

That's because `mouse-pos` was not a property back then, and we relied on `mp.get_mouse_pos()`.  
https://github.com/mpv-player/mpv/commit/a7686679564de584eaa720a6f682c8bd8ad062e6

`mp.get_mouse_pos()` is still usable today, and the commit message says they intend on keeping the wrapper.  
https://github.com/mpv-player/mpv/commit/0d5055fe93e35770235902e11ff39b3231e6e1b8

The obvious issues are that we have to change the way we watch for mouse movements (no property to observe), and that there is no "hover" state communicated by the old API (is it something we could compute ourselves?).

Is there a specific mpv version that you want to support (more specific than "pre-0.33.0")?  
I went with 0.29.0 for thumbfast because that's what I feel comfortable supporting, having applied the same compatibility fixes to mpv_sponsorblock years ago (it may actually support lower versions but I haven't tried it).  
But I think that going lower than 0.30.0 isn't worth the time, [shinchiro's builds](https://sourceforge.net/projects/mpv-player-windows/files/release/) only go back that far, and are the only Windows builds still linked on official pages.

**Comment by tomasklaen** [comment]
The reason I wanted to support pre-0.33 was that someone in issues here said that some semi popular distro still ships with 0.32 by default. But if the numbers are not that significant, I wouldn't mind setting support to 0.33 or higher. My support target is usually 95% of whats used in the world, but I don't think there's any data source to get these numbers, so I guess we need to guesstimate it.

I'd like to support the oldest version that won't make the development and maintenance too unreasonable, and this `mouse-pos` and `enter` & `leave` events missing issue sounds like it'd do just that. It's not like anyone here is getting payed to support ancient versions.

**Comment by FichteFoll** [comment]
[Debian bullseye](https://packages.debian.org/bullseye/mpv) and [Ubuntu 20.04LTS](https://packages.ubuntu.com/focal/mpv) ship 0.32. I don't know if people actually us debian for a desktop, though.

**Comment by tomasklaen** [comment]
So this sounds like supporting 0.33+ is good enough, right? This means we also wouldn't have to do the `uosc.lua` and `uosc_shared` shenanigans anymore.

**Comment by microraptor** [comment]
In the [official mpv installation instructions](https://mpv.io/installation/) it is explicitly recommend for Ubuntu and Debian users to install third-party mpv packages. There are repositories listed which allow to install mpv 0.33.1+ on Ubuntu Focal 20.04 and Debian Buster (2019). So Ubuntu or Debian should not be in the way of dropping 0.32.x support.

However, uosc is likely used relatively more on Linux than other software generally speaking. For those Linux users it is probably not uncommon to have a secondary/media computer running outdated Ubuntu or Debian versions. So when 0.32 support is dropped, it is probably best to mention it in the Readme with a link to the mpv installation instructions.

**Comment by msva** [comment]
> I think I'll be dropping support for 0.32 and lower. This will also allow us to stop splitting the codebase into `uosc.lua` + `uosc_shared/`, and just use one `uosc/` folder.
> 
> Any objections?

Yes, please!

I came here (to the uosc issue tracker) to exactly ask about this (fortunately, I've found this comment before I created a issue with this request :grin: )

**Comment by FichteFoll** [comment]
The situation isn't that different tbh, you just need to symlink two locations, the main lua file and the subfolder.

**Comment by hooke007** [comment]
@tomasklaen Here is an edge case.
https://github.com/mpv-player/mpv/issues/11949
Fix it or remove the support of 0.32.0 ASAP?
