### ISSUE TITLE
Margins crash console.lua

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#361]
(on the latest mpv commit)

`update_margins()` sets `osc-margins`, and console.lua will crash if any of them are not numbers (by performing math with them).

https://github.com/mpv-player/mpv/blob/fd91776207cd6b8d82e09765e0c6e2ec5e23d881/player/lua/console.lua#L85-L89

This should be fixed on the console.lua side too, the crash potential has been there forever and only doesn't happen because scripts don't set the bottom margin to an invalid value, even before https://github.com/mpv-player/mpv/commit/fd91776207cd6b8d82e09765e0c6e2ec5e23d881.  
uosc should add guards for this.

This can (and always does on init for me) return 'inf' for bottom. `tonumber()` in console.lua turns it into nil.

https://github.com/tomasklaen/uosc/blob/5f5bf4b842b7d3d3f1887780c8e5085d88ef100c/scripts/uosc.lua#L385

```
[console] stack traceback:
[console]       @console.lua:178: in function 'update'
[console]       @console.lua:224: in function 'set_active'
[console]       @console.lua:792: in function 'fn'
[console]       mp.defaults:230: in function 'fn'
[console]       mp.defaults:65: in function 'handler'
[console]       mp.defaults:380: in function 'handler'
[console]       mp.defaults:510: in function 'call_event_handlers'
[console]       mp.defaults:552: in function 'dispatch_events'
[console]       mp.defaults:503: in function <mp.defaults:502>
[console]       [C]: in ?
[console]       [C]: in ?
[console] Lua error: @console.lua:178: attempt to perform arithmetic on upvalue 'global_margin_bottom' (a nil value)
```

**Comment by christoph-heinrich** [comment]
I couldn't reproduce it myself, but that's clearly a race condition during initialization and I think a simple function guard should suffice. I've made a PR with that change.
