### ISSUE TITLE
Question: how to navigate back to the parent directory with a single key press?

### ISSUE THREAD

**Issue by idnsunset** [tomasklaen/uosc#367]
In the file navigation menu,  pressing the right arrow key enters the selected subdirectory but the left arrow doesn't navigate back to the parent. I have to press `Home` to jump to the `..` entry and then `Enter` to go back to the parent directory, which is a bit counterintuitive as `left` is usually expected to do the opposite to `right`.

**Comment by tomasklaen** [comment]
True. I'll implement back function for menus where it makes sense when I have some time.
