### ISSUE TITLE
[Feature Request] Seekable Chapter Markers and Maximized Window 

### ISSUE THREAD

**Issue by Ravencentric** [tomasklaen/uosc#370]
Seekable chapter markers, either by clicking the marker itself or near it and support for maximized window in uosc's custom border which currently only supports fullscreen and windowed.

**Comment by hooke007** [comment]
> Maximized Window

https://github.com/tomasklaen/uosc/issues/203

**Comment by tomasklaen** [comment]
Chapter indicators are now clickable.

As to why maximize button falls back to fullscreen, read through the the issue linked above. 
TL;DR: current limitation of mpv borderless window.

**Comment by Ravencentric** [comment]
Yea, I read it. Thank you!
