### ISSUE TITLE
Enhance thumbfast preview FPS

### ISSUE THREAD

**Issue by Yazeed-Alshehri** [tomasklaen/uosc#372]
How can we make it so thumbfast preview is updated for every second on the seeking bar, it only updates every ~5 seconds

**Comment by christoph-heinrich** [comment]
I don't think there is anything uosc can do about that.

thumbfast has an option `hwdec` which should help if your hardware supports decoding the used codec.

If that doesn't help, you can try searching `thumbfast.lua` for `--vd-lavc-threads=2` and replace 2 with a higher number, up to the number of threads your CPU has.

**Comment by hooke007** [comment]
Even though a low-end CPU shouldn't so slow. Probably sth terrible happened in pipe or hard-disk?

**Comment by tomasklaen** [comment]
I think he's asking for denser thumbnail spacing. Either way, that's a thumbfast configuration thing, so make an issue there: https://github.com/po5/thumbfast
