### ISSUE TITLE
[Console error message] Swapped to the new uosc 4.4.0 - 2022-Oct-28 instead of uosc 2.12.0 - 2020-Dec-03

### ISSUE THREAD

**Issue by CE-Yazeed** [tomasklaen/uosc#374]
I am using the new uosc 4.4.0 - 2022-Oct-28 instead of uosc 2.12.0 - 2020-Dec-03, however doing so results in an [error message](https://prnt.sc/L6F8Pw_hDhhf) shown in the mpv player console which I get when I try to use [this](https://prnt.sc/Zwp63jMj5PaV)(input.conf screenshot) video filter (vf) menu shortcut. How can I change my uosc.lua to fix this error or edit the line in input.conf to fix the problem?

**Comment by hooke007** [comment]
You are using the invaild input.conf stynax and it is not an uosc issue.
I think you need to take some time to read the manual first...https://mpv.io/manual/master/#list-of-input-commands

**Comment by hooke007** [comment]
I reviewed the uosc 2.12.0 and found darsain did defined the such syntax in that version.
But now it was removed, so just the official input syntax instead.

**Comment by hooke007** [comment]
why re-implement??? Is there any issue about adding the item into menu? The official syntax works well.

**Comment by hooke007** [comment]
Read the manual I showed.
i.e. `vf set format=colorlevels=full`

**Comment by hooke007** [comment]
Cannot reproduce.

**Comment by hooke007** [comment]
`# vf set vflip #! filter > vflip`
