### ISSUE TITLE
Lack of Originally Present UI Element 

### ISSUE THREAD

**Issue by CE-Yazeed** [tomasklaen/uosc#376]
MPV Player originally has chapter navigation UI buttons, however, uosc removes them entirely. I personally use them very often. Is there a way to make the adjustment?

Thank you!!
![image](https://user-images.githubusercontent.com/95697849/202871011-4cc299c3-812a-451b-8091-20625863a3f4.png)

**Comment by hooke007** [comment]
To see the docs in the uosc.conf
All you need to know is over there.

**Comment by hooke007** [comment]
What does this part mean `Prev_ch=` ? There is no such option.

**Comment by hooke007** [comment]
Add the contents ( `command:skip_next:script-binding betterchapters/chapterplaylist-prev?Next Chapter` ) into the value of `controls`
