### ISSUE TITLE
non rounded corner please

### ISSUE THREAD

**Issue by MonoGlory** [tomasklaen/uosc#377]
as the title, don't like the round corners, thank you

**Comment by manfred3000** [comment]
What do you expect from this "request"? Do you really expect the developer to change a feature (and doing all of this for free in their spare time) just because _you_ don't like it (and rudely demanding it, to boot)?

**Comment by FichteFoll** [comment]
To begin with, which corners exactly?

**Comment by duarm** [comment]
> What do you expect from this "request"? Do you really expect the developer to change a feature (and doing all of this for free in their spare time) just because you don't like it (and rudely demanding it, to boot)?

It's a request like any other, he just didn''t wasted anyone's time with pointless reasoning, he wants it because he doesnt like rounded corners. Make it an option if you need someone to tell you that much.

**Comment by fossist** [comment]
I like rounded corners and they are the present design choice of all the operating systems.
