### ISSUE TITLE
Load directory

### ISSUE THREAD

**Issue by escapezn** [tomasklaen/uosc#378]
Currently the file selector only supports loading files, it is inconvenient to load all contents in a directory and its subdirectories.
Please consider adding this feature.

**Comment by christoph-heinrich** [comment]
With [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) you can simply open the first file and the rest gets appended automatically.

**Comment by escapezn** [comment]
It is mainly useful in case of loading something in subdirectories.

**Comment by NaiveInvestigator** [comment]
or you could just set `autoload=yes` in your `uosc.conf` file, that should play all the files in your directory

**Comment by escapezn** [comment]
> or you could just set `autoload=yes` in your `uosc.conf` file, that should play all the files in your directory. I also have a lot of songs in a directory and use that to play the next songs.
> 
> Edit: Don't forget to add `keep-open=yes` in `mpv.conf`

This only applies to files in current directory itself, not those in subdirectories.

**Comment by tomasklaen** [comment]
`ctrl+enter` now force loads selected item.

`ctrl+click` doesn't have this behavior because apparently mpv doesn't allow binding key listeners to only modifiers, so I can't keep track whether `ctrl` is held down.

**Comment by escapezn** [comment]
Thanks for your update, but this commit broke LEFT key's behavior, please have a look.
```
[uosc]
[uosc] stack traceback:
[uosc]  ...ds/mpv/portable_config/scripts/uosc_shared/lib/menus.lua:239: in function 'on_back'
[uosc]  ...pv/portable_config/scripts/uosc_shared/elements/Menu.lua:450: in function 'maybe'
[uosc]  ...pv/portable_config/scripts/uosc_shared/elements/Menu.lua:620: in function 'fn'
[uosc]  mp.defaults:230: in function 'fn'
[uosc]  mp.defaults:65: in function 'handler'
[uosc]  mp.defaults:380: in function 'handler'
[uosc]  mp.defaults:510: in function 'call_event_handlers'
[uosc]  mp.defaults:552: in function 'dispatch_events'
[uosc]  mp.defaults:503: in function <mp.defaults:502>
[uosc]  [C]: at 0x7ff6b8079ba0
[uosc]  [C]: at 0x7ff6b8078280
[uosc] Lua error: ...ds/mpv/portable_config/scripts/uosc_shared/lib/menus.lua:226: attempt to index field 'modifiers' (a nil value) 
```

**Comment by tomasklaen** [comment]
Damn. Types should've caught it but checker didn't yell at me :/

**Comment by christoph-heinrich** [comment]
> `ctrl+click` doesn't have this behavior because apparently mpv doesn't allow binding key listeners to only modifiers, so I can't keep track whether `ctrl` is held down.

But mpv does allow listening to `ctrl+mbtn_left`, like we're already doing with `shift+mbtn_left`.

**Comment by tomasklaen** [comment]
> But mpv does allow listening to `ctrl+mbtn_left`, like we're already doing with `shift+mbtn_left`.

True. 🙄

**Comment by NaiveInvestigator** [comment]
Because of how uosc's autoload function works, we cannot autoclose mpv after it plays everything. So instead you'll have to use [this](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) as @christoph-heinrich mentioned. 

Download and move that script to your `scripts`  and remove the `keep-open=yes` in your `mpv.conf`. Now you should be able to able to play the next songs and it will close after it finishes playing all the files in that directory.

**Comment by christoph-heinrich** [comment]
Improving autoload.lua and adding an option to also load directories would also work. Probably wouldn't be hard to do in general, but that brings up the question in which order folders should be in. Interleaved with files or all folders at the very beginning? Arguably that should be another option...

**Comment by christoph-heinrich** [comment]
I implemented it in [here](https://github.com/christoph-heinrich/mpv/blob/autoload_directories/TOOLS/lua/autoload.lua).
Files and folders get interleaved, because testing has shown that this is how mpv itself behaves when loading directories.

If anyone tries it, let me know how well it works for you. If it's good enough I might make a PR for mpv :wink:.

**Comment by escapezn** [comment]
> I implemented it in [here](https://github.com/christoph-heinrich/mpv/blob/autoload_directories/TOOLS/lua/autoload.lua). Files and folders get interleaved, because testing has shown that this is how mpv itself behaves when loading directories.
> 
> If anyone tries it, let me know how well it works for you. If it's good enough I might make a PR for mpv 😉.
> 
> Edit: I already made the PR, seems like a solid improvement.

Your script works well but I'd rather use uosc to determine whether to load directory or not, because loading directory is not always preferred.
