### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DrZhang1208** [tomasklaen/uosc#379]
Would you consider adding a record history list?

**Comment by hooke007** [comment]
https://github.com/Eisa01/mpv-scripts#simplehistory

**Comment by DrZhang1208** [comment]
> 
感谢大佬

**Comment by tomasklaen** [comment]
You should maybe ask the simplehistory maintainer to integrate with uosc. But yeah, if there's a good solution out there, I don't see a reason to add it into uosc.
