### ISSUE TITLE
Text width measuring breaks uosc and mpv under certain circumstances

### ISSUE THREAD

**Issue by pintassilgo** [tomasklaen/uosc#381]
Edit: I just confirmed this bug was introduced in 4.4.0, still present in latest git. 4.3.0 is fine. It's something in text width measuring.

---

I want uosc to flash its entire UI when a media starts playing. For me it's important to see at least title and duration, specially when I jump to next playlist item (coincidentally, minutes ago someone opened a ticket about something similar - #380). So I created this simple script:

```lua
mp.register_event('start-file', function()
  mp.command('script-message-to uosc flash-elements timeline,controls,speed,top_bar,volume')
end)
```

It works when I open a single file, uosc flashes on startup as expected. But when I open a playlist (.m3u file with one filepath per line), uosc doesn't even load, there's no UI and shortcuts related to uosc don't work. Furthermore, mpv refuses to exit when I try, as if there's something blocking it, then I need to kill the process.

mpv console log doesn't show anything wrong.

I realized that if I remove `border=no` from mpv.conf it fixes the issue, but then uosc doesn't display media title because I use uosc default `top_bar=no-border`. If I change it to `top_bar=always`, then the bug happens even with `border=no`. I also don't want to have OS native titlebar in mpv, I want `border=no` anyway.

If I remove `top_bar` from the script above, the issue goes away but this doesn't solve my problem because I want to flash media title, so I need `top_bar`.

All of this proves the issue happens when uosc tries to flash `top_bar` on `start-file` event when loading a playlist with >1 item. Other elements like `timeline` work without any issue. **Maybe `start-file` event runs too early for current uosc code to count items in playlist  (this number is displayed in `top_bar`) and this breaks everything...**

Could someone please try to reproduce this issue and help me to fix it? Create the script above, set `border=no` in mpv.conf (or `top_bar=always` in uosc.conf), create a playlist (.m3u file with at least two lines, one filepath in each), open it with mpv then look if uosc is working and if you're able to exit mpv.

My config:
- mpv v0.35
- openSUSE Tumbleweed (Linux), KDE Plasma, Wayland.

The issue is still present if I use `file-loaded` event in the script instead of `start-file`. Using `playback-restart` seems to work fine, maybe with a little delay. That's what I'm going to use for now while this weird bug is open.

**Comment by tomasklaen** [comment]
Thx for reports. Should provide some pointers when someone has time to look at it. But it's hard when we can't replicate :/

> `text_width_estimation=no` doesn't prevent the bug. Shouldn't it prevent _all_ the code added in [bef4a77](https://github.com/tomasklaen/uosc/commit/bef4a77139bda67fb0fc43731b0716d4d4a15be4) from running?

The way text width _**estimation**_ works is that it measures widths of individual characters, caches that, and then calculates width of the text by combining widths of it's characters. After a couple measurements we usually get the widths of all characters in concerned language space and then we're just recalling them to estimate the width of any text passed in. So this is pretty fast.

If you disable estimation, it'll measure each text as a whole, this usually means every text passed in needs to be measured individually. This is slower, but you get a bit more accurate text width measurements.

So by disabling estimation, you're trading speed for accuracy, but text measurement is happening in both scenarios.

I think we should rename this option to something more descriptive. As it is now it gives an impression the user is disabling something, while actually they're enabling a more accurate and intensive text width measuring.

---

I wonder if it'd help to just delay all text measuring until we are sure the environment can handle it (lets say file load event + ~100ms), and until then just report every character as `0.75` relative width.

**Comment by christoph-heinrich** [comment]
Sounds like we might be getting BS values for osd-dimensions, so checking for `dim and dim.w > 0` in the observer should help, but I've just tried deliberately setting it to 0 and while the measurements aren't correct, it doesn't hang or crash.

Do you know if it crashes (error in console) or hangs (high cpu usage)?

**Comment by christoph-heinrich** [comment]
> Even trying this?

I've tried the test script together with different high resolution videos and playlists and unfortunately it still doesn't happen for me.

The osd resolution is not only set in the observer but also a few lines below that, maybe adding a check there too will help.
```diff
diff --git a/scripts/uosc_shared/lib/text.lua b/scripts/uosc_shared/lib/text.lua
index 7c1cf4e..d7f1004 100644
--- a/scripts/uosc_shared/lib/text.lua
+++ b/scripts/uosc_shared/lib/text.lua
@@ -120,13 +120,14 @@ text_osd.compute_bounds, text_osd.hidden = true, true
 ---@type integer, integer
 local osd_width, osd_height = 100, 100
 mp.observe_property('osd-dimensions', 'native', function (_, dim)
-	if dim then osd_width, osd_height = dim.w, dim.h end
+	if dim and dim.w > 0 then osd_width, osd_height = dim.w, dim.h end
 end)
 
 ---@param ass_text string
 ---@return integer, integer, integer, integer
 local function measure_bounds(ass_text)
-	osd_width, osd_height = mp.get_osd_size()
+	local w, h = mp.get_osd_size()
+	if w > 0 then osd_width, osd_height = w, h end
 	text_osd.res_x, text_osd.res_y = osd_width, osd_height
 	text_osd.data = ass_text
 	local res = text_osd:update()
```
Admittedly I don't understand why getting a resolution of 0 would result in an endless loop for you but not for me, but maybe I'll have some time tomorrow to have a closer look. One of the loop is already limited in the amount of iterations it's allowed to run, maybe it's a good idea to do the same for the second loop as well to make sure this doesn't happen.

**Comment by christoph-heinrich** [comment]
I'd assume it's the same problem with the rendering resolution.
```diff
diff --git a/scripts/uosc.lua b/scripts/uosc.lua
index 54f87ee..86bcaa4 100644
--- a/scripts/uosc.lua
+++ b/scripts/uosc.lua
@@ -343,6 +343,7 @@ require('uosc_shared/lib/menus')
 function update_display_dimensions()
 	local scale = (state.hidpi_scale or 1) * options.ui_scale
 	local real_width, real_height = mp.get_osd_size()
+	if real_width <= 0 then return end
 	local scaled_width, scaled_height = round(real_width / scale), round(real_height / scale)
 	display.width, display.height = scaled_width, scaled_height
 	display.scale_x, display.scale_y = real_width / scaled_width, real_height / scaled_height

```

**Comment by christoph-heinrich** [comment]
I've made a PR with the changes from above and also something to address the wrong initial render resolution.
Can  you please test if that fixes it?

**Comment by christoph-heinrich** [comment]
> When you jump from one video to other that have different aspect ratio, there's a brief misalignment in title.

That happens because when the aspect ratio changes, the drawn interface still assumes the previous resolution.
It gets updated as soon as we get notified about the updated resolution, but by that time mpv has already changed aspect ratio. There is nothing we can do about this.

> when the file has title tag, there's a little flickering when you jump files in playlist because top_bar initially displays filename, then a couple of frames later it changes to the title in file tag.

Showing the path when no title is available yet can also be a feature (e.g. opening URLs).
I suppose we could differentiate between local files and remote ones, but I'm not so sure the additional complexity is worth it for such a minor problem. (hide title when a local file gets loaded and show again when we get a title or we have enough metadata that we can be sure there won't be a title)
