### ISSUE TITLE
no osd gets shown when using keyboard seeking

### ISSUE THREAD

**Issue by gzpr** [tomasklaen/uosc#382]
The installation instructions say to disable the osd_bar as uosc provides it but no osd gets displayed when seeking with left/right arrow keys.

**Comment by christoph-heinrich** [comment]
You could put something like this in your `input.conf`
```
RIGHT seek  5  ; script-binding uosc/flash-timeline
LEFT  seek -5  ; script-binding uosc/flash-timeline
UP    seek  60 ; script-binding uosc/flash-timeline
DOWN  seek -60 ; script-binding uosc/flash-timeline
```

**Comment by tomasklaen** [comment]
Yup, use flash commands ([docs](https://github.com/tomasklaen/uosc#commands)) in your input bindings.
