### ISSUE TITLE
Text instead of icons

### ISSUE THREAD

**Issue by morning-paradigm** [tomasklaen/uosc#384]
Just installed the script following the manual and this is what I'm getting:

![mpv 2022-12-03 01:20:54](https://user-images.githubusercontent.com/39773982/205369824-a69cf692-2825-483b-a9b0-af084505a1ea.png)
![mpv 2022-12-03 01:23:45](https://user-images.githubusercontent.com/39773982/205369832-ac8ad3fd-e6ae-4a7b-b2b7-048069aa72c7.png)

The buttons and various menus work, but the icons won't show up.

Seems similar to the [issue](https://github.com/tomasklaen/uosc/issues/147#issuecomment-1232186875) in #147 
I have no idea how to symlink anything so I can't try the solution from that issue.

My `mpv.conf`:
```
# Start in fullscreen mode by default.
fs=yes

# Disable the On Screen Controller (OSC).
osc=no
# uosc provides its own seeking/volume indicators, so you also don't need this
osd-bar=no
# uosc will draw its own window controls if you disable window border
border=no

# Specify high quality video rendering preset (for --vo=gpu only)
# Can cause performance problems with some drivers and GPUs.
profile=gpu-hq
hwdec=auto
vo=gpu
volume-max=100

# Display English subtitles if available.
slang=jp,jpn,en,eng,ru,rus

# Play Finnish audio if available, fall back to English otherwise.
alang=jp,jpn,en,eng,ru,rus

# Load all subs and audio in the current and --sub-file-paths directories.
sub-auto=all
sub-file-paths=**:sub
audio-file-auto=fuzzy
audio-file-paths=**

# Plaintext subtitles style
sub-border-size=1.4
sub-font-size=28
sub-use-margins=no

# Screenshots
screenshot-high-bit-depth=no
screenshot-sw=no
screenshot-format=webp
screenshot-webp-lossless=no
screenshot-webp-quality=100
screenshot-webp-compression=6
screenshot-template="%F - %P"
screenshot-directory=~/Pictures/mpv screenshots/

# Advance if there is a next video, otherwise pause
keep-open=yes
```

mpv log:
```
[osd/libass] Setting up fonts...
[osd/libass] Loading font file '/home/alpin/.config/mpv/fonts/uosc_icons.otf'
[osd/libass] Loading font file '/home/alpin/.config/mpv/fonts/uosc_textures.ttf'
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
[osd/libass] fontselect: (sans-serif, 700, 0) -> /usr/share/fonts/noto/NotoSans-Bold.ttf, 0, NotoSans-Bold

[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
[osd/libass] fontselect: (MaterialIconsRound-Regular, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
[vo/gpu] Reallocating OSD texture to 4096x256.
[statusline] (Paused) AV: 00:00:01 / 00:22:52 (0%) A-V:  0.000
[vo/gpu] Reallocating OSD texture to 4096x512.
[statusline] (Paused) AV: 00:00:01 / 00:22:52 (0%) A-V:  0.000
[osd/libass] Glyph 0x2514 not found, selecting one more font for (sans-serif, 400, 0)
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/OTF/ipagp.ttf, 0, IPAPGothic
[cplayer] Set property: shared-script-properties -> 1
[osd/libass] fontselect: (sans-serif, 700, 0) -> /usr/share/fonts/noto/NotoSans-Bold.ttf, 0, NotoSans-Bold
[osd/libass] fontselect: (sans-serif, 400, 100) -> /usr/share/fonts/noto/NotoSans-Italic.ttf, 0, NotoSans-Italic
[osd/libass] Glyph 0x2514 not found, selecting one more font for (sans-serif, 400, 100)
[osd/libass] fontselect: (sans-serif, 400, 100) -> /usr/share/fonts/OTF/ipagp.ttf, 0, IPAPGothic
[cplayer] Set property: shared-script-properties -> 1
```

All the files are present in the right directories, I believe:
![image](https://user-images.githubusercontent.com/39773982/205368902-066c4510-e75b-41ee-8d33-c7cbd3fe9c01.png)

I even tried installing the fonts (as user, not system-wide), no effect.

OS: Garuda Linux (Arch-based)
mpv 0.35 (tried downgrading to 0.34, same issue)

**Comment by tomasklaen** [comment]
If I understand this line correctly:

```
[osd/libass] fontselect: (MaterialIconsRound-Regular, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
```

it seems like libass decided to use `NotoSans-Regular` as a fallback for `MaterialIconsRound-Regular` (font provided by `uosc_icons.otf` file). But these lines:

```
[osd/libass] Loading font file '/home/alpin/.config/mpv/fonts/uosc_icons.otf'
[osd/libass] Loading font file '/home/alpin/.config/mpv/fonts/uosc_textures.ttf'
```

indicate that the fonts are in the right place. So I guess they've failed to load for some reason?

Could it be something with permissions? Other than that I have no other ideas... :(

**Comment by hooke007** [comment]
It might be something wrong in the fontconfig conf.

**Comment by morning-paradigm** [comment]
> Could it be something with permissions?

Permissions are the same as the rest of the files in `~/.config`.

> It might be something wrong in the fontconfig conf. Try `sub-font-provider=none` first.

In `mpv.conf`, right? It doesn't help, but the log is slightly different.

```
[osd/libass] Setting up fonts...
[osd/libass] Loading font file '/home/alpin/.config/mpv/fonts/uosc_icons.otf'
[osd/libass] Loading font file '/home/alpin/.config/mpv/fonts/uosc_textures.ttf'
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
[osd/libass] fontselect: (sans-serif, 700, 0) -> /usr/share/fonts/noto/NotoSans-Bold.ttf, 0, NotoSans-Bold
[cplayer] Set property: shared-script-properties -> 1
[statusline] AV: 00:00:00 / 00:22:52 (0%) A-V:  0.000
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
[osd/libass] fontselect: (MaterialIconsRound-Regular, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
[vo/gpu] Reallocating OSD texture to 4096x128.
[statusline] AV: 00:00:01 / 00:22:52 (0%) A-V:  0.000
[osd/libass] fontselect: (sans-serif, 700, 0) -> /usr/share/fonts/noto/NotoSans-Bold.ttf, 0, NotoSans-Bold
[statusline] AV: 00:00:02 / 00:22:52 (0%) A-V:  0.000
[cplayer] EOF code: 5
```

**Comment by hooke007** [comment]
Sadly it seems osd is not controlled by this option...

**Comment by morning-paradigm** [comment]
That package didn't help either. I've tried symlinking to the font from the package (not sure if correctly) as mentioned in #147, it didn't work. I've even tried copying the `/usr/lib/node_modules/material-design-icons/iconfont/MaterialIcons-Regular.ttf` to `~/.config/mpv/fonts/uosc_icons.otf` (both converting to otf and as is), no effect.

Perhaps @christoph-heinrich could shed some light on how he managed to symlink it. Maybe I'm doing something wrong since there's two font files for uosc and the package has only one TTF file, the rest is just a bunch of PNGs.

It's even more odd since you can't reproduce on the same distro.

**Comment by christoph-heinrich** [comment]
I simply have the uosc git in a folder, and then symlinks to the files in there.
```
~/.config/mpv/fonts/uosc_icons.otf -> /home/christoph/Projects/uosc/fonts/uosc_icons.otf
~/.config/mpv/fonts/uosc_textures.ttf -> /home/christoph/Projects/uosc/fonts/uosc_textures.ttf
```

**Comment by morning-paradigm** [comment]
So yeah, `ln -s` is just how I tried to link create symlinks. Didn't work.

Is it possible to modify the script so it uses the system installed fonts instead of the one in `~/.config/mpv/fonts/`?
It doesn't seem like any of the Lua scripts explicitly link to `~/.config/mpv/fonts/`.

> PNGs? Afaik both font files should only contain vector graphics.
If you check the package contents, you can see:
```
/usr/lib/node_modules/material-design-icons/.babelrc
/usr/lib/node_modules/material-design-icons/.npmignore
/usr/lib/node_modules/material-design-icons/LICENSE
/usr/lib/node_modules/material-design-icons/README.md
/usr/lib/node_modules/material-design-icons/action/1x_web/ic_3d_rotation_black_18dp.png
/usr/lib/node_modules/material-design-icons/action/1x_web/ic_3d_rotation_black_24dp.png
...
```

**Comment by Orthestral** [comment]
Same issue here, with similar messages in the log. Running Void Linux

**Comment by FichteFoll** [comment]
> I've even tried copying the `/usr/lib/node_modules/material-design-icons/iconfont/MaterialIcons-Regular.ttf` to `~/.config/mpv/fonts/uosc_icons.otf` (both converting to otf and as is), no effect.

Since the font inside the `nodejs-material-design-icons` package is named `MaterialIcons-Regular` but uosc wants to use `MaterialIconsRound-Regular`, I can see how this wouldn't work.

As others have already pointed out, I am also clueless about the actual problem with the fonts in `.config/mpv/fonts` being loaded but not detected by libass/fontconfig, especially if `sub-font-provider=none` doesn't work. Perhaps that setting is ignored for OSDs and you indeed need to check your fontconfig configuration for any over-eager redirect to noto.

**Comment by Orthestral** [comment]
@FichteFoll Yep, matches the font it's switching to in the logs.

```
~/.local/share/fonts $ fc-match MaterialIconsRound-Regular
Vera.ttf: "Bitstream Vera Sans" "Roman"

~/.local/share/fonts $ ln -s ~/.config/mpv/fonts/uosc_icons.otf ./uosc_icons.otf

~/.local/share/fonts $ fc-match MaterialIconsRound-Regular
uosc_icons.otf: "Material Icons Round" "Regular"
```

Looking into `~/.config/fontconfig`, there was one file that seemingly was the culprit. It was designed to make Twemoji work in place of something like Noto emoji. Removing it and running `fc-cache -fv` fixed the issue immediately.

```xml
  <match target="pattern">
    <!-- If the requested font is sans-serif -->
    <test qual="any" name="family">
        <string>sans-serif</string>
    </test>
    <!-- Make Bitstream Vera Sans the first result -->
    <edit name="family" mode="prepend_first">
      <string>Bitstream Vera Sans</string>
    </edit>
    <!-- Followed by Twitter Color Emoji -->
    <edit name="family" mode="prepend_first">
      <string>Twitter Color Emoji</string>
    </edit>
  </match>
```

**Comment by morning-paradigm** [comment]
> Looking into ~/.config/fontconfig, there was one file that seemingly was the culprit. It was designed to make Twemoji work in place of something like Noto emoji. Removing it and running fc-cache -fv fixed the issue immediately.

Happy we've finally got somewhere, but I don't have anything emoji related in my `~/.config/fontconfig/fonts.conf`, so I've still got no idea what might be the issue. I think I edited my `fonts.conf` right after installing the OS to fix CJK fonts not having anti-aliasing, but I don't think this is related, as I have `fonts.conf.backup` which I've tried to use with `fc-cache -fv` to see if it fixes anything and it doesn't.

I do have `noto-color-emoji-fontconfig` installed, but I can't uninstall it since it's a dependency for `garuda-common-settings` which is one of core packages for Garuda Linux (also probably unrelated to my case since there's nothing related in fontconfig).

Here's my `font.conf` if anyone has any ideas:
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <!-- Default font (no fc-match pattern) -->
 <match>
  <edit name="family" mode="prepend">
   <string>Noto Sans</string>
  </edit>
 </match>
 <!-- Default font for the ja_JP locale (no fc-match pattern) -->
 <match>
  <test name="lang" compare="contains">
   <string>ja</string>
  </test>
  <edit name="family" mode="prepend">
   <string>Noto Sans CJK JP</string>
  </edit>
 </match>
 <!-- Default sans-serif font -->
 <match target="pattern">
  <test name="family" qual="any">
   <string>sans-serif</string>
  </test>
  <!--<test qual="any" name="lang"><string>ja</string></test>-->
  <edit name="family" binding="same" mode="prepend">
   <string>Noto Sans</string>
  </edit>
 </match>
 <!-- Default serif fonts -->
 <match target="pattern">
  <test name="family" qual="any">
   <string>serif</string>
  </test>
  <edit name="family" binding="same" mode="prepend">
   <string>Noto Serif</string>
  </edit>
  <edit name="family" binding="same" mode="append">
   <string>IPAPMincho</string>
  </edit>
  <edit name="family" binding="same" mode="append">
   <string>HanaMinA</string>
  </edit>
 </match>
 <!-- Default monospace fonts -->
 <match target="pattern">
  <test name="family" qual="any">
   <string>monospace</string>
  </test>
  <edit name="family" binding="same" mode="prepend">
   <string>Noto Sans Mono</string>
  </edit>
  <edit name="family" binding="same" mode="append">
   <string>Inconsolatazi4</string>
  </edit>
  <edit name="family" binding="same" mode="append">
   <string>IPAGothic</string>
  </edit>
 </match>
 <!-- Fallback fonts preference order -->
 <alias>
  <family>sans-serif</family>
  <prefer>
   <family>Noto Sans</family>
   <family>Open Sans</family>
   <family>Droid Sans</family>
   <family>Ubuntu</family>
   <family>Roboto</family>
   <family>NotoSansCJK</family>
   <family>Source Han Sans JP</family>
   <family>IPAPGothic</family>
   <family>VL PGothic</family>
   <family>Koruri</family>
  </prefer>
 </alias>
 <alias>
  <family>serif</family>
  <prefer>
   <family>Noto Serif</family>
   <family>Droid Serif</family>
   <family>Roboto Slab</family>
   <family>IPAPMincho</family>
  </prefer>
 </alias>
 <alias>
  <family>monospace</family>
  <prefer>
   <family>Noto Sans Mono</family>
   <family>Inconsolatazi4</family>
   <family>Ubuntu Mono</family>
   <family>Droid Sans Mono</family>
   <family>Roboto Mono</family>
   <family>IPAGothic</family>
  </prefer>
 </alias>
 <match target="font">
  <edit name="hinting" mode="assign">
   <bool>true</bool>
  </edit>
 </match>
 <match target="font">
  <edit name="hintstyle" mode="assign">
   <const>hintslight</const>
  </edit>
 </match>
 <match target="font">
  <edit name="rgba" mode="assign">
   <const>none</const>
  </edit>
 </match>
 <dir>~/.fonts</dir>
</fontconfig>
```

**Comment by Orthestral** [comment]
@morning-paradigm Emojis didn't have anything to do with it, it's the fact that some other font was being set as the first result when fontconfig searched for anything sans-serif.

The problem might have to do with the `Default xxxx font` sections, as that's extremely similar to what I had in the emoji file.
What else is in the conf.d subdirectory?

**Comment by morning-paradigm** [comment]
Not sure about conf.d (`/etc/conf.d`?)
If you mean `~/.config/fontconfig/`, then there's just `fonts.conf` and `fonts.conf.backup`

**Comment by Orthestral** [comment]
Then there's no other fontconfig files.
Delete lines  4-9 and 19-28 and then run `fc-cache -fv` and see if that fixes it
```xml
 <!-- Default font (no fc-match pattern) -->
 <match>
  <edit name="family" mode="prepend">
   <string>Noto Sans</string>
  </edit>
 </match>
```
```xml
 <!-- Default sans-serif font -->
 <match target="pattern">
  <test name="family" qual="any">
   <string>sans-serif</string>
  </test>
  <!--<test qual="any" name="lang"><string>ja</string></test>-->
  <edit name="family" binding="same" mode="prepend">
   <string>Noto Sans</string>
  </edit>
 </match>
```

**Comment by morning-paradigm** [comment]
I've finally fixed this (see the solution in the OP).

**Comment by wasi-master** [comment]
What would I need to do for windows since the ~/.config/fontconfig/fonts.conf directory doesn't exist

**Comment by tomasklaen** [comment]
Afaik you don't need font config on windows. Just extract uosc into your config/portable_config directory which will place fonts into `{config}/fonts` and it should work. Or just follow install instructions in readme.

**Comment by hooke007** [comment]
> What would I need to do for windows

https://mpv.io/manual/master/#files-on-windows

**Comment by dmnmsc** [comment]
I was facing the same issue because `uosc_icons.otf` and `uosc_textures.ttf` were missing in my `~/.config/mpv/fonts`

They were just present in /usr/share/mpv/fonts/. After copying them to my home folder everything worked as expected.

P.S: I'm not planing to reopen this issue. Just offering an alternative fix.

**Comment by xanshark** [comment]
> I was facing the same issue because `uosc_icons.otf` and `uosc_textures.ttf` were missing in my `~/.config/mpv/fonts`
> 
> They were just present in `/usr/share/mpv/fonts/`. After copying them to my home folder everything worked as expected.
> 
> P.S: I'm not planing to reopen this issue. Just offering an alternative fix. I was facing this issue in 2025.

This worked for me as well, thank you!
