### ISSUE TITLE
Add option for built-in autoload feature to ignore images and music?

### ISSUE THREAD

**Issue by Pentaphon** [tomasklaen/uosc#387]
I would like the option to make uosc only skip to the next video in the folder, not any images or music in a folder, since I only use mpv as a video player. 

Can we have that feature? Thanks.

**Comment by tomasklaen** [comment]
Sounds reasonable. No ETA though, seems like we're all busy these days.

**Comment by tomasklaen** [comment]
Added new option:

```
autoload_types=video,audio,image
```

Remove `audio` and `image` from it to get what you're asking for.

**Comment by Pentaphon** [comment]
> Remove `audio` and `image` from it to get what you're asking for.

@tomasklaen for some reason, this function has stopped working in 5.6.x. Not sure exactly which version. I get images and music even when I have `autoload_types=video`

**Comment by tomasklaen** [comment]
@Pentaphon I'd need more info, because I've just tried it and it seems to work fine.

**Comment by Pentaphon** [comment]
@tomasklaen sorry, this was totally my error while testing another plugin that conflicted with yours and I've removed it. Please ignore. My mistake.

**Comment by tomasklaen** [comment]
FYI: I've just refactored this option. It has been renamed to `load_types` (since it's used by prev/next file navigation too) and now accepts the `same` keyword to load files of the same type pool as currently open file.

**Comment by Pentaphon** [comment]
Noted. Glad to see this being improved. The `same` keyword is actually useful.
