### ISSUE TITLE
Option to not make UI elements fully appear until the mouse is directly on them

### ISSUE THREAD

**Issue by Pentaphon** [tomasklaen/uosc#388]
More often than I'd like, I accidentally keep the mouse too close to the window edge and UI elements begin to fade into view, getting in the way of the video, causing me to have to move the mouse to make the UI elements fade away and disappear. 

I'd like the option to not have the UI elements fully show up until my mouse is on them so I am less likely to make them appear by mistake. 

Don't get me wrong. I like the UI but I am not a big fan of the gradual mouse distance fade-in-out thing to make them fully appear and I'd just like to have the UI elements show up when my mouse is right on them. 

A simple "removegradualfadeUI=yes/no" to turn the behavior on or off would be a big help to me and I bet other people would like it too.

**Comment by Pentaphon** [comment]
I can't believe I missed that! I thought I looked at the settings well enough but I overlooked it! Thanks!

**Comment by tomasklaen** [comment]
You can also enable `autohide` if you're OK with it. I personally hate it.

**Comment by Pentaphon** [comment]
Nope, the proximity options made the only thing that annoyed me about uosc go away so I am more than satisfied now. Autohide seems unnecessary to me. Thanks again! Love this UI!
