### ISSUE TITLE
[Feature Requests] Delete file to Recycle Bin (Windows 10) | Option to change font and timeline bar colors | Show play/pause Indicator in timeline | Hide hour count for files less than 1 hour | Option to show media title, author, description, etc. in the UI

### ISSUE THREAD

**Issue by vitormathews** [tomasklaen/uosc#390]
About the last one: I miss being able to see file metadata in MPV like in MPC-HC/MPC-BE:
![image](https://user-images.githubusercontent.com/51209382/207672195-cfb1b10a-f617-405b-b745-ba1018272a2f.png)
      
They could be shown inside the timeline, or below the file name in the top bar, I don't know.

And about the "hide hour count" request, I have the milliseconds enabled, so I found it very visual polluted to have a count like this: 00:00:00.000
![image](https://user-images.githubusercontent.com/51209382/207677801-4b5c37ad-b75e-4322-9c62-16e5214d91a7.png)

- Windows 10 21H2 19044.2251
- uosc 4.5.0 - 2022-Dec-07
- mpv 0.35.0-30-g4574dd5dc6

**Comment by dyphire** [comment]
> Delete file to Recycle Bin

This request is possible, refer to [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/delete-current-file.lua)

> Option to change font and timeline bar colors

dup https://github.com/tomasklaen/uosc/issues/294

> Show play/pause Indicator in timeline

You can add `cycle:play_arrow:pause:no=pause/yes=play_arrow?play/pause` to the options of `controls` in your `script-opts/uosc.conf` to implement it.

> Hide hour count for files less than 1 hour

I haven't seen any other players behave like this. It's just your personal preference.

> Option to show media title, author, description, etc. in the UI

The media-title is already displayed in the UI, see: https://github.com/tomasklaen/uosc/blob/bfaccc8f66874d04339e9b1e515b61450b157aec/script-opts/uosc.conf#L119-L121

As for author and description, mpv does not seem to provide this metadata. I also can't see the benefits of further swelling the UI.

**Comment by vitormathews** [comment]
> This request is possible, refer to [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/delete-current-file.lua)

The problem is that when using this script together with uosc's built-in autoload the next file on the playlist is not played after file deletion, the player just closes (maybe because the default ```playlist-next / prev``` command is "disabled". I'm currently not using the individual [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) script because it conflicts with [keep-session.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua).

> I haven't seen any other players behave like this. It's just your personal preference.

[MPC-HC](https://i.imgur.com/xQllQMT.png) and [VLC](https://i.imgur.com/ktsDlNq.png) don't show the ```HH:``` part of the time unless the file is longer than 1 hour.

> The media-title is already displayed in the UI, see:

Yeah, I know, but on the top bar I prefer to see the filename instead (so I added ```title="${filename}"``` to mpv.conf). I'd like to see both title and filename.

**Comment by christoph-heinrich** [comment]
> the next file on the playlist is not played after file deletion

[delete_file.lua](https://github.com/zenyd/mpv-scripts/blob/master/delete_file.lua) queues up the files you want to delete and then deletes them when the player closes.

**Comment by dyphire** [comment]
> The problem is that when using this script together with uosc's built-in autoload the next file on the playlist is not played after file deletion, the player just closes (maybe because the default `playlist-next / prev` command is "disabled". I'm currently not using the individual [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) script because it conflicts with [keep-session.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua).

I mean that you can open a pr by referring to the code of [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/delete-current-file.lua). You just need to modify the following:

https://github.com/tomasklaen/uosc/blob/bfaccc8f66874d04339e9b1e515b61450b157aec/scripts/uosc_shared/lib/utils.lua#L382-L391

By the way, I think you also can try to replace this script of [keep-session.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua) with other scripts, such as [SimpleHistory.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua), [history-bookmark.lua](https://github.com/dyphire/yuukidach-mpv-scripts/blob/master/history-bookmark.lua)

**Comment by tomasklaen** [comment]
> Delete file to Recycle Bin

Yeah I think it'd be nice to have a `recycle_bin` option that does that.

> Option to change font and timeline bar colors

uosc uses the font you configured in `mpv.conf`. And you can change timeline progress color with `foreground` option.

> Show play/pause Indicator in timeline

There's already a huge pause indicator that can be statically always visible, or only flash if you want. If you want it as a button, you can add a control element as dyphire suggested above.

> Hide hour count for files less than 1 hour

Sounds reasonable to me.

> Option to show media title, author, description, etc. in the UI

The main focus of uosc is to be minimalist. Displaying all file meta in the UI is definitely not gonna happen. Also, try pressing `i` (default binding for `script-binding stats/display-stats-toggle`), I think it has all the data mpv has about the file.

But on the other hand, I'd also like to see both filename and media title in the title bar. Maybe we can add a `top_bar_subtitle` option that accepts a template to display a secondary title between main one and chapter name if it doesn't expand to empty string.

---

No ETA on any of these, really busy these days.

**Comment by christoph-heinrich** [comment]
> I'd also like to see both filename and media title in the title bar.

osc.lua shows the file name when clicking the title in the bottom bar, so maybe showing it on hover would make sense?

**Comment by tomasklaen** [comment]
But I want to see it when pressing `toggle-ui` binding. We might do a:

```
tob_bar_alt_title=never|click|below
top_bar_alt_title_template=${filename}
```

Also when it's `below` and template result matches main title we skip rendering it.

**Comment by vitormathews** [comment]
> [delete_file.lua](https://github.com/zenyd/mpv-scripts/blob/master/delete_file.lua) queues up the files you want to delete and then deletes them when the player closes. It doesn't move the files into trash and instead deletes them completely, but it has an option to move the files instead.

Any way to make it move to Recycle Bin?


> I mean that you can open a pr by referring to the code of [delete-current-file.lua](https://github.com/stax76/mpv-scripts/blob/main/delete-current-file.lua). You just need to modify the following:

What part exactly should I modify?

> By the way, I think you also can try to replace this script of [keep-session.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/keep-session.lua) with other scripts, such as [SimpleHistory.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua), [history-bookmark.lua](https://github.com/dyphire/yuukidach-mpv-scripts/blob/master/history-bookmark.lua)

I'll take a look at them, thanks!


> Also, try pressing i (default binding for script-binding stats/display-stats-toggle), I think it has all the data mpv has about the file.

Actually not all. ```show-text ${filtered-metadata}``` can show what I want. I'm now looking for a way to show (without a duration limit) and hide it with a keybind; and also to copy a desired metadata field. With ```${metadata/by-key/<key>}``` this would be possible, but I don't know yet what command to run. I tried ```KEY run "powershell" "set-clipboard" "${metadata/by-key/<key>}"``` and it works sometimes, but not always.

**Comment by christoph-heinrich** [comment]
> Any way to make it move to Recycle Bin?

It should be possible to take the [`delete_file()`](https://github.com/stax76/mpv-scripts/blob/7dbd142ed6c9013450780c539f9c87c7d7dec894/delete-current-file.lua#L52-L82) function, copy it into [delete_file.lua](https://github.com/zenyd/mpv-scripts/blob/master/delete_file.lua) and then call that instead of `os.remove()`.

**Comment by FichteFoll** [comment]
Can we split off the remaining open parts(s) (I believe it's only hiding hours when videos are <1h long) into separate issues? It makes tracking their individual state much more manageable.

**Comment by tomasklaen** [comment]
#402 #401
