### ISSUE TITLE
is there a way to move timeline to the top?

### ISSUE THREAD

**Issue by man9me2020** [tomasklaen/uosc#392]
The point is, timeline when you pause, covers all subtitles, is there a way to move it to the top of the window?

**Comment by tomasklaen** [comment]
No and I don't think there will be. It'd require too many code branches to render chapter indicators, tooltips, thumbnails, control bar, top bar and volume differently, as aall of their position depends on where the timeline is and what edge they are attached to. And where would the top bar go...

There are shortcuts and I think also a config to make subtitles higher. But why would you want to watch something with timeline fully visible?

**Comment by eko5624** [comment]
@man9me2020 One solution is: in uosc.conf, change `timeline_persistency=paused` to `timeline_persistency=idle,audio`

**Comment by tomasklaen** [comment]
Forgot to close :x but feel free to discuss alternatives.
