### ISSUE TITLE
[FR] Playlist entries names instead of URLs

### ISSUE THREAD

**Issue by xfzv** [tomasklaen/uosc#395]
I found https://github.com/tomasklaen/uosc/issues/80#issuecomment-1189690654 but it still doesn't seem to work here.

- With [jonniek/mpv-playlistmanager](https://github.com/jonniek/mpv-playlistmanager/blob/0c562fd104b5447082813b482733a3c307466568/playlistmanager.lua#L137-L138):
![image](https://user-images.githubusercontent.com/78810647/208908001-8d3b4b2c-4d2d-4d6a-8121-4506c9b10127.png)

- With uosc (4.5.0):
![image](https://user-images.githubusercontent.com/78810647/208908028-c3a49827-3b84-4a07-9f41-67fce65d0351.png)

Edit: The name is properly displayed in the title section:

![image](https://user-images.githubusercontent.com/78810647/208910347-4e84ca58-3ee4-40b9-9e3c-26394caecb15.png)

**Comment by christoph-heinrich** [comment]
playlistmanager [gets the titles with ytdl](https://github.com/jonniek/mpv-playlistmanager/blob/0c562fd104b5447082813b482733a3c307466568/playlistmanager.lua#L137-L138) and tbh I'm not that fond of making that many requests.

I do have a related open PR https://github.com/mpv-player/mpv/pull/10453

**Comment by tomasklaen** [comment]
Yeah I'm also against turning every user's uosc instance into a youtube ddos machine 😶. It also feels like it should be mpv's concern to retrieve and save url titles along playlist data when appropriate.
