### ISSUE TITLE
Add option to show time remaining (as opposed to playtime remaining)

### ISSUE THREAD

**Issue by sarmong** [tomasklaen/uosc#397]
Right now time in the right corner is shown as a playtime remaining. Meaning, it is divided by speed.

I think it would be good improvement to add an option to show time remaining not divided by speed.

If you agree, I am willing to open a PR.

**Comment by tomasklaen** [comment]
I personally don't see a value in that, but sure. This will require some refactoring tough.

I'd like this to be implemented by changing the `total_time` option into `destination_time`, which can be one of `total`, `remaining`, or `remaining-real`.

There also has to be a fallback for older settings where if default `destination_time` and `total_time=true` is detected, we set `destination_time=total`.
