### ISSUE TITLE
Hide hour portion of timestamps when duration lower than 1 hour

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#401]
Splitting from #390

---

If video duration is lower than 1 hour, timestamps should:

```
00:05:10 -> 05:10
```

**Comment by hooke007** [comment]
I doesn't like this idea. It makes me feel buggy that the duration is over 5 hours

**Comment by tomasklaen** [comment]
Yeah that's how I envisioned implementing it. A while loop -> if string starts with `00:` strip it.
