### ISSUE TITLE
Add configurable `top_bar` subtitle

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#402]
Splitting from #390

---

I'd like to see both filename and media title in the title bar. Maybe we can add a `top_bar_alt_title` option that accepts a template to display a secondary title between main one and chapter name if it doesn't expand to empty string.

Example option setup:

```
top_bar_alt_title=${filename}
top_bar_alt_title_reveal=click|below
```

Setting reveal to `click` would switch main title with alt title when clicking the top bar. `below` would render it always between the main title and chapter title.

Also when it's `below` and template result matches main title we skip rendering it.

**Comment by BhaturaGuy** [comment]
Also a feature similar to mpv's [`osd-playing-msg`](https://mpv.io/manual/master/#on-screen-controller-title) as an option.
And/Or a feature where uosc top bar title doesn't follow osc's `title=` rather it itself uses an option like `uosc-title=` and values can be the same as choices in [property list](https://mpv.io/manual/master/#property-list).
This feature is/might be useful for people like me who have `border=yes` and that border displays values from `title=` in mpv.conf and `uosc-title=` will display values (`${filename}` in my case) on hovering around area below mpv's border, and/only in fullscreen.

**Comment by tomasklaen** [comment]
The new top bar title options are:

```
# Can be: `no` (hide), `yes` (inherit title from mpv.conf), or a custom template string
top_bar_title=yes
# Template string to enable alternative top bar title. If alt title matches main title,
# it'll be hidden. Tip: use `${media-title}` for main, and `${filename}` for alt title.
top_bar_alt_title=
# Can be:
#   `below`  => display alt title below the main one
#   `toggle` => toggle the top bar title text between main and alt by clicking
#               the top bar, or calling `toggle-title` binding
top_bar_alt_title_place=below
```

Notable change is that `top_bar_title` no accepts a custom template in case someone wants it to be different from the one that would otherwise be inherited from `mpv.conf`.

**Comment by maaldheefee** [comment]
I have the title and alt_title set to `${media-title}` and `${filename}`. I want to hide `${media-title}` when it matches `${filename}` sans the extension. But now it's never hidden because of the file extension.

**Comment by tomasklaen** [comment]
Dunno about that. If one of your title options is `${filename}`, I'd assume you want to see the filename, of which the extension is part of. I sometimes want to check what container the file is using, and wouldn't like uosc hiding the filename in this scenario.
