### ISSUE TITLE
Turn off linear-downscaling when using SSimDownscaler

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#405]
To use [SSimDownscaler.glsl](https://gist.github.com/igv/36508af3ffc84410fe39761d6969be10), linear-downscaling needs to be turned off. Is it possible to set it to no when I click on SSimDownscaler in the usoc menu.  

My imput.conf can be found [here](https://github.com/Zabooby/mpv-config),

**Comment by christoph-heinrich** [comment]
I didn't test this, but appending ` ; no-osd set linear-downscaling no` to the command that adds SSimDownscaler should probably work. Since you're toggling SSimDownscaler you could also try using `cycle linear-downscaling yes no` instead.
Maybe there is also a way of doing this with a conditional profile, that would probably be the best way to go if it's possible.

**Comment by christoph-heinrich** [comment]
I don't know, it's probably best to ask in the SSimDownscaler gist, or maybe it's already answered somewhere in the comments.

**Comment by hooke007** [comment]
>  linear-downscaling needs to be turned off.

There is no such condition.

**Comment by Zabooby** [comment]
That's what it says [here](https://gist.github.com/igv/36508af3ffc84410fe39761d6969be10) though.

**Comment by hooke007** [comment]
That's not the condition. The shaders do not care about any options/properties.

**Comment by Zabooby** [comment]
So why did @igv write it as a requirement? Is it just a recommendation to make the scaler work better?

**Comment by dyphire** [comment]
> So why did @igv write it as a requirement? Is it just a recommendation to make the scaler work better?

https://gist.github.com/igv/36508af3ffc84410fe39761d6969be10?permalink_comment_id=3622397#gistcomment-3622397

> Less ringing artifacts. `linear-downscaling` should be used only with soft scalers (and only when it doesn't cause more aliasing artifacts).
But you can use it with `linear-downscaling` if you like it and don't notice any artifacts.

**Comment by Zabooby** [comment]
Before I close this issue, is there a way to know if linear-downscaling=no when playing a video so I can test:

> I didn't test this, but appending ` ; no-osd set linear-downscaling no` to the command that adds SSimDownscaler should probably work. Since you're toggling SSimDownscaler you could also try using `cycle linear-downscaling yes no` instead. Maybe there is also a way of doing this with a conditional profile, that would probably be the best way to go if it's possible.

**Comment by christoph-heinrich** [comment]
> is there a way to know if linear-downscaling=no

Enter `print-text ${linear-downscaling}` in the console.

**Comment by Zabooby** [comment]
Adding `; no-osd set linear-downscaling no` works.
