### ISSUE TITLE
choose the quality videos and audio youtube

### ISSUE THREAD

**Issue by candrapersada** [tomasklaen/uosc#406]
how to choose youtube video+audio stream quality?

**Comment by tomasklaen** [comment]
There's a **Stream quality** item in the default menu if you didn't overwrite it, or you can bind `script-binding uosc/stream-quality` command to some key.

It's all in the manual.

This however always selects best audio and video around the quality you selected in the menu. If you want to choose from exactly available formats or video and audio quality separately, you'll need to use something like https://github.com/christoph-heinrich/mpv-quality-menu

**Comment by candrapersada** [comment]
is there any option like this `script-binding uosc/video/quality_menu/video_formats_toggle` for merge menu Tracks video streaming from URL M3U8 and Stream Quality Video youtube?
