### ISSUE TITLE
Make menu work on touchscreen

### ISSUE THREAD

**Issue by chenxiex** [tomasklaen/uosc#411]
Manjaro Linux, wayland, mutter, gnome, touchscreen.
Hello, thanks for your great work but there's a problem on touchscreen. I use uosc with [https://github.com/christoph-heinrich/mpv-pointer-event](https://github.com/christoph-heinrich/mpv-pointer-event), which can call out the uosc menu by long pressing the screen. This works fine, but the menu items can't be clicked on a touchscreen. When I touch a item, it is highlighted just like the mouse hover it, but it won't be clicked. I tried to disable the mpv-pointer-event extension but the problem still exists.

**Comment by christoph-heinrich** [comment]
I've described the problem in https://github.com/christoph-heinrich/mpv-pointer-event/issues/2#issuecomment-1368430412. I'll talk to the mpv devs about it.

**Comment by christoph-heinrich** [comment]
I've made a PR that fixes this for me, would you mind testing it please?
