### ISSUE TITLE
Didn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by jalenzz** [tomasklaen/uosc#413]
Hello, uosc dit not work on my computer, other scripts can work well, but uosc not.

I install it follow the step in README, I think it right, but nothing happen, it dosen't display anything when I open an video.

What should I do?

**Comment by jalenzz** [comment]
@po5 Yes, I set `osc=no`, When I open a video, there is nothing display, no osc, no uosc.

![image](https://user-images.githubusercontent.com/57910033/210713509-1a6b5512-f420-4b6b-ab46-01837a64744f.png)

**Comment by jalenzz** [comment]
My `mpv.conf`
```sh
# required so that the 2 UIs don't fight each other
osc=no
# uosc provides its own seeking/volume indicators, so you also don't need this
osd-bar=no
# uosc will draw its own window controls if you disable window border
border=no
```

And mpv config directory
![image](https://user-images.githubusercontent.com/57910033/210714141-5027023c-e58b-46df-a62e-463e79a67623.png)

**Comment by christoph-heinrich** [comment]
If it doesn't show anything, it might have crashed somehow. Do you see an error in the console?

**Comment by jalenzz** [comment]
Thanks, I try to use console.
```sh
[uosc] 
[uosc] stack traceback:
[uosc] 	/home/jalen/.config/mpv/scripts/uosc.lua:552: in function 'prop'
[uosc] 	mp.defaults:392: in function 'handler'
[uosc] 	mp.defaults:486: in function 'call_event_handlers'
[uosc] 	mp.defaults:520: in function 'dispatch_events'
[uosc] 	mp.defaults:479: in function <mp.defaults:478>
[uosc] 	[C]: in ?
[uosc] 	[C]: in ?
[uosc] Lua error: /home/jalen/.config/mpv/scripts/uosc.lua:552: attempt to index local 'mouse' (a nil value)
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: SPS unavailable in decode_picture_timing
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: SPS unavailable in decode_picture_timing
 (+) Video --vid=1 (h264 1920x756 23.976fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
Using hardware decoding (vaapi).
```

**Comment by christoph-heinrich** [comment]
I've made a PR that should fix it for you.

**Comment by jalenzz** [comment]
> I've made a PR that should fix it for you.

thanks for that😆

**Comment by jalenzz** [comment]
@christoph-heinrich sorry, there is a new problem

```sh
[uosc] Lua error: /home/jalen/.config/mpv/scripts/uosc_shared/lib/utils.lua:520: attempt to call global 'thumbnail_render' (a nil value)
```

**Comment by tomasklaen** [comment]
There's no reference to `thumbnail_render` in `uosc_shared/lib/utils.lua`. What is going on here? o.O

**Comment by christoph-heinrich** [comment]
There is no reference to `thumbnail_render` in the whole project, nor can I find any place where something like it might be concatenated.

Let's make sure you're using all files from current master without any potential leftovers.
Can you please delete `uosc.lua` and `uosc_shared/` and then [download current master](https://github.com/tomasklaen/uosc/archive/refs/heads/main.zip) and use the files from that?

**Comment by christoph-heinrich** [comment]
@jalenzz I just realized you're using files from #353. Please use files from master branch only.

**Comment by jalenzz** [comment]
thanks, that's solved, but it still did't work, display nothing.
![image](https://user-images.githubusercontent.com/57910033/211028162-e3089c38-db69-4dbe-8a2e-5b577aa29221.png)

```sh
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: SPS unavailable in decode_picture_timing
[ffmpeg/video] h264: non-existing SPS 0 referenced in buffering period
[ffmpeg/video] h264: SPS unavailable in decode_picture_timing
```

**Comment by jalenzz** [comment]
> @jalenzz I just realized you're using files from #353. Please use files from master branch only.

I directly `git clone https://github.com/tomasklaen/uosc.git`, but still have the problem https://github.com/tomasklaen/uosc/issues/413#issuecomment-1373691320

**Comment by christoph-heinrich** [comment]
> display nothing

What exactly do you mean with that?
If the video is not showing, that's not a problem with uosc anymore.
That could be a problem with your config, mpv, drivers...
In that case you should open an issue over in https://github.com/mpv-player/mpv/issues or ask in their IRC. In both cases you'll need to provide a log file created with `--log-file=`.

**Comment by jalenzz** [comment]
I'm sorry for my unclear description.
This video can be played normally, but the uosc didn't show.
I run with `--log-file` [log.txt](https://github.com/tomasklaen/uosc/files/10360873/log.txt)

**Comment by christoph-heinrich** [comment]
I don't see anything related to `uosc_shared` in there, so maybe it's failing to load that? According to your previous error message it must have been able to load that, so I don't know what's going on here.
Is your directory structure still like it was in https://github.com/tomasklaen/uosc/issues/413#issuecomment-1371826801?

**Comment by jalenzz** [comment]
Yes, it's still like it was in https://github.com/tomasklaen/uosc/issues/413#issuecomment-1371826801

**Comment by christoph-heinrich** [comment]
If it's not something with your configuration then I have no idea what could be the problem.

If you want to be 100% sure that your config is not the problem, I've made a [minimal test configuration](https://github.com/tomasklaen/uosc/files/10366221/config.zip).
Simply unpack the folder inside somewhere and then run `mpv --config-dir=<path to folder>/test-config`.

**Comment by jalenzz** [comment]
I try that, but still, uosc didn't show :sob: 

I gave up, but sincerely thanks to you!
