### ISSUE TITLE
Menu for selecting shaders

### ISSUE THREAD

**Issue by duarm** [tomasklaen/uosc#414]
similarly how uosc provides a /playlist to select an entry on the playlist, it could also provide a /shaders, which would search a folder (by default ~/.config/mpv/shaders) for shaders, it would then toggle the shader with `change-list glsl-shaders toggle "SHADER_PATH/shader.glsl" `.

This can be done manually by adding each shader to a submenu, it would help a lot if uosc could lazily enumerate all shaders for us.

**Comment by hooke007** [comment]
> by default MPV_CONF_PATH/shaders

No such Specification at all.

**Comment by duarm** [comment]
That's supposed to mean ~/.config/mpv on linux, C:\users\USERNAME\AppData\Roaming\mpv\ on windows. The MPV_HOME env variable overrides these, not sure how to call tthem.

the idea is for the scripts to be by default, on linux, at:

~/.config/mpv/shaders/

because people usually place the scripts there.

**Comment by tomasklaen** [comment]
Haven't actually used shaders with mpv yet. Is `{mpv}/shaders/{shader_name}/shader.glsl` an enforced convention? If this is completely on a user to set up, and mpv accepts any `glsl` file located anywhere, I think this would be better left for a userland script that can be configured with a path convention of that particular user and use uosc menu API to display the selection menu.

**Comment by hooke007** [comment]
> this is completely on a user

**Comment by hooke007** [comment]
>  The other choice is to open and try to interpret the steps in the rendering pipeline for which shader they belong to

It seems unreliable. A shader usually contains multi-hooks, each of hook works independently and their `desc` name could be totally different with shader's filename.

**Comment by duarm** [comment]
just listing any files inside said default folder and assume they are shaders would be enough, uosc could internally keep the newly added shaders by comparing with `previous_descs`, then keep a dictionary filename:desc

**Comment by duarm** [comment]
> What is someone sets their shader cache dir to their main shaders dir? This should be a separate script, and it's entirely possible with script-defined menus.

Can shader caches be loaded directly with `change-list glsl-shaders`?  if so it wouldn't be much of a problem, since mpv would just error out.

**Comment by duarm** [comment]
Don't think mpv has a `on_load_shader` event to know when a shader was loaded, so my solution would not work with shaders loaded from outside. We could expose a `uosc-load-shader` command, and require the user to load the shader using that if they want to load anything from outside.

**Comment by Zabooby** [comment]
> EDIT: Don't think mpv has a on_load_shader event to know when a shader was loaded, so my solution would not work with shaders loaded from outside. We could expose a uosc-load-shader command, and require the user to load the shader using that if they want to load anything from outside.

Not sure if [this ](https://github.com/he2a/mpv-scripts/blob/main/scripts/sview.lua)is what you mean, I use it to show any shaders that are running.

**Comment by hooke007** [comment]
This is just print glsl-shaders properties. A shader in this list ≠ the shader is runing or the hooks it contains are activated. ref https://github.com/tomasklaen/uosc/issues/414#issuecomment-1370961901

**Comment by christoph-heinrich** [comment]
Someone should just make a "shader manager" script where people can define their shaders in the order they want with the name they want, the paths to the files (each entry can contain multiple shader files) and if it should be enabled by default. JSON seems like a good choice for that.
Add a menu where individual shader entries can be toggled and on each change the script just concatenates all shader paths in the correct order and sets the list. I'm surprised that doesn't exist yet.

**Comment by Zabooby** [comment]
> To be simple, this is a useless script, you could do the same thing by binding `show-text ${glsl-shaders}`

Just tried it, although it does the same thing, I like how the script displays the info.

**Comment by duarm** [comment]
> Someone should just make a "shader manager" script where people can define their shaders in the order they want with the name they want.

We can already do that with uosc, checkout FichteFoll answer, this request is about more robust way of doing that, which would update the list automatic and display the activated shaders.

**Comment by hooke007** [comment]
It's not simple. glsl-shaders is a list-option and allows dup items. For instance, for those who use anime4k presets, toggling one shader would break the hooks-chain.

**Comment by christoph-heinrich** [comment]
> We can already do that with uosc

Seems like you missed the "in the order they want" part. That is currently not possible. When a shader gets toggled on, it always gets appended at the end of the list, but what I proposed was a script that would be able to toggle shaders (and groups of shaders) in the middle of the shaders list.

FYI I'm currently toggling my shaders with lines like the follwing in input.conf
```
TAB      no-osd change-list glsl-shaders toggle "~~/shaders/adaptive-sharpen.glsl" ; show-text 'Toggle Adaptive Sharpen' #! Shaders > Sharpen > Toggle Adaptive Sharpen
```

But that becomes quite unwieldy for shaders like anime4k
```
Ctrl+KP1 no-osd change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_Clamp_Highlights.glsl" ; no-osd change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_Restore_CNN_M.glsl" ; no-osd change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_M.glsl" ; no-osd change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x2.glsl" ; no-osd change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x4.glsl" ; no-osd change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Toggle Anime4K: Mode A (Fast)" #! Shaders > Anime4k > Toggle Anime4K: Mode A (Fast)
```
But the problem with that is, that if I want shaders to be in a specific order, I'll have to be careful to toggle them on in the correct order.

For audio filters it's possible to name the filters while defining them, and then when toggling named filters, things always stay in the correct order.

So if I have in my mpv.conf
```
af-add=@dynaudnorm:dynaudnorm=f=21:g=11:m=10:r=1.0
af-add=@scaletempo2:scaletempo2=search-interval=50:window-size=40
```
And then toggle those on with a keybinding, it doesn't matter which one I toggle on first, dynaudnorm will always be applied before  scaletempo2.
The same is currently not possible with shaders.

**Comment by tomasklaen** [comment]
So I'll leave this for 3rd party scripts. This is too niche to be in a general UI script.

People can always use uosc's menu API to display selection lists.

**Comment by itsmeipg** [comment]
> hello, i am from 2 years in future, and i would argue it's not niche, but rather what makes mpv unique compared to every other player out there. uosc feels complete for everything, but doesn't have shaders, ah.

You can try my uosc shader menu embedded in my [video settings menu](https://github.com/itsmeipg/mpv-config/blob/main/portable_config/scripts/uosc_video_settings.lua). It has profiles and supports reordering but it has two small limitations: 1) Shaders can't be toggled twice. 2) Active shaders list only shows shaders from the glsl-shaders property and not if those shaders are being applied to the video.
