### ISSUE TITLE
Display Speed Widget as a Keybind

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#417]
Is there any way to display the speed widget as a keybind instead of it being there all the time? On default, the speed widget would be off. However, when pressing a key the speed widget will activate, and pressing it again will deactivate it.

**Comment by hooke007** [comment]
https://github.com/tomasklaen/uosc#toggle-ui

**Comment by Cananbolt** [comment]
This is something similar to what I want. I don't want to see the speed widget when I'm hovering over the controls. Similar to Volume Control, how it has the display option "none."

**Comment by BhaturaGuy** [comment]
I second this. Even I'd like a feature where volume and speed ui is only shown when I am changing their values with keybinds not when I am hovering around them. Could be optional whether to display volume and speed widget normally (current) or only when changing their values with keybinds or permanently hide just like it's available for volume.

**Comment by NaiveInvestigator** [comment]
As of now, if the speed widget is not enabled on the controls bar, then `script-message-to uosc toggle-elements speed` doesn't toggle the widget. 

I tried flashing the element too with `script-message-to uosc flash-elements timeline,speed` but it brings with same results. 

But if the speed widget is enabled on the controls bar, flashing and toggle works.

**Comment by Cananbolt** [comment]
> As of now, if the speed widget is not enabled on the controls bar, then `script-message-to uosc toggle-elements speed` doesn't toggle the widget. 
> 
> I tried flashing the element too with `script-message-to uosc flash-elements timeline,speed` but it brings with same results. 
> 
> But if the speed widget is enabled on the controls bar, flashing and toggle works.

How do you disable the speed widget?

**Comment by hooke007** [comment]
[read the doc](https://github.com/tomasklaen/uosc/blob/5a02c6d205fb0993adf07aacb894b4d444ff34b1/script-opts/uosc.conf#L30-L89)

**Comment by Cananbolt** [comment]
> [read the doc](https://github.com/tomasklaen/uosc/blob/5a02c6d205fb0993adf07aacb894b4d444ff34b1/script-opts/uosc.conf#L30-L89)

I've been reading it and making my own configs, but there isn't anything that completely removes the speed widget. Changing the speed_opacity didn't remove the widget

**Comment by hooke007** [comment]
Of course, because 
> As of now, if the speed widget is not enabled on the controls bar, then script-message-to uosc toggle-elements speed doesn't toggle the widget.

**Comment by Cananbolt** [comment]
> Of course, because 
> > As of now, if the speed widget is not enabled on the controls bar, then script-message-to uosc toggle-elements speed doesn't toggle the widget.

I understand, thanks for explaining it. Is it possible to make a display option like Volume Controls labeled "none" for the speed widget. This way those who does use it can leave it on and those who don't use it can just turn it off.

**Comment by tomasklaen** [comment]
`controls` option is a template that defines what elements should be in the controls bar, and where (with optional hiding based on current file disposition). `speed` is one of it's possible elements. So just remove it from there and it's gone.

**Comment by hooke007** [comment]
I am not sure if he want to make each element's visibility be toggled by one KEY on the fly?

**Comment by Cananbolt** [comment]
> `controls` option is a template that defines what elements should be in the controls bar, and where (with optional hiding based on current file disposition). `speed` is one of it's possible elements. So just remove it from there and it's gone.

I went to controls.lua removed...
`local Speed = require('uosc_shared/elements/Speed')`
and...
Removed speed.lua from the scripts folder

However, this causes uosc to not work at all (no timeline, top bar, a so on). Basically nothing shows when these two items are removed.

**Comment by tomasklaen** [comment]
> I went to controls.lua and removed...

I've sent you to `controls` **OPTION** (`script-opts/uosc.conf` file). Why did you start modifying the source code?

> he want to make each element's visibility be toggled by one KEY on the fly?

Yeah, I don't see myself implementing that. But I do see some value in BhaturaGuy's request of making some elements not interactive, so they completely ignore the mouse movement and clicks, and only show up when flashed.

**Comment by Cananbolt** [comment]
Thank you so much. I skimmed through that section so many times better never thought of removing it.
