### ISSUE TITLE
Feature Request: Play/Pause button

### ISSUE THREAD

**Issue by BhaturaGuy** [tomasklaen/uosc#420]
While I love uosc I can't seem to think otherwise that the main use of any other ui over mpv's `pseudo-gui` was to minimize the use of keyboard/keybinds. And one of the crucial feature missing in uosc is play/pause button.
I might be the only one here but I don't like left mouse click to play/pause (even on youtube).

**Comment by tomasklaen** [comment]
Read `controls` option docs. You can add any buttons you want.
