### ISSUE TITLE
Change Default Playback Speed

### ISSUE THREAD

**Issue by Lorograch1** [tomasklaen/uosc#433]
Hi,

First off, thank you for this amazing script for mpv.

I am in a pickle where the playback speed defaults to 1.5 every time I open a video file. Please could you help me navigate to which line I should change so that the playback speed default is 1? Thank you.

**Comment by christoph-heinrich** [comment]
Sounds like you have `speed=1.5` in your mpv.conf.

**Comment by Lorograch1** [comment]
> Sounds like you have `speed=1.5` in your mpv.conf.

yup, that does it. Thank you!
