### ISSUE TITLE
af=lavcac3enc breaks volume control

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [tomasklaen/uosc#434]
Windows, latest version.

Any volume changes only changes in the UI, does not affect the volume at all.
I tried to disable all my current scripts except for this and it still does not work.

Edit: 
**I narrowed the issue down to this command: af=lavcac3enc**
With it, it does not work and without it works.

**Comment by tomasklaen** [comment]
Sounds like mpv issue. uosc is just a UI. It doesn't decode or play audio. We just visualize the volume value mpv gives us.

**Comment by BrutalCSEjziponken** [comment]
> Sounds like mpv issue. uosc is just a UI. It doesn't decode or play audio. We just visualize the volume value mpv gives us.

Hm, how would it then break with one command? :P

**Comment by hooke007** [comment]
Cannot reproduce in my side.

**Comment by christoph-heinrich** [comment]
When starting with `--af=lavcac3enc` the volume slider works perfectly fine for me.

**Comment by BrutalCSEjziponken** [comment]
Seems to be a combo with these:

audio-channels=7.1,5.1,stereo
audio-spdif=ac3,eac3,truehd
af=lavcac3enc

I have to remove all 3 for it to work.

**Comment by BrutalCSEjziponken** [comment]
> > Seems to be a combo with these:
> 
> Works with all three as well. Do the volume key-bindings work for you? Does it work with the normal osc instead of uosc? Because of not then you should open an issue over at mpv instead.

Well Im so confused atm.. I cant get the volume OR the mute work at all now. Even if I remove all scripts its not working.
Not sure why it worked the first time I only removed af=lavcac3enc and now only if I remove all 3 of the above mentioned ones...

lol

**Comment by tomasklaen** [comment]
Seems like not a uosc issue. In case I'm wrong let me know and I'll reopen.
