### ISSUE TITLE
`top_bar=no-border` sometimes doesn't autohide topbar in fullscreen when `border=yes` and timeline is seeked in windowed.

### ISSUE THREAD

**Issue by BhaturaGuy** [tomasklaen/uosc#436]
`autohide=yes` doesn't do anything to prevent it.
![image](https://user-images.githubusercontent.com/93109835/213618501-7fc711fd-32cd-4157-bc23-230a5192db4b.png)

**Comment by hooke007** [comment]
Looks like the recent commit broke it. I was using the release ver. and looks fine.
