### ISSUE TITLE
Seekbar bugged?

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [tomasklaen/uosc#437]
So Im kinda new to this and the seekbar looks weird. I dont know if its a bug, feature or setting.
I include a pic.

https://i.imgur.com/YyAehyW.png
![eekbar](https://user-images.githubusercontent.com/3598735/213821434-c0871bb8-7599-4be5-bf9c-c0fb63429f6c.png)

**Comment by christoph-heinrich** [comment]
The regular osc shows you which areas are currently cached with a line in the timeline. uosc on the other hand shows you which areas are currently **not** cached with that texture.

**Comment by tomasklaen** [comment]
Yup, these are just indicators of uncached ranges for streaming media.
