### ISSUE TITLE
Space button to play last video when on idle screen

### ISSUE THREAD

**Issue by candrapersada** [tomasklaen/uosc#440]

**Comment by BhaturaGuy** [comment]
Can be achieved with `SPACE           script-binding simplehistory/history-load-last         #@click|idle_active`

These scripts are required:
[inputevent.lua](https://github.com/zhongfly/InputEvent/blob/property-expansion/inputevent.lua)
[simplehistory.lua](https://github.com/dyphire/mpv-config/blob/master/scripts/simplehistory.lua)

**Comment by candrapersada** [comment]
how to use Bookmarks in uosc?
