### ISSUE TITLE
On-demand thumbnail

### ISSUE THREAD

**Issue by escapezn** [tomasklaen/uosc#445]
For some videos there is no need to generate and show thumbnails, the only way to stop thumbfast.lua is not loading it on mpv startup. It would be nice if thumbfast.lua could be toggled with interaction, for example right click on progress bar (like deus0ww's thumbnail and osc scripts).

**Comment by hooke007** [comment]
Shouldn't it be requested in thumbfast's issue tracker?

**Comment by tomasklaen** [comment]
The development/maintenance time, additional configuration/setup bloat, and annoying UX this would cause (always having to press something to update the thumbnail) would only make sense if there was any issue with generating and showing thumbnails. But afaik there's not, so I don't see myself considering this.

> Shouldn't it be requested in thumbfast's issue tracker?

No, it's uosc that requests thumbnails to be generated. thumbfast is just a thumbnail server.

**Comment by po5** [comment]
Submit the issue here [po5/thumbfast](https://github.com/po5/thumbfast), this should be a script-binding if implemented.

**Comment by FichteFoll** [comment]
Created an issue at https://github.com/po5/thumbfast/issues/82 because I'm also interested in this but primarily for manually requesting thumbnails for network videos.

**Comment by maliayas** [comment]
Apart from the discussion about where this belongs to, I'd like to share my _quick hack_ to toggle thumbnails for those who need this feature until next releases:

````patch
diff --git a/scripts/uosc_shared/elements/Timeline.lua b/scripts/uosc_shared/elements/Timeline.lua
index 97f4224..8635612 100644
--- a/scripts/uosc_shared/elements/Timeline.lua
+++ b/scripts/uosc_shared/elements/Timeline.lua
@@ -150,6 +150,10 @@ end
 function Timeline:on_wheel_up() mp.commandv('seek', options.timeline_step) end
 function Timeline:on_wheel_down() mp.commandv('seek', -options.timeline_step) end
 
+bind_command('toggle-thumbnails', function()
+	thumbnail.disabled = not thumbnail.disabled
+end)
+
 function Timeline:render()
 	if self.size_max == 0 then return end
 
````

Then the key binding:

    t script-binding uosc/toggle-thumbnails

Disclaimer: Probably this should be handled in a better way. Use with care.
