### ISSUE TITLE
osd-bar replacement

### ISSUE THREAD

**Issue by akippnn** [tomasklaen/uosc#447]
When interacting with volume/seek through key binds, a bar would normally show up. I'm only aware of that function that osd-bar introduces. README recommends this disabled though.
```
# uosc provides its own seeking/volume indicators, so you also don't need this
osd-bar=no
```
The comment implies that uosc provides a replacement for this. I think clarification is needed if this functionality isn't in the scope of the project.

**Comment by tomasklaen** [comment]
Add `flash-volume` commands to your volume keybinds:

```
up           no-osd add volume  10; script-binding uosc/flash-volume
down         no-osd add volume -10; script-binding uosc/flash-volume
```

Documented in https://github.com/tomasklaen/uosc#flash-ui
