### ISSUE TITLE
Callback on menu close

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#448]
A few days ago I started working on a major refactor of [quality-menu](https://github.com/christoph-heinrich/mpv-quality-menu/tree/refactor) to run ytdl asynchronously and have better control over what gets shown when.

The problem I've run into is that there is really no way for my script to know if the uosc menu is still open or not.

For example if I want to show a loading indicator while ytdl is running and then update the menu as soon as data is available, I would open the menu with some loading message with `open-menu`, then the user closes the menu by clicking outside of it, and then when data is finally available, my script would open the menu again, because it still thinks the menu should be open.

Now that alone could be solved by making `update-menu` not open a menu when it's not already open, and not keeping track of if a uosc menu is open so that it always just assembles a menu and sends it with `open-menu` like it does on the master branch.

However I think it would be more flexible if there was a callback when the menu gets closed, similar to when an item gets selected. For my script that would mean a more similar code path for the uosc integration, but other scripts might also want to adjust what they are drawing while the menu is open, and for that they would also need to know when the menu gets closed without an item getting selected.

```
Menu {
  type?: string;
  title?: string;
  items: Item[];
  selected_index?: integer;
  keep_open?: boolean;
  on_close: string | string[];
}
```

**Comment by tomasklaen** [comment]
Sounds reasonable. No objections from me.
