### ISSUE TITLE
Option for thumbnail display size

### ISSUE THREAD

**Issue by xlucn** [tomasklaen/uosc#450]
The thumbnail preview seems small in higher dpi screens.

I found no options to change its size. `ui-scale` doesn't work on thumbnail.

Feature request: either apply `ui-scale` to thumbnail's display size (not image resolution), or add a standalone option for that.

**Comment by tomasklaen** [comment]
Thumbnail size is configured and controlled by [thumbfast](https://github.com/po5/thumbfast).
