### ISSUE TITLE
[suggestion]Make the buttons and menu items listen to mbtn_left hold down events

### ISSUE THREAD

**Issue by EdenChan** [tomasklaen/uosc#451]
I've been using uosc for a while and find it quite easy to use and customize. 

I managed to add buttons to controls and some items to menu, so as to add/reduce contrast, brightness and gamma, etc. 

But it's a bit tedious to repeatly click the mouse to make those changes. I think it would be better if users can press and hold the mouse button to increase/decrease the values continuously.

Roughly checked the mpv manual, but I didn't find a way to do such things. It would be great if this feature could be considered in the future.

**Comment by tomasklaen** [comment]
Buttons are a bad UI element for this, and any attempt to make them do something like that would ridiculously over-complicate the controls syntax, so I don't see myself adding it.

Keyboard shortcuts would be way better here.

If you absolutely need to do this with a cursor, than the only option are new UI elements with sliders. This would require considerable amount of work for something that isn't used very often, so not sure if this would ever move forward.

**Comment by EdenChan** [comment]
I agree with your opinion about buttons are bad choice here, and sliders are way more appropriate. 

But I still spent a couple of minutes to check the manual and applied 'mp.add_periodic_timer()' to those buttons and they worked just fine for me.
 
Anyway, sometimes when I use keyboard shortcuts, I don't want to touch the mouse, and vice versa. This quick and rough implementation did match a large part of my demands, and saved me from spending huge amount of time and rewriting too much code to add sliders ＾_＾.
