### ISSUE TITLE
Window Snapping

### ISSUE THREAD

**Issue by hl2guide** [tomasklaen/uosc#452]
Please add an option for Window snapping.

**Comment by hl2guide** [comment]
Seems to be a broken functionality of mpv, as using `--snap-window` when using your UI has not affect,

**Comment by FichteFoll** [comment]
> Try searching for "snap" in the mpv manual, it's a treasure trove (:

I'm not finding anything of interest when searching for `snap` on the manual outside of the `--snap-window` option with no discussion. Did you mean "issues"?

**Comment by tomasklaen** [comment]
mpv has a `snap-window=yes` config. just add it to `mpv.conf`.

If it doesn't work, it's either something with desktop environment or mpv. If it stops working when you install uosc, it's again something with DE or mpv, but manifests itself only when you disable window border (one of the uosc installation steps), so nothing to do with uosc. Either way, we can't do anything about snapping from here.
