### ISSUE TITLE
Feature: optimize `top_bar_alt_title_place=below` hidden conditions 

### ISSUE THREAD

**Issue by dyphire** [tomasklaen/uosc#455]
At present, `top_bar_alt_title` explicit and implicit logic has obvious defects.
Use `top_bar_alt_title=${media-title}` and open mpv on `idle`.
![image](https://user-images.githubusercontent.com/61936050/219662627-ad92d40f-7bfe-433d-ac01-ce84a198a895.png)

If use `top_bar_title=yes`, `top_bar_alt_title=${media-title}` and `top_bar_alt_title_place=below`, also use `title=${?pause==yes:⏸}${filename}` in mpv.conf. 
The following title status will be displayed when openthe playback file:
![image](https://user-images.githubusercontent.com/61936050/219663796-63a7cc54-d683-48ea-b5dd-1e9a7188fca9.png)

As you can see, it exposes some issues.
I created the following patches to fix the issues mentioned above
```diff
---
 scripts/uosc_shared/elements/TopBar.lua | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/scripts/uosc_shared/elements/TopBar.lua b/scripts/uosc_shared/elements/TopBar.lua
index 761d76b..1cb4684 100644
--- a/scripts/uosc_shared/elements/TopBar.lua
+++ b/scripts/uosc_shared/elements/TopBar.lua
@@ -167,7 +167,9 @@ function TopBar:render()
 		end
 
 		-- Alt title
-		if state.alt_title and options.top_bar_alt_title_place == 'below' and state.alt_title ~= state.title then
+		local function replace(str) str = string.gsub(str, "[%(%)%.%+%-%*%?%[%]%^%$%%]", "%%%1") return str end
+		if state.alt_title and options.top_bar_alt_title_place == 'below' and state.is_idle == false
+		and string.match(state.title, replace(state.alt_title)) == nil then
 			local font_size = self.font_size * 0.9
 			local height = font_size * 1.3
 			local by = title_ay + height
--
```

I want to know what you think about it.

**Comment by tomasklaen** [comment]
The referenced commit above deduplicates the main and alt titles by checking if one completely contains the other, and using only the longer one.

This is as far as I'd be willing to go with this as anything else risks hiding information that user wants to see.

Is this enough or does anyone have objections to it I might have missed?

**Comment by dyphire** [comment]
I made some suggestions in that commit

**Comment by tomasklaen** [comment]
Fixed the pattern escaping, but I'm not adding the `is_idle` condition. People might use title templates that display stuff that is available even during idle state. And `(unavilable)` is a valid window title when there's no file open. I don't see an issue here honestly.

**Comment by dyphire** [comment]
> but I'm not adding the `is_idle` condition. People might use title templates that display stuff that is available even during idle state. And `(unavilable)` is a valid window title when there's no file open. I don't see an issue here honestly.

It's just a bit of obsessive compulsive disorder, which may not be necessary.

**Comment by christoph-heinrich** [comment]
> It's just a bit of obsessive compulsive disorder, which may not be necessary.

You can avoid the `(unavailable)` by replacing the `filename` (or whatever else) with `?filename: ${filename}`.

**Comment by dyphire** [comment]
> You can avoid the `(unavailable)` by replacing the `filename` (or whatever else) with `?filename:${filename}`.

You cannot use an attribute that does not exist as a judgment condition. The correct usage should be `${?idle-active==no:${filename}}`.

The real problem here is that neither of `top_bar_title` and `top_bar_alt_title` supports this usage. Among them, the `top_bar_title` can achieve this in disguised form by setting `top_bar_title=yes` in uosc.conf and use `title=${?pause==yes:⏸}${?idle-active==no:${filename}}` in mpv.conf.

**Comment by christoph-heinrich** [comment]
> You cannot use an attribute that does not exist as a judgment condition.

Sure you can, I do and it works just fine.
From the man page:
```
${?NAME:STR}
       Expands to STR (recursively) if the property NAME is available.
```
So it expands `filename` only when it's available, resulting in `(unavailable)` not being shown.

**Comment by dyphire** [comment]
Yes, it seems that some of my previous modifications caused the error. Now I can confirm that it is available.
