### ISSUE TITLE
better/more `{disposition}` for `image`.

### ISSUE THREAD

**Issue by BhaturaGuy** [tomasklaen/uosc#458]
> `image` - true if current file is a single image

Is it possible to add more disposition for this? 
something like 
"`image` - true for image only files"
"`has_image` - true for files with an image track"
like you've done for audio (`audio`, `has_audio`,`has_many_audio`)
Since if I set disposition for `speed` to be `<!idle,!image>`.
It doesn't display speed button if the file (`.mkv` in my case) has a cover image. There should be a better way to handle it.

**Comment by tomasklaen** [comment]
`image` disposition should've already be `true` for image only files, but there were false positives in disposition determination. This should be fixed now.
