### ISSUE TITLE
Misaligned submenus when using keybinds

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#459]
My full [config](https://github.com/Zabooby/mpv-config). 

For example I have 
```
ALT+a script-message-to uosc show-submenu-blurred "File"
```
Here is what happens when I use the key bind:
![image](https://user-images.githubusercontent.com/78969986/220658352-248c52e4-8936-4702-a07f-99b13c3ae0e2.png)

This is how it should look:
![image](https://user-images.githubusercontent.com/78969986/220659119-a4528046-5fd1-4149-bc30-4c61ae3c80ef.png)

**Comment by Zabooby** [comment]
Here are some clearer screeenshots using `ALT+s script-message-to uosc show-submenu-blurred "Video > Shaders"`: 
![image](https://user-images.githubusercontent.com/78969986/221520908-628390f4-69ce-4bd8-a8f2-d87c8f407282.png)

How it looks when clicking through the menus: 
![image](https://user-images.githubusercontent.com/78969986/221521180-53b2232d-8c5d-4033-baf0-5cd8548e67c8.png)

**Comment by Zabooby** [comment]
Can anyone reproduce this issue?

**Comment by christoph-heinrich** [comment]
> Can anyone reproduce this issue?

Yes
