### ISSUE TITLE
Delete_file Lua Script does not consistently working with UOSC

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#460]
I'm not too sure why, but zenyd's [delete_file.lua](https://github.com/zenyd/mpv-scripts) does not consistently work with UOSC. 

What I mean by this is one moment the script would work properly. The keybinds works as intended.

But then, suddenly the script would fail. When pressing...

#i script-binding stats/display-stats then the number 4 (active key bindings)

The delete_lua file is not there anymore, along with any keybinds I had with the script. It completely disappears.

But with the default OSC it does work properly and I never had this issue. Is there any way to fix this?

**Comment by Cananbolt** [comment]
That's so strange, whenever I use it, it's really up to chance on working or not. Pertaining the keybinds, I just meant to say that UOSC completely deletes the delete_file lua script randomly, so the keybinds wouldn't really matter afterwards. I've been trying to figure out why, but to no avail.

**Comment by christoph-heinrich** [comment]
I don't think it's even possible for scripts to remove other scripts. Are you sure that delete_file doesn't crash and doesn't work anymore because of that?

**Comment by Cananbolt** [comment]
That may actually be the problem, however, I used it with the default OSC for over a year, and it worked completely fine. That's what I'm mainly confused about. Is it an UOSC problem or the script itself?

Also I just did a quick log file mpv in command prompt to see if there was anything wrong and nothing.

**Comment by NaiveInvestigator** [comment]
you could potentially also use uosc's own `delete-file-next` and `delete-file-quit` commands.

if remembering two keybinds annoys you, you could instead assign these commands  to a control button instead.

**Comment by Cananbolt** [comment]
> you could potentially also use uosc's own `delete-file-next` and `delete-file-quit` commands.
> 
> if remembering two keybinds annoys you, you could assign these commands  to a control button instead.
> 
> Edit: Fixed some Grammar

Thanks for the tip, I used it before and it works just fine, but it does delete the files right away. That's why I prefer zenyd's delete_file lua script as it first marks a file for deletion, and then when you CLOSE mpv it THEN deletes the file.

**Comment by NaiveInvestigator** [comment]
That does make sense. 

> but it does delete the files right away.

Just wanted to add someone didn't know this and stumbled on this issue, that there is a `use_trash` option (disabled by default) too in the `uosc.conf`, it moves the files you've deleted to the recycle bin instead of outright deleting them forever.

So even if you're accidentally deleted it or changed your mind and needed the file, you can recover it from the recycle bin.

**Comment by po5** [comment]
Doesn't seem like uosc lets you delay file deletion until file change, but that would be easily solved by taking advantage of the fact that most (all modern?) filesystems will only render a file inaccessible once all references to its inode are gone, and there are no open handle.  
You can test this by hard deleting any file currently open (as the playing file) in mpv, you'll be able to seek, select subtitles etc. until you switch files.  
The only advantage I can see to the deletion marking approach is that scripts that rely on the file being there (e.g. for subtitle extraction) will not work after deleting the playing file.

**Comment by tomasklaen** [comment]
> Doesn't seem like uosc lets you delay file deletion until file change

We first load a new file, and only then delete the old one. There shouldn't be any issues with this.

But that's not the issue here. uosc is supposedly somehow breaking/removing `delete_file.lua` script (dunno what that means exactly, I guess its UI never shows up again?), which I have no idea how that could even happen, and without OP providing steps to actually reproduce the issue, we'll never know either :)

**Comment by Cananbolt** [comment]
My apologies, I'm not sure what steps I should provide. Do you mean how the problem occurs. If so, it just happens randomly. I configured delete_lua on my input.conf file.

```
Enter async script-message-to delete_file delete_file mark_delete ;  sync playlist-next ; async script-message-to delete_file list_marks list_marks
```
There really isn't any consistency with the script breaking. Sometimes it would work just fine and then all of a sudden, it would break.

Is this what you are looking for? If not, may you please tell what I need to show.

**Comment by Cananbolt** [comment]
> The only advantage I can see to the deletion marking approach is that scripts that rely on the file being there (e.g. for subtitle extraction) will not work after deleting the playing file.

Another big advantage, is that it still lets you go back to file. What I mean by that is because the file is only marked for deletion it's still in the playlist and you can freely go back as you wish. Say if you input the UOSC propt ```
delete-file-next
``` once you input that command it'll be permanently removed from your device. And say you use the ```
trash
``` option, it would still get removed from the playlist and then you would still have to delete it if you permanently want it gone from your device.
