### ISSUE TITLE
Window cannot be resized with mouse left hold

### ISSUE THREAD

**Issue by cipricus** [tomasklaen/uosc#470]
Tested in Kubuntu with Plasma, kwin window manager. 
The kwin shortcuts work to move the window, but not the mouse or touchpad.

**Comment by christoph-heinrich** [comment]
Are you sure that is caused by uosc? Are you certain that neither your config files nor any other script [deactivate window dragging](https://mpv.io/manual/master/#options-no-window-dragging)?

**Comment by christoph-heinrich** [comment]
Initiating a window drag through the compositor works, but initiating it through mpv does not. Your initial post already made that clear, what's not clear is if this is actually a problem from uosc (which I doubt tbh).

**Comment by cipricus** [comment]
I should have clarified this as a question then, not to seem necessarily as a bug report. I _am under the impression_ this behavior is a feature (inherent) because there is no kwin window frame anymore. When I open mpv with uosc it goes to the middle of the screen. I can only make it full-screen or maximize, also move it by unusual methods (shortcuts, Super+click), and not with the normal left click. It seems that there is no margin/handle to move or resize the normal way.
I mean: is that so? expected? Can I change this?

**Comment by christoph-heinrich** [comment]
Moving the window via mouse button left down + moving the mouse should still work.
I'm a KDE plasma user as well (wayland) and moving the window works fine for me.
Resizing doesn't work without borders. Commenting out the correct check in mpv makes it work, but I don't know if that's a shortcoming of mpv or KWin.
You can try `--window-dragging=yes`, but it should be like that by default, hence my question if it's a problem of your configuration or some other script.

**Comment by cipricus** [comment]
> if it's a problem of your configuration or some other script

I cannot tell for the moment.

**Comment by cipricus** [comment]
Oh, I got it, I can now move it from the margin after i have increased the margin size. i had simply have not tried to move by clicking the middle of the window... I was keeping trying to move on an imaginary top margin. The only problem seems the non-dragging. But if that is expected this can be closed.

**Comment by christoph-heinrich** [comment]
Window resize should also work soon :wink: https://github.com/mpv-player/mpv/pull/11419

**Comment by ugurbolat** [comment]
so resizing is currently only for wayland? @christoph-heinrich 

in x11, I can't resize the window too.

**Comment by christoph-heinrich** [comment]
> so resizing is currently only for wayland?

Looks like it. I haven't found anything in the x11 code regarding that and the associated options are also called `wayland-*`.
