### ISSUE TITLE
[Feature Request] Add integration for mpvDLNA

### ISSUE THREAD

**Issue by kilisio** [tomasklaen/uosc#473]
Integrate `https://github.com/chachmu/mpvDLNA` into uosc to allow access of upnp servers using uosc

**Comment by christoph-heinrich** [comment]
Integrate how? They aren't exposing an API as far as I can tell.
uosc exposes an API for the menu, so they could make use of that and provide uosc integration from their side.

**Comment by tomasklaen** [comment]
As christoph mentioned, we are providing API so that other scripts can use uosc to render their menus, because it's not feasible for uosc to provide and maintain integrations for every script out there.

**Comment by kilisio** [comment]
Noted, Ill fork the plugin and try to create a menu for it using the api
