### ISSUE TITLE
How to hide "controls" by default and toggle it with a keybinding?

### ISSUE THREAD

**Issue by maliayas** [tomasklaen/uosc#474]
It sounds simple but I could've not managed to find a solution, yet. There is a loosely-related discussion in #417 but it didn't help.

Firstly, I want to hide "controls" by default; such that hovering will not show it. In order to do this, emptying "controls" setting in `uosc.conf` doesn't work because it persistently removes it. So I tried creating a simple script like `mp.command("script-message-to uosc set-min-visibility 0 controls")` but no way, controls still appear by hovering.

So how can I achieve this?

**Comment by tomasklaen** [comment]
This makes no sense to me. Control bar is meant to be used by mouse, so having a keyboard control its visibility, and mouse to use it is just super weird. You can't use it with one hand anymore, and have to shift between keyboard and mouse peripherals to use a single UI element. I don't think I want to put any effort or introduce more code complexity to support this, so if it's not possible now (afaik it isn't), than I don't think it'll ever be. Sorry about that.

**Comment by maliayas** [comment]
Most of the time, like 90%, I use key bindings. So I want to hide the control bar by default. And then, occasionally I want to check _at a glance_ how many subtitles/audio tracks the media have, or use something rarely like shuffle button; so I need to quickly enable the control bar with a key binding. It's a simple and nice GUI for that.

As you can see using both keyboard and mouse for one task is not a issue here because it's too rare.

I've also thought using the menu instead of the control bar for this purpose; but the control bar as a GUI would be better  for stateful stuff (e.g. shuffle button or sub/audio track counts).

Thanks for the great plugin. It's already very useful. I've created this issue to see if somebody points me to a solution or a hack.

**Comment by tomasklaen** [comment]
But the control bar **is** hidden by default. Or do you keep mouse cursor close to timeline to see it?

There's `toggle-ui` and sibling commands to quickly peek stuff that is hidden, and it can be also used to hide stuff if you are too lazy to move cursor away from any UI proximity.

**Comment by maliayas** [comment]
Yeah I know but that's part of the problem. Imagine that everytime I move cursor towards the timeline, an irrelevant control bar appears like an ad popup. Take "speed" setting for example; it's too much clutter when irrelevant, I very rarely use it but _it must be there when I need it_.

I've already read `toggle-ui` and siblings. The problem with them are: after hiding stuff with them, hovering still brings them back. Maybe we should change their behaviour? Currently, after running `toggle-elements timeline,controls`:

- If they became visible, they remain visible no matter mouse moves away (permanent).
- If they became hidden, they still can be brought back by hovering with mouse (so not permanent).

If everybody aggree with me that the latter above is inconsistent with the former, hiding behaviour can be made permament too.

Otherwise, I need a hack/workaround to accomplish this. I'm still in search. Thanks for joining the discussion so far.

**Comment by tomasklaen** [comment]
> everytime I move cursor towards the timeline

Then don't move the cursor towards timeline? It's like you're hitting yourself in the head and blaming me for it.

Other UIs display the whole UI after any small cursor movement, and hide it after arbitrary amount of time, which I've always found annoying, so I made uosc to only display it when you move the cursor towards a particular element, as it assumes you want to use it. This way you are always in 100% control when the UI is visible and when it isn't.

Just put cursor to the center/left side of the screen. If the screen is small, decrease min/max proximity settings. If your hand is not on a mouse/touchpad, but on a keyboard, just tap `toggle-ui` twice to hide it.

The only way how I can explain you having these problems of UI elements showing themselves when you don't want to (which none else seems to be having), is that you are using a mouse and living in an area with permanent earthquakes.

**Comment by maliayas** [comment]
> > everytime I move cursor towards the timeline
> 
> Then don't move the cursor towards timeline?

Why? Can't I simply want to use the timeline? While moving towards and using the timeline, control bar quickly appears and disappears; and I simply find that distracting.

I've never blamed you, just wanted to find a way to accomplish something. If that's not possible it's totally OK.

Again, uosc is alredy great and very useful, thanks for it.

**Comment by maliayas** [comment]
BTW, if you think the task is possible with a _quick&dirty_ patch, that would help, too. No need to change the upstream code.

(I'm unfortunately not good with Lua.)

**Comment by christoph-heinrich** [comment]
> _quick&dirty_ patch

``` diff
diff --git a/scripts/uosc_shared/elements/Controls.lua b/scripts/uosc_shared/elements/Controls.lua
index 9a6be72..4e96042 100644
--- a/scripts/uosc_shared/elements/Controls.lua
+++ b/scripts/uosc_shared/elements/Controls.lua
@@ -213,9 +213,14 @@ function Controls:register_badge_updater(badge, element)
 	else mp.observe_property(observable_name, 'native', handler) end
 end
 
+hide = -1
+bind_command('toggle_controls', function()
+	hide = hide * -1
+	request_render()
+end)
+
 function Controls:get_visibility()
-	return (Elements.speed and Elements.speed.dragging) and 1 or Elements.timeline:get_is_hovered()
-		and -1 or Element.get_visibility(self)
+	return hide
 end
 
 function Controls:update_dimensions()
```
Add the line `x script-binding uosc/toggle_controls` to your input.conf

**Comment by maliayas** [comment]
Works great! Thanks very much @christoph-heinrich. I'll tweak it for a few edge cases and then everything is perfect!

For future readers, here is my key binding:

    F5 script-binding uosc/toggle_controls; script-message-to uosc toggle-elements timeline

**Comment by ONISINO233** [comment]
Base on https://github.com/tomasklaen/uosc/issues/474#issuecomment-1468937024 ，I make these changes
```
visibility = true
bind_command('toggle_controls',
	function()
		visibility = not visibility
		request_render()
	end
)

function Controls:get_visibility()
	return not visibility and -1 or Elements:v('speed', 'dragging') and 1 or Elements:maybe('timeline', 'get_is_hovered')
		and -1 or Element.get_visibility(self)
end
```
than we still could use mouse to display control bar, `toggle_controls` just as a lock for display of control bar.
