### ISSUE TITLE
Set Default Audio & Subtitles Preferences

### ISSUE THREAD

**Issue by Jamiex304** [tomasklaen/uosc#476]
Hi, 

I have a lot of anime series locally with some having Japanese set as the default others English. I was wondering if there was a chance to get an option or something to set your preferred choice for example Japanese instead of having to open the file MVP and change it at the start each time.

Thanks.

**Comment by BhaturaGuy** [comment]
`alang=ja,jap,jpn`
`slang=en,eng`
add these in `mpv.conf`

**Comment by tomasklaen** [comment]
As noted above, this is mpv config, not uosc config.
