### ISSUE TITLE
Audio not loading when streaming youtube videos

### ISSUE THREAD

**Issue by lewdpatriot** [tomasklaen/uosc#477]
![Screenshot_20230318_085354](https://user-images.githubusercontent.com/63286528/226082110-fdb68dc0-8cfb-49c5-be1b-24652459715c.png)

**Comment by BhaturaGuy** [comment]
Not a uosc issue.
Check error logs and update yt-dlp

**Comment by christoph-heinrich** [comment]
That is because of this https://github.com/mpv-player/mpv/issues/11392.
You'll have to either save the newest ytdl_hook.lua to your scripts folder in combination with `--ytdl=no`, or update to a newer version of mpv (there has been no release since that fix, so you'll have to compile git master).

**Comment by lewdpatriot** [comment]
> That is because of this [mpv-player/mpv#11392](https://github.com/mpv-player/mpv/issues/11392). You'll have to either save the newest ytdl_hook.lua to your scripts folder in combination with `--ytdl=no`, or update to a newer version of mpv (there has been no release since that fix, so you'll have to compile git master).

Thank you very much, it worked.
