### ISSUE TITLE
Open the playlist menu when clicking top bar playlist indicator

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#480]
As the title suggest I was wondering if it would be possible to make the Playlist Position in the Tob Bar open the playlist menu when clicked upon.

**Comment by hooke007** [comment]
Why we need this strange feature. We already had the buttons to open the playlist.

**Comment by Cananbolt** [comment]
The main reason why I wanted it was so it could reduce cluster. I wouldn't need to have both open-file and playlist controls. They almost serve the same purpose so, I thought having the playlist display when clicking the playlist position would help this.

**Comment by tomasklaen** [comment]
I don't think it hurts anything, makes sense, and gives people an option to replace the playlist button with something else. I'm not against this at all.

I'll add it when I have some time.

**Comment by Cananbolt** [comment]
> I don't think it hurts anything, makes sense, and gives people an option to replace the playlist button with something else. I'm not against this at all.
> 
> I'll add it when I have some time.

I appreciate it, thank you so much!
