### ISSUE TITLE
Input/Write URL (a option in Menu & in Subtitles/Audio Button)

### ISSUE THREAD

**Issue by alexpandain** [tomasklaen/uosc#497]
![image](https://user-images.githubusercontent.com/73612338/230102598-7d8607ab-c520-43c9-a3ea-0268dd439ab5.png)
![image](https://user-images.githubusercontent.com/73612338/230102746-46de03f7-91fb-4e06-85b9-bc00fed9de5c.png)

**Comment by aicynide** [comment]
Thank you

**Comment by po5** [comment]
Here's a script that does what you want, but note that pasting in search menus is not currently supported.
```lua
-- open-url.lua

mp.utils = require "mp.utils"

mp.register_script_message("open-url:", function(path)
    mp.commandv("script-message-to", "uosc", "close-menu", "open-url")
    mp.commandv("loadfile", path)
end)

mp.add_forced_key_binding("F10", "open-url", function()
    local script_name = mp.get_script_name()
    local json = mp.utils.format_json({
        type = "open-url",
        title = "http://www.example.com/stream.avi",
        items = {
            {
            title = "Enter a network URL and press Ctrl+Enter",
            value = "ignore",
            muted = true,
            selectable = false
            }
        },
        on_search = {"script-message-to", script_name, "open-url:"},
        palette = true,
        search_style = "palette",
        search_debounce = "submit"
    }) or "{}"
    mp.commandv("script-message-to", "uosc", "open-menu", json)
end)
```

**Comment by tomasklaen** [comment]
Just an update: I don't want to add more loading items to subtitle/audio menus, especially not for something like this that won't be used by almost anyone, so it'll have to be as an alt action on the "Load {type}" item, which depends on menu item buttons, which is not implemented yet.

**Comment by tomasklaen** [comment]
There's still no button or UI so I'll keep this open, but thanks to the commit above, in 5.1 you'll be able to paste in subtitle/audio/video track select menus to automatically load whatever path/url is in the clipboard as current menu track type.

**Comment by cipricus** [comment]
Just in case, as a tip to the OP, showing that the need for this is rather limited. Dragging and dropping an url on mpv window does it. 

![image](https://github.com/tomasklaen/uosc/assets/3447868/63ab2849-5f43-41c8-8b94-d58d49dee238)

I guess this question is asked in Windows but in Linux you can do it by copying the link and in a terminal writing `mpv` and pasting.

And more specifically in Plasma if we associate `html` files to mpv, copying the link will open the list of applications associated with html.

**Comment by christoph-heinrich** [comment]
@aicynide Stop being annoying, just use the script from po5's comment.

**Comment by tomasklaen** [comment]
People can now paste paths or URLs into:

- File menu to open them immediately.
- Track menus (audio, video, subtitles) to add as new track and activate it.
- Playlist menu to add to playlist.

I think this covers most of the pasting/input needs.

**Comment by hooke007** [comment]
![image](https://github.com/user-attachments/assets/79d6ac06-ca8d-484b-ac95-2af2604df3a3)
I think you forget to handle the special characters.

**Comment by hooke007** [comment]
Any filename which contains `space`.

**Comment by tomasklaen** [comment]
I don't have issue with spaces in file names. Also, you can see the whole filename including spaces in the screenshot you posted, so that seems to not be an issue.

And dunno what the `Invalid argument` could mean. Pasting in a path/url results in the standard:

```lua
mp.commandv('loadfile', value)
```

**Comment by hooke007** [comment]
```
[VCB-Studio] Fate stay night Unlimited Blade Works [24][Ma10p_1080p][x265_flac].mkv
```

If I delete all `space` in the original filename, it will work.
![image](https://github.com/user-attachments/assets/8c05958e-f0a6-4449-8863-b90ea1757fbf)

**Comment by tomasklaen** [comment]
I used your name with spaced, and again, no issues for me. No idea what might be going on here.

**Comment by hooke007** [comment]
I got some clues.
I build the same dirs in Disk D and copy the file. Now it could read this file.
```
D:\Users\hooke007\Videos\[VCB-Studio] Fate stay night Unlimited Blade Works [24][Ma10p_1080p][x265_flac].mkv
```

> What menu are you pasting it into?

Filebrowser

**Comment by hooke007** [comment]
> I got some clues.

Now I confirmed that any file in my disk C which use `space` in the filename can not be read correctly.

**Comment by tomasklaen** [comment]
You can try debugging it yourself. The code that is opening the file is in file `lib/menus.lua` at line `738`:

```lua
mp.commandv(command, event.value)
```

Try adding this before it and checking if there's something unusual:

```lua
print(utils.to_string(command), utils.to_string(event.value))
```

**Comment by hooke007** [comment]
> Try adding this before it and checking if there's something unusual

Cannot found any difference with the actual filename.

**Comment by hooke007** [comment]
Hmm, Sorry for wasting a little time for both of us. I think that was a 'ghost' bug for windows.
I reboot my PC and then everything works fine...😂

**Comment by hooke007** [comment]
> Like this

You prefer to waste time type in each word one by one instead of pasting in one second?

**Comment by hooke007** [comment]
> add password in pasted URL.

Not sure if mpv natively support it.
https://github.com/mpv-player/mpv/issues/1512#issuecomment-71356159
So far it seems only smb's password is supported in mpv.
