### ISSUE TITLE
Title bar not showing

### ISSUE THREAD

**Issue by Erothas** [tomasklaen/uosc#500]
```
profile=gpu-hq
gpu-api=vulkan
# required so that the 2 UIs don't fight each other
osc=no
# uosc provides its own seeking/volume indicators, so you also don't need this
osd-bar=no
# uosc will draw its own window controls if you disable window border
border=no
video-sync=display-resample

```
That is my entire mpv.conf file. I haven't changed anything because everything is a 100% fresh installation. I did not touch uosc.conf file either. My title bar still does not showing. I even tried changing `top_bar` to `always`, and it still does not show.

Launching mpv from the terminal does not report back any errors.

I love uosc, by the way! It's pretty much the reason why I am able to use mpv. So, thank you very much for your work <3

**Comment by christoph-heinrich** [comment]
Everything else is showing except for the top bar? or is it literally just the title that's not showing, but playlist indicator and window controls do show?

**Comment by Erothas** [comment]
Only thing not showing is the top bar, yes. Everything else is works fine.

**Comment by tomasklaen** [comment]
I guess we need a video or something. Seems like you're leaving out some crucial information. Since it works for everyone else, "not showing" doesn't tells us anything.

From your description it looks like your border is enabled, but config you posted has it off. So no idea. Maybe if you provide `mpv.conf`, `scripts`, and `script-opts` directories.

**Comment by Erothas** [comment]
So, after fumbling around and redownloading everything from scratch, my title bar seems to be working now. However, only in fullscreen though? I don't want to full screen music or videos just to read the filename. Is there a way around this?

Thank you in advance.

**Comment by tomasklaen** [comment]
From your description this behaves as if your mpv window border was enabled, in which case the top bar will not be rendered.

Isolate the issue and zip the mpv config directory. Otherwise I don't have a slightest idea what is going on.

**Comment by Erothas** [comment]
[mpv.zip](https://github.com/tomasklaen/uosc/files/11181747/mpv.zip)
There you go. I verified that `border=no` like a million times. You can see for yourself from the zip file anyway.

**Comment by christoph-heinrich** [comment]
Your config works for me.

**Comment by Erothas** [comment]
https://user-images.githubusercontent.com/55455670/230697957-deac2553-78ef-4a56-8ada-2575689a8789.mp4

Oh god. I had to get OBS to work (it doesn't work with fractional scaling), learn how to use OBS for the first time, and then convert the video to x265 because the it was too large to upload. But here you go!

**Comment by hooke007** [comment]
Have you checked the mpv log? I wonder if desktop environment affect some window related props.

**Comment by Erothas** [comment]
I did run mpv through the terminal already, yeah. 0 errors or anything out of the ordinary.

For context, I am using the Hyprland Window Manager.

**Comment by hooke007** [comment]
>  terminal 

This is not log at all. use `--log-file=test.log` to check.

**Comment by Erothas** [comment]
[test.log](https://github.com/tomasklaen/uosc/files/11182385/test.log)
The log file is quite lengthy. So, hopefully you are okay with it as an attachment.

**Comment by hooke007** [comment]
I have no idea. Nothing showed in the log that border would change.

**Comment by christoph-heinrich** [comment]
We may have to provide a patch to insert a bunch of print/log statements into your uosc to figure out what's going on there.

Have you tried `top_bar=always` in your uosc.conf? If that doesn't help you can also try replacing modifying the function `TopBar:decide_enabled()` in file `uosc_shared/elements/TopBar.lua` by replacing everything except for the last for loop with `self.enabled = true`. That way we know for sure if it's a problem with the top bar getting disabled for some reason.

The only way I see for the behavior in the video would be for `border=yes`, but your config clearly shows borders set to `no`. I guess to make absolutely certain that it's actually `border=no` at runtime you could try `print-text ${border}` in the console, but unless the window manager can somehow overwrite that, I don't know how that's even possible.

**Comment by Erothas** [comment]
> Edit: I've checked mpv source code and it does indeed get set by the compositor. So I guess Hyprland doesn't allow client side decorations, therefore border=yes.
> top_bar=always in your uosc.conf should solve the problem.
> I assume you don't want window controls, so put top_bar_controls=no as well.

Eh, I hate to be the bearer of bad news. However, all these options changed absolutely nothing for me.

> edit: If you try to cycle border again and again on the fly, could the title bar be rendered?

Nope. Still nothing.

**Comment by tomasklaen** [comment]
Go to `uosc_shared/elements/TopBar.lua` and replace `TopBar:decide_enabled()` with this:

```lua
function TopBar:decide_enabled()
	print('options.top_bar', options.top_bar)
	print('options.top_bar_controls', options.top_bar_controls)
	print('options.top_bar_title', options.top_bar_title)
	print('state.border', state.border)
	print('state.fullscreen', state.fullscreen)
	if options.top_bar == 'no-border' then
		self.enabled = not state.border or state.fullscreen
	else
		self.enabled = options.top_bar == 'always'
	end
	self.enabled = self.enabled and (options.top_bar_controls or options.top_bar_title)
	for _, element in ipairs(self.buttons) do
		element.enabled = self.enabled and options.top_bar_controls
	end
end
```

and refer back what it logs in the console (don't need the file log).

And then try this:

```lua
function TopBar:decide_enabled()
	self.enabled = true
	for _, element in ipairs(self.buttons) do
		element.enabled = self.enabled and options.top_bar_controls
	end
end
```

to check if it starts being rendered, and that the issue is not somewhere else.

**Comment by Erothas** [comment]
https://user-images.githubusercontent.com/55455670/230746161-811cc8f0-7fd0-4f22-a45e-9cd187d11155.mp4

I felt like either I am doing a mistake or horribly missing something here. So, I recorded another video just as a proof that none of these solutions are working for me.

**Comment by hooke007** [comment]
> refer back what it logs in the console

You forgot it.

**Comment by Erothas** [comment]
My apologies. I just remembered it a few seconds before you replied. There is no special output in any either code blocks variations used. But here you go:

```
 (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:05 / 00:00:42 (14%) A-V: -0.004 DS: 2.400/21

Exiting... (Quit)
warning: queue 0x7f4f986fd250 destroyed while proxies still attached:
  zwp_linux_dmabuf_feedback_v1@32 still attached
```

**Comment by christoph-heinrich** [comment]
1. You were editing the wrong lua file. `~/.config/mpv/scripts/uosc_shared/elements/TopBar.lua` is what's used by mpv. You can delete the folder outside of the scripts directory.
2. You're uosc.conf needs to be at `~/.config/mpv/script-opts/uosc.conf`

**Comment by Erothas** [comment]
It's fixed, finally! Thank you very much!

The second lua code block you provided yesterday was the one that did it.

**Comment by christoph-heinrich** [comment]
Relying on that modified function is bad, because you'll then have to apply that to every update.
`top_bar=always` in `~/.config/mpv/script-opts/uosc.conf` is all you need.
