### ISSUE TITLE
On Screen Size or Large videos?

### ISSUE THREAD

**Issue by lavara123** [tomasklaen/uosc#501]
UI moves to bottom on first boot in videos larger than screen
![Ekran görüntüsü_2023-04-09_18-34-13](https://user-images.githubusercontent.com/12005386/230782236-5a86ae72-562b-40a3-af3d-f47251519160.jpg)

**Comment by christoph-heinrich** [comment]
I'm not sure what you mean with that, but I think something like this in you're `mpv.conf` might help
```
autofit=960x540
geometry=50%:50%
```
Those are what I use in my config, you'll have to adjust them to your preferences.

**Comment by lavara123** [comment]
> I'm not sure what you mean with that, but I think something like this in you're `mpv.conf` might help
> 
> ```
> autofit=960x540
> geometry=50%:50%
> ```
> 
> Those are what I use in my config, you'll have to adjust them to your preferences.

thanks this worked for me

```
# force starting with centered window
geometry=50%:50%

# don't allow a new window to have a size larger than 90% of the screen size
autofit-larger=90%x90%
```
