### ISSUE TITLE
Add command for setting secondary subtitles

### ISSUE THREAD

**Issue by leiserfg** [tomasklaen/uosc#504]
It could be the same as "uosc/subtitles" but for setting `--secondary-sid={the_id}`. Which is very useful for language learning.

**Comment by GunGunGun** [comment]
+1, I would love to have a sub-menu inside subtitle picker menu to pick 2nd sub, it's so so useful for language learning.

**Comment by bigorados** [comment]
+1 yes please, also i'm trying to solve a issue at the moment that it seems that the secondary subtitle visibility is tied to mouse proximity like the UI

**Comment by k1gen** [comment]
+1

**Comment by tomasklaen** [comment]
Implemented in [7150ceb](https://github.com/tomasklaen/uosc/commit/7150ceb1c16a2933e7ccff79685e312e1bf6517a).

You can now set/toggle secondary subtitles in main `uosc/subtitles` menu.
