### ISSUE TITLE
'open-config-directory' not working on MacOS

### ISSUE THREAD

**Issue by LampPrinter** [tomasklaen/uosc#512]
Stopped working in latest update.

Something to do with this commit
https://github.com/tomasklaen/uosc/commit/08734f1ddaee590953e289e1340978e6abe08af0

**Comment by christoph-heinrich** [comment]
Would you mind testing my PR? I don't have an apple device to test it on, but it's such a simple change that it should be fine.

**Comment by LampPrinter** [comment]
Yes, working now.
