### ISSUE TITLE
`text.lua` would be broken by embedd chapters? files

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#515]
sample here
[test3.zip](https://github.com/tomasklaen/uosc/files/11275575/test3.zip)

**Comment by christoph-heinrich** [comment]
Works fine for me.

**Comment by hooke007** [comment]
![Snipaste_2023-04-19_18-47-16](https://user-images.githubusercontent.com/41094733/233157916-a24a0d19-145c-44f2-9f56-d144a83f34dc.jpg)

**Comment by christoph-heinrich** [comment]
Are you on the latest version of uosc? Because I don't see how that error is even possible in that line.
``` lua
char_byte = str:byte(i + j - 1) - 0x80
```
`j` is from a for loop, therefore it can't be `nil`. `i` comes as a parameter, and the  function only ever gets called with the value 1.

**Comment by hooke007** [comment]
> Are you on the latest version of uosc?

Always here.

**Comment by dyphire** [comment]
> Always here. @dyphire If it's convenient for you, test it please.

Can't reproduce with sample, also works fine for me.

**Comment by hooke007** [comment]
I have no idea neither. It only works fine in the windows sandbox.

https://user-images.githubusercontent.com/41094733/233235803-f4172fae-bce4-4337-8ddf-bb6fa55db097.mov

**Comment by Xianglos** [comment]
Same bug here.
<img width=400 src="https://user-images.githubusercontent.com/33227442/233788653-9c7cab29-537d-4849-9bc1-7c5c8e525172.jpg">

**Comment by christoph-heinrich** [comment]
I think what's going on here is that `str` is actually not as long as expected, resulting in `str:byte()` returning nil.

It's hard to say what's actually going wrong here, invalid utf-8? Based on the stack trace it happens with a string that has already been wrapped by `wrap_text()`, so maybe that function breaks the utf-8 encoding somehow? But then the question is why it doesn't break for everyone on the same file...

You should be able to at least prevent the crash by wrapping the content of that for loop with a `if i + j - 1 <= #str then`, but that's certainly not a proper solution for this.

**Comment by hooke007** [comment]
> I'd assume you currently have a build with LuaJIT, so ideally you find a build with the Lua interpreter, to make sure it's not a LuaJIT bug.

Lua51 cannot make it work neither. (I tested MSYS2's mpv bin which is built by lua51.)

**Comment by dyphire** [comment]
> > I'd assume you currently have a build with LuaJIT, so ideally you find a build with the Lua interpreter, to make sure it's not a LuaJIT bug.
> 
> Lua51 cannot make it work neither. (I tested MSYS2's mpv bin which is built by lua51.)
> 
> By cutting the video into multiple clips, some of the clips played fine. So I think part of the reason might be that there are some strange symbols in the chapter names that could not be converted.

Does this setting have an impact?
![image](https://user-images.githubusercontent.com/61936050/234015395-3bd51316-bfcf-4ef7-84b9-dfea87bcf27f.png)
Enabling or disabling it in my tests will result in the same results.

**Comment by hooke007** [comment]
Nope.

**Comment by po5** [comment]
Here is a file with a non-utf8 chapter title, which leads to the same crash.

https://github.com/tomasklaen/uosc/assets/42466980/8708f81e-5d4a-45a8-b7ab-5c9738459d70

My understanding is that in this case the encoding is undefined, mkvtoolnix refuses to work with this file unless given the correct encoding (not sure which one that would be).  
I doubt we can make it display the correct text without taking many potentially wrong guesses, but we should at least make it not crash.

Default OSC displays garbage, maybe we can turn unknown text into garbage and use that for computing text dimensions.
![image](https://github.com/tomasklaen/uosc/assets/42466980/d87f7f97-d6e7-40e7-ab62-55897e496fdb)

**Comment by tomasklaen** [comment]
I think we should make a `sanitize_utf8()` function that just clamps the bytes to be within valid utf8 range, and wrap all received texts with it. It'll produce gibberish, but that is to be expected for invalid text. As long as it displays without crashing.

**Comment by po5** [comment]
Fallback values are the wrong approach, chapters need to be consistent between text that wraps and text that doesn't (in @christoph-heinrich's screenshot, see top left chapter display).  
It would be nice if we could have the same behavior as whatever libass does (same behavior as default osc and non-wrapped/non-measured text). Maybe that's clamping like @tomasklaen proposed.

**Comment by hooke007** [comment]
> I also wonder what the default osc displays for @hooke007's file on his side, surely garbled text somewhere.

Same here.

**Comment by christoph-heinrich** [comment]
Capping the byte count to the string length and pretending that everything is fine does work though and is pretty simple.
![image](https://github.com/tomasklaen/uosc/assets/8932183/a7f99f3d-2a22-4bff-911e-45fffb329c8a)
I'll make a PR with that.
