### ISSUE TITLE
Adding video equalizer with brightness

### ISSUE THREAD

**Issue by Mint-me123** [tomasklaen/uosc#516]
Can playback brightness be added to the osc? Would make it possible to control this parameter using only a mouse (like volume)

**Comment by tomasklaen** [comment]
#329

I don't think anything changed since then.

**Comment by Mint-me123** [comment]
Fair enough. In fact I really must be part of the 0.01% because I couldn't
find anything on it. Must be my tablet because I often need to lift the
brightness. However for anyone else in the 0.01% fraction you can use the
default keyboards shortcut settings and activate the on screen keyboard to
adjust brightness/contrast etc. just using the mouse.
