### ISSUE TITLE
Unclickable menus

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#536]
While the menu is open, try to drag the window (with window dragging option enable).
You will sometimes enter a state where buttons light up when hovered, but nothing happens on click.
Menus can still be navigated with keyboard.
Easiest to replicate with `--idle`, which also seems to have different behavior than normal playback, allowing window-dragging when drag starts from outside the menu once the buggy state is triggered.
I've been able to replicate with an open paused video too.
Can't get it to happen consistently, but it's very common (>50%) with `--idle`.
May be related to #496.

**Comment by christoph-heinrich** [comment]
How exactly do I reproduce this?
I've tried `mpv --config-dir=<path to uosc only config> --idle --force-window`, click on the Playlist/Files control to open up a scrollable menu and then trying to drag outside of the menu window, but all it does is close the menu every time I try it.

**Comment by hooke007** [comment]
How to reproduce this by other ways?

> While the menu is open, try to drag the window (with window dragging option enable).

I often do it but had never meet with the issue.

**Comment by po5** [comment]
Protip: do not accidentally keep two copies of uosc.lua in your scripts directory... :^)
