### ISSUE TITLE
Localizing menus comming from other scripts

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#538]
Currently, people can use `add-intl-direcory` message to provide their own localization json files which will be merged into uosc's ones, but that doesn't on it's own translate their menus yet.

I was thinking of maybe adding new options to menu data structure:

```
translate_title?: boolean;
translate_items?: boolean;
translate_hints?: boolean;
```

since these values need to only be translated on demand otherwise we are risking translating stuff that shouldn't be, like filenames.

We'll then translate inside Menu:update(), which already walks the whole menu data structure.

But this solution doesn't support translating dynamic strings like `"%s of something"`.

Should we instead just implement `get-option <option_name>` message, which will reply with the value of requested uosc's option so that scripts can inherit `langauges`, handle translations on their end, and just send us already translated menu data?

Because I don't see any way uosc could handle translation for other scripts without incredibly messy solutions full of compromises. Nor it makes much sense to be honest since most scripts add uosc menus as an optional feature, so they can't depend on it for localization.

**Comment by christoph-heinrich** [comment]
Scripts should take care of the translation themselves, it's the simplest way to get good results.

I'm not sure if providing them with the languages list all that useful. If the script does support multiple languages, it'll need it's own way of specifying the language anyway.

**Comment by po5** [comment]
Scripts can already do `options.read_options(uosc_options, "uosc")` if they want to retrieve the raw uosc config.

I guess scripts that want the feature should just copy uosc's language priority and translation code, so they can use translations in their custom-drawn menus.

**Comment by tomasklaen** [comment]
All right, makes sense, I'll leave it as it is.
