### ISSUE TITLE
Revert or drop `f4ef5e8` and `618e472`

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [tomasklaen/uosc#544]
A tiny regression, main title of third-party scripts can be translated before these two commits.

https://github.com/tomasklaen/uosc/commit/f4ef5e89907a9bca55e56e6080cd373df4f46583
https://github.com/tomasklaen/uosc/commit/618e4728f46539267cfbb1ae5b3a633a60b4094a

**Comment by po5** [comment]
It's intentional, see #538. The conclusion was that scripts should handle their own translations.

**Comment by tomasklaen** [comment]
Yup, see #538.
