### ISSUE TITLE
Border of timeline visible in windowed mode. Any fix?

### ISSUE THREAD

**Issue by Azkaas** [tomasklaen/uosc#549]
![image](https://user-images.githubusercontent.com/112915552/235556755-1f52c4a1-d4db-49da-9a90-227b883ac390.png)

As you can see in the picture the timeline have a few pixels of visibility in windowed mode. Is there any fix to this?
It is quite distracting in live streams where i keep sing the cache updated

**Comment by po5** [comment]
https://github.com/tomasklaen/uosc/blob/3c70ffd927a26261a221e6f9a2e5cf4d07f2c6df/script-opts/uosc.conf#L8-L9

**Comment by hooke007** [comment]
Just a joke. Sometimes I think we don't need to provide any options for users because they seems don't use conf file at all.

**Comment by Azkaas** [comment]
Ok now i feel stupid :sweat_smile: I should have checked the conf file first. Thanks for the help! :)
