### ISSUE TITLE
Show Current/Total Tracks

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#556]
I was wondering if it would be possible to show the current track / total tracks for, audio tracks, subtitle tracks, and so on. UOSC already shows the total tracks, but I think adding the current track as well, can be helpful due to letting you see what track you are viewing.

**Comment by hooke007** [comment]
see track menu

**Comment by dyphire** [comment]
This feature has been discussed before, ref https://github.com/tomasklaen/uosc/pull/212

**Comment by Cananbolt** [comment]
I see, I was wondering if it could be something like default osc mpv, where it has the current/total tracks always displayed without having to hover over the item.

Something like this...
![image](https://user-images.githubusercontent.com/100978782/236692913-85968b1f-4635-4278-ba47-2fbaacbdda29.png)

**Comment by dyphire** [comment]
> I see, I was wondering if it could be something like default osc mpv, where it has the current/total tracks always displayed without having to hover over the item.

see https://github.com/tomasklaen/uosc/pull/212#issuecomment-1251084638

**Comment by hooke007** [comment]
Isn't it answered in that PR？

**Comment by Cananbolt** [comment]
> > I see, I was wondering if it could be something like default osc mpv, where it has the current/total tracks always displayed without having to hover over the item.
> 
> see [#212 (comment)](https://github.com/tomasklaen/uosc/pull/212#issuecomment-1251084638)

Understood. Thanks for the clarification.

**Comment by Cananbolt** [comment]
> Isn't it answered in that PR？

I'm not too sure what PR means.

**Comment by hooke007** [comment]
> I don't see a value in telling people the index of currently selected sub/audio/... track. 

In the first line it was rejected. Dyphire tried to show more meanings but nothing changed.

**Comment by Cananbolt** [comment]
> > I don't see a value in telling people the index of currently selected sub/audio/... track.
> 
> In the first line it was rejected. Dyphire tried to show more meanings but nothing changed.

Oh my apologies that is what you meant by PR. Yes I understand that the idea was rejected, but thank you for clearing up my confusion. I appreciate it.

**Comment by hooke007** [comment]
Of course you could give more robust reasons to have a try :-)

**Comment by tomasklaen** [comment]
There's not enough room in the badge for this, and the informational value of knowing active index is near zero, so I don't see a reason to add it.

All you need to know is if there are any tracks by seeing a counter, which track button badges already display, and if there are any just use concerned track menu to browse and select track you want.

**Comment by Cananbolt** [comment]
> There's not enough room in the badge for this, and the informational value of knowing active index is near zero, so I don't see a reason to add it.
> 
> All you need to know is if there are any tracks by seeing a counter, which track button badges already display, and if there are any just use concerned track menu to browse and select track you want.

I understand, thanks for letting me know. Feel free to close the comment anytime you would like.
