### ISSUE TITLE
Subtitle load on streams are using home dir always

### ISSUE THREAD

**Issue by RexAckermann** [tomasklaen/uosc#559]
TL;DR : When streaming a video load sub should start in the $PWD ,I think.

So ,I was streaming a show from ftp that didn't have subs.So ,I downloaded it and tried to load it from the menu.I did cd into the directory where the .srt file was before but it started in the home directory anyways.I tried the same thing with a local video and it was looking into the video directory.

So, why didn't it do the same thing when it was streaming ? If it wasn't a bug then,

It's more convenient to cd into the sub dir and mpv to load that directory first.It's saves a lot of clicks.Can it be implemented ?

**Comment by tomasklaen** [comment]
> So, why didn't it do the same thing when it was streaming?

Because current working directory when people start streams is in 99% cases the location of the mpv binary.

Defaulting to home on streams was a requested feature and makes sense. You can also modify it with `default_directory=~/` option.
