### ISSUE TITLE
uosc not working in latest commit

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#561]
I get this error after trying the latest commit. 

I had similar issues in the past, with other scripts and it was due it mpv was built with lua 5.1 rather than 5.2. Not sure if this piece of info is useful but wanted to let you know just in case.

I am using nobara-appstream's version of mpv, which is patched for that particular distro to reduce headaches for ppl, not so sure why they build it with 5.1.

```
[uosc] 
[uosc] stack traceback:
[uosc]  [C]: in function 'format'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:83: in function 't'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:230: in function </home/maelstrom/.config/mpv/scripts/uosc.lua:200>
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:267: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ?
[uosc] Lua error: /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:83: invalid option '%' to 'format'
```

System config:
```
    ⠀⠀⢀⣤⣴⣶⣶⣶⣦⣤⡀⠀⣀⣠⣤⣴⣶⣶⣶⣶⣶⣶⣶⣶⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ---------------- 
    ⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀   OS: Nobara Linux 37 (KDE Plasma) x86_64 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀   Host: 82B1 Lenovo Legion 5 15ARH05H 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀   Kernel: 6.2.14-300.fsync.fc37.x86_64 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀   Uptime: 2 hours, 13 mins 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠉⠁⠀⠀⠉⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀   Packages: 3050 (rpm) 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁⠀⠀⠀⢀⣀⣀⡀⠀⠀⠀⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀   Shell: bash 5.2.15 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⢠⣾⣿⣿⣿⣿⣷⡄⠀⠀⠀⠻⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀   Resolution: 1920x1080 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⣀⣀⣬⣽⣿⣿⣿⣿⣿⣿⠀   DE: Plasma 5.27.4 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠈⠻⢿⣿⣿⡿⠟⠁⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀   WM: kwin 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀   Theme: [Plasma], Breeze [GTK2/3] 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀   Icons: [Plasma], breeze-dark [GTK2/3] 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀   Terminal: konsole 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀   CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz 
    ⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠛⠉⠉⠛⠛⢿⣿⣿⠀⠀⠀⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀   GPU: NVIDIA GeForce RTX 2060 Mobile 
    ⠀⠘⢿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⠟⠁⠀   Memory: 4166MiB / 15845MiB 
    ⠀⠀⠀⠈⠙⠛⠛⠛⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠛⠛⠛⠉⠁⠀⠀⠀
                                                                       
                                                                       



```
mpv version
```
mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.3
```

Edit: Fixed Grammar

**Comment by hooke007** [comment]
Lua5.1 is always the supported version and currently is used by official test build and many other builds.

**Comment by natural-harmonia-gropius** [comment]
Does `string.gsub(locale[text] or text, "%s", a or '')` works?
![image](https://github.com/tomasklaen/uosc/assets/50797982/cd75bc86-3629-45a3-929e-fcbd7164091a)

**Comment by aicynide** [comment]
Come back friend we want your English translated mpv config for windows

**Comment by NaiveInvestigator** [comment]
not sure if what caused it but also after updating i noticed the tooltips have their spaces stripped now.
before:
![image](https://github.com/tomasklaen/uosc/assets/72654596/f8fe693f-e818-43f1-aaa6-1ed2de494b2a)
current:
![image](https://github.com/tomasklaen/uosc/assets/72654596/bc273d07-6910-447c-a769-b1ff15f584ad)

> Come back friend we want your English translated mpv config for windows

oh lol glad ppl actually use it! it is maintained its just that i only update it if i make any big changes on the my config.
ty for using it, really honoured here  :>

i also plan on making the readme more nicer and informative instead of just pasting screenshots lol. someday ;-;

**Comment by natural-harmonia-gropius** [comment]
I don't understand why it crashes on string.format("%s"), What about replace %s to %q?

**Comment by natural-harmonia-gropius** [comment]
Alternativly, does this works?

```lua
---@param text string
function t(text, ...)
	if not text then
		return ''
	end

	local trans = locale[text] or text

	local arg = {...}
	if #arg > 0 then
		local key = text
		for _, value in ipairs(arg) do
			key = key .. '|' .. value
		end
		if not locale[key] then
			locale[key] = string.format(trans, unpack(arg))
		end
		return locale[key]
	end

	return trans
end
```

**Comment by NaiveInvestigator** [comment]
> We need to see the string on which it's crashing and where it's coming from. To me, this looks like menu item or video title that contains `%` and string.format is recognizing it as invalid format string. We'll have to escape these before they are passed to `t()`.
> 
> Try this and refer what it prints out:
> 
> ```diff
> diff --git a/scripts/uosc_shared/lib/intl.lua b/scripts/uosc_shared/lib/intl.lua
> index 0f51cec..ee0db8d 100644
> --- a/scripts/uosc_shared/lib/intl.lua
> +++ b/scripts/uosc_shared/lib/intl.lua
> @@ -80,7 +80,11 @@ function t(text, a)
>         local key = text
>         if a then key = key .. '|' .. a end
>         if cache[key] then return cache[key] end
> -       cache[key] = string.format(locale[text] or text, a or '')
> +       if pcall(function() cache[key] = string.format(locale[text] or text, a or '') end) then
> +               return cache[key]
> +       else
> +               print('Failed to translat
> ```


following Tomas's comment  this I get this in console:
```
[uosc] 
[uosc] stack traceback:
[uosc]  [C]: ?
[uosc]  [C]: in function 'require'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:136: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ?
[uosc] Lua error: error loading module 'uosc_shared/lib/intl' from file '/home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua':
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:84: unexpected symbol near '+'
```

**Comment by tomasklaen** [comment]
It's a diff, don't paste the `+` signs at the beginning of lines too. You should `git apply` it. If you don't want to bother with git, here's the whole function to paste:

```lua
function t(text, a)
	if not text then return '' end
	local key = text
	if a then key = key .. '|' .. a end
	if cache[key] then return cache[key] end
	if pcall(function() cache[key] = string.format(locale[text] or text, a or '') end) then
		return cache[key]
	else
		print('Failed to translate "' .. (locale[text] or text) .. '"')
	end
end
```

**Comment by NaiveInvestigator** [comment]
> ```lua
> function t(text, ...)
> 	if not text then
> 		return ''
> 	end
> 
> 	local trans = locale[text] or text
> 
> 	local arg = {...}
> 	if #arg > 0 then
> 		local key = text
> 		for _, value in ipairs(arg) do
> 			key = key .. '|' .. value
> 		end
> 		if not locale[key] then
> 			locale[key] = string.format(trans, unpack(arg))
> 		end
> 		return locale[key]
> 	end
> 
> 	return trans
> end
> ```

yes this does seem to work and nothing is out of usual yet , and the spaces do not get trimmed now.

![image](https://github.com/tomasklaen/uosc/assets/72654596/8b6a94b5-246b-4643-9fe8-d2e9de46a402)
![image](https://github.com/tomasklaen/uosc/assets/72654596/f250f1dd-34fc-4319-b02d-30793c72f3f1)

**Comment by NaiveInvestigator** [comment]
> It's a diff, don't paste the `+` signs at the beginning of lines too. You should `git apply` it. If you don't want to bother with git, here's the whole function to paste:
> 
> ```lua
> function t(text, a)
> 	if not text then return '' end
> 	local key = text
> 	if a then key = key .. '|' .. a end
> 	if cache[key] then return cache[key] end
> 	if pcall(function() cache[key] = string.format(locale[text] or text, a or '') end) then
> 		return cache[key]
> 	else
> 		print('Failed to translate "' .. (locale[text] or text) .. '"')
> 	end
> end
> ```

sorry i didn't set up my config that way lol so need to manually copy paste stuff, totally missed out the + signs oof. Hopefully i did it correct this time :>
```
[uosc] Failed to translate "50%" 
[uosc] Failed to translate "80%" 
[uosc] Failed to translate "100%" 
[uosc] Failed to translate "120%" 
[uosc] Failed to translate "150%" 
[uosc] Failed to translate "200%" 

```

**Comment by tomasklaen** [comment]
I've thought text would be enough to pin point the source, but I have no idea where those percentages are coming from. Use this now:

```lua
function t(text, a)
	if not text then return '' end
	local key = text
	if a then key = key .. '|' .. a end
	if cache[key] then return cache[key] end
	if pcall(function() cache[key] = string.format(locale[text] or text, a or '') end) then
		return cache[key]
	else
		print('Failed to translate "' .. (locale[text] or text) .. '"')
		print(debug.traceback())
	end
end
```

**Comment by natural-harmonia-gropius** [comment]
These from his input.conf, current code unnecessarily format every text.

**Comment by NaiveInvestigator** [comment]
> I've thought text would be enough to pin point the source, but I have no idea where those percentages are coming from. Use this now:
> 
> ```lua
> function t(text, a)
> 	if not text then return '' end
> 	local key = text
> 	if a then key = key .. '|' .. a end
> 	if cache[key] then return cache[key] end
> 	if pcall(function() cache[key] = string.format(locale[text] or text, a or '') end) then
> 		return cache[key]
> 	else
> 		print('Failed to translate "' .. (locale[text] or text) .. '"')
> 		print(debug.traceback())
> 	end
> end
> ```

This is what i get in console:
```
[uosc] Failed to translate "50%" 
[uosc] stack traceback:
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:87: in function 't'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:230: in function </home/maelstrom/.config/mpv/scripts/uosc.lua:200>
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:267: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ? 
[uosc] Failed to translate "80%" 
[uosc] stack traceback:
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:87: in function 't'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:230: in function </home/maelstrom/.config/mpv/scripts/uosc.lua:200>
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:267: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ? 
[uosc] Failed to translate "100%" 
[uosc] stack traceback:
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:87: in function 't'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:230: in function </home/maelstrom/.config/mpv/scripts/uosc.lua:200>
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:267: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ? 
[uosc] Failed to translate "120%" 
[uosc] stack traceback:
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:87: in function 't'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:230: in function </home/maelstrom/.config/mpv/scripts/uosc.lua:200>
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:267: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ? 
[uosc] Failed to translate "150%" 
[uosc] stack traceback:
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:87: in function 't'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:230: in function </home/maelstrom/.config/mpv/scripts/uosc.lua:200>
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:267: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ? 
[uosc] Failed to translate "200%" 
[uosc] stack traceback:
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc_shared/lib/intl.lua:87: in function 't'
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:230: in function </home/maelstrom/.config/mpv/scripts/uosc.lua:200>
[uosc]  /home/maelstrom/.config/mpv/scripts/uosc.lua:267: in main chunk
[uosc]  [C]: ?
[uosc]  [C]: ? 
```

**Comment by NaiveInvestigator** [comment]
> These from his input.conf, current code unnecessarily format every text.

now that you say it does seem to be the case ;0

relevant section of my input.conf
```
#                  set window-scale 0.5                                            #! Video > Window Scale > 50%
#                  set window-scale 0.8                                            #! Video > Window Scale > 80%
#                  set window-scale 1.0                                            #! Video > Window Scale > 100%
#                  set window-scale 1.2                                            #! Video > Window Scale > 120%
#                  set window-scale 1.5                                            #! Video > Window Scale > 150%
#                  set window-scale 2.0                                            #! Video > Window Scale > 200%
```

Screenshot of how that part looks:
![image](https://github.com/tomasklaen/uosc/assets/72654596/f756797b-992c-4094-8963-4ce8b820d453)

**Comment by tomasklaen** [comment]
Fixed by simply not translating menu items from `input.conf`, which in hindsight shouldn't have been happening in the first place.
