### ISSUE TITLE
Toggle both the uosc ui and thumbnails at the same time

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#562]
Would it be possible to toggle both the uosc ui and thumbnails at the same time? I've tried using the `toggle-ui` uosc command but it hides the buttons above the timeline when I show thumbnails.

**Comment by hooke007** [comment]
> it hides the buttons above the timeline when I show thumbnails

It's the intended design.

**Comment by Zabooby** [comment]
Makes sense.
