### ISSUE TITLE
Shuffle fix?

### ISSUE THREAD

**Issue by BhaturaGuy** [tomasklaen/uosc#569]
Can shuffle work like it does in every other media player? I've had many instances where it just repeats already played files even if loop playlist is off.
Simply speaking
* Play files in random order
* Does not repeat files until loop playlist is on.

**Comment by tomasklaen** [comment]
Shuffle now guarantees no path/url repetition until at least 80% of the playlist/directory has been exhausted.

I think this is a sweat spot where you still have unstable randomness (playlist won't always look the same on every iteration), but you'll also never feel like files are played too often.
