### ISSUE TITLE
Change options based on condition (profile-cond in MPV)

### ISSUE THREAD

**Issue by dnngll** [tomasklaen/uosc#573]
## Hello,

is there a way to use the `profile-cond`, like in MPV? I tried

```
[audio]
profile-cond=not vid
timeline_size_min=80
```

in `uosc.conf`, but that didn't work unfortunately.

Thanks : )

**Comment by christoph-heinrich** [comment]
That is currently not possible.

Options of scripts can be changed at runtime via [script-opts](https://mpv.io/manual/master/#options-script-opts), but we currently don't support that.
There is a PR to add support for that #571, but there is still a lot of work missing to make it actually usable with most options.

**Comment by dnngll** [comment]
Hello @christoph-heinrich ,

thanks for the quick reply. Looking forward to when this will be implemented!

**Comment by christoph-heinrich** [comment]
@bananakid You can change your controls by appending to script-opts in a conditional profile.

```ini
[audio-only]
profile-cond=vid == false
profile-restore=copy-equal
script-opts-append=uosc-controls=<your controls config but without speed widget and fullscreen button>
script-opts-append=uosc-progress_size=80
```

@tomasklaen I think this issue can be closed, or am I missing something?

**Comment by dnngll** [comment]
Hello @christoph-heinrich ,

> You can change your controls by appending to script-opts in a conditional profile.
> 
> ```ini
> [audio-only]
> profile-cond=vid == false
> profile-restore=copy-equal
> script-opts-append=uosc-controls=<your controls config but without speed widget and fullscreen button>
> script-opts-append=uosc-progress_size=80
> ```
> 
> @tomasklaen I think this issue can be closed, or am I missing something?

is there more info on what to do to get what I tried in https://github.com/tomasklaen/uosc/issues/573#issue-1743385845 ? Or is that still not possible?

Thanks!

**Comment by christoph-heinrich** [comment]
@dnngll Does the profile I posted not work for you? Simply remove the line with `uosc-controls` and it should do what you want.

**Comment by dnngll** [comment]
@christoph-heinrich

Nothing changed at first - but then I thought about updating uosc... Everything works now. Thank you so much!
