### ISSUE TITLE
Feature Request: seek buttons for the control bar

### ISSUE THREAD

**Issue by codl** [tomasklaen/uosc#577]
I wish uosc had buttons that seek forward/back a set amount, like the stock osc.

I think I can make my own with the `command:` syntax, but I don't think I can make them seek by a different amount on left/right click, like the osc buttons do. If that's possible then please let me know how.

**Comment by hooke007** [comment]
>  like the stock osc.

which button?

**Comment by tomasklaen** [comment]
To quickly seek, turn mouse wheel when hovering timeline. If you want to seek larger amounts of time, just turn it a lot. I might add shift/ctrl modifier to increase the scroll seek amount, but increasing the complexity of already pretty complex command config syntax to allow different behavior depending on a button pressing it is definitely not gonna happen.

**Comment by codl** [comment]
> which button?

![2023-06-25T19-36-58-glider-fHZxREXbgpD2](https://github.com/tomasklaen/uosc/assets/315139/e5be41c1-a0c5-4a86-809b-eaed82295caf)

> To quickly seek, turn mouse wheel when hovering timeline.

This doesn't fit my needs because it's difficult to scroll precisely on a laptop touchpad. The reason why I use buttons is that it is predictable where they'll take me in the video, if I wanted imprecise seeking I would just scrub with the seek bar.

> increasing the complexity |...] is definitely not gonna happen

Understandable, I guess I'll go back to the stock OSC.

**Comment by tomasklaen** [comment]
> on a laptop

👀 if you're on a laptop, just bind different seeking amounts to (shift/ctrl)+arrows. Way faster than aiming cursor on a button and clicking with a touchpad.

**Comment by tomasklaen** [comment]
Closing in favor of #588.
