### ISSUE TITLE
Pause indicator in controls doesn't always work

### ISSUE THREAD

**Issue by Niotferdi** [tomasklaen/uosc#578]
I added to `uosc.conf`, in the `controls=` line, the `cycle:play_arrow:pause:no=pause/yes=play_arrow?play/pause` element. It allows me to visually verify whether the video is paused or not. But sometimes when I press the space key with the controls pane open, the pause indicator stays in its previous, outdated state. 
I noticed that if you move the mouse cursor up a little bit, then the element is updated from the wrong state to the correct one. At the same time, if you move the mouse close, then the interface elements will not change in any way. The `proximity` option is responsible for this. I tried to edit the code, but I couldn't achieve the same neat result.

**Comment by hooke007** [comment]
have no idea what happened on your side. I cannot reproduce it here.

**Comment by Niotferdi** [comment]
I'm talking about the fact that if you add a play / pause button to the control panel, then its display in half of the cases will be incorrect if you keep the interface open while pressing the space key. This happens even with `--no-config` and default osc.

**Comment by hooke007** [comment]
As I said, cannot reproduce.

>  This happens even with and default osc.

Shouldn't be reported to mpv instead?

**Comment by tomasklaen** [comment]
I thought first that there might not be a call to request re-render in property listeners created by control buttons, but there is. So, I also can't replicate.

Could it be related to https://github.com/mpv-player/mpv/issues/8350?

**Comment by Niotferdi** [comment]
Yes! With `--no-config` and default osc the same effect.

**Comment by Niotferdi** [comment]
Do I need to write an issue to the mpv repository? This is a problem on their part. Despite its 'cloes' status, it is still present in mpv after several versions.

**Comment by christoph-heinrich** [comment]
If you're using the latest released version, then you don't have the fix yet.
It got merged in March, but the last release was in January.

**Comment by Niotferdi** [comment]
OK. For a long time they solved this problem, which was mentioned back in 2020. I'll wait. The uosc developer obviously won't help me with this.
