### ISSUE TITLE
Option to show Timeline on File-Load

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#581]
I was wondering if there could be a way to show the Timeline when loading into a new file. Currently, I believe, uosc only shows the Timeline on startup.

**Comment by tomasklaen** [comment]
Yes. You're not the first one to request an ability to control what flashes on new file, so I'm planning to implement a new options for this:

```
# What elements to flash when new media is loaded `<ids_to_flash>[:duration]` or `none`
# Available ids: controls,timeline,top_bar,volume,speed
new_file_flash=timeline,top_bar:2000
```

But I haven't decided on option name yet. Can't use `file` as urls can be loaded too. `item` is too ambiguous. Maybe `flash_on_load` or something like that.

If anyone has a better idea, or if there's already a similar option in mpv to establish a convention, let me know.

**Comment by christoph-heinrich** [comment]
mpv has `path`, so referring to it as as such instead of file would make sense.
(although urls are also just file on the internet, so I'd be fine with file as well)

**Comment by Cananbolt** [comment]
@tomasklaen I'm not too sure if this will help but I may have found an issue related to this.

I was trying to find a way to flash the timeline on file load and was able to find this in the uosc.lua script.

Lines 683-689
`mp.register_event('file-loaded', function()
	local path = normalize_path(mp.get_property_native('path'))
	itable_delete_value(state.history, path)
	state.history[#state.history + 1] = path
	set_state('path', path)
	Elements:flash({'top_bar'})
end)`

I added `Elements:flash({'timeline'})` underneath `Elements:flash({'top_bar'})`. However it did not work.

**Comment by tomasklaen** [comment]
You need to add timeline to the table:

```lua
Elements:flash({'top_bar', 'timeline'})
```

**Comment by Cananbolt** [comment]
> 
I put that in the config but unfortunately it did not work.

I wanted to see if the other flash elements work and it did. I replaced timeline for controls:

`Elements:flash({'top_bar', 'controls'})`

And it did work. 

Flash Timeline does not activate. Maybe it has something to do with file-loaded but I'm not too sure.

**Comment by hooke007** [comment]
A short timeout could make it work. have no idea what happened on `file-loaded`
```lua
	mp.add_timeout(0.1, function()
		Elements:flash({'top_bar', 'timeline'})
	end)
```

**Comment by Cananbolt** [comment]
> A short timeout could make it work. have no idea what happened on `file-loaded`
> 
> ```lua
> 	mp.add_timeout(0.1, function()
> 		Elements:flash({'top_bar', 'timeline'})
> 	end)
> ```
> 
> It seems `duration` is not available at that moment. Though I got duration after 0.01s, I still need 0.05s timeout to make it work.

This works! Thank you so much.

**Comment by Cananbolt** [comment]
> > It seems `duration` is not available at that moment. Though I got duration after 0.01s, I still need 0.05s timeout to make it work.

UOSC does have `flash_duration` which is what I use to increase duration of the flash events we have above.

**Comment by hooke007** [comment]
No I was talking about property not command.

**Comment by Cananbolt** [comment]
> No I was talking about property in mpv instead of command of uosc.
> 
> The fact proof that it is not a good workaround. If loading a url, it cannot work because we usually need more than 0.1s to get the necessary properties?

Oh I do see the issue with that. Maybe in the future it can be something to work upon. Regardless, I do appreciate the code, it works great for what I primarily use mpv for.
