### ISSUE TITLE
Reverse action of wheel scrolling above timeline

### ISSUE THREAD

**Issue by JenieX** [tomasklaen/uosc#582]
The current behavior is that scrolling the mouse wheel up would seek forward, down to seek backward. I assumed there was an option in `uosc.conf` to reverse the actions but couldn't find it.

**Comment by tomasklaen** [comment]
Set `timeline_step` to negative value.

**Comment by JenieX** [comment]
> Set `timeline_step` to negative value.

Awesome, thank you very much. 😄
