### ISSUE TITLE
5.0

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#587]
A to-do list with things I want in 5.0 so I won't forget:

- [x] Sort out license
- [x] Update installation scripts (`uosc_shared` -> `uosc`)
- [x] Save installation scripts into `installers/uosc.{sh,ps1}` files and have only oneliners in readme that fetch and execute these.
- [x] ~~Menu item actions/buttons.~~
- [x] ~~Improved menu callback API with pressed modifiers, action, and other meta data.~~
- [x] Searchable menus to make command palettes.
- [x] Built in command palette with all keybinds from `input.conf`. Useful for checking what the shortcut for the thing I need right now is.

Stroked-through items will be left for later releases.

**Comment by Zabooby** [comment]
Not sure if this is related but have you removed uosc.lua from the repo? I downloaded the code to get the latest changes but uosc.lua is missing.

**Comment by tomasklaen** [comment]
Support for older versions of mpv was dropped, so uosc is now only inside the `scripts/uosc` folder. If you want to update to current master, delete `uosc_shared` and `uosc.lua`.

**Comment by po5** [comment]
Some things that have been bugging me, around using the menu API's `on_close` for scripts that need to keep state of whether they're open or not to perform menu updates and close their own menu.

We can't react to an `on_close` callback immediately, only when our custom menu script frees the event loop again.  
It leads to two issues:
- We may call `update-menu` without yet knowing our menu was closed by the user, which causes it to reopen. Solution: ignore `update-menu` when there's no corresponding menu, but maybe that breaks someone else's use case? 
- In an attempt to close a menu, calling `open-menu` again without yet knowing our menu was closed by the user causes it to reopen. Solution: add a `close-menu` message to explicitly close a given menu, or do nothing if it doesn't exist.

These race conditions can be exacerbated by scripts that have to spend a lot of time in one event loop e.g. reading a large file, but affect any scripts that use menu updates or have to close their own menu.
