### ISSUE TITLE
Using uosc with other UIs

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#592]
Here's a case for #467.

It's perfectly possible to use uosc alongside other UI scripts, by disabling conflicting elements.  
Below is my config for disabling everything:
```
timeline_size_max=0
timeline_size_max_fullscreen=0
controls=never
top_bar=never
window_border_size=0
pause_indicator=none
volume=none
```
The ability to mix & match uosc with other UIs is great, it allows for example to add a title bar and volume controls to [mfpbar](https://codeberg.org/NRK/mpv-toolbox/src/branch/master/mfpbar).

Disabling all uosc on-screen actions also lets users benefit from uosc's menu system as requested in #94.  
This is useful for user-defined menus and scripts that are enhanced by uosc:  
https://github.com/christoph-heinrich/mpv-quality-menu  
https://github.com/po5/memo  
or scripts that even require it:  
https://github.com/natural-harmonia-gropius/recent-menu

I think the buffering indicator is the only uosc element that isn't explicitly brought up by the user, that can't be disabled.

**Comment by hooke007** [comment]
I think it's the extension of my FR https://github.com/tomasklaen/uosc/issues/503
It looks like a huge project to avoid any possible overlay rendering and bindings conflict.

**Comment by tomasklaen** [comment]
I think this use case might warrant a new option to easily declare which elements user wants uosc to render. Instead of having to read through all options to arrive at the config you posted, we might have:

```
# What elements should uosc render
elements=timeline,volume,controls,top_bar,pause_indicator,buffering_indicator,window_border
```

And then each individual element's options would just control how these elements look/behave. Since we are currently in the middle of a major bump, this is the best time to make these kind of changes.

BTW, any ideas for a better name for `top_bar`? Since the current one is not very descriptive, it just conveys its position. I can only think of `title_bar` or `window_title`, but these don't make it obvious that it contains window control button. Or maybe splitting it into `title_bar` and `window_controls` would be better.

**Comment by hooke007** [comment]
Considering most users would not use two UIs, probably we should use blacklist rather than whitelist?
`# What elements uosc would not render`

**Comment by po5** [comment]
A blacklist makes more sense as you don't want to hide newly added elements from users who set this option to its default value from an older version.

**Comment by christoph-heinrich** [comment]
I'm in favor of splitting the `top_bar` up into `title_bar` and `window_title`.
Should the playlist indicator also be a separate part? Visually it looks like it could be it's own part, but I don't really see the use-case for it.

Also +1 for blacklist over whitelist

**Comment by natural-harmonia-gropius** [comment]
I hope `*_persistency` can be integrated in this. Add `hidden` to hide the element. keep the default behavior for those elements not in this list.

`elements=top_bar:idle,volume:audio,timeline:hidden`

**Comment by po5** [comment]
`mp.set_property("osc", "no")` as the first line of an mpv script is enough to disable the original osc, without having the line in mpv.conf. (in recent versions, anyway)  
Would help streamline the install.

**Comment by FichteFoll** [comment]
> I hope `*_persistency` can be integrated in this. Add `hidden` to hide the element. keep the default behavior for those elements not in this list.

This would go against the idea of a blacklist and would also blow up this single configuration. Each element may also employ its own persistency values and documenting them all for this one setting could result in quite a wall of text. Having them separate with the rest of the respective element's configuration options make more sense imo.
