### ISSUE TITLE
Turn of mpv's anti-ringing when selecting new ravu scaler in menu

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#596]
For all scalers, I have the following in my mpv.conf:
```
scale-antiring=0.7
dscale-antiring=0.7
cscale-antiring=0.7
```
But the new ravu zoom scalers already have an anti-ringing filter and [doesn't require the above ](https://github.com/bjin/mpv-prescalers/issues/55#issuecomment-1657357570), what would I add to my ` input.conf ` to turn off anti-ringing when selecting ravu zoom in the uosc menu?

**Comment by hooke007** [comment]
I don't know why it is relevent to uosc?

**Comment by Zabooby** [comment]
> I don't know why it is relevent to uosc?
> 
> And those setting did nothing with any usr shaders.

In the comment I linked the dev of the ravu scalers said to turn off mpv's anti-ringing when using the new ravu zoom scalers as the scaler already does it. 

So I basically want to turn off mpv's anti-ringing when I select the new ravu zoom scaler in my uosc menu 

Similar to how I turn off `linear-downscaling` when selecting SSimDownscaler:
`# change-list glsl-shaders toggle ~~/shaders/ssimds.glsl ; no-osd set linear-downscaling no #! Video > Shaders > Generic Scaler > SSimDownscaler`

**Comment by hooke007** [comment]
No you don't understand his commennts.
Those setting will never affect user shaders.
