### ISSUE TITLE
any way to change playlist sorting (by name -> ascending) to how windows does?

### ISSUE THREAD

**Issue by BhaturaGuy** [tomasklaen/uosc#599]
mpv:
![image](https://github.com/tomasklaen/uosc/assets/93109835/9a954f6e-7813-49d0-8475-32d275eb8f86)

windows:
![image](https://github.com/tomasklaen/uosc/assets/93109835/52e49f53-ad66-485a-9f3b-59dab02d7c81)

**Comment by christoph-heinrich** [comment]
No, unless changing the [comperator](https://github.com/tomasklaen/uosc/blob/bc7b1a12bce15c069947e3bc2f01df757865c6dd/scripts/uosc/lib/utils.lua#L4-L47) is something you're willing to do.

**Comment by hooke007** [comment]
Impossible unless you know how to implement [it](https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strcmplogicalw) in lua

**Comment by BhaturaGuy** [comment]
ok. thanks

**Comment by Hrxn** [comment]
Easiest way is probably to change the filenames so that they get picked up in the correct order automatically..
