### ISSUE TITLE
 Please support in-app dark/light mode adjustment.

### ISSUE THREAD

**Issue by Ariacha** [tomasklaen/uosc#602]
This is a very powerful plugin, and I've been using it for almost a year. My only request now is to have a button within the app that supports switching between light and dark modes. The default method of switching within the Windows system is not very user-friendly and can also affect other applications. I would greatly appreciate it if you, dear developer, could make this addition. Thank you so much!

**Comment by tomasklaen** [comment]
You want to change OS light/dark mode from a button in uosc? Seems widely out of scope of this project. Though you might create a script that allows you to execute console commands it receives via `script-message-to` binding.

**Comment by Ariacha** [comment]
I apologize for not conveying it accurately. I mean to switch the light/dark mode exclusively within the MPV Player application, independent of the system settings.

**Comment by tomasklaen** [comment]
I don't think there are any APIs for that. All I noticed in quick docs search is `macos-title-bar-appearance`, so if you're on mac you might try creating a cycle button for it. But maybe I missed something, look around: https://mpv.io/manual/master/

Either way, this doesn't seem like something that would need a change to uosc. If mpv supports that, you should be able to add it yourself by configuring controls.

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/pull/11473#issuecomment-1489023149
If you want it, request it.
