### ISSUE TITLE
Latest release is 4.7.0 April 15

### ISSUE THREAD

**Issue by fdservices** [tomasklaen/uosc#603]
Is it time for a new release?

**Comment by tomasklaen** [comment]
Are you dissatisfied about the rate at which you're receiving free stuff?

Next release will be a major breaking bump that still needs stuff to be figured out and implemented.

**Comment by fdservices** [comment]
I did not mean to cause any offence, it is just that in the issues you have referred to some of the updates in main, but git clone download 4.7.0
