### ISSUE TITLE
Keybind next-file jumps to wrong file

### ISSUE THREAD

**Issue by vanbang9710** [tomasklaen/uosc#606]
- My config file [portable_config.zip](https://github.com/tomasklaen/uosc/files/12375131/portable_config.zip). I already unloaded all scripts excepts for uosc
- My keybind `Shift+n script-binding uosc/next-file; script-message-to uosc flash-elements top_bar,timeline #! Navigation > Next File`
- Open 01_welcome.mp4. This directory is 69MB so I don't know how to share it ![|50pct](https://i.imgur.com/Mx5rfzi.png)
- Spam Shift+n, look at the top bar to see what file is opened. The order seems to not even follow a cycle. ![|50pct](https://i.imgur.com/NeTZkRK.gif)

**Comment by christoph-heinrich** [comment]
When you browse files with [open-file](https://github.com/tomasklaen/uosc#open-file), is the sorting correct there?

**Comment by vanbang9710** [comment]
Oh, I forgot to mention that ![|50pct](https://i.imgur.com/OVjx7hj.png)

**Comment by christoph-heinrich** [comment]
I've now looked into this a bit and it works perfectly fine for me, the files get sorted correctly and everything.
Are you sure you don't have shuffle on?

**Comment by tomasklaen** [comment]
To remove instead of fix symbol sorting if none cares for it: sure

And by autoload sorting, you mean this?

```lua
function splitbynum(s)
    local result = {}
    for x, y in (s or ""):gmatch("(%d*)(%D*)") do
        if x ~= "" then table.insert(result, tonumber(x)) end
        if y ~= "" then table.insert(result, y) end
    end
    return result
end

function clean_key(k)
    k = (' '..k..' '):gsub("%s+", " "):sub(2, -2):lower()
    return splitbynum(k)
end

-- compare two strings
function alnumcomp(x, y)
    local xt, yt = clean_key(x), clean_key(y)
    for i = 1, math.min(#xt, #yt) do
        local xe, ye = xt[i], yt[i]
        if type(xe) == "string" then ye = tostring(ye)
        elseif type(ye) == "string" then xe = tostring(xe) end
        if xe ~= ye then return xe < ye end
    end
    return #xt < #yt
end
```

How is it better than what we have? It's doing some magicky things, so I can't tell. And wouldn't it be slower? It seems to create 2 tables for each comparison, while we create one table per item once.

**Comment by christoph-heinrich** [comment]
> And by autoload sorting, you mean this?

What I mean is [this](https://github.com/mpv-player/mpv/blob/ef4c6dfcf5d2b9a5d96a4cd2c6deaf49bbbe38c4/TOOLS/lua/autoload.lua#L125-L143). It's already the same algorithm, with the same optimizations, the only difference is that uosc also has the symbol order.

**Comment by vanbang9710** [comment]
May I ask if the merge fixes the problem? If so, I will try it.

**Comment by christoph-heinrich** [comment]
> May I ask if the merge fixes the problem? If so, I will try it.

No, and I honestly doubt there actually is any problem. You probably have [shuffle](https://github.com/tomasklaen/uosc/blob/6606f3e11fd652ce5a2ccfa67cbbd12b48167254/script-opts/uosc.conf#L148-L151) turned on.

**Comment by vanbang9710** [comment]
Indeed but I think shuffle should only apply to the keybind "next" instead of next-file
