### ISSUE TITLE
url drag and drop doesn't work

### ISSUE THREAD

**Issue by tazihad** [tomasklaen/uosc#613]
after applying `uosc` mpv drag and drop of url not working. any solution?

**Comment by tomasklaen** [comment]
Can't replicate. URL drag & drop works the same with or without uosc. Even when I try to drop it above uosc elements, still works fine. In fact it seems mpv doesn't even send any cursor events to uosc while you drag something above the window, making uosc dormant so it never tries taking over any cursor event handling, therefore it doesn't even matter where you drop the url.

My wild guess: maybe by disabling border (one of uosc install steps) your desktop environment does something to the window that makes it not droppable anymore?

In any case, this doesn't seem like a uosc issue.

**Comment by tomasklaen** [comment]
Feel free to post with more info if there's any, but since this seems abandoned and none else has this problem, I'll close this for now.
