### ISSUE TITLE
Setting video speed to x2.0 breaks UOSC and freezes the MPV window

### ISSUE THREAD

**Issue by RalfReddings** [tomasklaen/uosc#614]
UOSC freezes and stops responding to mouse hover and even breaks wheel scrolling functionality for MPV.
This only seems to happen when I set the speed to `x2.0` via a hotkey, before that UOSC is working as expected, if I set the speed back to `x1.0` everything goes back to working.

I Also found, placing  the following in the `Mpv.conf`, causes MPV to start with the same issue:
    
    speed=2.0

Setting the speed back to `x1.0` via a hotkey fixes the issues.    

I have tested this on both, USC `4.5.0` and `4.7.0` with MPV `0.35.0-33-gcf349d68e3` on Windows 11.
Tests were performed with with no other scripts present in MPV.

Any help would be greatly appreciated!

**Comment by tomasklaen** [comment]
Can't replicate on uosc 4.7, or the main branch, on either mpv 34 or latest 36.

And overall this doesn't sound like an issue with uosc. More like CPU not keeping up while trying to play high resolution video? Not sure.

**Comment by christoph-heinrich** [comment]
I have had `speed=2` in my mpv.conf since before uosc 4.0 and I never had a problem with it.

**Comment by RalfReddings** [comment]
> And overall this doesn't sound like an issue with uosc. More like CPU not keeping up while trying to play high resolution video? Not sure.

Hmm...If you have taken a look and are saying its not so, then it must be. Its just I was plagued by this issue until I had to let it be known.

Also I have a capable PC meant for high end graphics simulation. Why does MPV just not take processing power as it needs, or perhaps its capped to a limit. I will take your advice on board and investigate elswhere. Cheers.

**Comment by christoph-heinrich** [comment]
The default osc works fine with speed>=2 ?
