### ISSUE TITLE
Add a real time clock in the top bar

### ISSUE THREAD

**Issue by Alcatrazer** [tomasklaen/uosc#617]
Often I find myself watching series in fullscreen. Many times I spend more time then I originally desired.

I would like a clock feature which shows system date/time. I think it would be nice to have it in the Top Bar.

**Comment by tomasklaen** [comment]
👀 Just tap the fullscreen shortcut to glance time from your desktop. Displaying time here is silly, and unless this gets an insane support for some reason I'm against implementing stuff like this.

**Comment by Alcatrazer** [comment]
Its annoying having to leave full-screen to view time. Also I find MPV really hard to resize. An always on top clock thingy is also not as pretty as the everything out of the way interface UOSC provides.  I noticed if I am studying from a video leaving full screen also causes me to get more distracted.

**Comment by mrfragger** [comment]
**21:23 [ends at 22:49]**
basically shows you current local time and when video / audio will end
it's really small white text in bottom right corner.

https://github.com/zenwarr/mpv-config/blob/master/scripts/clock.lua
if on usoc
F12         script-message-to clock toggle          #! Utils > Clock on/off
and you can set it to start always if you wish
enabled_by_default = true
