### ISSUE TITLE
Playlist count text not aligned properly

### ISSUE THREAD

**Issue by xfzv** [tomasklaen/uosc#623]
I believe it started to occur lately. This is with the main branch, without any config file:

![count_main](https://github.com/tomasklaen/uosc/assets/78810647/8feabe94-c2a7-4198-a8e2-6d099ce847ca)

With 4.7.0 (no config file either):
![count_4 7 0](https://github.com/tomasklaen/uosc/assets/78810647/c9a3c5b2-8c2a-4d67-bef6-964f31aa33aa)

**Comment by christoph-heinrich** [comment]
That broke with 350f54f3217cbb2225bf7e259c20c6b766363abd

**Comment by tomasklaen** [comment]
Yeah, I committed in a hurry without testing the title with playlist present 😐.
