### ISSUE TITLE
Add option to hide background for tooltips 

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#636]
If some users have the background off for the title, tooltips look kinda out of place with backgrounds. As people commented in #237 we really love unreadable text. 🙃

**Comment by tomasklaen** [comment]
Forgot `top_bar_title_opacity` exists. I want to remove it now for 5.0. Why should we have, and keep adding more options that make text unreadable? Just look at this:

![image](https://github.com/tomasklaen/uosc/assets/47283320/e6e4af20-2932-4763-b6a8-dd83655ab806)

This happens and annoys me on Youtube almost daily, and I don't understand arguments that this should not only be developer oversight/disregard, but to have it as an option that does it on purpose?

This feature request triggers me. 💢

**Comment by Zabooby** [comment]
Totally get where you're coming from, I guess people want a ui that is as minimal as possible even if readability suffers as a result. 

Maybe keep this feature request open if others are interested, like with #237. 

But if you don't want to add this feature I don't mind (please keep `top_bar_title_opacity` though, @FichteFoll brought up good points for its existence).
