### ISSUE TITLE
searchable menus: sometimes, no match when performing a search

### ISSUE THREAD

**Issue by xfzv** [tomasklaen/uosc#637]
I was playing around with the new [searchable menus](https://github.com/tomasklaen/uosc/commit/18adf90af61736305677f731e178830a71c36837) feature and have noticed that _sometimes_, the search doesn't match any pattern in some menus.

Occurs with either `menu_type_to_search=yes` or `menu_type_to_search=no`. Two videos showcasing the issue:

1. Local video (no match in audio, subtitles, video and chapters menu, works in playlist menu)

2. YouTube video (no match in chapters and playlist menu, works in audio and video menus)

Edit: Removed the videos since GitHub doesn't load them for some reasons, here's a Send link: https://send.vis.ee/download/58f018edf5d509fb/#_TqijQWGCDPRR3QcLPk5PQ

**Comment by christoph-heinrich** [comment]
What the... I could have sworn that I made sure case insensitive search worked, but apparently the `query:lower()` must have gotten lost somehow. I'll quickly make PR.
