### ISSUE TITLE
Add option to remove the flashing of top bar

### ISSUE THREAD

**Issue by Neo-XP** [tomasklaen/uosc#639]
Is it possible to add an option not to flash the top bar when loading a new file?

It is forced by default in main.lua:

```
mp.register_event('file-loaded', function()
	local path = normalize_path(mp.get_property_native('path'))
	itable_delete_value(state.history, path)
	state.history[#state.history + 1] = path
	set_state('path', path)
	Elements:flash({'top_bar'})
end)
```

It works as I wish if I delete Elements:flash({'top_bar'}), but I have to do it for every new version.

Thank you

**Comment by dyphire** [comment]
I really don't understand why this is enabled by default. 
It conflicts with the option of `osd-playing-msg` in mpv.conf, and also has other potential OSD script compatibility issues,  for example: [editions-notification.lua](https://github.com/CogentRedTester/mpv-scripts/blob/master/editions-notification.lua)
