### ISSUE TITLE
Option to show/hide hidden files and directories

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#647]
### Discussed in https://github.com/tomasklaen/uosc/discussions/604

<div type='discussions-op-text'>

<sup>Originally posted by **AndyM48** August  6, 2023</sup>
Is there an option to exclude hidden files?</div>

---

Hidden files/directories should be hidden in all file listings by default.

How do we do this though?

On windows, I don't see any difference between normal and hidden files when inspecting file info table. They all have same modes, and no other flags.

On linux/mac, I guess hidden files are just files starting with a dot?

**Comment by christoph-heinrich** [comment]
> On linux/mac, I guess hidden files are just files starting with a dot?

Yes

The mpv code for loading directories only checks if the first char is `.`, and it does so without a platform check :upside_down_face: 

I couldn't find any issues about hidden files on windows, so I guess windows users don't care?

You could open an issue about that and maybe someone will introduce a mechanism for checking if a file is hidden that can be used for `utils.file_info()` as well as directory loading.

**Comment by tomasklaen** [comment]
All right, I'm not gonna stress it. Encountering hidden files on windows is not that common, so I'll just implement a mac/linux only solution for now, until there's a viable alternative.
