### ISSUE TITLE
Files in playlist changing from {filename} to {title} when clicking on them.

### ISSUE THREAD

**Issue by AKL55** [tomasklaen/uosc#670]
When opening the playlist
![1 when opened](https://github.com/tomasklaen/uosc/assets/89634553/405eda25-00a4-416d-9f30-25db9879ef0c)

When i click in any file in the playlist the name changes from {filename} to {title}
![2 when i click on the file](https://github.com/tomasklaen/uosc/assets/89634553/2602daa8-5503-44e9-80d7-9e6f761dc4db)

This only seems to happen in playlists
The playlist is in the .m3u file format with only the filepaths inside:

1.02. Away (Overture).ogg
1.19. Away.ogg
1.20. Winter's Bound.ogg
3.16. Find the Flame.ogg
3.27. Reflections – Drake's Head.ogg
5.04. Do or Die.ogg
5.05. Titan Lost.ogg
5.06. Heart of Stone.ogg
5.20. Beyond the Heavens.ogg
5.21. Ascension.ogg
6.09. No Risk, No Reward.ogg
7.14. Hymn of the Penitent.ogg
7.15. All As One.ogg

**Comment by christoph-heinrich** [comment]
The playlist menu shows the title of the playlist item if a title is available. Opening a file makes the title available to mpv, which stores that title in the playlist and thus the title is shown in the menu.
It's a feature, not a bug :)

**Comment by AKL55** [comment]
Closing this issue then, but i wish a could turn this off.

**Comment by AKL55** [comment]
> > When opening the playlist ![1 when opened](https://private-user-images.githubusercontent.com/89634553/272473370-405eda25-00a4-416d-9f30-25db9879ef0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzMwOTgsIm5iZiI6MTcyMTgzMjc5OCwicGF0aCI6Ii84OTYzNDU1My8yNzI0NzMzNzAtNDA1ZWRhMjUtMDBhNC00MTZkLTlmMzAtMjVkYjk4NzllZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE0NTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NTg0MmQxZGNjYWRiYjdjZmU3ZTM2OGIwM2E3NjBjMDM1ZjYzM2Q2MDJlNWE5NGQwYmYwZjJlOGQ2MTMyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7JtEb6nAZPB82YOBP4suB9Foi1nTW6AVYQTtq6U4BMw)
> > When i click in any file in the playlist the name changes from {filename} to {title} ![2 when i click on the file](https://private-user-images.githubusercontent.com/89634553/272473498-2602daa8-5503-44e9-80d7-9e6f761dc4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzMwOTgsIm5iZiI6MTcyMTgzMjc5OCwicGF0aCI6Ii84OTYzNDU1My8yNzI0NzM0OTgtMjYwMmRhYTgtNTUwMy00NGU5LTgwZDctOWU2Zjc2MWRjNGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE0NTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ODAxOTViZmYyYWE0ZjE5MWNiMjZkMTExNmQxNjhjZmJlZTczMjNiZGMwMTViNzc5NTM1ZTViYjEzNTBlNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UG0F9GFLhn4Y809FLCEu5oC-D38BEvERAR95cJZJ2uU)
> > This only seems to happen in playlists The playlist is in the .m3u file format with only the filepaths inside:
> > 1.02. Away (Overture).ogg 1.19. Away.ogg 1.20. Winter's Bound.ogg 3.16. Find the Flame.ogg 3.27. Reflections – Drake's Head.ogg 5.04. Do or Die.ogg 5.05. Titan Lost.ogg 5.06. Heart of Stone.ogg 5.20. Beyond the Heavens.ogg 5.21. Ascension.ogg 6.09. No Risk, No Reward.ogg 7.14. Hymn of the Penitent.ogg 7.15. All As One.ogg
> 
> What script do you use for playlist?

I don't use any script for playlists.
