### ISSUE TITLE
Internal menu search with updating items

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#671]
Updating the menu while also using the internal search causes the items to not be filtered anymore.

At least that's the most obvious problem here, but the underlying problem goes much deeper.
Updating the menu results in new items being created and `item.search` being assigned over from the old items, which contains a list of the original item objects in `item.search.source.items`.

That already caused problems during the development of the search feature and the workaround was a new update function for the search itself, but as it turns out that wasn't enough.

We have to make the normal update function able to deal with this somehow.
My first guess is replacing the items in `item.search.source.items` with the new ones and performing a search, but I didn't see an easy way of doing that when I had a quick look. Maybe I'll give it another try later.

I noticed it while working on [my new script](https://github.com/christoph-heinrich/mpv-subtitle-lines), but it turned out to also be a problem with builtin menus (e.g. chapter menu).

### Reproduction steps

1. open a file with chapters
2. open the chapter menu during playback
3. search for something
4. wait until playback progresses to the next chapter

**Comment by tomasklaen** [comment]
Yes, I've noticed that too and was planning on fixing it a couple days ago but forgot :) I'll look into it later.
