### ISSUE TITLE
Menu returns empty after reopening

### ISSUE THREAD

**Issue by PrinceOC912** [tomasklaen/uosc#674]
Since 473278c4bdd4297eb6f6cb1f2328bbd9f64c6c31, when I open the menu, close it, and reopen it, an empty menu is shown instead. I also noticed that this only happens when there is an input.conf file; simply creating the file, even if it is empty, causes this issue. This issue is not present with e7371f61e0814d9231b02621e83347aa4b83de55.

**Comment by tomasklaen** [comment]
Thx for the report!
