### ISSUE TITLE
Textures for menu titles aren't visible 

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#683]
Downloaded the latest updates and the textures for certain menus like the subtitle menu are no longer visible.

Before:
![image](https://github.com/tomasklaen/uosc/assets/78969986/d077be6b-c0d1-4d34-8541-a81c5b4b929e)

After: 
![image](https://github.com/tomasklaen/uosc/assets/78969986/ff655ae1-8ab2-4dfb-b748-0380e1ff4945)

**Comment by tomasklaen** [comment]
Yes, we removed them in #650.
