### ISSUE TITLE
Use autohide without proximity

### ISSUE THREAD

**Issue by 33KK** [tomasklaen/uosc#685]
I'd really prefer to see the entire UI at once rather than having to move mouse around.

Maybe this could be a persistency=autohide option. Currently only workaround I see is using proximity=99999, but its hacky and looks pretty bad, because there are no animations

**Comment by tomasklaen** [comment]
There's already `autohide` option in `uosc.conf` for that. So just put this combination in your conf:

```
proximity_in=99999
autohide=yes
```

There was a bug where elements would not nicely fade out when cursor was recognized as "left the screen", which was fixed by the commit above.

**Comment by tomasklaen** [comment]
Than I have no idea what you're asking for. Do you want UI to always be visible at all times? Than don't enable `autohide`. Do you want UI to always be visible when you want it? Use `toggle-ui` command.

**Comment by christoph-heinrich** [comment]
I think they want the UI to not appear immediately upon mouse movement, but instead have it fade in.

Trying a `animation_factor=0.1` and moving the mouse in and out of the window revealed some weird behavior.
Title and volumeslider need to fade out completely before they appear again, while window controls and timeline can abort their fading if the mouse enters the window again.
Controls don't fade at all.

**Comment by christoph-heinrich** [comment]
I've turned it into it's own issue while you were typing this :) #689
