### ISSUE TITLE
Inconsistent fading behavior

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#688]
Trying `animation_factor=0.1` and moving the mouse in and out of the window revealed some weird behavior.
Title and volumeslider need to fade out completely before they appear again, while window controls and timeline can abort their fading if the mouse enters the window again.
Controls don't fade at all.

I haven't yet looked at all as to why that is.

**Comment by tomasklaen** [comment]
I'll look into it later. But controls and potentially other elements don't fade because the fadeout code is quite old, and the table of elements it fades out is only:

```lua
{'timeline', 'volume', 'top_bar'}
```

I haven't noticed when fixing it :)
