### ISSUE TITLE
Add ways to add context menu titles and separators

### ISSUE THREAD

**Issue by microraptor** [tomasklaen/uosc#69]
It would be nice to have a way to add a context menu separator- and titles/header-cells.

My suggestion for separators: A line in input.conf is a separator, if the item name is '-':
`# ignore #! -`
`# ignore #! Example > -`

Similarly, if the command is 'ignore', but the name is not '-', it could be formatted exactly like the titles 'Subtitles' or 'Audio' in the track selection menus. This could then be used to make titles in the context menu.
`# ignore #! Example > Example-Title`

**Comment by tomasklaen** [comment]
I'm not against this, but can't give any ETA.
