### ISSUE TITLE
Feature request: Reload currently loaded external subtitles

### ISSUE THREAD

**Issue by magnilens** [tomasklaen/uosc#690]
I'd like to be able to _reload_ the currently loaded external subtitles, as opposed to load a new instance of it, which is what would happen if I used the Load External Subtitle command a second time on the same subtitle file.

When working with subtitles, it is important to run it though an actual player to see how the subs will appear in the player. This does mean that if we do spot something we need to fix, we'd like to be able to make the changes and refresh the subs on the video, as quickly and as often as necessary. Then we move on until we find the next issue that needs fixing. In MPV, this will quickly result in many, many instances of the same external subs being loaded. Or constantly closing and reopening the video, followed by reloading the external sub.

MPC-HC has the Reload command that will reload the external subs with a single action and no additional instances. I'd like to be able to do that in MPV too. I'm making this feature request here, since uosc is what I'm using to load external subs right now.

**Comment by dyphire** [comment]
mpv already has `sub-reload` command to do this, also has `sub-remove` command. We can assign some shortcut keys to the uosc track menu to achieve these functions.

**Comment by magnilens** [comment]
That'd be great. In the meantime, how can I access those commands by other means?

**Comment by christoph-heinrich** [comment]
You can put [`sub-reload`](https://mpv.io/manual/master/#command-interface-sub-reload) on a keybinding in input.conf,
and you can also put a button in uosc controls (the buttons above the timeline).

If it's your only subtitle track, it'll have an id of 1, so the command `sub-reload 1` should work.

**Comment by magnilens** [comment]
I'll have to experiment with making keybindings. 

The videos I work with may or may not already have internal subs when I'm working on the external subs. So just "sub-reload 1" won't be enough.

**Comment by christoph-heinrich** [comment]
In that case you might have to make a script that looks up the id of the external sub and then executes the command with that.

**Comment by christoph-heinrich** [comment]
Actually the track to reload will be the current one, so you could do `sub-reload ${current-tracks/sub/id}`

**Comment by tomasklaen** [comment]
According to docs, `sub-reload` will reload the currently selected subtitles when called without parameters. Or am I missing something?

**Comment by christoph-heinrich** [comment]
You're right, I totally missed that id is optional :laughing:

**Comment by dyphire** [comment]
Implementing this feature using scripts is not complicated, refer: [reloadTrack](https://github.com/dyphire/mpv-scripts/blob/475acfe31b10ef870b24e4c084bfb174bde83564/track-list.lua#L293-L327)
Since uosc has already implemented some playlist operations in the playlist menu, doing the same for the track menu is a good improvement.

**Comment by tomasklaen** [comment]
I don't think I'll be adding this to uosc. The number of people that would use it is incredibly small, and even there, putting `sub-reload` on a keybind is way better and more efficient than having to open a menu to press some button.

**Comment by magnilens** [comment]
I put sub-reload on keybind, and it does work better like you said. Thanks for the help!
