### ISSUE TITLE
Removing `volume=left` option

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#696]
Is anyone using volume on the left? I want to remove it :)

**Comment by christoph-heinrich** [comment]
Chances are there is at least one person that actually uses it.

I'm not.

**Comment by tomasklaen** [comment]
> I'm using it.

Any specific reason, or just rare preference?

**Comment by Niotferdi** [comment]
I'll be glad if you add `volume=up`. So that the volume scale is directly below my osd (in my config I placed it in the top center)

**Comment by Sneakpeakcss** [comment]
> > I'm using it.
> 
> Any specific reason, or just a rare preference?

I'm personally using it because it's quicker to navigate to the volume bar when mpv is on a secondary monitor that's physically positioned to the right. Having to move far right through the whole screen to access volume control would be bothersome in comparison.

**Comment by tomasklaen** [comment]
All right, I'll leave it. But no `up` though.
