### ISSUE TITLE
tween division by zero

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#702]
I was writing a big error report for "TopBar playlist position badge crash", but e9453fb579c578c978545cdb759a389316367708 fixed this case.  
Leaving the original report below as it leads to finding a bigger issue.

On commit cff7fa873a4a278cce4a3707cb6d27a55e635b41 (but issue unrelated to that PR)  
Reproduction steps: open a file with the cursor already positioned somewhere the mpv window will end up, and have more than 1 item in playlist. Do not move the mouse, let the initial topbar flash completely fade out. Crash.
I added a `print("x", fg, visibility, state.radius)` before the ass:rect call.

```
VO: [gpu] 960x540 nv12
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.000
[uosc] x FEFBFF 1 2 
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.023
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.021
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.019
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.017
[uosc] x FEFBFF 1 2 
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.015
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.014
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.012
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.011
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.010
[uosc] x FEFBFF 1 2 
AV: 00:00:00 / 00:04:37 (0%) A-V:  0.009
[uosc] x FEFBFF 1 2 
(Buffering) AV: 00:00:00 / 00:04:37 (0%) A-V:  0.009
[uosc] x FEFBFF 1 2 
(Buffering) AV: 00:00:00 / 00:04:37 (0%) A-V:  0.009
[uosc] x FEFBFF -nan 2 
[uosc] 
[uosc] stack traceback:
[uosc]  [C]: in function 'format'
[uosc]  /home/eva/.config/mpv/scripts/uosc/lib/ass.lua:120: in function 'rect'
[uosc]  /home/eva/.config/mpv/scripts/uosc/elements/TopBar.lua:218: in function </home/eva/.config/mpv/scripts/uosc/elements/TopBar.lua:192>
[uosc]  (...tail calls...)
[uosc]  /home/eva/.config/mpv/scripts/uosc/lib/utils.lua:720: in function 'cb'
[uosc]  mp.defaults:361: in function 'process_timers'
[uosc]  mp.defaults:530: in function 'dispatch_events'
[uosc]  mp.defaults:503: in function <mp.defaults:502>
[uosc]  [C]: in ?
[uosc]  [C]: in ?
[uosc] Lua error: /home/eva/.config/mpv/scripts/uosc/lib/ass.lua:120: bad argument #2 to 'format' (not a non-negative number in proper range)
```

`visibility` sometimes has a value of `-nan`, which indicates a `0/0` somewhere in the values used by `get_visibility`.  
A print reveals `forced_visibility` is the nan value.  
We can prevent the crash by using this weird quirk, though I don't know if all Lua implementations behave like this, where `math.max` will only return nan if it is the first argument:
```lua
> math.max(0/0, 123)
-nan
> math.max(123, 0/0)
123
```
So swapping around the arguments like this no longer crashes.
```lua
	-- Forced visibility
	if self.forced_visibility then return math.max(self.min_visibility, self.forced_visibility) end
```
There's clearly a deeper issue though, and while it fixes the crash it doesn't restore the intended fadeout of the top bar, instead its opacity abruptly jumps to 0.
`forced_visibility` has no complex assignments so only `tween_property` is suspect.

https://github.com/tomasklaen/uosc/blob/cff7fa873a4a278cce4a3707cb6d27a55e635b41/scripts/uosc/lib/utils.lua#L37-L40

When `distance` is zero, so is `cutoff`, and dividing them gives nan.  
I guess we never got into cases where we start tweening when already on target, but it should be handled.

**Comment by tomasklaen** [comment]
Thx for catching this.
