### ISSUE TITLE
Feature Request: Add Widget for shuffle and unshuffle similiar to vlc

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#71]
Sorry if it was already implemented but i really can't find a way to do it.

**Comment by tomasklaen** [comment]
No, there's no shuffle button to enable currently, but you can add an item to the menu that toggles it:

```
alt+s    cycle shuffle    #! Toggle shuffle
```

This will add `Toggle shuffle` item to the main menu, and also assign it an `Alt+s` shortcut. You can omit the shortcut by replacing it with `#`.

**Comment by NaiveInvestigator** [comment]
> No, there's no shuffle button to enable currently, but you can add an item to the menu that toggles it:
> 
> ```
> alt+s    cycle shuffle    #! Toggle shuffle
> ```
> 
> This will add `Toggle shuffle` item to the main menu, and also assign it an `Alt+s` shortcut. You can omit the shortcut by replacing it with `#`.

I am actually using that rn but i almost always misclick another item instead since i have similarly named items, and it gets annoying fast.

**Comment by NaiveInvestigator** [comment]
Thank you so much to consider it! Hopefully someday it will be implemented. Please have a great day!

**Comment by tomasklaen** [comment]
Landed in main as a part of `controls` bar.
