### ISSUE TITLE
Customizing UI icon theme

### ISSUE THREAD

**Issue by bananakid** [tomasklaen/uosc#712]
Thank you so much for UOSC, @tomasklaen!

I'd like to use `Segoe Fluent Icons` font or `Segoe UI MDL2 Assets` for UI icons (to better match Windows UI). Both fonts are missing `name` value for all the glyphs. However they have `index` and `unicode` values for glyphs. I figured out I change font by placing TTF file to `\portable_config\fonts` via line 31 in `\scripts\uosc_shared\lib/ass.lua` using it's `postscript` name (i.e. `SegoeFluentIcons`, this filed can be seen easily via [FontDrop!](https://fontdrop.info/) website).

Would you kindly explain how to switch referencing glyphs from name to index?

P.S. I can add `name` field to the required glyphs by editing font file but that's not an elegant solution.

**Comment by bananakid** [comment]
I assume you kindly explained how to change icons when the "codepoint" of icon is present, i.e. "play_outline" for circle play button. But I already know how to do it and done it successfully:
![uosc](https://github.com/tomasklaen/uosc/assets/17095595/64977f9b-3b91-4aa0-8e70-9a0d6f8ff7c4)
I'm curious if it's possible to reference glyph not by it's "codepoint" (which is "name" value of glyph) but by glyph's index because Segoe fonts glyphs are missing "name"/"codepoint".

**Comment by bananakid** [comment]
Another quick question is regarding badges for audio, subtitles, etc.: would you kindly provide an example? I have tried like everything to disable them as the manual teaches (i.e. by pasting `#audio>99` to `controls=...<has_many_audio>audio#audio>99,...` of `uosc.conf` but of course it doesn't work at all).

**Comment by tomasklaen** [comment]
`audio` is a shorthand for:

```
command:graphic_eq:script-binding uosc/audio#audio>1?Audio
```

Shorthands don't accept any parameters. You need to use the raw definition and remove the badge from there:

```
command:graphic_eq:script-binding uosc/audio?Audio
```

**Comment by tomasklaen** [comment]
By codepoint I mean the unicode codepoint of the character with the icon. Something like `\u0001` or something like that. I can't recall the format, or a valid way to use it in this environment atm.

**Comment by christoph-heinrich** [comment]
I've never tried it, but I think it should be possible to copy the symbol from somewhere in there.

**Comment by bananakid** [comment]
> Shorthands don't accept any parameters.

Thank you for prompt explanation, @tomasklaen, I succeeded with this.

> By codepoint I mean the unicode codepoint of the character with the icon. Something like `\u0001` or something like that. I can't recall the format, or a valid way to use it in this environment atm.
> I've never tried it, but I think it should be possible to copy the symbol from somewhere in there.

I'll try again and post the solution in case of success. Thanks for taking time to respond too, @christoph-heinrich.

In the mean time and in between time everyone's welcome to share the solution.

**Comment by bananakid** [comment]
> I've never tried it, but I think it should be possible to copy the symbol from somewhere in there.

Unfortunately this didn't work. I tried to find any documentation on the subject online and wasn't lucky. The closest topic on the subject that seems to answer the question with the right syntax was posted in [this answer](https://tex.stackexchange.com/questions/667669/), however I cannot figure out how to do it because, well, I have very little idea on what I'm doing with Lua. Please take a moment in a spare time to check the link with the answer @tomasklaen, @christoph-heinrich. Maybe you can tell how to reference glyph in `controls=` as `\char"E115` (and some variations) didn't work. All I know is it's a possible thing to do!

**Comment by christoph-heinrich** [comment]
Don't tell me this doesn't work dude...
![image](https://github.com/tomasklaen/uosc/assets/8932183/a1793c0c-9405-4b4e-927f-d04fb3b40c1e)

![image](https://github.com/tomasklaen/uosc/assets/8932183/cd3175b3-9af9-456b-b888-021c9bb9a356)

![image](https://github.com/tomasklaen/uosc/assets/8932183/96732556-857b-498e-b8c9-5fadce1e730e)

![image](https://github.com/tomasklaen/uosc/assets/8932183/8a7cb754-f1ca-4dda-8c47-66188e45ed46)

**Comment by bananakid** [comment]
> Don't tell me this doesn't work dude...

Unfortunately no, it doesn't work. I assume it works with regular Unicode glyphs like in your example (note that glyph in VSCode is different from what you get in mpv). Like, I can set `SegoeFluentIcons` font in `ass.lua` and then use set 😀 glyph directly to `uosc.conf` just as you did. This will work both in mpv and in, say, Notepad or VSCode. However as soon as I open Character Map and copy, say, "play" glyph from "Segoe Fluent Icons" font, the glyph will not be accepted in Notepad, VSCode or mpv — all of them will display … So I assume I have to reference glyphs by codepoints somehow!

**Comment by christoph-heinrich** [comment]
I had to reexport the font as otf for some reason, no idea why it wouldn't work with ttf but libass would always fall back to some other font.
![image](https://github.com/tomasklaen/uosc/assets/8932183/7f4684d4-13dc-4f26-82dc-b02a504b0c85)

![image](https://github.com/tomasklaen/uosc/assets/8932183/2f63db97-efb8-4237-aeb0-f5e598bcfaa1)

![image](https://github.com/tomasklaen/uosc/assets/8932183/27769f17-62e5-47c8-8229-05c0f3521b05)

**Comment by bananakid** [comment]
@christoph-heinrich thank you for this valuable observation! OTF file works fine indeed. I have successfully converted TTF to OTF with the best quality (--tolerance 0.0) using [TTF2OTF](https://ftcli.github.io/FoundryTools-CLI/commands/ftcli_converter.html#ftcli-converter-ttf2otf) from [FoundryTools-CLI](https://github.com/ftCLI/FoundryTools-CLI). This is OK approach for the time being.

However it would still be nice to have an idea on how to reference glyph codepoint of the TTF file as @tomasklaen stated.

**Comment by bananakid** [comment]
@christoph-heinrich thank you for this valuable observation! OTF file works fine indeed. I have successfully converted TTF to OTF with the best quality (--tolerance 0.0) using [TTF2OTF](https://ftcli.github.io/FoundryTools-CLI/commands/ftcli_converter.html#ftcli-converter-ttf2otf) from [FoundryTools-CLI](https://github.com/ftCLI/FoundryTools-CLI). This is OK approach for the time being.

I have also came across the [Fluent UI System Icons](https://github.com/microsoft/fluentui-system-icons#fluent-ui-system-icons) repository by Microsoft that contains [FluentSystemIcons-Regular.ttf](https://github.com/microsoft/fluentui-system-icons/blob/main/fonts/FluentSystemIcons-Regular.ttf) with `'name'` field specified for glyphs. So it appears this TTF can be used for latest UI guidelines by Microsoft as it replaces Segoe MDL2 Assets font (it's Windows 10 UI icons font and it won't be updated anymore). Unfortunately referencing by `'name'` value doesn't work for this TTF for some reason, but copy-pasting glyph from Character Map to `.lua` file works, just like with converted `SegoeIcons.ttf`. And I can't convert `FluentSystemIcons-Regular.ttf `to OTF because TTF2OTF fails (bug reported)…

There's definitely something going on here… It would still be nice to have an idea on how to reference glyph codepoint of the TTF file as @tomasklaen stated.

**Comment by bananakid** [comment]
So far I'm happy with the result, Fluent System Icons make mpv fit Windows 10 & 11 environment quite well:
![Preview](https://github.com/tomasklaen/uosc/assets/17095595/372ef050-4c34-47ba-a420-34c17e117538)
I just need to find all the icons in `.lua` files now as @tomasklaen suggested.
