### ISSUE TITLE
Request: Option to Change Position of "script-binding uosc/flash-timeline"

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#713]
Is there a way to set flash-timeline at the top of the screen, the center of the screen, or the bottom of the screen. 

An example may look like... 
[Keybind] script-binding uosc/flash-timeline top
[Keybind] script-binding uosc/flash-timeline center
[Keybind] script-binding uosc/flash-timeline bottom (what we currently have)

**Comment by po5** [comment]
There's no way to change the timeline position to begin with, so no.  
Sounds like you're looking for a separate script for this functionality, if you want something similar to osc.lua's flash on seek. This is not related to uosc.
