### ISSUE TITLE
Why is text in search input on the right?

### ISSUE THREAD

**Issue by BhaturaGuy** [tomasklaen/uosc#715]
![image](https://github.com/tomasklaen/uosc/assets/93109835/4a9c533c-3a55-4880-a6f2-200913bcc746)

Change `type to search` position to left.
Search icon to right.
Since English isn't [Right To Left](https://en.wikipedia.org/wiki/Right-to-left_script) Script.
Something like this:
![image](https://github.com/tomasklaen/uosc/assets/93109835/4b35d8ff-dcee-4af1-ab7f-cb6c3310be47)

Just wondering if possible?

Also can someone confirm if `script-binding uosc/delete-file-prev` is working? 
For me it isn't, `delete-file-next` and `delete-file-quit` are.

**Comment by tomasklaen** [comment]
The text is on the right in search input because it is a lot easier to implement in the environment we're in. This UI has to be written in libass, which is a very limited API. It's essentially a very complex set of subtitles on a screen. This means some tradeoffs, like having text on the right in this case.

---

I can replicate the `delete-file-prev` issue. I'll look into it.

**Comment by tomasklaen** [comment]
Huh, `delete-file-prev` isn't even implemented 👀.

**Comment by BhaturaGuy** [comment]
It's buggy, if I have 10 files in the playlist and I am playing the last file currently and I use `delete-file-prev` it deletes the current file and mpv goes idle. Same thing if it's not the last file, just deletes 2 files before going idle.

**Comment by po5** [comment]
Speed reset is now right click, that's intended.

**Comment by tomasklaen** [comment]
> It's buggy, if I have 10 files in the playlist and I am playing the last file currently and I use delete-file-prev it deletes the current file and mpv goes idle. Same thing if it's not the last file, just deletes 2 files before going idle.

Can't replicate.

> Also can you confirm if clicking on speed slider is resetting the speed to 1x? For me it isn't

We switched speed reset to right click to match volume, which needs it at right click because left sets a value. It being on right click also enables touch devices to tap on speed to "activate" it so it can be dragged (weird, but no way around it unfortunately).

**Comment by BhaturaGuy** [comment]
> > It's buggy, if I have 10 files in the playlist and I am playing the last file currently and I use delete-file-prev it deletes the current file and mpv goes idle. Same thing if it's not the last file, just deletes 2 files before going idle.
> 
> Can't replicate.
> 

Maybe its behaving same as `delete-file-next`?

**Comment by tomasklaen** [comment]
Are you sure you don't have shuffle on or something?

**Comment by BhaturaGuy** [comment]
> Are you sure you don't have shuffle on or something?

Yes I am sure I am not.

I use these binds
```
alt+.         script-binding uosc/delete-file-next                                  #! Navigation > Delete file & Next
alt+,         script-binding uosc/delete-file-prev                                  #! Navigation > Delete file & Prev
```
But both of them deletes the current file and plays next.
Sometimes it doesn't delete just plays next.

[Video](https://files.catbox.moe/3632tz.mp4)
