### ISSUE TITLE
`delete-file-prev` not working as intended

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#720]
_Originally posted by @BhaturaGuy in https://github.com/tomasklaen/uosc/issues/715#issuecomment-1773636988_

---

I use these binds
```
alt+.         script-binding uosc/delete-file-next                                  #! Navigation > Delete file & Next
alt+,         script-binding uosc/delete-file-prev                                  #! Navigation > Delete file & Prev
```
But both of them deletes the current file and plays next.
Sometimes it doesn't delete just plays next.

[Video](https://files.catbox.moe/3632tz.mp4)

**Comment by tomasklaen** [comment]
@BhaturaGuy what OS are you on? I don't know how could OS affect this, but I have no other ideas. It works fine for me :/

**Comment by BhaturaGuy** [comment]
> @BhaturaGuy what OS are you on? I don't know how could OS affect this, but I have no other ideas. It works fine for me :/

Windows 11

**Comment by christoph-heinrich** [comment]
It doesn't work with playlists, I tried fixing it and ran into a bug in mpv :laughing: 
I'll open a PR and talk to the mpv devs.

**Comment by tomasklaen** [comment]
Can you confirm #726 fixed it for you?

**Comment by christoph-heinrich** [comment]
I've figured out the "bug". It was autoload.lua immediately adding things back because it's hook runs on file-loaded, which happens after playlist-remove when it's quick enough.

**Comment by BhaturaGuy** [comment]
> Can you confirm [#726 ](https://github.com/tomasklaen/uosc/pull/726) fixed it for you?

Yes, fixed
