### ISSUE TITLE
Timeline font size in version 5.0.0

### ISSUE THREAD

**Issue by LampPrinter** [tomasklaen/uosc#722]
![iShot_2023-10-21_17 19 43](https://github.com/tomasklaen/uosc/assets/7559328/d15ba0a9-9913-42d5-88e0-a746b4a7090e)

Please see the attached photo. The font size in previous version of UOSC was larger.
I only see "font_scale=1" which makes all text bigger including title etc. which I do not want.

**Comment by tomasklaen** [comment]
This should fix it. If you could test what's on main, refer back if it doesn't.

**Comment by LampPrinter** [comment]
Yes it fixed it.
Another issue, all the text now has a dark background. Whereas earlier it was not like this.
![195072935-44d591d9-00bb-4a55-8795-9cf81f65d397](https://github.com/tomasklaen/uosc/assets/7559328/664bdd28-ca44-4b9f-9a17-af4295964a0f)

Am I missing some setting in uosc.conf?

**Comment by tomasklaen** [comment]
Related: #636

You can disable it with the new `opacity` option.

**Comment by bananakid** [comment]
@tomasklaen would you kindly tell if there's a way to set semi-transparent background for Controls? I've tried `opacity=controls=0.5` and it didn't work while `opacity=timeline=0.5` worked fine for Timeline.

**Comment by tomasklaen** [comment]
Controls don't have a background. But it wouldn't be a problem to add it now that we have the `opacity` option. I'll add it to a to-do list.

**Comment by bananakid** [comment]
@tomasklaen, thank you for support!

**Comment by bananakid** [comment]
@tomasklaen, by the way it appears to me that Volume doesn't respect `volume_border=0` in 5.0.0, I can make the border thicker but it retains thin black line even if zero is specified in `uosc.conf`.

**Comment by christoph-heinrich** [comment]
> the opacity of the progress bar when `timeline_style=bar` doesn't respect `opacity=timeline=0.3` value specified in `uosc.conf`.

`opacity=position=0.3`

**Comment by bananakid** [comment]
@christoph-heinrich, thanks, I've edited the initial comment since I figured how some of the things work (`position` was among them). Would you kindly tell if it's possible to set the color and opacity of the indicator that appears when you hover mouse cursor on the Timeline? It looks like a thin vertical line in full height of timeline right where the cursor is pointing.

**Comment by christoph-heinrich** [comment]
> Another small issue is when milliseconds are enabled in Timeline the time indicator on the right keeps moving

That is because it's not a monospace font. It's mostly stationary because numbers seem to effectively be monospace, however when they contain `11` it takes up slightly less space then any other combination for some reason, which is why it moves a little bit.
At least that's the case for me, maybe it's different with other fonts/font renderers.

**Comment by christoph-heinrich** [comment]
> Would you kindly tell if it's possible to set the color and opacity of the indicator that appears when you hover mouse cursor on the Timeline? It looks like a thin vertical line in full height of timeline right where the cursor is pointing.

As color it uses the foreground or background color, depending on if it's on the position indicator or the timeline background, and the opacity is currently not configurable.

**Comment by bananakid** [comment]
> That is because it's not a monospace font.

Yeah, I guess I'll just stick with `destination_time=total` for now. However I remember it's possible to make any font fixed-width via CSS, maybe Lua has something similar to offer.

> and the opacity is currently not configurable.

Thank you for taking time to look into it, I believe it's a good candidate for extending `opacity`.

By the way I think English wording on the idle screen is a bit incorrect, perhaps it should say `Drop files or URLs here to play…`

**Comment by christoph-heinrich** [comment]
> However I remember it's possible to make any font fixed-width via CSS, maybe Lua has something similar to offer.

That's not directly possible. We could position and draw each symbol individually to make it semi monospace (I don't think `:` and `.` should take up as much space as digits), but I don't know if we want to do that.

**Comment by bananakid** [comment]
@christoph-heinrich, thank you for explanation. It appears to me I've found a minor imperfection with Timeline > Chapters: for some reason _some_ regular chapters' names that appear when hovering Timeline do not have left and right padding inside black background. I fixed it by adding a 1.5 multiplier to this line `width_overwrite = chapter.title_wrapped_width * self.font_size * 1.5,` in `-- Chapter title` in `Timeline.lua`.

**Comment by christoph-heinrich** [comment]
> It appears to me I've found a minor imperfection with Timeline > Chapters: for some reason _some_ regular chapters' names that appear when hovering Timeline do not have left and right padding inside black background.

That must be caused by incorrect estimation of the text width, you can try `text_width_estimation=no` to see if it makes a difference.

**Comment by christoph-heinrich** [comment]
I've tried that idea with drawing each symbol individually, but the problem is that the border then overlaps the previous symbol. This starts becoming a problem with border sizes > 1.5, and we use 2 for those timestamps.

I made it bigger so it's easier to see, but it's already noticeable at normal scale.
![image](https://github.com/tomasklaen/uosc/assets/8932183/c9cfeef9-05c8-4af5-8d1b-2bc3872f886e)

**Comment by bananakid** [comment]
> That must be caused by incorrect estimation of the text width, you can try `text_width_estimation=no` to see if it makes a difference.

Nope, tested to be not related to `text_width_estimation`.

> I've tried that idea with drawing each symbol individually, but the problem is that the border then overlaps the previous symbol. This starts becoming a problem with border sizes > 1.5, and we use 2 for those timestamps.

Perhaps set character tracking to be calculated based on border size value for values greater than 1.5? If Lua features tracking control.

**Comment by christoph-heinrich** [comment]
> > That must be caused by incorrect estimation of the text width, you can try `text_width_estimation=no` to see if it makes a difference.
> 
> Nope, tested to be not related to `text_width_estimation`.

Then I have no idea what might be causing that. Can you provide a sample where this happens?

> > I've tried that idea with drawing each symbol individually, but the problem is that the border then overlaps the previous symbol. This starts becoming a problem with border sizes > 1.5, and we use 2 for those timestamps.
> 
> Perhaps set character tracking to be calculated based on border size value for values greater than 1.5? If Lua features tracking control.

I don't know what you mean with tracking. Do you mean increasing the spacing between characters to avoid overlap?

BTW all the UI you see is drawn with libass, the subtitle rendering library used by mpv. Everything just is fancy subtitles. We assemble the subtitle text in Lua and that's then handed to libass. In case you're curious [here](https://aegi.vmoe.info/docs/3.0/ASS_Tags/) is a description of the tags available to us. Everything except animations can be used.

**Comment by bananakid** [comment]
> Then I have no idea what might be causing that. Can you provide a sample where this happens?

I'll try it but basically it happens with any "regular" (with black background) chapters, while it's fine with "special" (with cyan background, like openings) chapters.

> I don't know what you mean with tracking. Do you mean increasing the spacing between characters to avoid overlap?

Yes, totally. Thank you for the link to ASS. It appears like [ASS letter spacing](https://aegi.vmoe.info/docs/3.0/ASS_Tags/#index17h3) may be a conditional fix, however I'm not sure how to apply it to see. By the way my OSD font is Segoe UI 5.65.
