### ISSUE TITLE
Feature Request: Show thumbnail preview of videos in playlist ?

### ISSUE THREAD

**Issue by rexackermann** [tomasklaen/uosc#729]
So, I was wondering now that we can search things in the menu, playlist and chapters and what not ! Is it possible to preview the thumbnails of videos as well ?
I have used a similar script called [mpv-gallery-view](https://github.com/occivink/mpv-gallery-view).
I think something like this would be awesome ! Like when watching a from youtube playlist or something ?

**Comment by dyphire** [comment]
dup #479 , #487

**Comment by tomasklaen** [comment]
Yeah this is not planned. If you want thumbnails, you'll need to use your OS file explored, or a script that specializes in this.
