### ISSUE TITLE
Modernize the Timeline UI

### ISSUE THREAD

**Issue by xd003** [tomasklaen/uosc#733]
This is by far the most feature rich and well maintained OSC for mpv but the the timeline UI looks a bit off to me. Are there any plans to add additional timeline UI options which can be configured through the uosc.conf

**Comment by hooke007** [comment]
Honestly, modernx is ugly.

**Comment by dyphire** [comment]
This is an issue of aesthetic subjectivity, and I don't think uosc's UI is outdated. You cannot demand developers to work hard to meet your aesthetic preferences. If you are dissatisfied with this, you can fork it out and make any modifications.

**Comment by po5** [comment]
I just set the colors to not be pure black, that's the only thing I find unappealing.  
`color=foreground=FFFBFE,foreground_text=1C1B1F,background=1C1B1F,background_text=FFFBFE`

Maybe you can describe what's wrong with uosc instead of pointing to a completely different UI :^)  
Otherwise just add the cool uosc features to those UIs you prefer?

You can already selectively disable uosc's elements and use it alongside another UI script, you'll keep the menu system and whatever else you decide to not disable. https://github.com/tomasklaen/uosc/blob/1f26c3ec23208a2498d469d3de861c27fcb9407f/script-opts/uosc.conf#L228-L231

**Comment by xd003** [comment]
> Maybe you can describe what's wrong with uosc instead of pointing to a completely different UI :^) Otherwise just add the cool uosc features to those UIs you prefer?

Sure, mainly this portion in the bottom which displays the video timeline looks pretty weird to me
![Picsart_23-10-23_12-17-31-580](https://github.com/tomasklaen/uosc/assets/26503185/c564b119-decd-4998-a2c8-03ec9168d61c)

> You can already selectively disable uosc's elements and use it alongside another UI script, you'll keep the menu system and whatever else you decide to not disable.

Really appreciate your informative reply, i wasn't aware this is possible. Let's say say i keep ```disable_elements=timeline```, will the timeline from my other UI ( modern-compact) load automatically or i will to change something in there as well ?

**Comment by tomasklaen** [comment]
> Mainly this portion in the bottom which displays the video timeline looks pretty weird to me.

You'll just have to accept we have different tastes driven by different priorities. I want an easy to use and click on timeline that is usable on any window size, turns into a discrete progress indicator when I'm not using it, and looks good. The current one satisfied this.

Like can you snap cursor to chapter icon to click on the chapter time exactly? This would be impossible or incredibly annoying on a thin timeline. Not to mention how annoying it is to click thin seeklines in general, and how much easier it is to use uosc's especially in fullscreen when you can just throw the cursor against the bottom edge and start clicking, no concern for precisely aiming on a thin line positioned somewhere off the edge.

You're essentially using the word "modernize" to say "make it look like I'd prefer, regardless of hits to UX".

Just disable uosc's timeline and controls as suggested above, and use something you like.

**Comment by xd003** [comment]
@tomasklaen thanks for the detailed explanation, i really wasn't aware of the UX aspects you mentioned, they seem quite fair now that i analyse about it. I should have explored the project in bit more depth to understand why some elements are kept the way they are. It just initially struck me a bit off since not really used to seeing such timeline anywhere but the reasoning is quite valid. I guess will stick with uosc's timeline after considering the UX aspects. Closing this

**Comment by xd003** [comment]
@tomasklaen Just one doubt, is there an option to add the video info icon to the bottom bar ? That one is quite useful to see all the stats
