### ISSUE TITLE
Icons cutoff

### ISSUE THREAD

**Issue by BEST8OY** [tomasklaen/uosc#735]
When decresing sound with "/" (2% reduction) the sound icon has a cutoff.

![image](https://github.com/tomasklaen/uosc/assets/70865987/686a1cf5-1d6c-4e3e-aa58-678a94a6bf7b)

**Comment by christoph-heinrich** [comment]
1. This has nothing to do with uosc
2. You make the osd bar slim and move it all the way to the way to the edge and then complain about the icon being cut off? How about you don't do that.

**Comment by BEST8OY** [comment]
> 1. This has nothing to do with uosc
> 2. You make the osd bar slim and move it all the way to the way to the edge and then complain about the icon being cut off? How about you don't do that.

Chill bro :|
I'm pretty new to MPV so I'm LEARNING
I've used someone else's conf so yeah, I changed this part 
`osd-bar-h=3`
And now it's okay.
Even though you were a bit mad but thanks for help. :)
