### ISSUE TITLE
Outdated wiki page

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#738]
This doesn't seem to be a problem anymore https://github.com/tomasklaen/uosc/wiki/Interoperability-notes

If there are still issues I didn't spot, they would be caused by us not explicitly setting `\an7`, can be reproduced by setting `--osd-align-x` or `--osd-align-y` to non-default values, see https://github.com/po5/thumbfast/issues/100

**Comment by tomasklaen** [comment]
I mentioned on the page that this might not be necessary anymore. But I'll keep it there in case it still is.
