### ISSUE TITLE
Gap priority in controls

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#740]
Gaps should be treated with lower priority then other dynamic elements.

![image](https://github.com/tomasklaen/uosc/assets/8932183/b20a1e3d-d0d5-4df5-b57d-e5a89d1d56a7)
And that is with `controls_spacing=0`. With the default value of 2 it doesn't even show `speed` anymore.

Meanwhile there is enough space that it could be like this.
![image](https://github.com/tomasklaen/uosc/assets/8932183/e09a7f4e-51ff-4a92-a00e-987fd6e05fbc)

**Comment by tomasklaen** [comment]
Yeah makes sense. Gaps should work like spaces if there's no space left. I'll add it to a to-do list. Or are you going to try to tweak the layout algorithm yourself? It's not very nice :)

**Comment by christoph-heinrich** [comment]
I've tried adding a loop for disabling gaps if there isn't enough space above the other element disabling loop and that helped a little, but it not great and results in situations where the speed shrinks with increasing window size because there is enough space to fit some gaps.
I think the space for gaps needs to be accounted for separately from other dynamic elements, but that doesn't seem like a trivial change.

Ultimately the reason why there are so many gaps to the left of speed is because I want speed to be centered and thus have a bunch of conditional gaps.

Maybe we could change it so that spaces don't divide the space up evenly among themselves, and instead try to center clusters of controls at certain fractions of the width. So that 2 spaces means that the thing between those spaces is in the middle, 3 spaces would mean that in addition to the edges, there are two clusters at 1/3 and 2/3 of the width, etc.

I don't know how hard it would be to get that right, but I've been wondering about that idea for a while.

**Comment by natural-harmonia-gropius** [comment]
Can we use text_width_estimation?

Idea basically this. 
```css
grid-template-columns: max-content auto max-content;
gap: 1fr;
```

Split all icon into groups by space.
Get width of widest group.
For example:
1000px viewport, left 200px middle 100px right 300px actual.
Give containers of left and right 300px space, max(left, right). middle 100px, auto (keep actual). Sum of all fr be 300px, 2 fr here so 150px for each space (300/count_of(spaces)).

For more spaces `grid-template-columns: max-content ...auto max-content;` will be fine I guess.

**Comment by tomasklaen** [comment]
All right, this is as far as I'm willing to tinker with it:

![gaps](https://github.com/tomasklaen/uosc/assets/47283320/18da3ec8-de81-4197-975a-ec729244f675)

**Comment by christoph-heinrich** [comment]
That's a huge improvement, thanks.

One thing I notices is that the margin on the right also shrinks with the gaps.

Also any thoughts on my idea about changing the way spaces work? If you're not against it I'd work on it at some point (no eta).

**Comment by tomasklaen** [comment]
> One thing I notices is that the margin on the right also shrinks with the gaps.

Yeah I see that. I guess there's some leftover spacing in layout calculation somewhere. I'll look at it later hopefully.

> Also any thoughts on my idea about changing the way spaces work? If you're not against it I'd work on it at some point (no eta).

No, I don't want this to be more complicated than it already is. Making spaces behave like that would add a lot more code and complexity, more edge cases, potentially more options to turn this behavior off for people who just want everything evenly spaced (me for example). It's fine now.
