### ISSUE TITLE
Menu items don't react to mouse clicks on Windows

### ISSUE THREAD

**Issue by asuetin** [tomasklaen/uosc#746]
mpv version: [mpv-x86_64-v3-20231022](https://sourceforge.net/projects/mpv-player-windows/)
uosc version: 5.0.0
OS version: Windows 11 build 23565.1000

Reproduction steps:
1. Click on one of the OSC menus ("Menu", "Audio", "Subtitles")
2. Click on any of the menu items
3. Nothing happens

Additional info:
1. Hover effects work, clicks don't
2. Happens even on the default mpv/uosc configs with no other scripts running
3. Keyboard inputs work
4. Happens on older builds of mpv/uosc as well

**Comment by christoph-heinrich** [comment]
Do you have any other scripts running?

**Comment by zhongfly** [comment]
Oh, this is a bug! I originally thought that's how uosc was designed before.

**Comment by asuetin** [comment]
@christoph-heinrich 
> Do you have any other scripts running?

Yes, thumbfast and dynamic-crop, but I tried it without them. I amended the OP to make that clear.

**Comment by tomasklaen** [comment]
> Hover effects work, clicks don't

I'm on Win 10 and never had any such issues. If you see a hover effect, the uosc has already bound a click listener for the item. So clicking it would have to work.

Is this only happening in menus? Like control buttons or clicking on timeline is working?

> Happens on older builds of mpv/uosc as well

We even changed the way we register and handle pointer events in 5.0, so if it doesn't work even on older version, this is super weird.

I have no ideas here.

**Comment by asuetin** [comment]
> Is this only happening in menus? Like control buttons or clicking on timeline is working?

Yes to both. To add more context, when a menu is open you can click through it. For example, if you have "cycle fullscreen" bound to LMB and you double click on an item in an open menu, it cycles fullscreen.

**Comment by asuetin** [comment]
> We differentiate between clicking and dragging, but to trigger a drag you'd have to move the mouse during the click and the menu would scroll a bit (at least when it's scroll-able, otherwise nothing happens)

It doesn't seem like a drag is being triggered when clicking, but I actually discovered two more weird things:
1. Scroll wheel inputs don't work either for scrolling the menu;
2. When I was trying to make the menu small enough for it to become scrollable, it suddenly started working, clicks and all. But it only worked up to a certain window size. As soon as I resized the window above some arbitrary threshold, it broke again. I can't reproduce this anymore though.

> Clicks get registered on button up instead of button down (because of the dragging thing), so maybe you're not getting any up events for some reason? But that would also cause other problems like that dragging the menu or the volume indicator never ends.

The volume indicator works normally. Can't start dragging the menu since the `down` click goes right through it.

**Comment by McBaws** [comment]
I am also experiencing this issue, exactly as described by @asuetin. I also found that holding down shift or alt allows me to click on the menu items, but not the osc items. Not holding down shift or alt allows me to click on the osc items, but not the menu items. Arrow keys and other keyboard inputs still work.

This may be related to issue #804 as well.

**Comment by McBaws** [comment]
I found the source of my problems, massive config issue: I had mpv installed in \AppData\Roaming. Because of this, every script was loaded twice. 

Perhaps OP should check if they did the same, as I was experiencing the exact same problems as them.

**Comment by asuetin** [comment]
@McBaws oh wow, thanks, that was it! I certainly didn't expect that to be the solution.

**Comment by guyman624** [comment]
> I had mpv installed in \AppData\Roaming. 

Just bumping this to confirm that I had the same issue for the same reason, perhaps there should be a warning in the installation section?

**Comment by McBaws** [comment]
@Dunxter Just copy the mpv executables and the files it needs to a different folder and leave the scripts in roaming. Or move everything to a different folder. 

My hypothesis is that mpv loads everything in its current directory then everything in roaming, causing it to load everything twice if the current directory _is_ roaming. So just move mpv somewhere else.
