### ISSUE TITLE
Keybind to open a submenu 

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#75]
So if you look at my input.conf from the imgur link you can see I have a submenu for scalers for example. I want to know how to set a keybind so that when i press it, it opens the scalers menu directly without having to go through all the menus all the time.

https://imgur.com/gallery/joMmXXN

**Comment by tomasklaen** [comment]
Currently not possible. I might add it when I have some time.

**Comment by Zabooby** [comment]
I see, let me know when you do add it. 

Unrelated question, but what would I write in the input.conf file if I want the scroll wheel/middle mouse button to act as a play/pause button.

**Comment by FichteFoll** [comment]
```
AXIS_UP set pause yes
AXIS_DOWN set pause no
```
or use `cycle pause` if you want to toggle the state instead.

**Comment by Zabooby** [comment]
Thank you! a
Do you have an eta for adding the keybinds to submenus?

**Comment by tomasklaen** [comment]
```
m    script-message-to uosc show-submenu "Foo > Bar"
```
