### ISSUE TITLE
First character of hint is missing

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [tomasklaen/uosc#753]
It happens to Video, Audio and Subtitle for me.
![image](https://github.com/tomasklaen/uosc/assets/50797982/1bd748e3-3270-425f-9726-fa78ae5fe94a)
![image](https://github.com/tomasklaen/uosc/assets/50797982/2e66966a-44aa-4a88-816f-a453d894473b)
![image](https://github.com/tomasklaen/uosc/assets/50797982/0462bbf8-6329-4063-b822-f84eb7ea2205)

Also in english.
![image](https://github.com/tomasklaen/uosc/assets/50797982/bf99d208-58f6-4fc4-bbb8-08095c84fb74)

Not always happening.
![image](https://github.com/tomasklaen/uosc/assets/50797982/58399b56-f9dc-4875-9597-6d277e2979d2)

**Comment by dyphire** [comment]
I can't reproduce it on my end.
![image](https://github.com/tomasklaen/uosc/assets/61936050/64735582-8ca8-49b1-8c84-623c1015adc3)
![image](https://github.com/tomasklaen/uosc/assets/61936050/a5f1585f-52b8-43a5-a0d4-13b0d5906691)

**Comment by christoph-heinrich** [comment]
I started looking into this and I already know what's wrong, but I need to deal with something else now. I'll get back to it in ~4 hours.
