### ISSUE TITLE
Support pasting in search menus

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#765]
Useful for things like #497.

**Comment by christoph-heinrich** [comment]
Afaik the best clipboard script is https://github.com/CogentRedTester/mpv-clipboard, which we could use as a reference (or optional dependency).

**Comment by hooke007** [comment]
Nope, it's unnecessary. Just copy the code from console. The script you mentioned did the same work.

**Comment by christoph-heinrich** [comment]
> Nope, it's unnecessary. Just copy the code from console.

True, I forgot that it got that from console.

**Comment by tomasklaen** [comment]
That's a perfect job for ziggy! I'll extend it with `set-clipboard` and `get-clipboard` commands. That's going to be way more stable and instant, as opposed to spawning powershell scripts, which is really slow on windows.

**Comment by dyphire** [comment]
> That's a perfect job for ziggy! I'll extend it with `set-clipboard` and `get-clipboard` commands. That's going to be way more stable and instant, as opposed to spawning powershell scripts, which is really slow on windows.

I tested the clipboard function using the console on Windows and it doesn't seem to be slow. I'm curious about what the testing benchmark is.

**Comment by hooke007** [comment]
It doesn't respond the input immediately on Win. But it isn't slow for common usage.

**Comment by po5** [comment]
Powershell is slow to launch if it hasn't been launched recently.  
I agree that a custom program would be more responsive, but it's also a lot of work. On Linux, there's no universal concept of a clipboard afaik. It's different on wayland and x11, and clipboard managers exist.

**Comment by dyphire** [comment]
> Powershell is slow to launch if it hasn't been launched recently. 

I can reproduce it.

**Comment by tomasklaen** [comment]
Yeah and even after powershell "warms up" it's still around half a second to paste (at least for me). With ziggy it's perceptually instant.
