### ISSUE TITLE
another subtitle provider

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#773]
I see it from iina - a libmpv frontend. Not sure if it could be ported to uosc.

https://github.com/iina/iina/blob/develop/iina/AssrtSubtitle.swift
https://github.com/iina/iina/pull/4672

https://github.com/AssrtOSS

**Comment by dyphire** [comment]
Although I also like this idea, it should be pointed out that this subtitle provider of assrt is only applicable to Chinese users.

**Comment by hooke007** [comment]
>only applicable to Chinese users.

It provides en subs too.

**Comment by tomasklaen** [comment]
Is this not what you're asking for? https://github.com/AssrtOSS/mpv-assrt

I don't want to bite off more than I can chew by maintaining many subtitle providers, so if there's already a downloading script for one, I'd rather not be re-implement it in uosc if I don't have to. 

I think it'd be way easier if they added a uosc menu integration then if I've had to maintain an alternative implementation.

We could than have a new option:

```
download_subtitles_command=script-binding uosc/download-subtitles
```

which would configure what command should be executed when you activate the **Download subtitles** item in the subtitles menu, and you could change it to `assrt`.
