### ISSUE TITLE
How to change top-bar playlist button's background opacity?

### ISSUE THREAD

**Issue by 921j** [tomasklaen/uosc#774]
This element's background opacity can't change

![2023-11-05_215239](https://github.com/tomasklaen/uosc/assets/29940386/5698eda7-25d0-474c-9220-bfd991fbd14a)

I tried this, but It still white
opacity=timeline=0,position=0,chapters=0,slider=0,slider_gauge=0,speed=0,menu=0,submenu=0,border=0,title=0,tooltip=0,thumbnail=0,curtain=0,idle_indicator=0audio_indicator=0,buffering_indicator=0

**Comment by po5** [comment]
https://github.com/tomasklaen/uosc/blob/26d71a863015a3af45a41d17bb2f8678b8cde0d0/src/uosc/elements/TopBar.lua#L217
would need `opacity = visibility * config.opacity.playlist_position`
