### ISSUE TITLE
Calling update-menu with a new selected_index should scroll to the new index

### ISSUE THREAD

**Issue by Lypheo** [tomasklaen/uosc#775]
Afaict, there is no way to force uosc to scroll to a certain item in a custom menu. Setting ``selected_index`` in an ``update-menu`` call doesn’t seem to work, nor does setting ``active`` on the item to scroll to. 
My usecase is that I’m continuously adding items to a menu and, in the worst case, only know which item to select (and scroll to) after the last item is added.

**Comment by tomasklaen** [comment]
Setting `selected_index` is only allowed during creation of menu, afterwards it's controlled by user, and setting it with `update-menu` is ignored.

Why would you want to change user's selected item from underneath them, and start randomly scrolling the menu while they're trying to browse it? This sounds horrible and not like something I'd want to happen as a user.

What's the use case here?

**Comment by Lypheo** [comment]
[My use case](https://github.com/Lypheo/mpv-subtitle-lines/blob/master/subtitle-lines.lua) is that I’m constantly updating the menu by appending new items (subtitle lines), and once a certain item is added (the current subtitle), I want to scroll to that item because it would be annoying to try to find it manually.
>  This sounds horrible and not like something I'd want to happen as a user.

In this case I want it to happen because one of the main purposes of the script is to display neighboring subtitle lines, which are only availabe some time after the menu was opened for the first time.
