### ISSUE TITLE
controls doesn't work

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#777]
controls = `cycle:developer_board_off:hwdec:no=developer_board_off/yes=memory/auto-copy=developer_board?test`

It doesn't work in current git version.

**Comment by tomasklaen** [comment]
Can you describe how is it not working? Because I don't see an issue:

![hwdec](https://github.com/tomasklaen/uosc/assets/47283320/82556086-ca7d-4ce5-941b-cb8379aa8b28)

**Comment by hooke007** [comment]
load a video and click the button.
The video could only change its hwdec mode once.

**Comment by hooke007** [comment]
![test](https://github.com/tomasklaen/uosc/assets/41094733/556f6265-eb7a-472c-8fbd-b2194403e258)
git version

**Comment by hooke007** [comment]
release 4.7 works well
![test2](https://github.com/tomasklaen/uosc/assets/41094733/6a3d1f38-d92a-48c9-84ed-27739bf99eff)

**Comment by hooke007** [comment]
>  And on the gif above you can see that uosc is triggering proper commands. 

I don't see your console is switching hwdec mode. `[vd] Using ....`

**Comment by tomasklaen** [comment]
That looks more like a cursor events issue. Does something like `toggle:shuffle:shuffle` work? Or does it freeze after first click too?

> I don't see your console is switching hwdec mode. [vd] Using ....

It's a static paused image with `--quiet` enabled. One of those variables is why the output is clean. I get `VO:` changes on videos and observing `hwdec` reports changes correctly.

**Comment by hooke007** [comment]
> That looks more like a cursor events issue.

I tried `cycle:developer_board_off:hue:10=developer_board_off/20=memory/30=developer_board?test` and it works. So it looks like something else.

**Comment by hooke007** [comment]
The first broken version https://github.com/tomasklaen/uosc/tree/3af5ccff9fb98606b323a9993ea1896974011ff3
The last safe version
https://github.com/tomasklaen/uosc/tree/d2febcbd4709001f5db61b4d6befe545ab65d578

**Comment by tomasklaen** [comment]
Can you report what is this logging?

```diff
diff --git a/src/uosc/elements/CycleButton.lua b/src/uosc/elements/CycleButton.lua
index 6059849..6d5ca85 100644
--- a/src/uosc/elements/CycleButton.lua
+++ b/src/uosc/elements/CycleButton.lua
@@ -24,6 +24,7 @@ function CycleButton:init(id, props)
 	self.on_click = function()
 		local new_state = self.states[self.current_state_index + 1] or self.states[1]
 		local new_value = new_state.value
+		print('current:', self.states[self.current_state_index].value, 'next:', new_value)
 		if self.owner then
 			mp.commandv('script-message-to', self.owner, 'set', self.prop, new_value)
 		elseif is_state_prop then
```

**Comment by hooke007** [comment]
![Snipaste_2023-11-07_17-12-05](https://github.com/tomasklaen/uosc/assets/41094733/46147b03-6b0f-42a0-b3ac-e888696000e8)

**Comment by tomasklaen** [comment]
Yeah I though this was gonna be the issue. Now to figure out why is it failing to set or select next state for you.

Can you screenshot the result of this too?:

```lua
print('current:', self.states[self.current_state_index].value, 'next:', new_value, 'real:', mp.get_property_native('hwdec'))
```

**Comment by hooke007** [comment]
<img width=400 src="https://github.com/tomasklaen/uosc/assets/41094733/483b54e7-be9a-4dd5-b678-64af4357779f">

**Comment by tomasklaen** [comment]
Oh my god. How do we handle this now? There's one property for reading, and another for setting? Jesus. And why does it work for me and not for you?

**Comment by hooke007** [comment]
https://github.com/tomasklaen/uosc/issues/777#issuecomment-1798084745
But there must be sth happened in this commit right?

**Comment by tomasklaen** [comment]
Does this work for you?

```diff
diff --git a/src/uosc/elements/CycleButton.lua b/src/uosc/elements/CycleButton.lua
index 6059849..475f2e5 100644
--- a/src/uosc/elements/CycleButton.lua
+++ b/src/uosc/elements/CycleButton.lua
@@ -1,5 +1,9 @@
 local Button = require('elements/Button')
 
+local writer_reader_map = {
+	hwdec = 'hwdec-current'
+}
+
 ---@alias CycleState {value: any; icon: string; active?: boolean}
 ---@alias CycleButtonProps {prop: string; states: CycleState[]; anchor_id?: string; tooltip?: string}
 
@@ -52,7 +56,7 @@ function CycleButton:init(id, props)
 		self['on_prop_' .. self.prop] = function(self, value) handle_change(self.prop, value) end
 		handle_change(self.prop, state[self.prop])
 	else
-		self:observe_mp_property(self.prop, handle_change)
+		self:observe_mp_property(writer_reader_map[self.prop] or self.prop, handle_change)
 	end
 end
```

> But there must be sth happened in this commit right?

I'll try to look.

**Comment by hooke007** [comment]
> Does this work for you?

No, because I think `hwdec-current` reflects the name of hwdec.

![Snipaste_2023-11-07_17-47-53](https://github.com/tomasklaen/uosc/assets/41094733/0cde1a70-9eda-435c-8d8b-bc779fc5e8ef)

**Comment by tomasklaen** [comment]
Try this? 😬

```diff
diff --git a/src/uosc/elements/CycleButton.lua b/src/uosc/elements/CycleButton.lua
index 6059849..61cd666 100644
--- a/src/uosc/elements/CycleButton.lua
+++ b/src/uosc/elements/CycleButton.lua
@@ -52,7 +52,7 @@ function CycleButton:init(id, props)
 		self['on_prop_' .. self.prop] = function(self, value) handle_change(self.prop, value) end
 		handle_change(self.prop, state[self.prop])
 	else
-		self:observe_mp_property(self.prop, handle_change)
+		self:observe_mp_property(self.prop, 'string', handle_change)
 	end
 end
 
diff --git a/src/uosc/elements/Element.lua b/src/uosc/elements/Element.lua
index 3e3f458..733d63e 100644
--- a/src/uosc/elements/Element.lua
+++ b/src/uosc/elements/Element.lua
@@ -182,9 +182,12 @@ end
 
 -- Automatically registers disposer for the observer.
 ---@param name string
----@param callback fun(name: string, value: any)
-function Element:observe_mp_property(name, callback)
-	mp.observe_property(name, 'native', callback)
+---@param type_or_callback string|fun(name: string, value: any)
+---@param callback_maybe nil|fun(name: string, value: any)
+function Element:observe_mp_property(name, type_or_callback, callback_maybe)
+	local callback = type(type_or_callback) == 'function' and type_or_callback or callback_maybe
+	local prop_type = type(type_or_callback) == 'string' and type_or_callback or 'native'
+	mp.observe_property(name, prop_type, callback)
 	self:register_disposer(function() mp.unobserve_property(callback) end)
 end
```

**Comment by hooke007** [comment]
Yes, it works.
