### ISSUE TITLE
Unable to download 5.1.0 on Windows (Trojan:Win32/Wacatac.B!ml)

### ISSUE THREAD

**Issue by StrangePeanut** [tomasklaen/uosc#783]
Windows Security keeps detecting 'Trojan:Win32/Wacatac.B!ml' and deleting the files despite having explicitly allowed it. Is there any workaround? 😢

**Comment by vanbang9710** [comment]
I have the same problem ![|50pct](https://i.imgur.com/iZ9QM51.png)

**Comment by StrangePeanut** [comment]
I've given it another go and it let me download the zip. I've extracted all files but ziggy-linux (the 'offender') and everything seems to be fine. Not sure why Windows Security was going mad by not honouring 'allowed threats' before.

If you're still unable to download the zip, temporarily disabling 'real-time protection' could help if your company lets you.

**Comment by hooke007** [comment]
You do not need this file. It's prepared for linux users.

**Comment by StrangePeanut** [comment]
> > everything seems to be **fine.**
> 
> You do not need file `ziggy-linux`. It's prepared for linux users.

@hooke007 not sure why I've been quoted out of context. It was referring to none of the other files causing 'threat detections'.

**Comment by StrangePeanut** [comment]
Just to kindly reiterate, the issue is that the zip could not be downloaded at all let alone extracted. This is especially bothersome if you're using a company-issued device which tends to be more restrictive.

**Comment by hooke007** [comment]
I was just telling you that the feature is not affected. Do not worry about sth cannot work.

**Comment by hooke007** [comment]
I found that bin archived by upx are easir to be dectected.
The bin built by myself
https://www.virustotal.com/gui/file/fce19a74ef304cfa8a9accfba53d92434e36f95f9e05b6b7b3c3334bfd1a1db1/detection
The bin archived by upx
https://www.virustotal.com/gui/file/27de3ea783e9aff520a5fe4355a0b9d8ef968176e3ace389f7db68b76583d283/detection

**Comment by tomasklaen** [comment]
So apparently the way go package binaries makes them suspicious to antivirsues and causes a lot of false positives :(

Does this file cause issues to you too? -> [uosc.zip](https://github.com/tomasklaen/uosc/files/13316971/uosc.zip)

I've removed binary compression, which according to virustotal silences google's and microsoft's detection, but there are still some false positives from less known virus detectors.

**Comment by StrangePeanut** [comment]
Oh that makes sense. UPX has always been a wee troublesome in my experience.

@tomasklaen nope, that one downloads just fine here

**Comment by tomasklaen** [comment]
I've released 5.1.1 with uncompressed binaries. Hopefully that solves this for everyone, but as mentioned, there are still some obscure antiviruses that find them suspicious. I think the only way to solve this would be to sign them (not 100% sure though), but I'm not paying to work on free stuff. If anyone is bothered by this, and would be willing to donate a code signing certificate, let me know.

I'll close this for now, but feel free to report if anyone still has issues and I'll reopen, but not sure what else I can do apart of rewriting binaries in something else, for which I won't have time that soon.
