### ISSUE TITLE
Automatically load the last downloaded subtitle, replacing the previous one

### ISSUE THREAD

**Issue by cipricus** [tomasklaen/uosc#786]
That is default in VLC and SMPlayer, very useful in order to test the sub (and decide whether to search for another or not) and to not have to select it manually. 
Maybe related to https://github.com/tomasklaen/uosc/issues/785.

**Comment by tomasklaen** [comment]
We already load downloaded subtitles with `sub-add <file>` command, which sets it as current subtitle track by default, and afterwards we ensure `sub-visibility yes`.

Not sure what else is to be done here, or why it doesn't work for you.

**Comment by candrapersada** [comment]
auto load subtitle use the same name
```
Sonic the Hedgehog 2.mp4
Sonic the Hedgehog 2.srt
```

**Comment by cipricus** [comment]
https://github.com/tomasklaen/uosc/issues/785#issuecomment-3817681472
