### ISSUE TITLE
Go above the limit of 5 sub downloads

### ISSUE THREAD

**Issue by cipricus** [tomasklaen/uosc#787]
What is the cause of the 5 downloads limit? Is there a way to go above? I don't see that limit in VLC and in SMPlayer I can enter credentials.

**Comment by tomasklaen** [comment]
This is documented here: https://github.com/tomasklaen/uosc#download-subtitles

> Current Open Subtitles limit for unauthenticated requests is 5 download per day, but searching is unlimited. Authentication raises downloads to 10, which doesn't feel like it's wroth the effort of implementing it, so currently there's no way to authenticate.

If you need to download more than 5 subs per day, you should probably just deal with it in the browser beforehand so you don't have to fiddle with the menu every time a new file starts.

There's also #761 to add Podnapisi.net as an anternative subtitle provider, as they don't seem to have download limits, but they also don't have their API documented properly, it's quite slow and errors out often, and I didn't have much time to reverse engineer it and gave up. PRs/docs welcome.

**Comment by cipricus** [comment]
Thanks! I didn't realize that's a 10 subs limit anyway. The 5+ search is a rare thing, but then what I do is use SMPlayer, I have even added a button to start the sub search with smplayer from mpv , the command being `command:download:run smplayer -actions "show_find_sub_dialog"`. 

More important  (in order to use the uosc sub search instead of smplayer) would be my other post about loading the downloaded sub.
