### ISSUE TITLE
Question: can we create a button and/or shortcut to get more directly to subtitle downloads?

### ISSUE THREAD

**Issue by cipricus** [tomasklaen/uosc#789]
Is there a command to use with a button or shortcut so that it would open directly this option:

![image](https://github.com/tomasklaen/uosc/assets/3447868/c29d584c-6c60-4951-858e-0b6afa590e67)

Or one to open directly the next one?

![image](https://github.com/tomasklaen/uosc/assets/3447868/302a3dcf-64d9-4613-a836-a7b30126f625)

**Comment by christoph-heinrich** [comment]
Do you mean `script-message-to uosc download-subtitles` ?

**Comment by cipricus** [comment]
> Do you mean [`script-message-to uosc download-subtitles`](https://github.com/tomasklaen/uosc#download-subtitles) ?

Yes!

Using `Ctrl+s script-binding uosc/download-subtitles` in `~/.config/mpv/input.conf` the shortcut gives the interface in my first image. 

To get a button for that, one should have something like:

`controls=...gap,command:download:script-message-to uosc download-subtitles ${path}?Download subtitle,gap...`

**Comment by christoph-heinrich** [comment]
> I guess there's no way to get to the second image directly, right? or a way to get to that next stage by just Enter instead of Ctrl-Enter?

correct

**Comment by cipricus** [comment]
> > I guess there's no way to get to the second image directly, right? or a way to get to that next stage by just Enter instead of Ctrl-Enter?
> 
> correct

But now I see it's just subtitles in English. #791
