### ISSUE TITLE
How to edit UI color in 5.x?

### ISSUE THREAD

**Issue by cipricus** [tomasklaen/uosc#790]
In 4.x version of uosc I have these lines in `uosc.conf`:

```
#RGB HEX color codes
foreground=6aabcf
foreground_text=000000
background=1d2f38
background_text=ffffff
```

to get 

![image](https://github.com/tomasklaen/uosc/assets/3447868/de1791d6-4deb-481d-9ad3-8ceb32b1f891)

but in 5.1.1 (updated with the script and a new `uosc.conf`) with 

```
# A comma delimited list of color overrides in RGB HEX format. Defaults:
foreground=6aabcf,foreground_text=000000,background=1d2f38,background_text=ffffff,curtain=111111,success=a5e075,error=ff616e
color=
```

![image](https://github.com/tomasklaen/uosc/assets/3447868/b73055c0-5fcb-4175-8211-6ff67912e428)

`color=yes` or `color=1d2f38` changes nothing.

**Comment by christoph-heinrich** [comment]
`color=foreground=6aabcf,foreground_text=000000,background=1d2f38,background_text=ffffff`

**Comment by AndydeCleyre** [comment]
Is it documented anywhere which elements are affected by which color names? Maybe an annotated screenshot?

**Comment by tomasklaen** [comment]
It'd be a picture of 4 colors with arrows pointing to all elements. Colors affect all elements. Success/error colors are only for update messages.
