### ISSUE TITLE
Subtitle search in all languages seems absent

### ISSUE THREAD

**Issue by cipricus** [tomasklaen/uosc#791]
Is it the case that only English results are provided? 
Can this be changed by the user?
If no, I want to post this as a feature request.

(I guess it should be an option in `uosc.conf`  to specify the search languages.)

**Comment by tomasklaen** [comment]
The language of fetched subtitles is configurable with uosc's `languages` option, which defaults to your mpv's `slang` config.

The opensubtitles.com catalogue of subtitles in languages other than english is limited though, so depending on searched language, you might not get many results.

**Comment by cipricus** [comment]
> The language of fetched subtitles is configurable with uosc's `languages` option, which defaults to your mpv's `slang` config.
> 
> The opensubtitles.com catalogue of subtitles in languages other than english is limited though, so depending on searched language, you might not get many results.

Can you tell me please how is that practically done for all languages? What about adding just French, Romanian and Italian?

I have tried  to edit `mpv.conf` and add `slang=fre`, but that doesn't find French subs when it should. `slang=all` gives only English.
