### ISSUE TITLE
Cannot find subtitles in some languages (French, Spanish, German, Russian, Romanian) as their language tag (mpv.conf, `slang=`) crash/disable uosc 

### ISSUE THREAD

**Issue by cipricus** [tomasklaen/uosc#792]
I have updated the title of the issue to reflect the conclusions I have arrived at after more testing. See them [here](https://github.com/tomasklaen/uosc/issues/792#issuecomment-1807898596).

---

As per [this](https://github.com/tomasklaen/uosc/issues/791#issuecomment-1807201511) comment, and uosc settings [download-subtitles](https://github.com/tomasklaen/uosc#download-subtitles): 
```
We fetch results for languages defined in uosc*'s languages option, which defaults to your mpv slang configuration.
```
relating to `slang` mpv.conf [setting](https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst).

Editing  `~/.config/mpv/mpv.conf`, I have added `slang=ron,fra,it` to get subtitles in Romanian, French and Italian.  But only Italian subs are found (beside English). I have tested with a Chaplin movie where SMPlayer and VLC also list French and Romanian subs. 

I have also used `rou`, `ron` and `rum` for Romanian, and `fre` for French, with the same result. 

Oddly, some formats crash or disable  uosc completely, like `ro` and `fr`, but others, which mean nothing, used just to test the matter, have no bad effect (like `slang=roux,frex,itx, xxx`). I read at https://mpv.io/manual/stable/ that for `slang` are to be used  _IETF language tags. Equivalent ISO 639-1 two-letter and ISO 639-2 three-letter codes are treated the same_. The [IETF tag ](https://en.wikipedia.org/wiki/IETF_language_tag#Syntax_of_language_tags)for French is `fr`! `slang=fr` disables uosc! the same with `ro` for Romanian!

Maybe I'm not putting the correct formats for French and Romanian. Am I?

Another odd thing: I had to remove other subtitle scripts (namely, autosubsync) in order to have the `slang` option active at all (before that, not even Italian was found, just English).

The only other formats that I was able to confirm to be correct and working were Hungarian (`hu`) and Bulgarian (`bg`).

By the way: is there an `all` setting so that all available subs are listed?

How could I get access to French and Romanian subtitles?

**Comment by tomasklaen** [comment]
Can't replicate. It'd be useful to provide crash logs. They should be visible in console, which by default is bound to ` key.

And I don't think `all` is supported, as why would anyone want to see results from all languages 99% of which they don't speak, but you can dig yourself: https://opensubtitles.stoplight.io/docs/opensubtitles-api/a172317bd5ccc-search-for-subtitles

**Comment by cipricus** [comment]
>crash logs

Running with `--slang=fr` (which disabled uosc) all I see is this:

![image](https://github.com/tomasklaen/uosc/assets/3447868/6378d66f-a876-4340-93fd-99d1b68d5e0a)


>why would anyone want to see results from all

Because the specific setting per language (e.g. Romanian and French, as said above) doesn't work for some cases I need. I am a native Romanian and I watch all movies in a foreign language that I can read (English, French and Italian) subbed in that language, and the other movies subbed in Romanian.

>Can't replicate

You mean that something like  `mpv --slang=fr --player-operation-mode=pseudo-gui 'SOME_MOVIE` still shows uosc? 
In my case it reverts to defautl pseudo-gui (in case osc isn't hidden by mpv.conf)! — Or that you somehow do find Romanian and French subtitles? With what setting exactly?

**Comment by cipricus** [comment]
Update: 
- `el` Greek, `he` Hebrew, `tr` Turkish work and find subs!
- `es` Spanish, `de` German, `ru` Russian also disable uosc.
-  `spa` and `sp`,  `deu` and `ger`, `ar` and `ara` (Arabic), `gre`,`ell` (Greek), `heb` (Hebrew), `pt`,`por`, `pb` (Portuguese), `rus` Russian, `tur` Turkish don't affect uosc, but no subs are found with them (for a movie that does have them and are found by SMPlayer and VLC). 

As far as I can see, only 2-letter language codes work with uosc+`slang` mpv option, but some that should work, don't and also disable the uosc interface.

**Comment by christoph-heinrich** [comment]
In `uosc/lib/intl.lua:37` you'll find `'*all'`, would you mind replacing that with `'a'` and see what happens?

**Comment by cipricus** [comment]
>In uosc/lib/intl.lua:37 you'll find '*all', would you mind replacing that with 'a' and see what happens?

After that it becomes still more odd. 

- There is no improvement if I use `slang=fr,ro,it` (no uosc). 
-  If I _remove_ the line completely, oddly, the subtitle downloader sees, beside English, other languages, namely in one case Hungarian and Bulgarian, no idea why just these, given that Arabic, Turkish, Greek, for example, could have also been there, based on the 'ok' list mentioned in previous comment and on what SMPlayer shows.
- If, I on the other hand use `slang=ar,tr,et`, to add the 3 languages absent, only English and these are seen (not Bulgarian and Hungarian anymore, but these can be added by adding their tags

**Comment by cipricus** [comment]
Now, after making the changes to `sdt.lua` like [here](https://github.com/tomasklaen/uosc/pull/794/files) and changing `uosc/lib/intl.lua:37` back to '*all', my problem is fixed!

Thank you!
