### ISSUE TITLE
Control-bar buttons and badge

### ISSUE THREAD

**Issue by hubblec4** [tomasklaen/uosc#802]
Hi uosc-Team

## Badge track count versus track id

The badge for each "track-button" is nice, but the info how many tracks are there is not so useful.

It would be nicer when the number in a badge are equal to the current track id.
That info which track is currently played is more useful.

The built-in OSC shows the current played track id.

## Badge count(number) not shown after changing the mpv chapter list by mpvMatroska

mpvMatroska creates a new correct chapter list after the file was loading and then there is longer a badge on the chapter button shown.
How can I restore the badge?

## own badge counter

mpvMatroska uses an internal edition list, because the mpv edition list is not always correct and the wrong edition name is shown after switching editions.
Therefor I use my own edition button in the uosc control-bar.

```lua
command:bookmarks:script-binding mpvMatroska/open-editions?Editions
```

How can I make a badge with the count(better with the current played edition id) of the internal editions of mpvMatroska?

**Comment by hooke007** [comment]
> Badge track count versus track id

https://github.com/tomasklaen/uosc/pull/212#issuecomment-1250253347

**Comment by tomasklaen** [comment]
> Badge track count versus track id

You mean displaying id of tracks, like language codes for subtitle/audio? I don't want that as those can be long and badge only has a real estate for 1-2 letters at most. More will lead to it covering too much of the icon, and overflow into the one on the left.

> Badge count(number) not shown after changing the mpv chapter list by mpvMatroska

As far as I recall we just listen for relevant mpv properties holding those counts/lists and display it. If mpv doesn't notify us of the change, there's not much we can do.

> own badge counter

As documented in the readme, every script can make its own badge by sending:

```lua
mp.commandv('script-message-to', 'uosc', 'set', 'foo', 1)
```

And used as badges:

```
controls=command:icon_name:command_name#foo@script_name?My foo button
```

Docs: https://github.com/tomasklaen/uosc#set-prop-value
