### ISSUE TITLE
Own buttons: everywhere createable on the screen

### ISSUE THREAD

**Issue by hubblec4** [tomasklaen/uosc#803]
Hi uosc-Team

To bring up the Matroska Interactive Movie menu support, it is necessary to create buttons or areas on the screen where the user can make a click action.

Is this possible with uosc?
Or can I use some source code from uosc in mpvMatroska?

Since this topic is completely new to me, I would be very grateful for any information and help.

**Comment by christoph-heinrich** [comment]
You can listen to mouse clicks with the `mbtn_left` keybind and you can get the current mouse position with the `mouse-pos` property.

There is an old deprecated keybind interface where you can specify regions and then the keybind is only active when the mouse is in that area, but since it's deprecated it's probably better if you check if the mouse is within some region yourself.

**Comment by hubblec4** [comment]
> You can listen to mouse clicks with the mbtn_left keybind and you can get the current mouse position with the mouse-pos property.

Thanks, very good to know.

>  probably better if you check if the mouse is within some region yourself.

I have no idea how but it sounds the right way.
What is when I want draw some text to such area or an image should be placed in that area.

Can I create a button with uosc and place it where I want?

**Comment by po5** [comment]
You will need custom mouse region handling within your code, uosc isn't a general purpose scripting API.

**Comment by christoph-heinrich** [comment]
> What is when I want draw some text to such area or an image should be placed in that area.

You can draw text with [`mp.create_osd_overlay()`](https://mpv.io/manual/master/#lua-scripting-mp-create-osd-overlay(format)). With that you can draw subtitles in the ASS format. Everything you see from uosc has been drawn that way.

Images can be drawn with [overlay-add](https://mpv.io/manual/master/#command-interface-overlay-add), which only supports raw image data in bgra format, so you'll have to decode you images to temporary files before displaying them.
That's how [thumbfast](https://github.com/po5/thumbfast/tree/master) draws it's preview and how [gallery-view](https://github.com/occivink/mpv-gallery-view/tree/master) draws it's gallery.

**Comment by hooke007** [comment]
> Or can I use some source code from uosc in mpvMatroska?

Why cannot? Are your repo's license incompatible?

**Comment by hubblec4** [comment]
> You will need custom mouse region handling within your code, uosc isn't a general purpose scripting API.

OK, I have to learn how it works with the regions.

> You can draw text with.....
Images can be drawn with....

OK, sounds also easy but I guess it isn't.

> Are your repo's license incompatible?

That was more a question about the code, not the license. But I guess I can't use some classes so easy out of uosc.

I'm total new to mpv, Lua and all the other player relevant things.

**Comment by tomasklaen** [comment]
uosc isn't a UI drawing library, so it can't be used for this. You'll have to write your own I'm afraid. But feel free to use whatever you need from uosc.
