### ISSUE TITLE
UOSC Control Buttons Unclickable If Ctrl, Alt, Shift Keys Held Down

### ISSUE THREAD

**Issue by AziRizvi** [tomasklaen/uosc#804]
The UOSC buttons become unclickable if the Ctrl, Shift or Alt Key is held down.. is this behaviour intentional and can this be changed?
I use a windows program called AutoHotKey because I use multiple macro devices like this 

![1](https://github.com/tomasklaen/uosc/assets/129892077/b029afdd-3f3a-4741-ba9d-2d4d10a54f1b)

And this:

![2](https://github.com/tomasklaen/uosc/assets/129892077/c67776ff-deef-49df-8179-c763be3e576f)

A bug in the AHK program is that modifier keys like Ctrl, Alt, Win and Shift can sometimes be stuck down because AutoHotKey intercepts the original input that was sent and then overrides it and sends it as whatever you want. [https://en.wikipedia.org/wiki/AutoHotkey](url)

The consequence of the keys getting stuck down is that UOSC control buttons become unclickable and I have to mash the Ctrl, Alt, Shift keys on my keyboard a bunch of times to release them and then get the menu to work again, so can I change something in the script to make it work despite the keys being held down?

**Comment by po5** [comment]
You're gonna run into issues with many more programs, consider fixing your setup or running another AHK script constantly unpressing modifier keys.

**Comment by christoph-heinrich** [comment]
In `cursor.lua` at the bottom we create a binding for `mbtn_left`. You'll have to copy that and create bindings for `ctrl+mbtn_left`, `alt+mbtn_left`, ... and then make sure that in `cursor:decide_keybinds()` those bindings get enabled and disabled just like `mbtn_left`. I think that's all, but I can't be bothered to try it out myself.

But like @po5 already said, uosc isn't the only place where those stuck modifiers will cause problems for you, so you'll be better off finding a fix for that instead of working around it in uosc.

**Comment by AziRizvi** [comment]
> You're gonna run into issues with many more programs, consider fixing your setup or running another AHK script constantly unpressing modifier keys.

I am running another script to constantly check every 4.5 seconds and see if a modifier key is being held down and if it is, it releases it by sending that Key + Up, but that solution doesn't always work, this is a known bug in AHK and everyone that uses it has to live it with sadly.

**Comment by AziRizvi** [comment]
> In `cursor.lua` at the bottom we create a binding for `mbtn_left`. You'll have to copy that and create bindings for `ctrl+mbtn_left`, `alt+mbtn_left`, ... and then make sure that in `cursor:decide_keybinds()` those bindings get enabled and disabled just like `mbtn_left`. I think that's all, but I can't be bothered to try it out myself.
> 
> But like @po5 already said, uosc isn't the only place where those stuck modifiers will cause problems for you, so you'll be better off finding a fix for that instead of working around it in uosc.

Here are the changes that I've made to both sections:

Replaced The older keybind section with this:

```
-- Key Binding Groups With Ctrl, Shift, And Alt Keys
mp.set_key_bindings({
    {'mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
    {'ctrl+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
    {'shift+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
    {'alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
}, 'mbtn_left', 'force')

mp.set_key_bindings({
    {'mbtn_left_dbl', 'ignore'},
    {'ctrl+mbtn_left_dbl', 'ignore'},
    {'shift+mbtn_left_dbl', 'ignore'},
    {'alt+mbtn_left_dbl', 'ignore'},
}, 'mbtn_left_dbl', 'force')

mp.set_key_bindings({
    {'mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
    {'ctrl+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
    {'shift+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
    {'alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
}, 'mbtn_right', 'force')

mp.set_key_bindings({
    {'wheel_up', cursor:create_handler('wheel_up')},
    {'ctrl+wheel_up', cursor:create_handler('wheel_up')},
    {'shift+wheel_up', cursor:create_handler('wheel_up')},
    {'alt+wheel_up', cursor:create_handler('wheel_up')},
    {'wheel_down', cursor:create_handler('wheel_down')},
    {'ctrl+wheel_down', cursor:create_handler('wheel_down')},
    {'shift+wheel_down', cursor:create_handler('wheel_down')},
    {'alt+wheel_down', cursor:create_handler('wheel_down')},
}, 'wheel', 'force')
```

Replaced the older cursor:decide_keybinds() with this:

```
-- Enables or disables keybinding groups based on what event listeners are bound.
function cursor:decide_keybinds()
    local enable_mbtn_left = self:has_any_handler('primary_down') or self:has_any_handler('primary_up')
    local enable_mbtn_left_dbl = self:has_handler('primary_down') or self:has_handler('primary_up')
    local enable_mbtn_right = self:has_handler('secondary_down') or self:has_handler('secondary_up')
    local enable_wheel = self:has_handler('wheel_down') or self:has_handler('wheel_up')
    local enable_ctrl_mbtn_left = self:has_any_handler('primary_down') or self:has_any_handler('primary_up')
    local enable_ctrl_mbtn_left_dbl = self:has_handler('primary_down') or self:has_handler('primary_up')
    local enable_ctrl_mbtn_right = self:has_handler('secondary_down') or self:has_handler('secondary_up')
    local enable_ctrl_wheel = self:has_handler('wheel_down') or self:has_handler('wheel_up')
    local enable_shift_mbtn_left = self:has_any_handler('primary_down') or self:has_any_handler('primary_up')
    local enable_shift_mbtn_left_dbl = self:has_handler('primary_down') or self:has_handler('primary_up')
    local enable_shift_mbtn_right = self:has_handler('secondary_down') or self:has_handler('secondary_up')
    local enable_shift_wheel = self:has_handler('wheel_down') or self:has_handler('wheel_up')
    local enable_alt_mbtn_left = self:has_any_handler('primary_down') or self:has_any_handler('primary_up')
    local enable_alt_mbtn_left_dbl = self:has_handler('primary_down') or self:has_handler('primary_up')
    local enable_alt_mbtn_right = self:has_handler('secondary_down') or self:has_handler('secondary_up')
    local enable_alt_wheel = self:has_handler('wheel_down') or self:has_handler('wheel_up')
	
	if enable_mbtn_left ~= self.mbtn_left_enabled then
		local flags = 'allow-vo-dragging+allow-hide-cursor'
		mp[(enable_mbtn_left and 'enable' or 'disable') .. '_key_bindings']('mbtn_left', flags)
		self.mbtn_left_enabled = enable_mbtn_left
	end
	if enable_mbtn_left_dbl ~= self.mbtn_left_dbl_enabled then
		mp[(enable_mbtn_left_dbl and 'enable' or 'disable') .. '_key_bindings']('mbtn_left_dbl')
		self.mbtn_left_dbl_enabled = enable_mbtn_left_dbl
		self:queue_autohide()
	end
	if enable_mbtn_right ~= self.mbtn_right_enabled then
		mp[(enable_mbtn_right and 'enable' or 'disable') .. '_key_bindings']('mbtn_right')
		self.mbtn_right_enabled = enable_mbtn_right
		self:queue_autohide()
	end
	if enable_wheel ~= self.wheel_enabled then
		mp[(enable_wheel and 'enable' or 'disable') .. '_key_bindings']('wheel')
		self.wheel_enabled = enable_wheel
		self:queue_autohide()
	end
	    if enable_ctrl_mbtn_left ~= self.ctrl_mbtn_left_enabled then
        mp[(enable_ctrl_mbtn_left and 'enable' or 'disable') .. '_key_bindings']('ctrl+mbtn_left')
        self.ctrl_mbtn_left_enabled = enable_ctrl_mbtn_left
    end

    if enable_ctrl_mbtn_left_dbl ~= self.ctrl_mbtn_left_dbl_enabled then
        mp[(enable_ctrl_mbtn_left_dbl and 'enable' or 'disable') .. '_key_bindings']('ctrl+mbtn_left_dbl')
        self.ctrl_mbtn_left_dbl_enabled = enable_ctrl_mbtn_left_dbl
        self:queue_autohide()
    end
    if enable_ctrl_mbtn_right ~= self.ctrl_mbtn_right_enabled then
        mp[(enable_ctrl_mbtn_right and 'enable' or 'disable') .. '_key_bindings']('ctrl+mbtn_right')
        self.ctrl_mbtn_right_enabled = enable_ctrl_mbtn_right
        self:queue_autohide()
    end
    if enable_ctrl_wheel ~= self.ctrl_wheel_enabled then
        mp[(enable_ctrl_wheel and 'enable' or 'disable') .. '_key_bindings']('ctrl+wheel')
        self.ctrl_wheel_enabled = enable_ctrl_wheel
        self:queue_autohide()
    end
	    if enable_shift_mbtn_left ~= self.shift_mbtn_left_enabled then
        mp[(enable_shift_mbtn_left and 'enable' or 'disable') .. '_key_bindings']('shift+mbtn_left')
        self.shift_mbtn_left_enabled = enable_shift_mbtn_left
    end
    if enable_shift_mbtn_left_dbl ~= self.shift_mbtn_left_dbl_enabled then
        mp[(enable_shift_mbtn_left_dbl and 'enable' or 'disable') .. '_key_bindings']('shift+mbtn_left_dbl')
        self.shift_mbtn_left_dbl_enabled = enable_shift_mbtn_left_dbl
        self:queue_autohide()
    end
    if enable_shift_mbtn_right ~= self.shift_mbtn_right_enabled then
        mp[(enable_shift_mbtn_right and 'enable' or 'disable') .. '_key_bindings']('shift+mbtn_right')
        self.shift_mbtn_right_enabled = enable_shift_mbtn_right
        self:queue_autohide()
    end
    if enable_shift_wheel ~= self.shift_wheel_enabled then
        mp[(enable_shift_wheel and 'enable' or 'disable') .. '_key_bindings']('shift+wheel')
        self.shift_wheel_enabled = enable_shift_wheel
        self:queue_autohide()
    end
    if enable_alt_mbtn_left ~= self.alt_mbtn_left_enabled then
        mp[(enable_alt_mbtn_left and 'enable' or 'disable') .. '_key_bindings']('alt+mbtn_left')
        self.alt_mbtn_left_enabled = enable_alt_mbtn_left
    end
    if enable_alt_mbtn_left_dbl ~= self.alt_mbtn_left_dbl_enabled then
        mp[(enable_alt_mbtn_left_dbl and 'enable' or 'disable') .. '_key_bindings']('alt+mbtn_left_dbl')
        self.alt_mbtn_left_dbl_enabled = enable_alt_mbtn_left_dbl
        self:queue_autohide()
    end
    if enable_alt_mbtn_right ~= self.alt_mbtn_right_enabled then
        mp[(enable_alt_mbtn_right and 'enable' or 'disable') .. '_key_bindings']('alt+mbtn_right')
        self.alt_mbtn_right_enabled = enable_alt_mbtn_right
        self:queue_autohide()
    end

    if enable_alt_wheel ~= self.alt_wheel_enabled then
        mp[(enable_alt_wheel and 'enable' or 'disable') .. '_key_bindings']('alt+wheel')
        self.alt_wheel_enabled = enable
	end
end
```

Is that all that I needed to do?

**Comment by christoph-heinrich** [comment]
I've now had a look and the only thing you have to do is this:
```diff
diff --git a/src/uosc/lib/cursor.lua b/src/uosc/lib/cursor.lua
index c1600ed..39e14ac 100644
--- a/src/uosc/lib/cursor.lua
+++ b/src/uosc/lib/cursor.lua
@@ -310,23 +310,45 @@ mp.observe_property('mouse-pos', 'native', handle_mouse_pos)
 
 -- Key binding groups
 mp.set_key_bindings({
-	{
-		'mbtn_left',
-		cursor:create_handler('primary_up'),
-		cursor:create_handler('primary_down', function(...)
-			handle_mouse_pos(nil, mp.get_property_native('mouse-pos'))
-		end),
-	},
+	{'mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
+	{'ctrl+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
+	{'shift+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
+	{'alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
+	{'ctrl+alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
+	{'shift+alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
+	{'shift+ctrl+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
+	{'shift+ctrl+alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
 }, 'mbtn_left', 'force')
 mp.set_key_bindings({
 	{'mbtn_left_dbl', 'ignore'},
 }, 'mbtn_left_dbl', 'force')
 mp.set_key_bindings({
 	{'mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
+	{'ctrl+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
+	{'shift+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
+	{'alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
+	{'ctrl+alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
+	{'shift+alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
+	{'shift+ctrl+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
+	{'shift+ctrl+alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
 }, 'mbtn_right', 'force')
 mp.set_key_bindings({
 	{'wheel_up', cursor:create_handler('wheel_up')},
+	{'ctrl+wheel_up', cursor:create_handler('wheel_up')},
+	{'shift+wheel_up', cursor:create_handler('wheel_up')},
+	{'alt+wheel_up', cursor:create_handler('wheel_up')},
+	{'ctrl+alt+wheel_up', cursor:create_handler('wheel_up')},
+	{'shift+alt+wheel_up', cursor:create_handler('wheel_up')},
+	{'shift+ctrl+wheel_up', cursor:create_handler('wheel_up')},
+	{'shift+ctrl+alt+wheel_up', cursor:create_handler('wheel_up')},
 	{'wheel_down', cursor:create_handler('wheel_down')},
+	{'ctrl+wheel_down', cursor:create_handler('wheel_down')},
+	{'shift+wheel_down', cursor:create_handler('wheel_down')},
+	{'alt+wheel_down', cursor:create_handler('wheel_down')},
+	{'ctrl+alt+wheel_down', cursor:create_handler('wheel_down')},
+	{'shift+alt+wheel_down', cursor:create_handler('wheel_down')},
+	{'shift+ctrl+wheel_down', cursor:create_handler('wheel_down')},
+	{'shift+ctrl+alt+wheel_down', cursor:create_handler('wheel_down')},
 }, 'wheel', 'force')
 
 return cursor
```

**Comment by AziRizvi** [comment]
> I've now had a look and the only thing you have to do is this:
> 
> ```diff
> diff --git a/src/uosc/lib/cursor.lua b/src/uosc/lib/cursor.lua
> index c1600ed..39e14ac 100644
> --- a/src/uosc/lib/cursor.lua
> +++ b/src/uosc/lib/cursor.lua
> @@ -310,23 +310,45 @@ mp.observe_property('mouse-pos', 'native', handle_mouse_pos)
>  
>  -- Key binding groups
>  mp.set_key_bindings({
> -	{
> -		'mbtn_left',
> -		cursor:create_handler('primary_up'),
> -		cursor:create_handler('primary_down', function(...)
> -			handle_mouse_pos(nil, mp.get_property_native('mouse-pos'))
> -		end),
> -	},
> +	{'mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
> +	{'ctrl+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
> +	{'shift+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
> +	{'alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
> +	{'ctrl+alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
> +	{'shift+alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
> +	{'shift+ctrl+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
> +	{'shift+ctrl+alt+mbtn_left', cursor:create_handler('primary_up'), cursor:create_handler('primary_down', function(...) handle_mouse_pos(nil, mp.get_property_native('mouse-pos')) end)},
>  }, 'mbtn_left', 'force')
>  mp.set_key_bindings({
>  	{'mbtn_left_dbl', 'ignore'},
>  }, 'mbtn_left_dbl', 'force')
>  mp.set_key_bindings({
>  	{'mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
> +	{'ctrl+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
> +	{'shift+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
> +	{'alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
> +	{'ctrl+alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
> +	{'shift+alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
> +	{'shift+ctrl+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
> +	{'shift+ctrl+alt+mbtn_right', cursor:create_handler('secondary_up'), cursor:create_handler('secondary_down')},
>  }, 'mbtn_right', 'force')
>  mp.set_key_bindings({
>  	{'wheel_up', cursor:create_handler('wheel_up')},
> +	{'ctrl+wheel_up', cursor:create_handler('wheel_up')},
> +	{'shift+wheel_up', cursor:create_handler('wheel_up')},
> +	{'alt+wheel_up', cursor:create_handler('wheel_up')},
> +	{'ctrl+alt+wheel_up', cursor:create_handler('wheel_up')},
> +	{'shift+alt+wheel_up', cursor:create_handler('wheel_up')},
> +	{'shift+ctrl+wheel_up', cursor:create_handler('wheel_up')},
> +	{'shift+ctrl+alt+wheel_up', cursor:create_handler('wheel_up')},
>  	{'wheel_down', cursor:create_handler('wheel_down')},
> +	{'ctrl+wheel_down', cursor:create_handler('wheel_down')},
> +	{'shift+wheel_down', cursor:create_handler('wheel_down')},
> +	{'alt+wheel_down', cursor:create_handler('wheel_down')},
> +	{'ctrl+alt+wheel_down', cursor:create_handler('wheel_down')},
> +	{'shift+alt+wheel_down', cursor:create_handler('wheel_down')},
> +	{'shift+ctrl+wheel_down', cursor:create_handler('wheel_down')},
> +	{'shift+ctrl+alt+wheel_down', cursor:create_handler('wheel_down')},
>  }, 'wheel', 'force')
>  
>  return cursor
> ```

Thank you very much!!

**Comment by tomasklaen** [comment]
So now you'll be patching every app you use instead of fixing the source of the issue? :)

Besides `ctrl+click` is a different action than `click`. It'd be wrong to ignore modifiers here.

But, godspeed to you.

**Comment by AziRizvi** [comment]
> So now you'll be patching every app you use instead of fixing the source of the issue? :)
> 
> Besides `ctrl+click` is a different action than `click`. It'd be wrong to ignore modifiers here.
> 
> But, godspeed to you.

As I explained it above, It's a bug in the program natively.. there is no solution, everyone writes their own solution to deal with it, mine is where it constantly checks if a modifier key is held and frees it up, and it checks every 4.5 seconds. Sometimes when a key has not been "unstuck" because 4.5 seconds are not up, I need to use the control buttons, so this workaround is just for that.
