### ISSUE TITLE
Warning This Package zip file contains a virus!!!!!

### ISSUE THREAD

**Issue by Vern2** [tomasklaen/uosc#806]
![Screenshot (38)](https://github.com/tomasklaen/uosc/assets/137419028/ebfbe1a4-813c-4f2d-95ea-e28397385f67)

**Comment by po5** [comment]
You can look through the ziggy code and build it yourself: https://github.com/tomasklaen/uosc#setup

**Comment by Vern2** [comment]
Noticed a comment about a false positive, but windows not only detected it, but quarantined it.  So for now I'm not taking a chance.

**Comment by po5** [comment]
Feel free to clone the repo, your antivirus will delete ziggy binaries and uosc will still work, only with some features being degraded.

**Comment by tomasklaen** [comment]
As we already [describe in readme faq](https://github.com/tomasklaen/uosc#why-is-the-release-reported-as-malicious-by-some-antiviruses), the binary tool we use to handle things we can't from mpv's lua scripting environemnt (subtitle downloading, pasting from clipboard) is written in go, and go binaries are packaged in a way that triggers false positives in some antiviruses (https://go.dev/doc/faq#virus).

I'll probably rewrite it in something else some time. Sorry for the inconvenience.

You can always examine the source, and build it yourself by running:

```
tools/build ziggy
```

_You need go installed._
