### ISSUE TITLE
[Question] How to use disable-elements in inputs.conf

### ISSUE THREAD

**Issue by Br31zh** [tomasklaen/uosc#808]
Hello,

Another case for the #592 and #467: watching loops with `--loop-file` make the buffering indicator flashing at the start of the loop. So I disabled it totally, I tried to add keybinds to toggle it, but if `script-message-to 'uosc' 'disable-elements' 'user' ''` do reenable it, `script-message-to 'uosc' 'disable-elements' 'user' 'buffering_indicator'` don’t seems to work in the inputs.conf

If anyone have an idea about why, that would help me a lot (I like the idea of having the indicator on network videos but removing it when watching loops). At worst I'd disable it by default, but I'd rather do the opposite (I watch less loops than network videos).

Thanks.

**Comment by christoph-heinrich** [comment]
Turns out there was a bug that prevented this from working. I've made a PR to fix it.

**Comment by christoph-heinrich** [comment]
> Turns out there was a bug that prevented this from working with this specific element. I've made a PR to fix it.
