### ISSUE TITLE
How to make the timeline look similar to native osc.lua?

### ISSUE THREAD

**Issue by AziRizvi** [tomasklaen/uosc#815]
I want to shift to UOSC completely and discard the native osc.lua but I need help and answers about a few things.

Q1) In the native OSC.lua we have the ability to add/change/display all kinds of additional information above the timeline using the title= property in osc.conf, I use it to display the total file duration, filename and the media-title, is there a way to achieve similar functionality in UOSC's timeline and have that information displayed above it in a way similar to osc.lua?

I'm attaching a picture and highlighting the section in a red box for ease of understanding.
![mpv_hoyneNxIFt](https://github.com/tomasklaen/uosc/assets/129892077/643e6fda-be44-4ca3-8c48-3b6903810c47)

Q2) Is there a way to have the video fit above the timeline like we can in osc.lua? In it we do it using boxvideo=yes. Currently the UOSC timeline overlays on top of the video, I want to have it always be displayed and fit the video above it.

Q3) Can I change the colour of the timeline? The background and the foreground? As well as the colour of the timecodes?

Q4) How to hide the UOSC logo and the text "Drop files or urls to play here" when MPV is launched?

**Comment by christoph-heinrich** [comment]
Look at https://github.com/tomasklaen/uosc/blob/main/src/uosc.conf and then come back with any questions that aren't answered in there :wink:

**Comment by christoph-heinrich** [comment]
> I re-read the conf file again just now and I saw that I had missed the colour section, my bad, but other than that, I didn't find anything about the rest of the things that I asked...

Oh really?
> information above the timeline using the title= property

It's in the top bar instead of above the timeline, but there are two texts you can configure like the `title=` in vanilla osc.
https://github.com/tomasklaen/uosc/blob/96b57b259ee6ca547564c20745531804deff0f0d/src/uosc.conf#L113-L117

> How to hide the UOSC logo

https://github.com/tomasklaen/uosc/blob/96b57b259ee6ca547564c20745531804deff0f0d/src/uosc.conf#L230

> Is there a way to have the video fit above the timeline like we can in osc.lua?

You mean the `boxvideo` option of osc.lua? That doesn't exist in uosc, but I think you can replicate that with `timeline_persistency=windowed,fullscreen` and a conditional profile in your mpv.conf that sets `video-margin-ratio-bottom` to the ratio of the `osd-height` property and the configured `timeline_size`.

> I just tried the colours option out and changing the foreground color changes the colour of the timline and the control buttons, any way to separate the colours the two?

There is not. There was a [PR](https://github.com/tomasklaen/uosc/pull/762) for that, but we thought that would make the configuration too complicated.

**Comment by AziRizvi** [comment]
> > I re-read the conf file again just now and I saw that I had missed the colour section, my bad, but other than that, I didn't find anything about the rest of the things that I asked...
> 
> Oh really?
> 
> > information above the timeline using the title= property
> 
> It's in the top bar instead of above the timeline, but there are two texts you can configure like the `title=` in vanilla osc.
> 
> https://github.com/tomasklaen/uosc/blob/96b57b259ee6ca547564c20745531804deff0f0d/src/uosc.conf#L113-L117
> 
> > How to hide the UOSC logo
> 
> https://github.com/tomasklaen/uosc/blob/96b57b259ee6ca547564c20745531804deff0f0d/src/uosc.conf#L230
> 
> > Is there a way to have the video fit above the timeline like we can in osc.lua?
> 
> You mean the `boxvideo` option of osc.lua? That doesn't exist in uosc, but I think you can replicate that with `timeline_persistency=windowed,fullscreen` and a conditional profile in your mpv.conf that sets `video-margin-ratio-bottom` to the ratio of the `osd-height` property and the configured `timeline_size`.
> 
> > I just tried the colours option out and changing the foreground color changes the colour of the timline and the control buttons, any way to separate the colours the two?
> 
> There is not. There was a [PR](https://github.com/tomasklaen/uosc/pull/762) for that, but we thought that would make the configuration too complicated.

I thought the idle_indicator was for something else so I was looking for something like logo/osd.
Yes, I meant the boxvideo option, in vanilla osc we do it with boxvideo=yes.
I tried with your workaround solution, I had my timeline size set to 25, and in a profile I set video-margin-ratio-bottom=0.044 and that worked nicely.

It's a bummer that colour customisability is not supported, I think many people would've appreciated this feature.
Thanks for your help!
