### ISSUE TITLE
show-santa-logo

### ISSUE THREAD

**Issue by candrapersada** [tomasklaen/uosc#817]
how to show-santa-logo
![image](https://github.com/tomasklaen/uosc/assets/36833664/157d2555-55a5-4937-a3ca-367e04054b8b)

**Comment by hooke007** [comment]
There is no santa logo in this script.

**Comment by christoph-heinrich** [comment]
You can use https://github.com/christoph-heinrich/sosc together with `disable_elements=idle_indicator` in uosc.conf to get the default idle indicator back, which has the santa hat in december.
