### ISSUE TITLE
interface freeze

### ISSUE THREAD

**Issue by zaeboba** [tomasklaen/uosc#818]
strange shell behavior that works every once in a while (the one in the video is a 100% bug, the rest I can't catch).
if you open via a youtube link, the interface (bottom!) may not load (I use the plugin "copy-paste-url" but I doubt it's the problem) out of 10 launches 2 bugs.
When the player is empty and the menu is opened - 80% there's a chance that the interface will freeze

https://github.com/tomasklaen/uosc/assets/57330346/9863b768-b26f-4b8f-9695-9b5bb800cc41

https://github.com/tomasklaen/uosc/assets/57330346/d9dbbb16-419a-43c3-b1fc-0007db62156c

version 5.1.1

**Comment by hooke007** [comment]
Log is always better than description.

**Comment by christoph-heinrich** [comment]
In your second video when you fullscreen it looks like there are two interfaces on top of each other. I think you have an old and a new version of uosc installed at the same time. The folder structure has changed, so the files don't overwrite each other when installing the new one. Please remove all uosc related files from your scripts directory and reinstall according to the readme. (removing `uosc.lua` and `uosc_shared` is probably enough, but just to make sure it would be better to remove it completely and reinstall)

**Comment by zaeboba** [comment]
> [--журнальный файл ](https://mpv.io/manual/master/#options-log-file)

I probably don't understand something, I run "mpv --log-file=C:\log.txt <path_to_video_file>" but nothing is saved, okay I don't understand how it works(

> Please remove all uosc related files from your scripts directory and reinstall according to the readme.

To answer your second question, it's not a clean install, but I deleted the past files cleanly.

**Comment by zaeboba** [comment]
![изображение](https://github.com/tomasklaen/uosc/assets/57330346/72b67ff8-b650-41e5-bc78-89b0417b981e)
I did a clean install from scratch, I think it still overlaps the second interface (where did it come from?).

And while I'm here, I want to ask, is the mouse not supported anymore? I can't flip through the huge playlist and select.

**Comment by hooke007** [comment]
I cannot help without log. Use a correct dir for log-file instead (i.e. your desktop)

**Comment by zaeboba** [comment]
> Без лога помочь не смогу. Вместо этого используйте правильный каталог для файла журнала (т. е. ваш рабочий стол).

found
[log.txt](https://github.com/tomasklaen/uosc/files/13635805/log.txt)

**Comment by hooke007** [comment]
You were using multi-configdirs, removing them first.
```
[   0.008][d][global] config path: 'scripts' -> 'C:\Users\jacka\AppData\Roaming/mpv/scripts'
[   0.008][d][global] config path: 'scripts' -> 'p:/portable apps/youtube-dl/scripts'
[   0.008][d][global] config path: 'scripts' -/-> 'p:/portable apps/youtube-dl/mpv/scripts'
```

**Comment by zaeboba** [comment]
I mean this.

![изображение](https://github.com/tomasklaen/uosc/assets/57330346/299f0688-dc88-43b9-9be9-3de9096f504b)

because I didn't install the player from choco, scoop and winget.
