### ISSUE TITLE
Menu to append files to playlist

### ISSUE THREAD

**Issue by candrapersada** [tomasklaen/uosc#821]
how to create Open file in queue/playlist from Context Menu?
https://github.com/tomasklaen/uosc/blob/b36cefed888c1cd2d4e0b667cc177d781c2af987/README.md?plain=1#L428

**Comment by po5** [comment]
No such thing. Would need `loadfile <file> append`
https://github.com/tomasklaen/uosc/blob/b36cefed888c1cd2d4e0b667cc177d781c2af987/src/uosc/lib/menus.lua#L538

**Comment by tomasklaen** [comment]
There is currently no menu to append files to playlist. But I wouldn't mind adding it when I have some time.

**Comment by candrapersada** [comment]
and Menu to append history to playlist

**Comment by christoph-heinrich** [comment]
> and Menu to append history to playlist

uosc doesn't keep track of a history, but [memo](https://github.com/po5/memo) is a great script for that with good uosc integration.

**Comment by po5** [comment]
Sadly we probably won't have similar functionality in scripts like memo since it'd conflict with the palette menu's submit binding. Interest in buttons has been shown in #475.

**Comment by candrapersada** [comment]
And Add files to playlist from clipboard

**Comment by christoph-heinrich** [comment]
> And Add files to playlist from clipboard

There are clipboard scripts, no need to add this to uosc.

**Comment by candrapersada** [comment]
how to create clipboard to Context Menu?

**Comment by hooke007** [comment]
Isn't it a script-binding command in your input.conf?
