### ISSUE TITLE
Can I remove the timeline stripes pattern?

### ISSUE THREAD

**Issue by leocacom** [tomasklaen/uosc#824]
Hello and thank you for this wonderful script! I love it ♥

Here is my problem: there are stripes in the timeline background which makes my screen flickering. I looked it up on and it's a LCD technology limitation of my screen apparently. Nothing I can do except avoiding this kind of pattern.

So how could I remove it? I took a look at the `Timeline:render` function in `Timeline.lua` but I can't pinpoint what should I edit precisely.

Thank you!
Léo

![pattern](https://github.com/tomasklaen/uosc/assets/5097877/c67e3ca1-bd86-44d2-abfd-c73f984ec4d2)

**Comment by christoph-heinrich** [comment]
There is an option for this `timeline_cache=no`

**Comment by leocacom** [comment]
Yes! But it removes all cache indicators, I'd prefer to keep those and just tweak the color or opacity!

**Comment by christoph-heinrich** [comment]
In Timeline:render() is a code block with a comment `uncached ranges`, that is what deals with those and it contains a check for the aforementioned option. Change the code in that if to change what they look like.

**Comment by leocacom** [comment]
Alright! Thank you, here what I did for those wondering:

```
			if options.timeline_cache then
				local ax = range[1] < 0.5 and bax or math.floor(t2x(range[1]))
				local bx = range[2] > state.duration - 0.5 and bbx or math.ceil(t2x(range[2]))
				opts.color, opts.opacity, opts.anchor_x = 'ffffff', 0.4 - (0.2 * visibility), bax
				-- ass:texture(ax, fay, bx, fby, texture_char, opts)
				-- opts.color, opts.opacity, opts.anchor_x = '000000', 0.6 - (0.2 * visibility), bax + offset
				-- ass:texture(ax, fay, bx, fby, texture_char, opts)

				ass:rect(ax, fay, bx, fby, {size = opts.size, color = opts.color, opacity = opts.opacity}) -- avoid screen flickering
			end

```

I just replaced the texture draw by a rect draw using the options from the stripes.

Thank you again!
