### ISSUE TITLE
Don't show "audio icon"?

### ISSUE THREAD

**Issue by defaultxr** [tomasklaen/uosc#825]
When playing audio files, is there some way to make the indicator in the center of the screen not show up at all?

![2023-12-31-220322_2880x1620](https://github.com/tomasklaen/uosc/assets/601567/85b9484c-7704-47f7-99fe-a6450237cd56)

The thing that is 5 lines in the middle. How can I get rid of that?

Apologies if I missed this information somewhere. I didn't see anything in the config file that looked relevant, nor when I checked over the issues/PRs.

**Comment by christoph-heinrich** [comment]
`disable_elements=audio_indicator`
