### ISSUE TITLE
Is it possible to give loop playlist three options ?

### ISSUE THREAD

**Issue by Yunuuuu** [tomasklaen/uosc#829]
Is it possible to give loop playlist three options ?
1. no
2. 1
3. Inf

**Comment by Yunuuuu** [comment]
Currently, I find only two option (no or inf) can supported

**Comment by Yunuuuu** [comment]
I have try following config but cannot work
```conf
cycle:repeat_one_on:loop-playlist:1=repeat_one_on/no=repeat/inf=repeat_on?Loop playlist
```

**Comment by Yunuuuu** [comment]
The full config for `controls`, only support two option, I cannot use three option
```
controls=menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality,gap,space,speed,space,shuffle,cycle:repeat:loop-playlist:1=repeat_one_on/inf=repeat_on!?Loop playlist,loop-file,gap,prev,items,next,gap,fullscreen
```

**Comment by tomasklaen** [comment]
Everything is working as expected. From the documentation:

```
no is the same as 1 and disables looping
```

So setting `loop-playlist` to `1` and `no` both result in `no`.

**Comment by Yunuuuu** [comment]
This is not same thing when our playlist has more than 1 items, if we set it into no, mpv will just play the current video, won’t play the second video, but for 1, mpv will play the whole playlist but will only play once

**Comment by Yunuuuu** [comment]
![IMG_0576](https://github.com/tomasklaen/uosc/assets/19575010/3acd5280-ff5b-4ec6-b413-87066c0528e7)

**Comment by tomasklaen** [comment]
> This is not same thing when our playlist has more than 1 items

You seem to misunderstand how `loop-playlist` works. Or at least your description doesn't match the documentation and implementation in mpv.

All we do is set `loop-playlist` to what you described in the control declaration. So after `inf`, we cycle it to `1`, but mpv casts it into `no` every time, which (correctly) flips the button into `no` state.

Just try opening the console (backtick \` button by default), and typing `loop-playlist 1`, and see it cast to `no` regardless of how many files are in the playlist. `loop-playlist 2` works as expected.

**Comment by Yunuuuu** [comment]
THanks for your patient explain. I have checked it, with loop-playlist = 1, the osd print the loop: no, but the behaviour are different, for loop-playlist = 1, prev or next can work as expected in uosc, but for loop-playlist = 0, we cannot use prev or next.

The osd message was not wrong, 1 loop of playlist means no loop

**Comment by Yunuuuu** [comment]
It's easily to check it, download a simple video, https://file-examples.com/index.php/sample-video-files/sample-mp4-files/, just copy the same video so we can have more than 1 videos in our playlist, and then use mpv to open them

**Comment by Yunuuuu** [comment]
Sorry, It seems wrong, I'll check again, sorry
