### ISSUE TITLE
UI not working when slang is set in mpv.conf

### ISSUE THREAD

**Issue by Lovecraft-github** [tomasklaen/uosc#830]
I have slang=en,es set in mpv.conf and when I open a file I get this error:

      uosc: script-opts/uosc.conf:163 unknown key 'refine', ignoring 
      uosc: 
      uosc: stack traceback:
      uosc:     [C]: in function 'pairs'
      uosc:     /home/user/.config/mpv/scripts/uosc/lib/std.lua:205: in function 'table_assign'
      uosc:     /home/user/.config/mpv/scripts/uosc/lib/intl.lua:63: in main chunk
      uosc:     [C]: in function 'require'
      uosc:     /home/user/.config/mpv/scripts/uosc/main.lua:130: in main chunk
      uosc:     [C]: in ?
      uosc:     [C]: in ?
      uosc: Lua error: /home/user/.config/mpv/scripts/uosc/lib/std.lua:205: bad argument #1 to 'pairs' (table expected, got string)

and the UI doesn't load

Removing the option in mpv.conf and it works again

**Comment by christoph-heinrich** [comment]
That has been fixed in https://github.com/tomasklaen/uosc/commit/210a1216feed0eeb7e780b93971fa562094f6b91, please update to the latest git version, as there hasn't been a release since then.

**Comment by tomasklaen** [comment]
To update to latest git, overwrite your `scripts/uosc` with our `src/uosc` folder. Don't delete your copy first, as that would also delete `uosc/bin` which is not part of `src/uosc`.
