### ISSUE TITLE
How to dynamically enable/disable milliseconds in the timeline?

### ISSUE THREAD

**Issue by maliayas** [tomasklaen/uosc#834]
`time_precision=2` in `uosc.conf` works fine but I want to do this on the fly via a command, so that I can set keybinding for it or use in the menu.

I've searched the issues here but could not find a solution. `script-message-to uosc set time_precision 4` is not related to this I assume, which doesn't work either.

Thanks in advance.

**Comment by christoph-heinrich** [comment]
You can update the options set in uosc.conf at runtime.
E.g. `set script-opts uosc-time_precision=4`

**Comment by Sneakpeakcss** [comment]
> You can update the options set in uosc.conf at runtime. E.g. `set script-opts uosc-time_precision=4`

This kinda gets all wonky when `destination_time` is set to `playtime-remaining` and you change `time_precision` to a value that's different than the one set in `uosc.conf`:

https://github.com/tomasklaen/uosc/assets/77424331/fd53bdcf-2c23-47d6-b0e5-a7ab0f79e09f



https://github.com/tomasklaen/uosc/assets/77424331/8b0f16e1-dc74-466b-a309-fd5fcfc4cce2



Perhaps this is another case of [this](https://github.com/tomasklaen/uosc/issues/760#issuecomment-1791873131), or something similar ?

**Comment by christoph-heinrich** [comment]
That's super weird, and I can reproduce it. wtf

**Comment by maliayas** [comment]
> You can update the options set in uosc.conf at runtime.
> E.g. `set script-opts uosc-time_precision=4`

Perfect. I created a menu option as `cycle-values script-opts uosc-time_precision=3 uosc-time_precision=0`
