### ISSUE TITLE
Feature Request: Show UI When not Playing Video

### ISSUE THREAD

**Issue by wisnoskij** [tomasklaen/uosc#845]
It can be hard to find the menu ui when the window is a blank screen and your wallpaper is black. I would suggest that after a movie has ended, or before one is loaded showing the ui is probably only a positive. Their is no use case (I can think of) to hide the ui on a blank screen.

**Comment by Sneakpeakcss** [comment]
Isn't `controls_persistency=idle` basically what you want?

**Comment by christoph-heinrich** [comment]
I think they're not actually idle, otherwise they would see the idle screen. Its probably showing the last frame of the movie, which happens to be black.

**Comment by wisnoskij** [comment]
> I think they're not actually idle, otherwise they would see the idle screen. Its probably showing the last frame of the movie, which happens to be black.

The UI shows the same behavior before loading any files.

**Comment by wisnoskij** [comment]
> Isn't `controls_persistency=idle` basically what you want?

This appears to only effect the menu before loading any files (does not work after a movie has ended), and it only works for the bottom UI elements, 90% of which have no purpose without a loaded file. I like that the menu button is visible, but I was primarily worried about the window control buttons, min, max, quit.

**Comment by wisnoskij** [comment]
`top_bar_persistency=idle`
Appears to be the equivalent for the top bar.

But again, neither work when a movie has finished. I totally agree that the controls should remain hidden when paused; Their are use cases to having a UI-less movie paused. But I dont see why everyone would not want `controls_persistency=idle` and `top_bar_persistency=idle` enabled by default and for them to work before and after a movie.

**Comment by christoph-heinrich** [comment]
Have a look at [`keep-open`](https://mpv.io/manual/master/#options-keep-open) and [`idle`](https://mpv.io/manual/master/#options-idle).

**Comment by wisnoskij** [comment]
Yes, that replicates the experience I was suggesting. Thank you. 

mpv.conf:
> keep-open=no
> idle=yes

uosc.conf:
> controls_persistency=idle
> top_bar_persistency=idle

But it looks like keep-open does defaults to no, I had keep-open=yes I think from whatever tutorial I used to figure out how to install mpv.

Do you want me to close this issue, or is their any merit in suggesting a change in uosc default behavior (specifically only the uosc behavior)?

**Comment by christoph-heinrich** [comment]
You can close this.
