### ISSUE TITLE
Disable chapters and chapter tooltips

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#849]
Is it possible to disable chapters and/or chapter tooltips?
I found `disable_elements` option in the config, but elements that can be disabled are limited.

**Comment by tomasklaen** [comment]
In your `uosc.conf`:

```
opacity=chapters=0
```

**Comment by Solarunit** [comment]
I added this at the bottom and it disabled chapters indicators on the timeline, but Chapters tooltips above time tooltips are still there

**Comment by Solarunit** [comment]
thanks for the fix! :+1:
