### ISSUE TITLE
More disable_elements items in the config

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#851]
I think it would be nice to have more items that can be disabled by `disable_elements` setting.

For example:

- speed (item in the center and above the timeline)
- chapters
- every default button in the controls panel: menu, audio, etc..

**Comment by po5** [comment]
Controls are user-defined. https://github.com/tomasklaen/uosc/blob/0d7825a4ad8ffb317ec901aafff53f8e65c12aa4/src/uosc.conf#L81

**Comment by tomasklaen** [comment]
All of these can be disabled in config. Use `opacity` and `controls` options.
