### ISSUE TITLE
Menu selection is hard to see

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#853]
A small issue with selection of items in the menus.
Menu selection is a bit hard to see, because it's grey on black.

Not sure, maybe make it more contrast, or add some color indicator on the left.

**Comment by tomasklaen** [comment]
I don't think it's hard to see at all. Could it be you have badly calibrated display with really low contrast?

**Comment by Solarunit** [comment]
I don't think my display is badly calibrated, but I have set a pretty low brightness.

The related issue is that the active item in the menu (currently activated subtitles for example) when selected/highlighted - you have no idea if it's selected, because the states are almost the same, you have to check if other items are not selected to make sure. That's a little bit confusing.


One of the solution I think could be an **indicator** like this:

![example](https://github.com/tomasklaen/uosc/assets/20891064/604b5c82-5669-41dd-8cad-c5b556a54f40)

Another solution is introducing **accent color**. 
Can we already change selection color in the config?

**Comment by tomasklaen** [comment]
![selected_item_indicator](https://github.com/tomasklaen/uosc/assets/47283320/5171cfb1-d661-4622-8928-4e14a2cad693)

**Comment by Solarunit** [comment]
this is a lot better, thanks!
