### ISSUE TITLE
Error: unknown element kind "play-pause"

### ISSUE THREAD

**Issue by TheOddler** [tomasklaen/uosc#860]
When I try to add the play-pause button to my controls I get the error `unknown element kind "play-pause"`. However, using the non-shorthand version does work.

If I use:

```
controls = "play-pause";
```

I get the error, however, this does work:

```
controls = "cycle:pause:pause:no/yes=play_arrow?";
```

Not sure why, all other shorthands do work.

**Comment by tomasklaen** [comment]
I think `play-pause` shorthand was added recently, so I guess this is also due to you running running on old uosc version, just like the other issue.

**Comment by TheOddler** [comment]
Yea, you're right. Thank you for your help!

Nixpkgs stable has version 4.7 at the moment, unstable 5.1.1, so updating works. Thanks!
