### ISSUE TITLE
Video title appears for a second on video playback

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#862]
Video title (and close/minimize buttons) appears for a second when you start playing the video. It feels a little bit distracting. 
mpv is set to start in fullscreen mode.

Not sure maybe it's a bug. 

PS: I know I can disable video-title and buttons from the uosc config.

**Comment by hooke007** [comment]
It's a feature.
https://github.com/tomasklaen/uosc/commit/32cc283397dd99a24fbf9e28f6221ea25a2b522c

**Comment by tomasklaen** [comment]
Remove `video` and `audio` from config for this option:

```
top_bar_flash_on=video,audio
```

**Comment by Solarunit** [comment]
I tried 
`top_bar_flash_on=`

and comment it all:
`#top_bar_flash_on=`

No effect, it keep show me Title and buttons

**Comment by hooke007** [comment]
cannot reproduce here.

**Comment by Solarunit** [comment]
when launching mpv in fuulscreen, mpv.conf: `fullscreen=yes`

and `top_bar_flash_on=`

Title an buttons stay visible forever until you move the cursor.


`top_bar_flash_on=` works when launching mpv in window mode

**Comment by hooke007** [comment]
@tomasklaen Sth was broken.
I edited the script:
```
    top_bar_flash_on = '',
```
And set  `script-opts-append = top_bar_flash_on=video,audio`

The option doesn't work.

**Comment by hooke007** [comment]
I messed up sth. It works here.

**Comment by tomasklaen** [comment]
Just tested it and `top_bar_flash_on=` works as expected (no flashing on new files).

> when launching mpv in fullscreen ...

When launching mpv, and maybe also when switching to fullscreen, in some desktop environments mpv reports cursor in top left corner. Or maybe the cursor was somewhere around new title proximity already. uosc then just sets the title bar opacity based on its proximity to the current reported cursor position.

I suggest to bind `toggle-ui` command to some key (I have it on `tab`) and tap it twice when you want to hide the UI when something like this happens.

**Comment by tomasklaen** [comment]
> I tested it again and the cursor stays at the same position

Yes, the cursor position doesn't change, but I assume desktop environment tells mpv, and then mpv tells uosc that it's at `0,0`. This is almost certainly what's going on here.

You can debug it yourself to make sure. Add:

```diff
diff --git a/src/uosc/lib/cursor.lua b/src/uosc/lib/cursor.lua
index 0bd3e02..0f32a81 100644
--- a/src/uosc/lib/cursor.lua
+++ b/src/uosc/lib/cursor.lua
@@ -272,6 +272,7 @@ end
 ---@param x integer
 ---@param y integer
 function cursor:move(x, y)
+	print(utils.to_string(x), utils.to_string(y))
 	local old_x, old_y = self.x, self.y
 
 	-- mpv reports initial mouse position on linux as (0, 0), which always
```

and check in terminal/console what last cursor position is when titlebar is visible.

We already have a mechanism to detect this false `0,0` on mpv startup and translate it to `infinity,infinity`, but I guess it's not working in your case.
