### ISSUE TITLE
Timeline color option

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#864]
We already have colors for some chapters on the Timeline (blue and red)

![uosc-timeline-color](https://github.com/tomasklaen/uosc/assets/20891064/611ae0a8-0f45-470a-b3f2-482dce48f22e)

I think it would be nice to have configurable color for

- the whole Timeline.
- cache area (and text)
- time left text
- time tooltips text

**Comment by tomasklaen** [comment]
Extending color customization beyond what is currently available was determined in #762 to be net negative for majority of people.

Most are fine with current options, and extending it to allow what you want would mean bloating the config file for everyone else, and more things to maintain.

So if you want to turn your uosc into a rainbow, you'll need to maintain your own fork.

**Comment by Solarunit** [comment]
>Extending color customization beyond what is currently available was determined in https://github.com/tomasklaen/uosc/pull/762 to be net negative for majority of people.

It was already considered, I see. I was late to the party.

>So if you want to turn your uosc into a rainbow, you'll need to maintain your own fork.

Not rainbow, but I wanted to customize mostly Timeline, and add some color to cache loading thing to make it more distinct.

**Comment by Mark-Joy** [comment]
I second this feature, please.
