### ISSUE TITLE
Pattern options for the Timeline

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#865]
I think such patterns on the Timeline looks very cool.

![uosc-timeline-pattern](https://github.com/tomasklaen/uosc/assets/20891064/a0dd8f71-f67b-47a9-8cf3-756b2611f47c)

My idea is to add more different patterns for the Timeline that can be selected from the config.

Such patterns could be applied to:
- the whole timeline
- loading cache area

**Comment by tomasklaen** [comment]
No, this will also be a wontfix. I don't see a value here. It'd just add more options to config and noise to the timeline that is not meaningful in any way. Two different patters next to each other would also optically clash and just look bad.

If you want to customize uosc like this, you'll have to do it in your fork.

**Comment by Solarunit** [comment]
>Two different patters next to each other would also optically clash and just look bad.

Probably, my original idea was apply some pattern for the whole timeline to make it look more visually interesting.
