### ISSUE TITLE
`scale` has no effect on tiling window managers

### ISSUE THREAD

**Issue by musjj** [tomasklaen/uosc#868]
On tiling window manager (at least on Hyprland), `scale` has no effect, even when mpv is not fullscreened. Only `scale_fullscreen` gets applied, so it seems that uosc thinks that the mpv window is always fullscreened, somehow.

**Comment by tomasklaen** [comment]
Afaik the way these window managers work is making mpv think it's fullscreen. It then tells us we're in fullscreen, so we apply `scale_fullscreen`.

Nothing we can do about it our side.
