### ISSUE TITLE
Please add support for mpv-user-input

### ISSUE THREAD

**Issue by parasiteoflife** [tomasklaen/uosc#876]
I'm trying to use a plugin for creating chapters that uses mpv-user-input for custom chapter titles but the console prompt is not shown when using uosc, can support for this be added?

Thank you

**Comment by christoph-heinrich** [comment]
https://mpv.io/manual/master/#mp-input-functions

**Comment by dyphire** [comment]
The feature you mentioned has already been implemented in other scripts. Please refer to the implementation methods in the relevant scripts: [chapter-list.lua](https://github.com/dyphire/mpv-scripts/blob/main/chapter-list.lua) and [chapter-make-read.lua](https://github.com/dyphire/mpv-scripts/blob/main/chapter-make-read.lua).
