### ISSUE TITLE
option to disable file autoplay

### ISSUE THREAD

**Issue by wooshaq** [tomasklaen/uosc#877]
I just started using mpv, your config is great but i would like to disable playlisting all the files in folder when i open only one file. How can i turn it off? Lease note that im new to lua. I tried looking for something logical to cut from the config but i failed.

**Comment by christoph-heinrich** [comment]
sounds like you're using autoload.lua

**Comment by wooshaq** [comment]
I found and option innmainnsettingbto load folder, solved
