### ISSUE TITLE
Option to place timeline_cache on the controls bar

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#885]
I wish there was an option to put timeline_cache to the controls bar.
IIRC it's the default position in stock UI.

**Comment by christoph-heinrich** [comment]
Can you draw a rough mock up or something of what you're imagining? I have a hard time picturing what that would be like.

**Comment by Solarunit** [comment]
Sure

**Comment by Solarunit** [comment]
Something similar to stock UI:

![mpv-cache](https://github.com/tomasklaen/uosc/assets/20891064/ef08096c-33e2-427e-98cb-c7635fb35320)

it could be with `Cache:` text or without it.

**Comment by christoph-heinrich** [comment]
Oh that's what you mean.

IDK about showing it in the controls bar, it's not a great fit there with all the configurable buttons and such, but let's see what others have to say about that.

**Comment by tomasklaen** [comment]
If my suggestion in #886 ever lands, you should be able to just disable timeline cache in timeline, and put something like `demuxer-cache-time` in the mentioned meta element's template.

Other than that, I don't see a reason for different cache position. I'm fine with current one, and can't imagine a good alternative. Above controls bar is not an option, and content of controls bar is completely in hands of users, so it can't be affected by timeline options.

**Comment by Solarunit** [comment]
I think the current implementation is not bad and i kinda like that it moves along with the progress bar, this is cool.

But I see some cons:

1.  It's not static, so you can't detect it immediately like static one in stock UI.
2.  It interferes a bit with start and end timers.

**Comment by tomasklaen** [comment]
I'll close this in favor of #886.
