### ISSUE TITLE
Friends, hello! How to disable the file browsing function.

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#890]
Hello friends! How to disable the file browsing function (Quick directory).

Hello friends! How to disable the file browsing function (Quick directory), because this function is very difficult to use, it cannot pop up the dialog box like other players for users to select files, so I need to disable it😜

Thank you for providing a very excellent extension for MPV.🍦🎉👏👍

Windows 10

**Comment by tomasklaen** [comment]
I don't see a point or what it even means to disable something you have to explicitly open to use.

Just don't use it.
