### ISSUE TITLE
Full screen exit and dragging weird behavior 

### ISSUE THREAD

**Issue by nikolaevaxenov** [tomasklaen/uosc#891]
Hi! After I open and close full screen mode the window changes it's size to the vertical maximum using whole screen size, not the one I resized it to or the one that was when I opened the file for the first time. Also, I use Windows and I can't stick mpv window to side, it keeps reappearing on the center of the screen.
[Video](https://youtu.be/_ytqs21YykA)
Aside from that uosc works perfectly I really like it, so I want to resolve this annoying issue.

**Comment by tomasklaen** [comment]
uosc just renders UI. We don't manage window size or position, that's mpv and its config.
