### ISSUE TITLE
Follow theme's preference for the window controls location (left vs right)

### ISSUE THREAD

**Issue by nick-s-b** [tomasklaen/uosc#892]
Hi all,

I started using `uosc` and absolutely love it so far but I always get tripped-up by windows controls. I use Linux and all my window control buttons (minimize/max/close) are on the top left side of the window. `uosc` has them on the top right at all times. Default `mpv` OSD detects the preference automatically and places it on the left or right. I have `border=no` set.

Any way to move them to the left? 

Thanks so much!

**Comment by christoph-heinrich** [comment]
The default osc has a config `windowcontrols_alignment=right|left`, so no automatic detection.

You mean like that?
![image](https://github.com/tomasklaen/uosc/assets/8932183/5c301d82-2df4-419f-91f6-9ffb2bf1eaa7)

**Comment by nick-s-b** [comment]
@christoph-heinrich yes, like that! In my mpv.conf I don't have anything about the alignment of window controls yet mpv somehow follows whatever is set in my WM. Default mpv OSD had them on left when my theme had them on left.

If I try to do it manually, I get an error:
````
$ mpv --version
**Error parsing option windowcontrols_alignment (option not found)**
~/.config/mpv/mpv.conf:9: setting option windowcontrols_alignment='left' failed.
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 18 2024 06:31:17
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
````
Really weird.

**Comment by christoph-heinrich** [comment]
> If I try to do it manually, I get an error:

That option needs to go into `~~/script-opts/osc.conf`

> follows whatever is set in my WM

It [gets the value of the option](https://github.com/mpv-player/mpv/blob/b68c742b271f6e36d9aedd9fa906a692d267dcd2/player/lua/osc.lua#L450) and then [checks if it's left](https://github.com/mpv-player/mpv/blob/b68c742b271f6e36d9aedd9fa906a692d267dcd2/player/lua/osc.lua#L1073), so idk what magic is makes this work for you.

**Comment by nick-s-b** [comment]
I really don't understand why it's not working.. I've emptied all conf files and folders of all other scripts.

````
$ cat mpv.conf
osd-bar=no
border=no
$ cat script-opts/osc.conf
windowcontrols_alignment=left
$ ls scripts/
uosc
$ head scripts/uosc/main.lua
--[[ uosc | https://github.com/tomasklaen/uosc ]]
local uosc_version = '5.2.0'
````
Yet it's still on the right:
![Screenshot at 2024-04-30 17-42-22-fs8](https://github.com/tomasklaen/uosc/assets/7957590/23dcb021-81c3-4011-a62b-104846124e15)

I'm stumped.

**Comment by christoph-heinrich** [comment]
To get what's in my screenshot you need https://github.com/tomasklaen/uosc/pull/894 and `top_bar_controls=left` in your `uosc.conf`.

`windowcontrols_alignment` is for the default osc :wink:

**Comment by nick-s-b** [comment]
Got it! Thank you so much!

**Comment by nick-s-b** [comment]
@christoph-heinrich  Another quick question if you don't mind.. is there a way to alight the title text to the left side right after the window widgets? Currently, if I set alignment to left, window widgets are on the left but the title is way on the right. Default mpv OSC aligns it to the left... right after the widgets. The current arrangement might work with right-to-left languages but it's weird with L-to-R langs. Thanks!

**Comment by christoph-heinrich** [comment]
@nick-s-b That's the way it used to be (see screenshot in this issue), but that looks bad so I changed it yesterday so that title is aligned to the right (see screenshot in the PR).

If you don't use the last commit to that PR, you'll have left alignment again.
