### ISSUE TITLE
Hello, friend! Playing 1080P Full HD video stutters and is not smooth, is there any solution?

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#895]
Hello, friend! Playing 1080P Full HD video stutters and is not smooth, is there any solution?

**PC environment:**

1. Windows 10 19044
2. CPU i5 3210
3. Memory 8G
4. Graphics card:
   4.1. Intel Integrated Graphics 4000
   4.2. NVIDIA: GT610
5. Western Digital mechanical hard drive 5400 rpm
6. mpv [0.38](https://sourceforge.net/projects/mpv-player-windows/files/)
7. uosc [5.2.0](https://github.com/tomasklaen/uosc/releases/tag/5.2.0)

If uosc is disabled, then playback of 1080P Full HD videos is very smooth and does not stutter.

**Comment by tomasklaen** [comment]
Does it stutter when the whole uosc UI is visible, or when uosc is hidden?

Either way, we already do everything we can to be as performant as possible in this environment. Not much else that can be done here.

Also, you seem to be the only one with this issues. I have a pretty old laptop for testing which is slower than your setup, and I haven't noticed any stuttering there yet.

**Comment by zhouxinghong** [comment]
It is during video playback that the video screen often appears to be lagging and not smooth.

**Comment by zhouxinghong** [comment]
I am experiencing the lagging and lack of smoothness when playing 1080P streams.

It seems that the problem would be improved if just the core functionality of Uosc is kept or turned on?

**Comment by tomasklaen** [comment]
> It seems that the problem would be improved if just the core functionality of Uosc is kept or turned on?

uosc doesn't render anything when UI is not visible. It literally just sends an empty string to libass.

You can try using `disable_elements` and enable one element at a time to maybe identify the culprit.

**Comment by zhouxinghong** [comment]
I will follow this method you provided and try to disable each element one by one to see if that solves the problem.

If there is precise control over whether each element is enabled or not in the UOSC, then I think it will be easier to get to the root cause of this problem.

**Comment by zhouxinghong** [comment]
I'll continue to report back here if I find the problem, so please keep this issue open.

**Comment by Solarunit** [comment]
All 1080P Full HD videos stutter? Local and remote streams? What about youtube 1080 streams?

**Comment by zhouxinghong** [comment]
`All 1080P Full HD videos stutter? Local and remote streams? What about youtube 1080 videos?`
I haven't noticed any lagging issues when playing Youtube 1080P videos yet.

**Comment by tomasklaen** [comment]
So I have no idea how could uosc be causing this for you and only for you, and all the reports thus far make no sense (stuttering only when uosc doesn't render anything?).

I'll close this until there are some steps to reproduce, and someone reproduces it.
