### ISSUE TITLE
[Question] Hello friend! May I ask how this is set up and what are its units?

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#897]
[Question] Hello friend! May I ask how this is set up and what are its units?
```
# Available: paused, audio, image, video, idle, windowed, fullscreen
timeline_persistency=
```
Please give an example? Thanks a lot!
My setting: 
`timeline_persistency=5000` but it doesn't work!

**Comment by FichteFoll** [comment]
`timeline_persistency` specifies under which states (available states are listed above) the timeline should be visible. You might be looking for `flash_duration`:

https://github.com/tomasklaen/uosc/blob/56b62bb0b25d01a5500f3a6c5abef749f24cb4f1/src/uosc.conf#L170-L171

**Comment by zhouxinghong** [comment]
Thank you!
