### ISSUE TITLE
Troblue searching for Brazilian Portuguese subtitles

### ISSUE THREAD

**Issue by Blasg2** [tomasklaen/uosc#898]
The subtitles exist on opensubtitles, and i tried adding some variations on uosc languages config but i'm probably writing something wrong. I tried with "pt-br" just "br". 
How would the full line of the code be?

ps: i still want to keep searching in en, but also for brazilian portuguese.
ps2: idk if this is possible but it would be cool to implement a search on mpv and right click to go to the opensubtitles link for it, so the 5 subs per day limit is a little easier to deal with.

**Comment by tomasklaen** [comment]
We just use opensubtitles' `v1/subtitles` API endpoint with `query`, `hash`, and `languages` parameters.

There isn't an easy way for you to get the file hash, but you can try `query` + `languages` search yourself here: https://opensubtitles.stoplight.io/docs/opensubtitles-api/a172317bd5ccc-search-for-subtitles

And according to [their language code docs](https://opensubtitles.stoplight.io/docs/opensubtitles-api/1de776d20e873-languages), I think the code for portuguese should be `pt-pt`.

Opening opensubtitles page should be doable, once we have menu item buttons. Dunno when I'll get to it :(

**Comment by tomasklaen** [comment]
Commit above adds the aforementioned "Open in browser" button.

Due to no reply and none else complaining, I'll close this for now. If someone provides an API query to opensubtitles that returns results but uosc returns nothing so I can look into it, I'll reopen.
