### ISSUE TITLE
[REQUEST] `Command Palette` enhancement to display unbinded commands

### ISSUE THREAD

**Issue by Sneakpeakcss** [tomasklaen/uosc#901]
Currently it doesn't display commands that are unbinded by either `uosc` (`#`) or `mpv.net / mpv-menu-plugin` (`_`) syntax.

Technically in case of `_` it actually displays it since it's a valid key, but `input-bindings` seems to only return the very last defined keybind in `input.conf`

**Comment by tomasklaen** [comment]
Yeah in the commit that closed this I just wanted to dump everything from `input.conf` and be done with it, but after thinking about it for a bit this time I went back on this. It now displays only active keybinds, and keyless uosc or mpv-menu-plugin menu commands.

**Comment by Mark-Joy** [comment]
@tomasklaen 
1. The implementation seems to break uosc menu items with no command. They are not showing in Menu:
```
#  ignore  #! Folder title >
#    #! Title
#    #! Section > Title
#    #! ---
#    #! Section > ---
```
2. I think `ignore` is a valid command and should be showing for `active keybinds`.
I have a commit address above issues: [6b83194](https://github.com/Mark-Joy/uosc/commit/6b8319416432568ced871cf47e2745f37fc31c7a)

**Comment by dyphire** [comment]
I also noticed that the separator no longer seemed to show.

**Comment by tomasklaen** [comment]
I fixed the separator being ignored, and the syntax now also allows for ignore in separator definition (`# ignore #! ---`). I think this should be the only allowed, but don't want to break existing configs.

> I think ignore is a valid command and should be showing for active keybinds.

`ignore` is by definition a lack of a command :) I don't see a reason to have it in a list of bound commands. Why search for something that does nothing when you activate it?

**Comment by Mark-Joy** [comment]
> I don't see a reason to have it in a list of bound commands. Why search for something that does nothing when you activate it?

It's unlikely to happen but suppose the key was bound to `ignore` by some other scripts (or even accidentally bound to `ignore` in `input.conf`). Now user gets confused and has no idea why the key is not working because looking in the binding table, the `ignore` command does not shows up.

**Comment by tomasklaen** [comment]
Ignored bindings are back in the menu.
