### ISSUE TITLE
Dynamically adding menu items

### ISSUE THREAD

**Issue by Mark-Joy** [tomasklaen/uosc#905]
Is there a way to dynamically adding menu items in lua script?
Example:
```
for i =1,#mylist,1 do
  uosc.add_menu_item('#script-message-to  myscript   myfunction  args #! ItemList > Item' .. i)
end
```

**Comment by christoph-heinrich** [comment]
That's not currently possible.

Why do you need that?

**Comment by Mark-Joy** [comment]
`mpv.net` has a `Profile` menu item which list all the profiles for user to choose. I want to add it to `uosc` menu.
Another example is `Track` menu item from `mpv.net`. These 2 menu items were not automatically populated to `uosc` menu. I guess because they were created dynamically.
> Why do you need that?


So the reason is, some menu items just can't be pre-defined in input.conf.
I wonder how `uosc` populates almost all the the `mpv.net` menu items even when my `input.conf` has only one line, but that's not the point.
```MBTN_Right  script-binding uosc/menu-blurred```

I think expose the `uosc` menu parser as an api to be called in Lua script should not be too difficult.. but that just me hoping it so

**Comment by tomasklaen** [comment]
Personally I wouldn't want to traverse menu to get to some profile/track lists. That sounds like it should be its own menu accessible via shortcuts directly. User can then add a command to open this list into their menu.

And uosc already has pretty advanced menus for all track types that also support loading or even searching and downloading from web in case of subtitles.

Adding APIs to dynamically edit menu parsed from `input.conf` sounds like a can of worms I don't want to open to be honest.

**Comment by Mark-Joy** [comment]
@tomasklaen 
I have a commit dceffe9 that support dynamically adding menu items. I'd like to see it included in the next release if possible.
It can be used in other scripts like this:
```
mp.commandv('script-message-to', 'uosc', 'add-menu-item', config_menu_line)
```
Example:
```
-- binding without menu-item
mp.commandv('script-message-to', 'uosc', 'add-menu-item', 'MBTN_Left ignore')
-- add separator menu-item
mp.commandv('script-message-to', 'uosc', 'add-menu-item', '#    #! ---')
-- binding menu-item
mp.commandv('script-message-to', 'uosc', 'add-menu-item', 'ESC cycle fullscreen   #! Cycle Fullscreen')
```

**Comment by Mark-Joy** [comment]
> Even after thinking about it some more, I still don't want this API. I don't want scripts to start polluting user's menus with unsolicited items in an order user might not prefer.

The menu-items dynamically added always be under a main menu-item. That main menu-item can be ordered just fine in input.conf. Example:
```
#  #! static-menu-item1
#  #! dynamic-item
#  #! static-menu-item2
```
In script, add:
```
mp.commandv('script-message-to', 'uosc', 'add-menu-item', 'ESC cycle fullscreen   #! dynamic-item > Cycle Fullscreen')
```
The menu-item `cycle fullscreen` now come under `#  #! dynamic-item`, as if we have the below in input.conf:
```
#  #! static-menu-item1
#  #! dynamic-item > Cycle Fullscreen
#  #! static-menu-item2
```

> And if you need items that are populated dynamically based on some conditions, that should be a custom menu where you can do that already. And if it's its own menu, people can go to that directly with custom keybinds or control buttons, and don't have to traverse menu to get there.

Well, then why need the main menu at all? Every sub-menu can be bound to a key? Oh.. we just have to remember every key!
Then we can have every sub menu as control button? Oh.. the screen now is polluted by all the buttons!

With this feature added, I now can add `#@tracks` `#@profiles`   `#@stream-quality` or `#@my-custom-list` easily
With `stream-quality`, if there is a way to obtain available quality list, it can also be customized dynamically.

**Comment by tomasklaen** [comment]
The menu serves the same purpose as an app context menu of any other app. It's a jumping point to other sections/features of the app that are not used frequently enough to be a part of the visible UI.

In your example, I'd do:

```
#  script-binding my-script/open-dynamic-menu  #! My dynamic menu
```

Which would open the custom menu that can manage itself. The functionality is pretty much the same, but an order of magnitude easier on us to maintain, and no new complicated APIs for both developers and users to learn.

And if I use some menu frequently, I'd appreciate the ability to open it directly with a control bar button or a shortcut and not have to navigate submenu trees to get to it. And you get that by exposing it as a script-binding command and not a submenu of a uosc menu.
