### ISSUE TITLE
Consider providing build from source instructions and/or a Makefile

### ISSUE THREAD

**Issue by intelfx** [tomasklaen/uosc#906]
It would be nice (especially in the wake of the xz incident) if there were end-user installation instructions other than "download this binary from here".

Thanks!

**Comment by tomasklaen** [comment]
The build scripts are in `tools/`. Just run:

```bash
tools/build
```

Which in turn just runs:

```bash
go build -ldflags "-s -w" -o "$out_dir/ziggy-linux" $src
```
