### ISSUE TITLE
Recent `mpv` changes break mouse dragging functionality.

### ISSUE THREAD

**Issue by Sneakpeakcss** [tomasklaen/uosc#911]
Every part of the UI that uses mouse dragging (speed control/volumebar/menu drag scrolling) isn't working properly after [this](https://github.com/mpv-player/mpv/pull/14251) PR was merged. All of them only detect a single mouse press.

New deadzone command doesn't fix anything in this case, while `input-builtin-dragging no` keeps it working, but obviously that completely disables `mpv` window dragging.

**Comment by tomasklaen** [comment]
Looking at the comments it seems like there's another PR coming that should fix this? It'd be weird if they shipped something that breaks all UI scripts.

**Comment by zhongfly** [comment]
https://github.com/mpv-player/mpv/commit/0509e5b2edf837e1f06570374de46391d6f6fce6 should fix this?
Latest Windows build can download from https://github.com/zhongfly/mpv-winbuild/releases/tag/2024-06-05-0509e5b

**Comment by Sneakpeakcss** [comment]
Quite the timing. I wasn't even aware that default osc also had the same issue, so yea, that's back to normal.
