### ISSUE TITLE
Hide window controls by default on macOS

### ISSUE THREAD

**Issue by kidonng** [tomasklaen/uosc#913]
Windows-style window controls just looks plain weird on macOS. Hiding them by default instead of having to manually set `top_bar_controls=no` is an undisputed improvement in my opinion.

This is just a suggestion though, feel free to close if it reads too opinionated. Love uosc.

EDIT: to clarify a bit: by default on macOS with Homebrew (vanilla) mpv build, uosc window controls only show in fullscreen, in addition to the native window controls.

https://github.com/tomasklaen/uosc/assets/44045911/713586e1-ae30-4a8e-8da9-1c0196a93f89

**Comment by tomasklaen** [comment]
I don't understand. You want us to hide the window controls on mac even when they're explicitly configured (default config) to be visible? That doesn't sound like a good idea.

Your use case is why `top_bar_controls=no` exists. I don't want to add magical behaviors that try to read user's minds to determine what they want.

**Comment by hooke007** [comment]
> is an undisputed improvement in my opinion.

IMO, it's ridiculous...
