### ISSUE TITLE
Can binding such as `Ctrl + Enter` for confirming searches be customized?

### ISSUE THREAD

**Issue by Kabouik** [tomasklaen/uosc#915]
I use `mpv`/`uosc` through `ssh` and taking advantage of `mpv --terminal-input`, but it seems this fails to convey keybinds such as `Ctrl + Enter`. This is a shame because I'd need it to confirm search for the `download_subs` feature (a wonderful addition by the way; I'll soon reach the limit when binging episodes, but might be able to reset it using a proxy I guess).

I really love the new `uosc`. So many QOL additions since the old version I was using so far (`download_subtitles`, `keybinds`, *etc.*).

**Comment by tomasklaen** [comment]
No, these are not configurable. We use alt, shift, and ctrl each for something else, so there's not much else to configure it to. Also, you'd be the only person on the planet using it, and I don't like adding options with such low relevance.

But the inability to send some shortcuts sounds like a bug/issue with your environment, so I'd try to solve it there.

If anything is going to happen regarding this on uosc's side, I'd probably just want to eliminate ctrl+enter binding completely, and replace it with only enter that is aware of what is focused atm (input or item).

**Comment by Kabouik** [comment]
Tha\fnks! I don't think my environment is the cause, it seems that those bindings with modifier are not properly conveyed by `mpv --terminal-input`, even locally, and using `mpv` through `ssh` just makes me rely on terminal input.

It would be convenient if `uosc` could be entirely manipulated with the limited list of bindings that c[an work with terminal input, but I understand it's not really a `uosc`limitation in the first place. I may not know exactly what motivates the use of a modifier for confirming searches but if I understand correctly your message, that may be because `uosc` may not know what is currently focused.

**Comment by abhishekmj303** [comment]
@Kabouik I also stumbled upon this as i have `Ctrl + Enter` binding to opening terminal. As a work around I tried changing this line in this file `~/.config/mpv/scripts/uosc/elements/Menu.lua`:

https://github.com/tomasklaen/uosc/blob/9fa7220da45815855df6c6d62adf82ee7d9df5e3/src/uosc/elements/Menu.lua#L1040

I changed `ctrl+enter` to `shift+ctrl+enter`.

**Comment by tomasklaen** [comment]
With commit above, submit-able search menus are now aware of item list or search input being focused. In case search input is focused, enter will submit a search instead of activating an item. You can focus the input with arrows keys, or just start typing to change your query, which will do that automatically.
