### ISSUE TITLE
feature request: gradient timeline 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [tomasklaen/uosc#917]
please add an option for gradient timeline

**Comment by po5** [comment]
The way you do gradients in ASS is overlay a solid color on top of another, with the top layer having a really high blur value, then \clip to the area you care about. I don't think it'd look good in uosc, anyway.

**Comment by tomasklaen** [comment]
> Then , how to change it's color?

All options are documented in the default config file, link to which is also in readme, and it's also available in release downloads.
