### ISSUE TITLE
Is it possible to automate the progress bar visibility based on mouse position?

### ISSUE THREAD

**Issue by Dkzn** [tomasklaen/uosc#920]
I'm referring to the mini progress bar. I was wondering if there's a way to have it only be visible in windowed mode AND the mouse is positioned inside the window. 
So:
Windowed and mouse inside window - visible
Windowed and mouse outside window - not visible
Full screen - not visible

**Comment by tomasklaen** [comment]
No, this level of visibility control is not possible. If you want to see the progress only when hovering the window, there's not much difference between what you're asking for and hovering somewhere around the timeline to trigger its proximity visibility.

Or you can enable autohide and increase proximity distances to force all elements to be visible when cursor moves inside window and hide them after some delay.

**Comment by Dkzn** [comment]
Ok thanks. I think I'll just use toggle-progress
