### ISSUE TITLE
Items respond to hover through the menu title bar

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#937]
Items respond to hover through the menu title bar (but can't be clicked).
![image](https://github.com/user-attachments/assets/f418da05-0753-4c57-8d71-fc7ef91fb392)
Applies to the actions PR as well.
![image](https://github.com/user-attachments/assets/ff71eeee-ef6c-4c70-8a94-cca79386c9b4)

**Comment by tomasklaen** [comment]
Fixed in the actions PR now.
