### ISSUE TITLE
Automatically detect video file extensions

### ISSUE THREAD

**Issue by ahaoboy** [tomasklaen/uosc#940]
I have some video files named in the format of ```xxx.bundle```. When I use mpv+uosc to play the video, only one video will be opened. Of course, I can add the video type ```bundle``` to ```video_types```, but maybe we can support automatic detection of video file extensions.

When opening a video file, files with the same suffix can be automatically opened and displayed in the playlist
When the opened video file has no extension, add all files without extension in the same directory to the playlist

**Comment by tomasklaen** [comment]
This is too niche. I don't want to spend time adding/maintaining this. Honestly just use appropriate extensions, or add new ones to `video_types`.
