### ISSUE TITLE
UOSC's Volume OSD on the Right side of the Screen doesn't display itself whenever i press Up/Down keys. Instead i see MPV's default Volume OSD on Top-Left Screen. Can you fix it?

### ISSUE THREAD

**Issue by XSpark0** [tomasklaen/uosc#942]
I even tried to add "osd-level=0" in mpv.conf which disables MPV's default Volume OSD but UOSC's own Volume OSD still wont display itself whenever i press Up/Down keys. 
I am already using "osd-bar=no" and "border=no" in mpv.conf to better integrate with UOSC. Currently can't use "osd-level=0" since UOSC's Volume OSD doesn't display itself for 2 seconds like MPV's default Volume OSD does whenever i press Up/Down keys. 
Fixing this would allow UOSC to integrate even better.

**Comment by hooke007** [comment]
Nothing needs to fix here. You just need to learn that how input.conf should work.

**Comment by hooke007** [comment]
`no-osd add volume  1 ; script-message-to uosc flash-elements volume`

**Comment by XSpark0** [comment]
Added that line to input.conf but it didn't work. I still only see MPV's default Volume OSD showing up for 2 seconds in top-left of screen instead of UOSC's Volume OSD showing up for 2 seconds on the right side of screen when i press Up/Down keys.

**Comment by hooke007** [comment]
What you did in input.conf?

**Comment by XSpark0** [comment]
Realized my mistake. I got it working now.

input.conf:

> UP	no-osd	add	volume 5 ; script-message-to uosc flash-elements volume
> DOWN	no-osd	add	volume -5 ; script-message-to uosc flash-elements volume

Thanks @hooke007

**Comment by hooke007** [comment]
It's overthere.
https://github.com/tomasklaen/uosc/blob/main/README.md#flash-ui
