### ISSUE TITLE
How to remove audio indicator on files with no images

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#943]
![mpv-shot0324](https://github.com/user-attachments/assets/48fa4ba9-e6f6-458e-af63-4d38d2d0c33a)

The audio indicator interferes with some script such as visualizer.lua, is there any way to remove the audio indicator?

**Comment by Sneakpeakcss** [comment]
https://github.com/tomasklaen/uosc/blob/fe0d394435ad562176ae850175ebd5a083f0a6c2/src/uosc.conf#L233-L236

`audio_indicator`
