### ISSUE TITLE
Monitor problem with 21:9 scale and subtitles

### ISSUE THREAD

**Issue by Jokerss2** [tomasklaen/uosc#944]
Hello, I have a 21:9 monitor and unfortunately when running movies, TV series - starts mpv with a rectangle in the center and with frames at the bottom, top and left, right. I managed to solve this problem with the following command: –panscan=1.0. However, I prefer to watch in subtitles and they disappear when this command is applied.

Who knows, please tell me how to adjust subtitles to the scale of the monitor 21:9 and to run the content on full screen?

**Comment by hooke007** [comment]
Why do you think it's a dummy UI's feature to adjust the subtitle in this case?

**Comment by tomasklaen** [comment]
We don't control subtitles or how mpv pans the video. We just render the UI. Read mpv docs on how to configure it to do what you want it to.
