### ISSUE TITLE
Allows hiding tooltips message in the outside of new track menu or only showing them when the menu is first opened

### ISSUE THREAD

**Issue by dyphire** [tomasklaen/uosc#955]
![image](https://github.com/user-attachments/assets/dc8cca1c-f363-410a-ba35-5683eb15cef4)
Personally I don't like seeing this tooltips message all the time.

**Comment by Sneakpeakcss** [comment]
On one hand, it's nice that we now have clear descriptions of "hidden" actions in the menus (modifiers etc.), so it doesn't rely on going through the whole docummentation and remembering rarely used actions, and on the other, this one seems a bit in the face, even when the menu is rarely opened. 

This is one of those things that would look better as a `ⓘ` / `🅘` sign somewhere in the corner that can be hovered to display a tooltip. If that's currently possible to implement then i would vote for that solution.

**Comment by dyphire** [comment]
> I've tried to make it discrete so it doesn't bother anyone, so of course it bothers someone 😭.
> 
> Will you really not get used to it? Does it really bother you _that_ much? Do we really have to have an option for this little line there?

It's a bit ugly to me and reduces my interest in opening the track menu.



> On one hand, it's nice that we now have clear descriptions of "hidden" actions in the menus (modifiers etc.), so it doesn't rely on going through the whole docummentation and remembering rarely used actions, and on the other, this one seems a bit in the face, even when the menu is rarely opened.
> 
> This is one of those things that would look better as a `ⓘ` / `🅘` sign somewhere in the corner that can be hovered to display a tooltip. If that's currently possible to implement then i would vote for that solution.

This suggestion sounds good, and we're totally going to provide a hover sign for tooltips.

**Comment by tomasklaen** [comment]
Yeah that's not a bad suggestion.

**Comment by tomasklaen** [comment]
![footnote](https://github.com/user-attachments/assets/cb00ab72-a43d-4fbd-8191-6099d674ded5)

**Comment by dyphire** [comment]
> ![footnote](https://private-user-images.githubusercontent.com/47283320/363203760-cb00ab72-a43d-4fbd-8191-6099d674ded5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjc0NjQsIm5iZiI6MTcyNTAyNzE2NCwicGF0aCI6Ii80NzI4MzMyMC8zNjMyMDM3NjAtY2IwMGFiNzItYTQzZC00ZmJkLTgxOTEtNjA5OWQ2NzRkZWQ1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE0MTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNTY1ZTUyMGFiMDIwNGQyZjUyZDc3YmJiMDU0Yjk0NTIzZmE4ZjY3ZWM0M2E3ZjlmNTBlMGE2Y2U2ZTA4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqbvVis0ILYuuWmGEPs3PhM0zPw8RKP_4Y3loQFZnDw) 

LGTM.

What I'm more curious about now is why the action signs in the file menu are placed inside the menu, why it behaves differently.

**Comment by tomasklaen** [comment]
> What I'm more curious about now is why the action signs in the file menu are placed inside the menu, why it behaves differently.

I'm trying to minimize clashing of item icon/hint with actions:

- If items have no icon & no hint -> always inside. (no icon/hint to clash with/cover)
- If items **do** have an icon or hint, and there is space for them to be outside -> outside.
- If there's no space outside -> inside, even if it covers icon or hint.

**Comment by Sneakpeakcss** [comment]
Yeah, this is far better. The only nitpick i would have is that the `help`/`help_outline` icon is more 'visually shifting' than the `info`/`info_outline` :



https://github.com/user-attachments/assets/4a2b8987-1154-46cc-9070-ac078e7c336e

https://github.com/user-attachments/assets/37f41fce-848a-4772-a40f-f6fcaab4c626

Though at this scale `info` looks a bit like a semicolon, but that might be just me being blind.

**Comment by Solarunit** [comment]
I haven't tried these new features yet, but looking on screenshots/gifs, I don't like it either - any tooltips below the menu.
I would like to have option to hide it. (I never Paste anything to the mpv)

Not sure about new way to enable/disable subtitles, I need to test it first.

**Comment by Solarunit** [comment]
So, I tested latest version 5.3.1 and yes, I wish there was a way to hide that 🅘 sign and also **Activate as secondary subs** button. I do not plan to use secondary subs but I am forced to see this button every time now.

**Comment by poslat-pismo** [comment]
Please make an optoin in "disable_elements" or something to get rid of this help sign and tooltips in playlist (the arrow and trash buttons are awesome)
