### ISSUE TITLE
Problem with enable/disable subtitles and audio tracks

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#961]
In some cases you want do disable or enable subtitles for certain videos. I see a problem here because you can't simply enable the same subtitles (or audio track) that was before, the list could be huge and the last used subtitles item is not highlighted/selected in the menu.

**Comment by hooke007** [comment]
In this case, why not use mute/visible instead?

**Comment by tomasklaen** [comment]
I don't think I follow the issue here. You want to disable subtitles, but than have next video in queue load the previous one? That's not uosc's concenr, that's mpv behavior. We just provide a way to enable/disable tracks. And yeah, you can just toggle their visbility per video instead.

**Comment by Solarunit** [comment]
>In this case, why not use mute/visible instead?

There is a shortcut in mpv that show/hide subtitles, but no option in the GUI. 

>And yeah, you can just toggle their visbility per video instead.

I thought in previous version there was Disable option in the subtitles menu that does exactly this - show/hide subtitles? In new menu you have to specify exactly what  subtitles you want to enable/disable.

Or those are 2 different features? :thinking:

**Comment by hooke007** [comment]
Why each command must have a option/gui in uosc?
It's impossible. IMO uosc only implement less than 10% of mpv' featureds.
Just add any commands in input.conf. Or build a button by your self via the `controls` option.

**Comment by hooke007** [comment]
> Or those are 2 different features?

They are different.

https://mpv.io/manual/master/#options-sub-visibility
https://mpv.io/manual/master/#command-interface-sid

**Comment by Solarunit** [comment]
>Why each command must have a option/gui in uosc?

Only most important ones. And show/hide subtitles I think is important. 

>They are different.

But they kinda do the same thing - show/hide subtitles? (both manual links open at the top page for me :shrug: )

**Comment by tomasklaen** [comment]
The previous menu was doing the exact same thing as it is now, disabling a track, just now the disable button is unnecessary.

I guess the concern is that if there's a lot of subtitles, scrolling to the active one to disable could be annoying. But the way menus work, the active item should be preselected and in the middle of the UI. If it's not, it's a bug. And I actually think this is a case, because these are self updating menus that populate themselves after initial load, so this behavior is lost. I'll look into it.

**Comment by tomasklaen** [comment]
No it seems to preselect and slide to view fine already.

**Comment by Solarunit** [comment]
>No it seems to preselect and slide active item to view fine already.

I have `en` subs enable by default in mpv.conf (not sure if that's important) and when playing a video with en subs:

- open subs menu in I see Eng-subs highlighted and selected
- I press Enter to disable Eng-subs and open subtitles menu again
- Nothing is highlighted and only 1st item is selected (not Eng-subs)

 I see 2 problems here:

1. if videos has a lot of subtitles you have to scroll to the previous active ones
2. There could be several Eng-subs with similar names and you have no idea what were the previous active ones

IIRC  in previous menu with disable button we didn't have such problem? Maybe bring it back @tomasklaen ?

**Comment by tomasklaen** [comment]
I also don't understand the issue. It behaves same as before, you just don't need the disable button anymore. If you disabled subtitle track before, disabled button was active, which was the 1st item at the top. Now there's nothing active, which is imo a more accurate representation of what's going on.

And if you have tons of subtitles in the list and want to quickly go to `en`, than literally just type `en`, you'll get instant filtering, unless you disabled type to search in your uosc.conf.

**Comment by Solarunit** [comment]
>I also don't understand the issue.

Ok, I went and set previous version to check how it worked before. 
I was wrong. I thought Disable button would become Enable button to enable previous disabled subtitles. But nope, it does nothing.
_____

So I guess, for the new menu improvement would be to select last active subtitles when you open menu? @tomasklaen 

>And if you have tons of subtitles in the list and want to quickly go to en, than literally just type en, you'll get instant filtering, unless you disabled type to search in your uosc.conf.

yep, sure I disabled it :smile:

**Comment by tomasklaen** [comment]
Track menus are for selecting active tracks. To control them further you use other methods, like `sub-visibility` for subtitles, and `volume`/`mute` for audio. I don't think it's appropriate to have these in track menu. Maybe when I add menu scoped actions.

Adding code to remember last active item and preselect it is imo too much hassle for too little benefit. Just use sub visibility and you don't need it.

> yep, sure I disabled it

You can trigger search with `/` or `ctrl+f`.
