### ISSUE TITLE
Option to disable Load (open file)

### ISSUE THREAD

**Issue by Solarunit** [tomasklaen/uosc#962]
Is there a way to disable Load (open file) item from the menus? I never use it.

**Comment by tomasklaen** [comment]
No. And I use it a lot, especially the side action for downloading subs.

But I also didn't like the action pollution that was in that menu. It used to be:

- Load file
- Search and downlaod
- Disable

before the list of tracks started, so I condensed it into a single **Load file** item, where downloading now its side button, and disable function was moved to toggling active item.

For now this has to be enough. In future I might move even the Load file to something like menu actions which will be displayed next to or inside menu title, but I'm definitely not adding an option for this.
