### ISSUE TITLE
The shortcut keys for secondary subtitles actions do not work

### ISSUE THREAD

**Issue by dyphire** [tomasklaen/uosc#965]
Buttons work fine.

Edit: By the way, the alt shortcut doesn't work either.

**Comment by hooke007** [comment]
The shortcut key for secondary subtitles is `shift+(enter)`

**Comment by dyphire** [comment]
Well, it's very misleading.

**Comment by tomasklaen** [comment]
I only added `(shift)` to the label because it can be used for both enter and mouse click to activate secondary subtitle, and adding `(shift+enter, shift+click)` seemed too long.

I was hoping none would think that modifier on its own would have a function.

**Comment by mrfragger** [comment]
yea I would've never figured it out without reading this thread and another thread...perhaps two lines.  I kept hitting shift and couldn't figure out what was supposed to happen.
Activate as secondary subs
(shift+ENTER or shift+click)
