### ISSUE TITLE
[5.3.1]/uosc/lib/cursor.lua error

### ISSUE THREAD

**Issue by redomCL** [tomasklaen/uosc#967]
![QQ截图20240901160257](https://github.com/user-attachments/assets/5ca01b79-b329-40fd-a50c-b9e3d4fe5735)

After right-clicking to pop up the uosc menu and left-clicking elsewhere to close it, this error will be reported.

mpv version : https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20240901/mpv-x86_64-v3-20240901-git-7c672e3.7z

**Comment by tomasklaen** [comment]
Couldn't reproduce, but hopefully the commit above prevents that.

**Comment by redomCL** [comment]
> 无法重现，但希望上面的提交可以防止这种情况发生。

yea!    fixed,thankyou!
