### ISSUE TITLE
Feature Request: Add a subtitle reload command

### ISSUE THREAD

**Issue by McBaws** [tomasklaen/uosc#972]
The new subtitle reload feature is very useful. It would be even more useful if it could be invoked without opening the subtitle menu; as far as I can tell this can't be done at the moment.

It would be nice if there was a command for this action. The command could either reload the currently selected external subtitle or reload all of the loaded external subtitles, or these could even be separate commands.

Thank you!

**Comment by mrfragger** [comment]
`\           sub-reload                           #! [Subtitles] > Reload Current External Subs`

**Comment by McBaws** [comment]
I missed that lol. Thanks
