### ISSUE TITLE
Potential bug with subtitle reload.

### ISSUE THREAD

**Issue by Sneakpeakcss** [tomasklaen/uosc#976]
Reloading subtitles for local files shifts the menu width because a magical comma gets added:

https://github.com/user-attachments/assets/7ed26535-2d30-49df-a10d-8c8c3f329f24

When reloading subtitles from youtube it gets even better:

https://github.com/user-attachments/assets/f43d3a20-c310-45c1-994d-73a22ad13586

**Comment by tomasklaen** [comment]
I cant replicate the comma, but try this:

```diff
diff --git a/src/uosc/lib/menus.lua b/src/uosc/lib/menus.lua
index 936c93c..6cfadd7 100644
--- a/src/uosc/lib/menus.lua
+++ b/src/uosc/lib/menus.lua
@@ -236,7 +236,10 @@ function create_select_tracklist_type_menu_opener(opts)
 				local hint_values = {}
 				local track_selected = track.selected and track.id == track_prop_index
 				local snd_selected = snd and track.id == snd_prop_index
-				local function h(value) hint_values[#hint_values + 1] = value end
+				local function h(value)
+					value = trim(value)
+					if #value > 0 then hint_values[#hint_values + 1] = value end
+				end
 
 				if track.lang then h(track.lang) end
 				if track['demux-h'] then
```

The second youtube example, I'm not sure what we can about it, we are just displaying the info we get:

```lua
title = (track.title and track.title or t('Track %s', track.id))
```

That's just what mpv reports. You probably need to complain there.

**Comment by Sneakpeakcss** [comment]
Nice, that fixed it. Here's a sample that i used if you want to check if you can reproduce it: 

[subtitle-reload.zip](https://github.com/user-attachments/files/16851919/subtitle-reload.zip)
