### ISSUE TITLE
5.5.0 left/right arrow not working for load video or load subs

### ISSUE THREAD

**Issue by mrfragger** [tomasklaen/uosc#977]
Thanks for reverting back as newcomers to uosc will be able to figure it out.  However, the 5.5.0 update the arrow keys do work for the menus like they did before but NOT for menu when using load subtitle nor for menu when using load video file. They did back in 5.2.0 and prior.

Changelog 5.5.0
Reverted left/right keys back to navigating submenus (https://github.com/tomasklaen/uosc/commit/6e06fa25b98213ac93fcb5dfe2361ff5d9fb3661) @tomasklaen

These are just comments below...no issues 
memo history works great now for page navigation
API: on_close & keep_open not working as documented (https://github.com/tomasklaen/uosc/commit/e4e8f077cfbb43c7e952564c2dfd8ef53d9872f6) @tomasklaen

Selecting secondary subs is no longer confusing and easily done...this is wonderful...well done.
Simplify external track titles (https://github.com/tomasklaen/uosc/pull/975) (https://github.com/tomasklaen/uosc/commit/904d23e29da6500f442055999373c2d2bce2243c) @dyphire

**Comment by tomasklaen** [comment]
Yes I didn't like overloading arrows with also activating items, so they only navigate between submenus now.

**Comment by mrfragger** [comment]
For those who wish to have left/right functioning even in load subs or load video change the following two lines in elements/menu.lua

`	--if (key == 'enter' and selected_item) or (id == 'right' and is_submenu) then`
change to
`	--if (key == 'enter' and selected_item) or (id == 'right') then`

`elseif id == 'left' and menu.parent_menu then`
change to
`elseif id == 'left' then`
