### ISSUE TITLE
5.5.0 menu not closing after selection youtube-download.lua

### ISSUE THREAD

**Issue by mrfragger** [tomasklaen/uosc#978]
Pretty sure this is uosc related as in 5.2.0, 5.3.1, 5.4.0 it always closed after selecting download subs or video, etc.
<img width="515" alt="image" src="https://github.com/user-attachments/assets/7cf20174-93d6-4ba9-b676-9b7e47bee998">

5.5.0 it just remains open and one must hit ESC or click outside window to close it even after choosing download subs or download video.

**Comment by tomasklaen** [comment]
The script author is explicitly configuring menu to stay open after item is activated (`keep_open = true`):

https://github.com/cvzi/mpv-youtube-download/blob/main/youtube-download.lua#L1254-L1260

I did fix `keep_open` not working yesterday, maybe I thought I broke it just a couple days ago. It's possible it was broken for a longer time and none noticed, and cvzi just added that prop thinking it does something else and left it there. Dunno.

**Comment by mrfragger** [comment]
thanks....it was always configured like this but never worked I guess as it always closed
      type = 'yt_download_menu',
      title = locale('Download'),
      keep_open = true,

changed it to
      type = 'yt_download_menu',
      title = locale('Download'),
      keep_open = false,
