### ISSUE TITLE
The current playback time position jumps around.

### ISSUE THREAD

**Issue by zhouxinghong** [tomasklaen/uosc#981]
The current playback time position jumps around.

Greetings, friend! While playing .m3u8 live stream I find that the current playback time position jumps around. Is it possible to fix this problem?

https://github.com/user-attachments/assets/edd6a3b5-a339-4b5f-b28f-3d463ae1b6d1

https://kbsworld-ott.akamaized.net/hls/live/2002341/kbsworld/01.m3u8

---

Windows 10 19044 
mpv v0.38.0-736-gafdbbac8 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep  2 2024 00:08:43
libplacebo version: v7.349.0 (v7.349.0-9-gefb8934-dirty)
FFmpeg version: N-116830-g01f2d95fb
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.35.100
   libswresample   5.2.100
   libswscale      8.2.100

UOS [5.5.0](https://github.com/tomasklaen/uosc/releases/tag/5.5.0)

**Comment by tomasklaen** [comment]
It's a new chunk of video being appended to timeline during streaming. That's how streaming works. No issue here, nor is there anything to be done about it. Everything works as it should.

**Comment by zhouxinghong** [comment]
Okay, thanks for the answer!
