### ISSUE TITLE
Timeline not rendered when opening a YouTube video in paused state

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#982]
When opening a video that needs time to load, such as a YouTube video,and you pause that video before it can start playing, uosc 5.4.0 doesn't show the timeline anymore – neither on hover, nor when flashing or toggling it. Everything else renders fine. One way to cause it to properly render is resizing the window, as is seeking of course.

I suspect this is a caching issue where the update of the video length doesn't reach the timeline component and does not cause it to re-evaluate its render data or similar.

**Comment by tomasklaen** [comment]
Timeline doesn't render when wither `duration` or `time` are `nil`. No idea why resizing a window would have an effect on that.

If this worked before, the only commit I suspect might be causing the issue is #969 by @po5.

**Comment by FichteFoll** [comment]
My assumption is that resizing the window causes some properties to be re-read, at which point it sees that whatever was nil before (duration) is now not nil anymore and the timeline can be rendered again.

**Comment by FichteFoll** [comment]
Yes, I am 100% unable to reproduce with this patch for a video I had about 70% fail rate before.

**Comment by tomasklaen** [comment]
Cool. The fix is already in the commit above (dc7c822).
