### ISSUE TITLE
in version higher than 5.2.2 the menu is no longer displayed

### ISSUE THREAD

**Issue by zaeboba** [tomasklaen/uosc#984]
was
![изображение](https://github.com/user-attachments/assets/9085bcbc-edd4-491f-8596-08859ffc6573)
It's empty now.
466 https://github.com/zaeboba/portable_config/blob/main/input.conf there's also version 5.2.2
Since I'm not a programmer, I don't know how to fix it :( this is from a clearly observed

**Comment by zaeboba** [comment]
Can anyone help me with this? Or give me some hints on what I need to do.
If anything, I'm at kindergarten level with software.

**Comment by tomasklaen** [comment]
If you're looking for these items in the menu:

```
#Meta+v      script-binding paste     #! [Онлайн-видео] > Вставьте URL онлайн-видео
#Meta+c      script-binding copy     #! [Онлайн-видео] > Скопировать URL онлайн-видео
#Ctrl+u       script-message-to youtube_upnext menu                    #! [Онлайн-видео] > Рекомендации YouTube
#d               script-message-to youtube_download menu                 #! [Онлайн-видео] > Скачать онлайн видео/аудио
#Ctrl+d      script-message-to youtube_download download-video       #! [Онлайн-видео] > Скачать лучшее онлайн-видео
#Ctrl+a      script-message-to youtube_download download-audio       #! [Онлайн-видео] > Скачать лучшее онлайн-аудио
#Ctrl+D      script-message-to youtube_download download-subtitle    #! [Онлайн-видео] > Скачать субтитры онлайн
```

You have them commented out. This:

```
#Meta+v
```

is treated as commented out. To display it in menu, you need to either drop `#`, or `Meta+v` from that line.

**Comment by zaeboba** [comment]
and really, thank you for telling me.
It's just that some scripts didn't want to work if there wasn't a letter after #. 🤔
