### ISSUE TITLE
[segment_linking] Subprocess failed: init

### ISSUE THREAD

**Issue by aicynide** [tomasklaen/uosc#985]
I tried to play this [URL ](https://asia.xyzcdn.cloud/855b5e23b545b47023138cd2b5df8e706e7bd73542fc4cd701a8be33da2d4bbcd97bc2535ceec3325478c155e4135d464e4518a080b6f7f0a9808d94f0e282c7f1ef7db0ea47dd9af28b79585ce3caf6955bccc0aea3cde3397ee8d1748130b2c816671962d398044967136eab0a203d97e503ae146175720aefb6d3be08c707e82055ec3495061011a5c65551ad09f0ca097d65920039e030ab4863b74d9599dd7c6ed86365f38c7eb4a2d54f22d2a3::622381143bf04cc74452fe78edbccb3a/Siren.108.2024.1080p.HS.WEB-DL.DUAL.DDP5.1.H.265-Archie.mkv) but i get this error `[segment_linking] Subprocess failed: init`

I don't get this error when playing with `mpv --no-config`

**Comment by hooke007** [comment]
cannot reproduce. It works for me.
![image](https://github.com/user-attachments/assets/46d29fc1-7fb3-4a93-af93-19d0fe50301f)
