### ISSUE TITLE
5.6.0 paste playlist-count > 1 should be 0

### ISSUE THREAD

**Issue by mrfragger** [tomasklaen/uosc#988]
If you open mpv and paste Ctrl-v it opens a online video.
Ctrl+v      script-binding uosc/paste     #! [Video Online] > Paste online video URL

Once you're watching it then you could use the paste-to-playlist but wish to avoid that keybind altogether.

I'm just trying to replicate how copy-and-paste.lua worked.  If you change in main.lua 
`	local has_playlist = mp.get_property_native('playlist-count') > 1`
to
` 	local has_playlist = mp.get_property_native('playlist-count') > 0`

then it works as you're watching one online video and Ctrl+v paste then it appends it to the playlist rather than open it immediately.  I think the paste-to-open could be used for those who need that.  Excellent release...thanks. Now no longer need copy-and-paste.lua script.

**Comment by tomasklaen** [comment]
`paste-to-playlist` also opens a file if mpv if idle. Is that the behavior you want? I'll clarify it in docs.

**Comment by mrfragger** [comment]
yea it's clear in the commit not so much the docs but yeah I only want two keybinds keybind Ctrl+v for paste and Ctrl+c for copy.  Doing it playlist-count > 0 replicates the exact functionality of what I'm used to and prefer it that way.  I don't need the paste-to-open nor the paste-to-playlist keybinds.

**Comment by tomasklaen** [comment]
I still don't follow what exactly you're requesting. Is the current `paste-to-playlist` behavior what you want? Can I close this issue?

**Comment by mrfragger** [comment]
everything is fine if once I changed playlist-count > 0...it negates the need for paste-to-playlist and paste-to-open for me.  I was just suggesting to change default to playlist-count > 0 rather than playlist-count > 1.

**Comment by mrfragger** [comment]
As of 5.6.2 this is the only thing I wish different or a setting available, especially since one can navigate with left/right arrow keys once again.

`# run /bin/bash -c "cd ~/.config/mpv/scripts/uosc; cat main.lua | sed \"s/playlist-count') > 1/playlist-count') > 0/g\" > mainnew.lua; rm main.lua; mv mainnew.lua main.lua"; show-text "sets playlist-count > 0 rather than > 1 so it'll play video right away rather than just adding to playlist - restart mpv to take effect" #! [Utilities] > [Advanced] > After updating uosc fix playlist-count 0 not 1`
