### ISSUE TITLE
I cannot select the options with the mouse

### ISSUE THREAD

**Issue by sergiohzph** [tomasklaen/uosc#991]
For example, when changing subtitle tracks, I can't do it with the mouse, only with the Enter key.
![image](https://github.com/user-attachments/assets/14ce787a-2aab-4b38-b19a-6f4678ebd8de)

**Comment by tomasklaen** [comment]
Can't reproduce. What version/os are you on?

**Comment by sergiohzph** [comment]
> Can't reproduce. What version/os are you on?

OS: W11 23H2
Latest MPV Windows build.

**Comment by tomasklaen** [comment]
I've meant version of uosc. But I can't reproduce on latest or main branch. I'm on Win 10. And since none else complains, so I'd wager it's something on your end.

**Comment by tomasklaen** [comment]
I'm gonna assume this is not uosc related. If there's more info let me know and I'll reopen.
