### ISSUE TITLE
button title display

### ISSUE THREAD

**Issue by zaeboba** [tomasklaen/uosc#998]
Sorry for annoying, but how to fix the display on the buttons, if there is a lot of text, in the old version the last line lay on the panel, and in the new version it is in the middle.
here's an example (it doesn't depend on the window size)
![JjWYdAmAr8](https://github.com/user-attachments/assets/b3f0a7f3-ff65-43ac-b5d6-a43e205b57a8)

**Comment by mrfragger** [comment]
With the new keybindings don't think it's good to list out all the shortcut keys in the timeline menu anymore.  Now I just put the shortcut key to the button and nothing more.

`K     script-binding uosc/keybinds   #! [Utilities] > Show keybindings`

`controls=menu?Menu,command:info_outline:script-binding display-stats-toggle?i I Stats,gap,subtitles?o load sub\N? Subtitles,gap,chapters?c Chapters,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality?q Stream Video Quality,command:history:script-binding memo-history?h History,command:format_list_numbered_rtl:script_message bookmarker-menu?b Bookmarks,command:dark_mode:add contrast -20?Ctrl+Alt+z Dark mode,command:light_mode:add contrast 20?Ctrl+Alt+x Light mode,command:invert_colors:add saturation -100?Ctrl+Alt+Z B&W video,command:invert_colors_off:add saturation 100?Ctrl+Alt+X B&W off,gap,space,speed,space,cycle:play_arrow:pause:no=pause/yes=play_arrow?spacebar play/pause,shuffle?N Shuffle,loop-playlist?l set/clear A/B Loop points,loop-file?L Loop file,gap,first?Home First,prev?< Previous,items?Tab Playlist,next?> | Enter Next,last?End Last,gap,fullscreen?F fullscreen,`

**Comment by zaeboba** [comment]
> don't think it's good to list out all the shortcut keys in the timeline menu anymore.

Heck, it was handy to see at a glance what keyboard shortcuts could be used.    
 “script-binding uosc/keybinds #! [Utilities] > Show keybindings” is not convenient, because it's all there together
😢

**Comment by tomasklaen** [comment]
Putting documentation with multiple lines into a button tooltip is crazy. It's meant for short single line hints.

To support this we'd need to update our text measuring utility to detect new lines and measure height as well (which has not been necessary until now). Not something I'm interested in spending time on unless there's a valid need for it (which I don't consider this to be).

But I'll keep this open if someone else wants to pick it up, as it _is_ an issue.

**Comment by zaeboba** [comment]
Maybe, although I'm not sure if it's possible to create some kind of division or addition in the menu that MrFragger indicated, with an explanation for those who are not familiar—it's easy to get confused about who is responsible for what
![изображение](https://github.com/user-attachments/assets/f4623d43-3dbf-4e17-9691-b49d010393ae)

**Comment by zaeboba** [comment]
Okay, I get that this idea is bullshit.
Can I delete it so I don't embarrass myself?
